### ISSUE TITLE
Intero doesn't load the dependecies for Setup.hs

### ISSUE THREAD

**Issue by enolan** [commercialhaskell/intero#101]
When I open a Setup.hs file, I get the little red dot next to `import Distribution.Simple` and a message saying it couldn't find the module and that's it's a part of Cabal but Cabal is hidden. I guess the problem is because Setup.hs files have a different compilation environment?

**Comment by chrisdone** [comment]
Indeed. I'm not sure how to resolve this. Newer cabal is getting a way to set `Setup.hs` dependencies in the .cabal file, IIRC.

We *could* make checking any file named `Setup.hs`/`Setup.lhs` in the same directory as the `.cabal` file, automatically enable `-package Cabal`. That's pretty easy.

**Comment by chrisdone** [comment]
We'll be adding `M-x intero-add-package` which is a more general solution to "I want a package for this file right now", also. #102

**Comment by enolan** [comment]
#102 is a pretty good stopgap. Ideally it would use whatever parameters Stack does. You could add a command to Stack to get that information. That'd cover the simple problem of loading Cabal and the more complicated one of dealing with `setup-depends`.

**Comment by chrisdone** [comment]
I implemented #102, and also enabling the package is now a suggestion. So if you open a Setup.hs file and it says that the module isn't in scope but it's in hidden package Cabal, then you can hit `C-c C-r` and you'll see

<img width="850" alt="screenshot 2016-11-23 15 18 23" src="https://cloud.githubusercontent.com/assets/11019/20567307/1b943e1a-b190-11e6-9ec9-d6a5d050727c.png">

If you're editing your Setup.hs, you might have other dependencies too. This feature will work for those deps too, if you already ran a `stack build`.
