### ISSUE TITLE
Add M-x intero-add-package

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/intero#102]
Which will just send `:set -package foo` and re-check the current buffer.

**Comment by mgsloan** [comment]
Makes sense!

For use with files in a stack project, I imagine the usecases for this will be covered by https://github.com/commercialhaskell/intero/issues/39 .  With that, it ought to be possible to add the dep to your cabal file, have it build the dep if needed, and add the package-id in intero's arguments.

**Comment by fosskers** [comment]
That would be nice, given that `intero` currently doesn't detect `.cabal` changes.

**Comment by fosskers** [comment]
Will `intero-add-package` happen automatically, or must it always be called manually?

**Comment by chrisdone** [comment]
Manually for the moment. I think we have another issue for auto-detecting changes to the .cabal file.
