### ISSUE TITLE
Request for docs: Intero key-bindings

### ISSUE THREAD

**Issue by saurabhnanda** [commercialhaskell/intero#104]
Apart from the few that are given in the README, would it be possible to have a beginner-friendly document that describes the relevant key-bindings that are required for meaningful Haskell development using Intero? Thanks.

**Comment by chrisdone** [comment]
You mean something which includes the keybindings for flycheck and such?

**Comment by saurabhnanda** [comment]
Yes. For example, I still haven't been able to figure out how to cycle
between prev/next flycheck **errors alone** (not warnings).

**Comment by saurabhnanda** [comment]
Another one which always stumps me. After I use `M-.` to jump to a definition, how do I jump back to where I was earlier?

**Comment by chrisdone** [comment]
`M-,` should jump back; it's the standard Emacs keybinding to return after a jump.

**Comment by saurabhnanda** [comment]
@chrisdone `M-,` doesn't work (even when used immediately after a successful `M-.` jump). It says:

> No M-x tags search or M-x tags-query-replace in progress

**Comment by simon-bourne** [comment]
I had the exactly the same issue with `M-,`. To get it working, I added this to my `init.el`:

    (eval-after-load 'haskell-mode
      '(define-key haskell-mode-map (kbd "M-,") (function xref-pop-marker-stack)))

I also tried this instead, but without success:

    (eval-after-load 'intero-mode
      '(define-key intero-mode-map (kbd "M-,") (function xref-pop-marker-stack)))

**Comment by saurabhnanda** [comment]
@simon-bourne the keybinding doesn't work due to some weird error (I put it in `.spacemacs` btw). I also tried calling the actual function `M-x  xref-pop-marker-stack` and got the following error: `No previous locations for find-tag invocation`

**Comment by saurabhnanda** [comment]
I just checked `M-.` is bound to `intero-goto-definition`. I'm not sure if `xref-pop-marker-stack` is the logical reverse of that command.

**Comment by saurabhnanda** [comment]
Is it not working because of https://github.com/commercialhaskell/intero/blob/9049a0ad7cb8282cdc41fe47d2d4690898794b63/elisp/intero.el#L233 -- expected to work in Emacs 25 only? I'm on Emacs 24.5.1

**Comment by simon-bourne** [comment]
I'm on 24.5.1 as well (using prelude, not spacemacs). I'm new to emacs as well, so not really sure why it works for me. It looks like it's doing `ring-insert find-tag-marker-ring (point-marker)` instead, which sounds like something similar. As to why the keybinding doesn't work, maybe you need a `require`. I've got:

    (require 'prelude-haskell)

which is prelude specific. Maybe try `require 'haskell`.

**Comment by saurabhnanda** [comment]
Filed #137

**Comment by saurabhnanda** [comment]
Another question related to keybindings. What's the equivalent of Sublime's `Cmd-r` or `Ctrl-r` in intero? Basically, it's "goto symbol definition" and one can start typing the symbol name.

**Comment by chrisdone** [comment]
There isn't such a keybinding. There is `M-:`  to go the thing at point, but nothing to enter an arbitrary name.
