### ISSUE TITLE
In elisp, allow a specification of which stack.yaml to use

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/intero#105]
It' be convenient to have a way to switch which stack config you're using (the `--stack-yaml` flag).  This'd be particularly convenient if it's provided by filepath selection filtered to `.yaml`, starting in the dir of the current stack config.

Since targets are provided directly to stack, it turns out that you can already pass `--stack-yaml stack-7.8.yaml` in via `intero-targets`.  However, this does not work with intero's auto-install, because it doesn't know to target GHC 7.8, and instead we can get a compiler mismatch if the primary `stack.yaml` uses a different ghc.

**Comment by mgsloan** [comment]
We could also consider being able to provide extra stack args in general.  These would get passed to both the intero invocation and the auto-install.

It's hard to be sure that all of the arguments should be provided to the auto-install step. Lets say we somehow disallow (or document) that targets shouldn't go in the list, this'd get us most of the way there. Even so, it's hard to be sure that there aren't arguments that would interfere with that auto-install. Maybe it's no big issue?

**Comment by chrisdone** [comment]
I think this is reasonable and straight-forward to add. 

Question: what's the use-case for this? I feel like I'd use it *only* when I'm trying to port a package to different versions of GHC. Otherwise I'd just run my test suite against different versions and just stick to my current version. With that in mind, we can reasonably consider it an "advanced" use-case with documented care to be taken.

**Comment by mgsloan** [comment]
> Question: what's the use-case for this? I feel like I'd use it only when I'm trying to port a package to different versions of GHC.

Sometimes the number of configuration-specific changes are non-trivial, and they can also change a lot more than just GHC version.  For example, when you have a dependency on template-haskell which varies between stack.yaml versions, it's easy to need to use CPP.  In these cases, I'd rather not need to fall back on doing manual iterations with ghc via `stack build --stack-yaml ...` for this circumstance.

`M-x intero-stack-yaml` seems fine, I would have discovered that.

I think I'd prefer if there was a way to provide extra args and have them "just work" when it comes to also configuring how intero gets installed.
