### ISSUE TITLE
Editing lags on slow to compile files

### ISSUE THREAD

**Issue by enolan** [commercialhaskell/intero#107]
When editing a large file - I've noticed it in Idris' AbsSyntaxTree.hs which is around 2500 lines and in a Yesod file with a bit of TH in it - typing stops responding for up to five seconds every few seconds. It'd be a big improvement if loading could be made asynchronous.

**Comment by chrisdone** [comment]
Loading _is_ asynchronous. However, I think you've caught a nice issue which is that while flycheck is async, company mode is syncronous. Therefore company sometimes blocks while waiting for the flycheck command to finish.

The solution is: Look into company's API to see whether it supports async operation.

**Comment by kRITZCREEK** [comment]
It does: https://github.com/epost/psc-ide-emacs/blob/af44f9a4d2cbe84fdfae5e286a06d0207229d21c/psc-ide.el#L394-L404

We're using it in `psc-ide`, if you want I can take a look and see if I can port it over.

**Comment by chrisdone** [comment]
Excellent news! Thanks! I'll look into it and get back to you.

**Comment by chrisdone** [comment]
Well, sorry that took so long. The async call needs to be called in the right buffer or company fails silently.

I've made the company integration asynchronous now, which should stop editor lock up.

**Comment by kRITZCREEK** [comment]
:+1:

**Comment by enolan** [comment]
Awesome, this is much better. :)
