### ISSUE TITLE
Spaces in filenames

### ISSUE THREAD

**Issue by VitorCBSB** [commercialhaskell/intero#109]
Hey guys, I decided to give Emacs a chance and installed Intero.

Since I'm absolutely new to it, I just tried opening a random file from a (stack enabled) project I have and nothing seems to work. Moving around the buffer shows a message saying "Couldn't guess that module name. Does it exist?", autocompletion does not work, type inspection doesn't either.

After trying to load the module in the REPL (with `C-c C-l`), I think I might know what's wrong. So, I have a special thing that has broken so many projects, it's kind of baffling. My home directory has a space character in it. I suspect this project is yet another victim. This is what happens when I try to load it:

    Starting:
      stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-load --no-build --ghci-options -odir=c:/Users/VITORC~1/AppData/Local/Temp/intero4620cWq --ghci-options -hidir=c:/Users/VITORC~1/AppData/Local/Temp/intero4620cWq hetris
    Intero 0.1.13 (GHC 7.10.3)
    Type :intro and press enter for an introduction of the standard commands.
    
    target `Coimbra\AppData\Local\Temp\intero-script4620pgw' is not a module name or a source file
    Prelude> target `C:\Users\Vitor' is not a module name or a source file
    Prelude> 

My home directory is called "Vitor Coimbra", so anything inside it probably won't open correctly.

Edit: If it helps, I reported a similar issue to the stack project some time ago (https://github.com/commercialhaskell/stack/issues/1401).

**Comment by chrisdone** [comment]
We can fix that readily in the elisp. I'll get to it tomorrow!

**Comment by chrisdone** [comment]
I looked into this; it's not because of the Elisp; it's passing the filenames properly. It's `stack ghci` itself. Please refer to that issue: https://github.com/commercialhaskell/stack/issues/2266 For future updates. I am going to work on fixing in stack.

**Comment by VitorCBSB** [comment]
Hey Chris, once again, thank you for your work. Fixing that stack issue _still_ didn't make this work for me, I'm still having this issue. Did I miss something (like updating intero as well) or should updating stack have been enough to make this work?

**Comment by chrisdone** [comment]
Did you update to stack as of today?

**Comment by VitorCBSB** [comment]
Yes, I did it about half an hour ago.
