### ISSUE TITLE
wrong type-at output with Prelude-hidden imports

### ISSUE THREAD

**Issue by berdario** [commercialhaskell/intero#110]
I have the following 2 lines in a source file:

```
import Prelude hiding (lookup)
import STMContainers.Map (lookup)
```

the `intero-type-at` command, when the cursor is on `lookup` yields

```
GHC.List.lookup :: Eq a => a -> [(a, b)] -> Maybe b
```

**Comment by chrisdone** [comment]
I don't think that imports are supported, so it's falling back to a global rather than line/col-specific lookup. Let's mark this as a bug because it would preferably return nothing rather than something unaccurate here.

**Comment by meditans** [comment]
Another data-point for this bug:

    {-# LANGUAGE NoImplicitPrelude #-}
    {-# LANGUAGE OverloadedStrings #-}
    {-# LANGUAGE ScopedTypeVariables #-}
    
    module Main where
    
    import ClassyPrelude
    
    main :: IO ()
    main = putStrLn "hi"

The type of putStrLn, according to `intero`, is

    System.IO.putStrLn :: String -> IO ()

So, I thought `intero` was querying for the type of an expression in a computation inside the `Ghc` monad or similar abstraction (like what happens in a `ghci` repl with `:t`). How does it actually work?

**Comment by chrisdone** [comment]
Does your module type-check? The type I get is:

``` haskell
putStrLn :: Text -> IO ()
```

**Comment by meditans** [comment]
Yes, it does, and curiously enough, the inferred type for `"hi"` is, correctly, `Text`. May this be due to an old version of the melpa package or the executable?
