### ISSUE TITLE
Recompiling on dependency package change

### ISSUE THREAD

**Issue by meditans** [commercialhaskell/intero#111]
For some reason, if I have in my `stack.yaml`

```
packages:
- .
- location: /path/to/local/subpackage
```

When I modify the subpackage and then reload the repl with `C-c C-l` in my project, I don't get the subpackage recompiled.

This baffles me because I'm quite sure I had this feature working when first trying intero.

What am I missing here?

**Comment by chrisdone** [comment]
Today, intero defaults to loading only the current .cabal package. So you'll have to use `M-x intero-targets RET thispkg thatpkg RET` to work with all of them. The reason for this is that in large projects it becomes ridiculous to try to load all packages, both in space and time and compatibility.
