### ISSUE TITLE
Auto-completion in intero-repl? 

### ISSUE THREAD

**Issue by pozix604** [commercialhaskell/intero#112]
What is the possibility of having auto-completion inside intero-repl? The repl is significant more useable with it.

**Comment by chrisdone** [comment]
Totally possible! We just need to enable company mode in `intero-repl-mode`.

**Comment by pozix604** [comment]
Seeing as intero has great auto complete support when editing, it's a glaring mismatch to not have it in the repl. Hope to see it available soon.

**Comment by chrisdone** [comment]
@pozix604 implemented!
