### ISSUE TITLE
error "No such directory found via CDPATH environment variable"

### ISSUE THREAD

**Issue by josefs** [commercialhaskell/intero#113]
I'm running Emacs 24.5.2 in Ubuntu within VirtualBox on a Windows 10 machine. The error in the title stops me from doing a whole range of things like syntax checking, repl etc.

What to do?

**Comment by chrisdone** [comment]
Perhaps try `M-x toggle-debug-on-error` and paste the backlog into here?

**Comment by josefs** [comment]
Debugger entered--Lisp error: (error "No such directory found via CDPATH environment variable")
  signal(error ("No such directory found via CDPATH environment variable"))
  (condition-case err (let* ((checker (flycheck-get-checker-for-buffer))) (if checker (flycheck-start-current-syntax-check checker) (flycheck-clear) (flycheck-report-status (quote no-checker)))) (error (flycheck-report-failed-syntax-check) (signal (car err) (cdr err))))
  (if (flycheck-running-p) nil (run-hooks (quote flycheck-before-syntax-check-hook)) (flycheck-clear-errors) (flycheck-mark-all-overlays-for-deletion) (condition-case err (let* ((checker (flycheck-get-checker-for-buffer))) (if checker (flycheck-start-current-syntax-check checker) (flycheck-clear) (flycheck-report-status (quote no-checker)))) (error (flycheck-report-failed-syntax-check) (signal (car err) (cdr err)))))
  (if flycheck-mode (if (flycheck-running-p) nil (run-hooks (quote flycheck-before-syntax-check-hook)) (flycheck-clear-errors) (flycheck-mark-all-overlays-for-deletion) (condition-case err (let* ((checker (flycheck-get-checker-for-buffer))) (if checker (flycheck-start-current-syntax-check checker) (flycheck-clear) (flycheck-report-status (quote no-checker)))) (error (flycheck-report-failed-syntax-check) (signal (car err) (cdr err))))) (user-error "Flycheck mode disabled"))
  flycheck-buffer()
  (condition-case err (flycheck-buffer) ((debug error) (message "Error while checking syntax automatically: %S" err) nil))
  (if (or force-deferred (flycheck-must-defer-check)) (flycheck-buffer-deferred) (condition-case err (flycheck-buffer) ((debug error) (message "Error while checking syntax automatically: %S" err) nil)))
  (progn (if (or force-deferred (flycheck-must-defer-check)) (flycheck-buffer-deferred) (condition-case err (flycheck-buffer) ((debug error) (message "Error while checking syntax automatically: %S" err) nil))))
  (if (and flycheck-mode (flycheck-may-check-automatically condition)) (progn (if (or force-deferred (flycheck-must-defer-check)) (flycheck-buffer-deferred) (condition-case err (flycheck-buffer) ((debug error) (message "Error while checking syntax automatically: %S" err) nil)))))
  flycheck-buffer-automatically(idle-change)
  flycheck-handle-idle-change()
  apply(flycheck-handle-idle-change nil)
  byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 22367 61929 674119 nil flycheck-handle-idle-change nil nil 30000])

**Comment by chrisdone** [comment]
Does your directory exist on disk?

**Comment by josefs** [comment]
Yes. It's a windows directory which is mounted in VirtualBox. I have no problem e.g. running ghci by hand on the Haskell files from within Ubuntu.

**Comment by josefs** [comment]
FWIW, the owner and group of the directory is root because of the way it's mounted. When I use stack I have to add the flag `--allow-different-user`.
