### ISSUE TITLE
REPL error: Too late for parseStaticFlags: call it before runGhc or runGhcT

### ISSUE THREAD

**Issue by clojj** [commercialhaskell/intero#114]
After creating a new stack project

```
stack new ghc8-playground new-template --resolver nightly-2016-06-14
```

...the C-c C-l command opens the REPL, but it is not possible to execute the `main` function.
` works though.

Starting the (stack) REPL outside of emacs in the native terminal, the `main` function works Ok.

stack.yaml
![screen shot 2016-06-14 at 13 23 35](https://cloud.githubusercontent.com/assets/4367963/16041369/332c40ac-3235-11e6-838f-5b9bf7a31c22.png)

**error "Too late for parseStaticFlags: call it before runGhc or runGhcT"**
![screen shot 2016-06-14 at 13 26 30](https://cloud.githubusercontent.com/assets/4367963/16041395/5b461446-3235-11e6-8ca9-cf55b9426898.png)

Native terminal (no error with `main`)
![screen shot 2016-06-14 at 13 20 23](https://cloud.githubusercontent.com/assets/4367963/16041413/72951d86-3235-11e6-8d34-a5eb521d42ed.png)

**Comment by chrisdone** [comment]
What if you run `stack ghci --with-ghc intero ghc8-playground`?

**Comment by clojj** [comment]
running that in the Mac terminal works Ok (main function is called correctly)

**Comment by clojj** [comment]
Seems to be Mac only
https://ghc.haskell.org/trac/ghc/ticket/10053

**Comment by chrisdone** [comment]
Hm, I think it might have something to do with `-fobject-code`

**Comment by chrisdone** [comment]
Try `:set -fbyte-code` before loading any modules and retry?

**Comment by clojj** [comment]
How can I set this option, when starting the repl by C-c C-l in Intero ?
(this problem is only inside Intero-Repl !)

**Comment by chrisdone** [comment]
You can write `:set -fbyte-code` in the REPL and then re-load your module with `C-c C-l`. :)

**Comment by chrisdone** [comment]
So I just ran into this myself and discovered something strange:
```
> main
Too late for parseStaticFlags: call it before runGhc or runGhcT
*** Exception: ExitFailure 1

> hspec spec

Parsing: Path Abs Dir
...
```

It seems like `main` itself doesn't work, but calling the function directly does. Go figure!

**Comment by AlainODea** [comment]
Perhaps **main** is special due to the relationship to OS-level entry-point.

Either way I found a workaround for this. If I declare it like this:

```haskell
main :: IO ()
main = tests

tests :: IO ()
tests = hspec spec
```

And invoke **tests** from Intero it works.

This indicates a possible bug in GHC that leaks the entry-point dependencies of **main** even when invoked from Haskell code.

**Comment by chrisdone** [comment]
@AlainODea Indeed, I found that other functions work just fine. Came to the same conclusion.

**Comment by chrisdone** [comment]
I've switched the REPL mode to `-fbyte-code`, and using `:r` when loading the same module as last time (which gives a substantial speed up, almost making up for not using `-fobject-code`).

**Comment by AlainODea** [comment]
@chrisdone awesome! Thank you :)

I'll give this a spin tonight.

**Comment by AlainODea** [comment]
@chrisdone ! I forgot to report back. This works beautifully. Thank you for the fix :)
