### ISSUE TITLE
"putStrLn" doesn't appear in company-mode's candidate.

### ISSUE THREAD

**Issue by tshinohara** [commercialhaskell/intero#115]
I created a new stack project with `stack new`, opened src/Lib.hs and tried if completion works. I deleted characters of "putStrLn" to "put" and invoked `company-complete`, but "putStrLn" doesn't appear in the candidates. Is this intended behaviour?

![ezgif-4227599189](https://cloud.githubusercontent.com/assets/64248/16043536/10e50ede-327b-11e6-8dbe-8e44ebee7bb2.gif)

emacs version: 24.5.1
intero: intero-20160613.758
company-mode: company-20160611.439

**Comment by chrisdone** [comment]
I suspect it's some kind of clever behaviour of company, removing the candidate that you deleted. If you type `put` out again you should get all three.

**Comment by chrisdone** [comment]
Actually, I think there's a bug in `:complete-at` which sometimes does not return `putStrLn` as a candidate.

**Comment by CarstenKoenig** [comment]
this might or might not be related but I noticed that the completion is really buggy in not-tiny sized project with a few cabal-stanzas (lib,exec,test) and modules (around 30).

I usually see only half of all top-level functions in the file when I use complete - if I try to force the missing ones intero dies on me and I have to restart it.

**Comment by chrisdone** [comment]
I think it's related. I have to take a look at the source of information I'm using, as it's obviously a bit flaky.

**Comment by CarstenKoenig** [comment]
I still try to figure this out and I just saw a workaround:

let's say I have lot's of things beginning with `"blog"` in scope (from a TH-model).

If I type any of the prefix (say `"blog"`) and ask for completion it seems to only find a top-level function in scope but not the model functions.

But if I type noting, ask for `company-complete` and then start typing `"blog"` it will *find them all*!

BTW: I don't know where this information is comming from as the functions are not in the TAGS file and the intero-debug will not log any commands into "*messages*" if I do it that way.

**Comment by CarstenKoenig** [comment]
a question: am I the only one having this problem? Because nobody seems to care/complain to much and for me (and my puny memory) completion is one of the major usability factors.

Is there some workaround? Or are you using company-ghc/company-ghci instead?

**Comment by chrisdone** [comment]
No, I have the same problem. I think people don't rely on completion as much as other features, though.

**Comment by CarstenKoenig** [comment]
oh ok - sorry - I guess I'm too spoiled by VS - do you think it's a problem in the ELIPS part? I don't know much but maybe I can try to figure it out - but right now I don't even know where to look

**Comment by chrisdone** [comment]
I think it's in the Haskell side. The completions coming back aren't consistent. The Elisp side is relatively simple.

**Comment by chrisdone** [comment]
@tshinohara The completion problem is fixed by #237. 🎉 

@CarstenKoenig Can you open a new issue with a simple test-case of the problem?

**Comment by CarstenKoenig** [comment]
a test-case for what? The completion issue? I had another issue opened for this earlier: https://github.com/commercialhaskell/intero/issues/158
