### ISSUE TITLE
intero: Most RTS options are disabled. Link with -rtsopts to enable them.

### ISSUE THREAD

**Issue by martinvlk** [commercialhaskell/intero#118]
Hi, I have tried using intero on my project, but GHCI won't start and it gives the following error:
intero: Most RTS options are disabled. Link with -rtsopts to enable them.

I am not sure what the proiblem is, can you suggest some investigation steps here? Is intero supposed to be built with -rtsopts, but isn't? Or should my executable be built withh -rtsopts?

Please advise.

**Comment by chrisdone** [comment]
How are you building intero and with what GHC version and what OS?

**Comment by martinvlk** [comment]
I am using Ubuntu Linux, on a stack-based project using nightly-2016-03-16 which has GHC 7.10.3

Intero installed automatically after I added the corresponding package to my e-macs (intero 20160613.758)

**Comment by chrisdone** [comment]
Perhaps your cabal file specifies rts opts? If so, I can try reproducing it locally and make a fix.

Intero doesn't normally require them, but perhaps it needs them enabled to load cabal targets which require them.

**Comment by martinvlk** [comment]
Yes, I got this in my cabal file:
ghc-options:         -fno-full-laziness -Wall -fwarn-incomplete-uni-patterns -funbox-strict-fields -O2 +RTS -A128m -n4m -RTS

Happy to try a workaround here to test the fix if there is some.

**Comment by chrisdone** [comment]
Okay, building intero with `-rtsopts` fixes this issue. I'll update the build opts.

**Comment by chrisdone** [comment]
Can you update your emacs lisp package and try again?

**Comment by martinvlk** [comment]
Installation of new intero fals when I start emacs. The screen with the error then disappears so I don't see what it really says.

**Comment by chrisdone** [comment]
Oh, we have to wait about half an hour for stack to pick up the new hackage package.

**Comment by martinvlk** [comment]
It worked now, intero booted up, yai! On to trying it out so!
Many Thanks, keep up the good work!

**Comment by chrisdone** [comment]
Hurrah!
