### ISSUE TITLE
Goto symbol (M-.) prints errormessage if (target-)file not already loaded

### ISSUE THREAD

**Issue by clojj** [commercialhaskell/intero#119]
**file-error "Cannot open load file" "no such file or directory" "ghc"**

Navigating by M-. shows error, if the targetfile (with the relevant symbol) is not already loaded in emacs
(vanilla new-template stack project with nightly LTS)

Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "ghc")
  (ghc-init)
  (lambda nil (ghc-init))()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook haskell-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook haskell-mode-hook))
  run-mode-hooks(haskell-mode-hook)
  haskell-mode()
  set-auto-mode-0(haskell-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer Lib.hs> "~/stack-projects/ghc8-playground/src/Lib.hs" nil nil "~/stack-projects/ghc8-playground/src/Lib.hs" (7343988 2049))
  find-file-noselect("/home/jwin/stack-projects/ghc8-playground/src/Lib.hs" nil nil nil)
  find-file("/home/jwin/stack-projects/ghc8-playground/src/Lib.hs")
  intero-goto-definition()
  call-interactively(intero-goto-definition nil nil)
  command-execute(intero-goto-definition)

**Comment by chrisdone** [comment]
This is an error from the ghc-mod package. I suggest finding where `ghc-init` lies in your `.emacs` file and just removing any reference to it. :+1:

**Comment by clojj** [comment]
Thx for hinting at ghc-mod.
It wasn't any ref in .emacs (vanilla emacs + intero only).

Removing ghc-mod-el Ubuntu-package did it.
