### ISSUE TITLE
Keep backend and REPL in sync

### ISSUE THREAD

**Issue by cqfd** [commercialhaskell/intero#120]
For example, if you C-c C-l a source file and then switch to your test target, running C-c C-l on a test file will load the file in the old target's repl (which might not work, e.g. if the tests depend on QuickCheck but the source target doesn't). Killing the old repl buffer and starting a fresh one works though.

**Comment by chrisdone** [comment]
Should it do that?

**Comment by happy4crazy** [comment]
The initial thing that confused me was that when you switch targets, C-c C-t *does* work, but C-c C-l doesn't.

That said, I'm a little fuzzy on my desired workflow :) Would it make sense to have a repl buffer per target? If you start working on file F and press C-c C-l, do you always want to load it within a particular target? (I'm not too familiar with cabal. For simple setups, I assume each file lives in only one target?) I guess I can imagine intero keeping track of a mapping from file F to target T, and remembering to C-c C-l into `*intero:project:T:repl*`, but maybe there are edge cases that make that workflow not quite work?

Practically speaking though, I'm all set now that I know I can just kill a repl that's no longer on target.

**Comment by fosskers** [comment]
Personally, I'd like whatever module I'm in to "just compile", regardless of if target switching needs to happen in the background or not.

**Comment by meditans** [comment]
But isn't the variable `intero-targets` buffer-local when setted? I was under the impression that an `intero-targets` is associated to each file, and when you invoke the repl it just uses the targets which happen to be selected (ad least, that probably would be the optimal behaviour for me).

**Comment by chrisdone** [comment]
The `intero-targets` variable is set in the process buffer for the backend. When launching the REPL it uses that buffer-local variable for the targets. 

The "missing" behavior for this ticket is to _re-launch_ the REPL when changing targets.

**Comment by happy4crazy** [comment]
One reason why I think I'd like to have a repl per target is that if you kill an old repl, you lose any repl state you built up. With that scenario in mind, I don't really want intero to *automatically* relaunch the repl if I switch targets, since at least with the current design I have a chance to realize, nah, I want to keep that repl state around. Having intero launch a *new* repl would be fine though.

**Comment by fosskers** [comment]
Target switching is still awkward :S

**Comment by mgsloan** [comment]
My preference for this is:

1) Don't auto-switch repl.  Instead support switching directly in the repl https://github.com/commercialhaskell/intero/issues/39 

2) Have a command that automatically sends `:load <file>` or `:add <file>` to the repl, for the current buffer.

**Comment by chrisdone** [comment]
We may have to compromise and make it just restart the REPL when switching targets or run `intero-restart` -- it's an inconsistency in user experience that these two aren't in sync. You have to restart your REPL anyway when you install new dependencies, for example.

**Comment by chrisdone** [comment]
> The initial thing that confused me was that when you switch targets, C-c C-t does work, but C-c C-l doesn't.

and

> Personally, I'd like whatever module I'm in to "just compile", regardless of if target switching needs to happen in the background or not.

Lend support for this approach. I have the same experience; I'll restart with `M-x intero-restart` and then be temporarily confused when `C-c C-l` doesn't work. I'm marking this as a bug. At least the REPL can be re-started without killing or wiping the REPL buffer or its history.

**Comment by chrisdone** [comment]
The REPL now restarts when the backend restarts. The REPL buffer itself is not erased, its content preserved.
