### ISSUE TITLE
Inserting the type info on line above

### ISSUE THREAD

**Issue by Tehnix** [commercialhaskell/intero#121]
I often used the insert type feature which I think stems from `ghc-mod`, it would be cool to have it here too. 

Since I just switched from VIM to emacs I'm afraid my elisp foo is a bit lacking, but I'd imagine it would just be capturing the output from the show type info (`C-c C-t`) and then inserting it on the line above the point.

Or is this already there behind some hidden keybinding?

**Comment by meditans** [comment]
I can access it via the universal argument, with `C-u C-c C-t` (or `SPC u C-c C-t` if you use spacemacs). Does it work for you?

**Comment by chrisdone** [comment]
@Tehnix Did @meditans's answer solve your problem?

**Comment by Tehnix** [comment]
Ah, yeah that works! Thanks a bunch :)

@chrisdone Heh, was actually in the middle of writing a reply :) It can be closed, although if someone feels like it, can they explain how the universal argument knows to insert the information from `C-c C-t`? :O

**Comment by chrisdone** [comment]
@Tehnix cool, I documented this hidden behavior in the type. It's a normal pattern borrowed from haskell-mode, so I forgot to document it. 🙈
