### ISSUE TITLE
Installation fails (obsolete `stack` ?)

### ISSUE THREAD

**Issue by ocramz** [commercialhaskell/intero#125]
$ stack --version    
    Version 1.1.2 x86_64 hpack-0.14.0

Starting from the minimal `init.el` provided at https://commercialhaskell.github.io/intero/ and an empty `elpa` directory, `intero` can't install and shows this message: 
```
Usage: stack ghci [TARGET] [--ghc-options OPTION] [--with-ghc GHC] [--no-load]
                  [--package ARG] [--main-is TARGET]
  Run ghci in the context of project(s) (experimental)

<snip>

  stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-load --no-build 
--ghci-options -odir=/var/folders/n0/zx3dkw3d2hd3x59rjk3gtj5r0000gn/T/intero35060d9d 
--ghci-options -hidir=/var/folders/n0/zx3dkw3d2hd3x59rjk3gtj5r0000gn/T/intero35060d9d
```

I guess it's due to an obsolete version of stack? Arguments mismatch? The `intero` page doesn't mention any dependencies AFAICS.

Thanks in advance

**Comment by chrisdone** [comment]
Yeah, that's an old stack. I'll open an issue to track adding some version detection so that it can inform the user. Thanks!

**Comment by ocramz** [comment]
OTOH, `stack upgrade` says `Already at latest version`, and Hackage too shows 1.1.2 to be the latest. Where do I get the latest-latest working Stack?

**Comment by chrisdone** [comment]
I think the version of `stack` in your terminal is correct, but the one being launched by Emacs is old. Try the following:

    $ stack ghci --help
    $ which stack

And then try the same in Emacs with `M-:`. 👍 

The output in your terminal will have `--no-build`, but the one in Emacs should be like the one you pasted above.

**Comment by ocramz** [comment]
@chrisdone Yes, figured out thank you. Old `stack` was installed in /usr/bin and Emacs was still referring to that. Now I removed the old binary, adjusted the Emacs paths to GHC in `exec-path` and it works. I find this disconnect of Emacs from the underlying system still counterintuitive and a bit disturbing. Thanks for the help!
