### ISSUE TITLE
TypeApplications parse error

### ISSUE THREAD

**Issue by acowley** [commercialhaskell/intero#126]
Given a nightly resolver (I used `resolver: nightly-2016-06-21`) to use GHC-8.0.1, and this source,

```
{-# LANGUAGE TypeApplications #-}
module Main where

test = Nothing @ Int

main :: IO ()
main = putStrLn "hello world"
```

I get a flycheck error,

```
Parse error: @
Found:
    module Main where
    
  > test = Nothing @ Int
    
    main :: IO ()
```

Though loading the file into the repl works fine.

**Comment by chrisdone** [comment]
Is that a hlint error?

**Comment by chrisdone** [comment]
Yeah, this works fine with GHC 8. That output looks like hlint output. It should only be a warning, right?

**Comment by chrisdone** [comment]
I've removed hlint from next-checkers, as it seems to just annoy or confuse people.

**Comment by acowley** [comment]
Ah, drat you're surely right and I should have figured that out. I actually somewhat like having hlint available as it makes some useful suggestions, but you're right in moving it off the default configuration. Parse errors are kind of a deal breaker.

**Comment by ndmitchell** [comment]
@chrisdone - is it just the parse errors? You can always opt to ignore them by default.

**Comment by emmanueltouzery** [comment]
I really like having the hlint errors inline. I'm not really good with elisp..
How could I revert the previous setup in my config? I've currently actually edited the intero.el in my config, to manually revert this commit...

**Comment by cydparser** [comment]
@emmanueltouzery, the following works for me: `(setf (flycheck-checker-get 'intero 'next-checkers) '((warning . haskell-hlint)))`

**Comment by emmanueltouzery** [comment]
@cydparser thanks a lot, doesn't yet work for me right now. I've added:

    (require 'flycheck)
    (require 'intero)

but I still get:

    (Spacemacs) Error in dotspacemacs/user-config: Symbol’s function definition is void: \(setf\ flycheck-checker-get\)

I guess I miss just an extra `require` or something trivial like that...

**Comment by cydparser** [comment]
@emmanueltouzery try this:
```elisp
  (with-eval-after-load 'intero
    (setf (flycheck-checker-get 'intero 'next-checkers) '((warning . haskell-hlint))))
```

**Comment by emmanueltouzery** [comment]
@cydparser thank you! But that doesn't help, also I'm using your spacemacs layer, pulled from it and I get:

    Error (use-package): intero :config: Symbol’s function definition is void: \(setf\ flycheck-checker-get\)

using emacs 25 but I doubt it has anything to do with that...

**Comment by emmanueltouzery** [comment]
tried to make this work but I can't :-(

**Comment by emmanueltouzery** [comment]
Ok this works for me:

      (flycheck-add-next-checker 'intero
                                 '(warning . haskell-hlint))

\o/

**Comment by unhammer** [comment]
I noticed someone complaining about the above giving errors on emacs startup (since it requires intero and flycheck loaded); this should fix that:

```
 (with-eval-after-load 'intero  
   (with-eval-after-load 'flycheck 
     (flycheck-add-next-checker 'intero '(warning . haskell-hlint))))
```
