### ISSUE TITLE
Graceful failure when no stack.yaml

### ISSUE THREAD

**Issue by conal** [commercialhaskell/intero#128]
I'm starting to use Intero. Looks great so far! However, I'm having trouble with non-stack projects. Since Intero assumes Stack, I think I just want `intero-mode` to step aside gracefully when there's no stack.yaml, falling back to `interactive-haskell-mode`. Instead, I have to turn off `intero-mode` explicitly and turn `interactive-haskell-mode` back on. Operator error? Expected behavior? Workarounds?

**Comment by chrisdone** [comment]
Right, it is meant as a replacement for HIM, it could fallback to that if
there's no stack.yaml, though the difference in user experience is likely
to be jarring. Another option would be to offer to run stack init to make a
stack.yaml.

I'll come back to this when I'm at my keyboard! :-)

**Comment by conal** [comment]
I'm working with some projects that use Stack and some that don't. The ones that don't may require a fair amount of effort to get a working stack.yaml. I imagine that this mixture is fairly common. I think what I'd like is to use intero-mode when possible and HIM otherwise. I could just leave `intero-mode` out of my `haskell-mode-hook` and invoke it manually, but I assume I'd have to do so for every module in a given project.

**Comment by chrisdone** [comment]
I intend on remaining independent of haskell-mode directly for the forseeable future. 

How about a customizable variable that disables activating intero-mode, which you could put in a `.dir-locals.el` file in the root of your projects for which intero shouldn't be activated?

**Comment by chrisdone** [comment]
Actually it seems that buffer local variables are triggered _after_ mode hooks.

**Comment by chrisdone** [comment]
@conal A workaround looks like this, pop it in a `.dir-locals.el` in your stackless project:

``` lisp
((haskell-mode . ((eval . (intero-mode -1)))))
```

**Comment by conal** [comment]
Thanks! I didn't know about `.dir-locals.el`. Looks very useful. I'm trying another route: a `haskell-mode-hook` that adds `intero-mode` only if there's a project stack file:

```lisp
;; Like haskell-cabal-find-file
(defun haskell-stack-find-file ()
  (let ((stack (concat (file-name-directory (haskell-cabal-find-file))
                       "stack.yaml")))
    (and stack (file-exists-p stack) stack)))

(defun intero-mode-if-stack ()
  (if (haskell-stack-find-file) (intero-mode)))

(package-install 'intero)

;; (add-hook 'haskell-mode-hook 'intero-mode)

(add-hook 'haskell-mode-hook 'intero-mode-if-stack)
```
Works fine so far.
