### ISSUE TITLE
Add hoogle support

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/intero#129]
The next version of stack will support a `hoogle` command, currently available on `master`.

```
bash-3.2$ stack hoogle 'a -> Maybe a'
Just :: a -> Maybe a
fromJust :: Maybe a -> a
isJust :: Maybe a -> Bool
```

This presents a good deal of features "for free":
1. Support `C-h f`-style documentation lookup for the ident at point.
2. Support a search-as-you-type buffer (or helm-like-driven).
3. An additional completion source.
4. Capability to automatically import the module necessary for a given identifier when GHC reports "not in scope". 

And possibly other things I haven't thought of.

I will implement it in the same way as `stack ghci --with-ghc intero`: open a process buffer, run hoogle server inside it with a randomly generated available port, and then talk to it via the port and the JSON API. Example locally:

```
$ stack hoogle -- server  --port 3000 --local
$ curl 'http://localhost:3000/?hoogle=a%20-%3E%20Maybe%20a&mode=json'
```

The HTML in the results can be stripped out with a trivial regex (although another option may be to propertize the text too):

```
[{"url":"file:///Users/chris/.stack/programs/x86_64-osx/ghc-7.10.3/share/doc/ghc/html/libraries/base-
4.8.2.0/Prelude.html#v:Just","module":{"url":"file:///Users/chris/.stack/programs/x86_64-osx/ghc-
7.10.3/share/doc/ghc/html/libraries/base-4.8.2.0/Prelude.html","name":"Prelude"},"package":
{"url":"file:///Users/chris/.stack/programs/x86_64-osx/ghc-7.10.3/share/doc/ghc/html/libraries/base-
4.8.2.0/","name":"base"},"item":"<span class=name><0>Just</0></span> :: a -&gt; Maybe 
a","type":"","docs":""}
```

**Comment by meditans** [comment]
Can we try this already with the git versions of `stack` and `intero`? What remains to be done?

**Comment by chrisdone** [comment]
@meditans what remains is setting up launching and installing/setting up of hoogle automatically from inside intero, without necessarily bothering people who don't want it. It takes some time to make it friendly and robust, but I haven't had much time to dedicate to it recently.

`stack hoogle` works with the latest stack release. intero needs a few internal functions implemented.

**Comment by tepf** [comment]
It would be great to just point at a function and have it's documentation open locally.

**Comment by chrisdone** [comment]
I'm not sure this is going to happen.
