### ISSUE TITLE
What causes C-c C-t to stop working?

### ISSUE THREAD

**Issue by saurabhnanda** [commercialhaskell/intero#130]
(noob alert)

A number of times pressing C-c C-t (or even C-c C-i) throws up a "not in scope" or "couldn't guess module" error. Why? How can I fix it?

**Comment by chrisdone** [comment]
Usually that means the module couldn't be compiled by flycheck, which needs to happen for type info to be collected.

**Comment by saurabhnanda** [comment]
Hmm... what happens if I'm in the middle of my development and really need
the compiler/flycheck to help me with some types, to be able to complete
the development?

**Comment by chrisdone** [comment]
It remembers type info from previous checks, but there has to have been a valid check.

**Comment by saurabhnanda** [comment]
Is this the appropriate place to ask such questions?

**Comment by chrisdone** [comment]
Sure. 👍
