### ISSUE TITLE
Hlint fails to parse file when loading literate Haskell file

### ISSUE THREAD

**Issue by abailly** [commercialhaskell/intero#134]
When working with intero on a literate Haskell file, the following message pops up in minibuffer:

```
Suspicious state from syntax checker haskell-hlint: Checker haskell-hlint returned non-zero exit code 1, but no errors from output: hlint: In file /Users/arnaud/projects/murex/rtdb-spark/cvar/flycheck_Model.lhs at line 1: comment line before program line.


Checker definition probably flawed.
```

**Comment by chrisdone** [comment]
hlint is now not enabled by default with intero. I suggest pulling the latest Emacs Lisp! 

If you really want hlint on, then [this comment](https://github.com/commercialhaskell/intero/issues/126#issuecomment-228612696) shows how to enable it manually via the proper flycheck way.

**Comment by abailly** [comment]
Thanks a lot for lightning-fast answer. I am ok with not using hlint.
