### ISSUE TITLE
Does intero ignore the cabal file settings?

### ISSUE THREAD

**Issue by minad** [commercialhaskell/intero#135]
I am using some default-extensions and ghc-options. But intero in emacs doesn't show any Wall warnings. Only if I add {-# OPTIONS -Wall #-} to the head of the file I am looking at. Is this not yet implemented or am I missing something?

**Comment by chrisdone** [comment]
Is it perhaps the section in the cabal file?

**Comment by minad** [comment]
I am using the executable section. Should I use the library section?

**Comment by chrisdone** [comment]
Are you loading a file which is part of the section in the cabal file which specifies -Wall?

**Comment by minad** [comment]
I open files with emacs+intero from the library and executable sections which specify ghc-options. Then emacs doesn't show the -Wall warnings (it seems to use ghc defaults).

What do you mean by loading? Within the repl?

**Comment by mjrussell** [comment]
Im sorry I know this is a really old issue but I think I have a similar question. 

Im currently playing with Intero to see if it could be used with an Atom plugin and Im currently running intero in the repl (`stack exec intero`). I use stack with sub packages and inside those packages are `default-extensions` and `ghc-options`. Is there anyway to start up intero with those settings automatically or load them in from a file (stack/cabal/package)? Currently Im doing `stack exec intero -- -XSomeExtension` and its a bit tedious.

Thanks!

**Comment by mgsloan** [comment]
@mjrussell Try `stack ghci --with-ghc intero`

**Comment by mjrussell** [comment]
Interesting, I ran it from the root folder and it gave me a bunch of candidate main modules to load (and then complained because of duplicate modules within each sub package). But it clearly was trying to load the options. Its almost like I'd rather start it without picking up the packages and then manually set/unset within intero to avoid clashing

**Comment by mgsloan** [comment]
I agree that it would be really cool to have intero be able to load stack targets after it's started - see https://github.com/commercialhaskell/intero/issues/39

**Comment by mjrussell** [comment]
Ok I finally got it behaving properly when settings targets. Looks like its possible with emacs integration but they just kill and restart intero. 

👍 thanks for helping me understand whats going on here.
