### ISSUE TITLE
M-. and M-, not working as expected

### ISSUE THREAD

**Issue by saurabhnanda** [commercialhaskell/intero#137]
Following up from the discussion at #104 here's what I've found:
- `(fboundp 'xref-push-marker-stack)` at https://github.com/commercialhaskell/intero/blob/9049a0ad7cb8282cdc41fe47d2d4690898794b63/elisp/intero.el#L233 evaluates to `t` when evaluated via `M-x eval-expression`
- `xref-push-marker-stack` and `xref-pop-marker-stack` when evaluated manually, work as expected
- However, `M-,` does not work as expected.

I believe this is a bug. I'm in spacemacs which uses Emacs 24.5.1

**Comment by kRITZCREEK** [comment]
@saurabhnanda if you're using evil pop-mark is bound to `C-o`. Could you give that a try?

**Comment by saurabhnanda** [comment]
@kRITZCREEK `C-o` is bound to `open-line` I tried search for anything that matches `pop-mark` and found the following. Tried all, but nothing worked:

`xref-pop-marker-stack`
`pop-mark-tag`
`pop-global-mark`
`pop-to-mark-command`

**Comment by kRITZCREEK** [comment]
In Evil at least, C-o is bound to evil-jump-backwards. I guess in emacs
editing Mode I can't help you, Sry.
Am 06.07.2016 7:30 vorm. schrieb "Saurabh Nanda" <notifications@github.com>:

**Comment by saurabhnanda** [comment]
@kRITZCREEK tried running `evil-jump-backward` and `evil-jump-forward` manually, but nothing worked. Is it supposed to work? To my newbie eye it seems that `M-.` is using some other component to maintain the jumps (xref?) and not evil.

**Comment by saurabhnanda** [comment]
I've upgraded to the latest version of Intero and now `xref-pop-marker-stack` works, but `M-,` doesn't seem to be bound to that command.

**Comment by RasmusWL** [comment]
@saurabhnanda just stumbled upon this issue. If you're still having trouble, could you try to do the following?

`M-x help <enter> k <enter> M-,` while `intero-mode` is active? This should show you the current keybinding of `M-,`
