### ISSUE TITLE
What's the expected behavior of loading modules at start?

### ISSUE THREAD

**Issue by parsonsmatt** [commercialhaskell/intero#140]
Starting GHCi with Intero doesn't load the type information at first. Instead, Intero has to reload and recompile the module using `:load`.

I'll get a minimal reproduction project together soon if this isn't expected, but currently I have the following behavior:

```
$ stack build intero
$ stack ghci --with-ghc intero
... lots of output scrolls by as it compiles and loads the project, finally printing:
[19 of 19] Compiling Main             ( /home/matt/Projects/foobar/app/Main.hs, interpreted )
Ok, modules loaded: ... Worker, ...
```
At this point I expect to be able to do `:type-at`, since it says the module is loaded. Here's the interaction I have:

```
λ> :type-at Worker 27 17 27 17 runWorker
Couldn't guess the module name. Is this module loaded?
λ> :type-at Worker.hs 27 17 27 17 runWorker
Couldn't guess that module name. Does it exist?
λ> :type-at src/Worker.hs 27 17 27 17 runWorker
Couldn't guess that module name. Does it exist?
```

The issue is solved by reloading and recompiling:

```
λ> :load Worker
... lots of output scrolls by as it recompiles everything ...
λ> :type-at Worker 27 17 27 17 runWorker
runWorker :: IO ()
```

This is with 0.1.15 version of Intero.

**Comment by chrisdone** [comment]
I think perhaps 0.1.16 might succeed. 😄

**Comment by chrisdone** [comment]
Context: https://github.com/commercialhaskell/intero/commit/eccf4eb16c7dc577414521130dad4f87c6966565
