### ISSUE TITLE
Intero REPL should be only modifiable after the prompt.

### ISSUE THREAD

**Issue by crocket** [commercialhaskell/intero#144]
Intero REPL currently allows users to modify everything in the REPL buffer, and it is inconvenient.
Most users would want the prompt and the lines above the prompt to be unmodifiable by default.
I want to be able to modify texts only after the prompt.
Since I don't remember a time when I wanted to modify the prompt and the lines above the prompt, it'd be safe to make it impossible by default to modify the prompt and the lines above.

**Comment by chrisdone** [comment]
Popping this down as low prio. I originally set the prompt to read-only, but had trouble where it applied it globally to all comint buffers. If anyone with Elisp-fu wants to try, please PR.
