### ISSUE TITLE
How to build the complete project with Intero?

### ISSUE THREAD

**Issue by saurabhnanda** [commercialhaskell/intero#145]
Intero keeps compiling my file as I edit it (due to flycheck?), which is pretty cool. However, sometimes that isn't enough. Suppose, I change a function's type, which makes some code in a different file break. The only way to find out is to open that file and trigger a flycheck recompile. 

Alternatively, is there any way to trigger a full project build using 'stack build', such that one can cycle through all the errors and warnings?

PS: The key binding in haskell-layer used to be `M-m m c b` IIRC.

**Comment by chrisdone** [comment]
My flycheck fork on my GitHub will show errors and warnings from other
modules. I made a PR for the flycheck repo but so far it has been left
gathering dust. I'm going to be patient for a little while longer before
forking flycheck.

Regarding compiling the whole project I'm going to add stack build support,
and hopefully somehow integrate it with flycheck.

**Comment by chrisdone** [comment]
I opened two issues here: #146 and #147  to deal with these two use-cases.
