### ISSUE TITLE
Make a `stack build` command

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/intero#146]
Which will use `compliation-mode`, but maybe also integrate with flycheck using clever invocations. _Waves arms mystically_

**Comment by chrisdone** [comment]
Pinging @saurabhnanda.

**Comment by mrBliss** [comment]
I use [ebal](https://github.com/mrkkrp/ebal) (which uses `compilation-mode`) for this. It doesn't integrate with flycheck though.

**Comment by WraithM** [comment]
I just use `(add-hook 'haskell-mode-hook (setq compile-command "stack build --fast --test --bench --no-run-tests --no-run-benchmarks"))` and the normal `compile` and `recompile` commands. This works great for the most part. It'd be nice if this integrated into flycheck well. Sometimes it feels like compilation-mode and intero-mode are fighting over flycheck, but maybe my flycheck configuration is wrong.
