### ISSUE TITLE
Deal with the errors-from-other-buffers problem once and for all

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/intero#147]
Flycheck does not display errors from other files which were imported by the current file. This is problematic. I [opened a PR](https://github.com/flycheck/flycheck/pull/972) for this, but it has lingered for one month.

Let's give it a little more time, and then if nothing happens, we'll just have to 
1. Fork flycheck. Call it `intero-flycheck`.
2. Make it a rebase upon upstream flycheck.
3. Add the feature ontop of recent flycheck.

If the flycheck maintainers eventually merge this patch, we make `intero-flycheck` an alias for `flycheck` and phase it out. There will likely be other enhancements made for flycheck.

**Comment by chrisdone** [comment]
Going to take months to get anywhere going via flycheck. This simple change took two months and about 4 PR's, the author simply doesn't have time to maintain the project. Other issues like hooking into `stack build`, `stack test` and adding refactor buttons into messages are more things which are likely to require upstream modifications.

As such, I'll look into a straight-forward way to fork it for Intero's purposes. Hopefully while still rebasing ontop of flycheck, which will enable fixes and facilitate and eventual re-merge upstream.

**Comment by chrissound** [comment]
It seems this should be fixed by https://github.com/flycheck/flycheck/pull/1427

**Comment by purcell** [comment]
> It seems this should be fixed by flycheck/flycheck#1427

Indeed, we've now tackled this. :tada:
