### ISSUE TITLE
Emacs+Intero doesn't reload file if changed externally

### ISSUE THREAD

**Issue by minad** [commercialhaskell/intero#148]
If I am using intero and change the file externally for example using git, the file isn't reloaded in emacs. I don't expect intero to change such editor behaviour. Is there a reason for that?

**Comment by chrisdone** [comment]
That's because we save the file periodically for flycheck and that causes
emacs to ask to revert when you make an editing change. We reset the last
modified to nothing to avoid this, but it conflicts with magit.

The good news is I may have just thought of a solution while writing this
reply.

**Comment by minad** [comment]
Great to hear! I am looking forward to a solution. But for now I am already pretty happy with intero (except for the issue #135 which I am still having). Many thx for the tool!

**Comment by LukeHoersten** [comment]
I'm having a similar issue but I don't use magit:
https://github.com/haskell/haskell-mode/issues/1372

**Comment by minad** [comment]
I am also not using magit. If I am changing a file externally, it is not reloaded. Usually emacs detects this and asks me if I want to reload.

**Comment by cocreature** [comment]
Any news on this? I keep screwing things up because I’m so used to magit.

**Comment by chrisdone** [comment]
I'm a bit stuck on a simple way to do this. I thought I had a fix but I don't. I'll put some time aside and try to find a way.

**Comment by da-x** [comment]
How about instead of overriding the file, we would be saving the file to some `/tmp` location, and then use `LD_PRELOAD` to transparently redirect GHC to open the file from there? Would work on Linux at least... I wish there standard sandboxing APIs on the OS level for these kinds of feats.

**Comment by chrisdone** [comment]
Okay, I'm sitting down to take another crack at this with magit open so that I can test that the revert experience works out as normal.

**Comment by mgsloan** [comment]
One fix I've considered for this sort of thing is to add an additional .hs file include directory.  Then, populate this directory just with the buffers that have been edited.  Not sure how well this approach pans out in practice, but it's a hack worth considering.  I really don't like constantly saving the buffer, it can have some funky interactions with magit.

**Comment by chrisdone** [comment]
I didn't make heavy progress on this. One thing I was attempting was: open a fresh buffer, write to the same filename, and then reset the "last read" time on the original buffer to this one (this is like a revert but without resetting the buffer's variables and contents), so that the buffer thinks it's already on the latest version (which it technically is). I didn't get too far due to time constraints.

**Comment by chrisdone** [comment]
For years I used `C-c C-l` to check the file, which saves the buffer and then `:load`'s it, which didn't have unexpected behaviour with magit or the like. We just need to make the save both (1) proper (updating the modfiication information), and (2) not bothersome.

Bothersome means if we simply call save-buffer, then when you do `C-x C-s` and flycheck triggers a `flycheck-buffer` from the save hooks, we get into a loop. It may be easier just to attempt to resolve that loop in Emacs instead. I'll take a small crack at that.

**Comment by chrisdone** [comment]
Oh, this looks very promising:

``` lisp
(let ((before-save-hook nil)
      (after-save-hook nil)
      (auto-save-hook nil)
      (write-contents-functions nil)
      (write-file-functions nil))
  (save-buffer))
```

I thought I'd tried that in the past, but I must've screwed it up. This save works nicely and interacts properly with magit. 

**Remaining problem:** stop it from showing "Saving file X... Wrote file X.hs". 💭

**Comment by cocreature** [comment]
You could always use [shut-up](https://github.com/cask/shut-up/blob/master/shut-up.el) for that or extract the parts that are needed into intero.

**Comment by chrisdone** [comment]
[Fixed it!](https://github.com/commercialhaskell/intero/commit/4571743abd6bbfe301667e6a7d2330276ccd5ab6) We already [require Emacs 24.3](https://github.com/commercialhaskell/intero/blob/4571743abd6bbfe301667e6a7d2330276ccd5ab6/elisp/intero.el#L14), so we don't need any hacks. We just use the disabling flags that are available.

**Comment by cocreature** [comment]
Thanks a lot!

**Comment by da-x** [comment]
Cool, I tested it, and the behavior I get now is an auto-reload if I edit the file externally, but occasionally it would ask if I want to revert the buffer. Still better than before, as prompts prevents from lose any changes either way. 

BTW I do get "Wrote <filename>" messages appearing in the minibuffer during edits (emacs 24.5).  Would I need emacs 25 to shut it up? Or use 'shut-up'?

**Comment by chrisdone** [comment]
Hm, you're right. If I invoke the call manually I don't see a message, but from flycheck it seems to be displaying the message. Investigating...

**Comment by chrisdone** [comment]
Ahh. It doesn't appear in the log, but it does temporarily show it in the mini buffer. I guess I'll have to extract `shut-up` after all.

**Comment by cocreature** [comment]
There is a `save-silently` variable which seems to do the job correctly. Not sure which emacs version that was introduced in.

**Comment by chrisdone** [comment]
I pushed the change inspired by [this post](http://emacs.stackexchange.com/a/16982/2445). Can everyone check that it works for them?

* Open a fresh file.
* Check that it's clean in magit.
* Add a new decl like `x = 1`.
* Change it to `x = 1 []` to trigger a compile error.
* Delete it. Check that it goes away.
* Go to magit and see the `x = 1`. Discard the hunk.
* Switch back to the file and start typing, expect that it prompts to revert.

All the while there should be no messages in the minibuffer.

**Comment by chrisdone** [comment]
@cocreature That function doesn't exist in my emacs version (24.3).

**Comment by da-x** [comment]
Works with emacs 24.5. I've tested with an external editor (not having the habit of using magit much).

**Comment by chrisdone** [comment]
@da-x Great. Cheers!
