### ISSUE TITLE
Intero doesn't work on `stack` (like ghci) — it doesn't preprocess the library to create `cabal_macros.h`

### ISSUE THREAD

**Issue by Blaisorblade** [commercialhaskell/intero#149]
`stack ghci` works (though it loads slowly), but `intero` fails exactly like `stack exec -- ghci`, not finding `cabal_macros.h`:

```
/Users/pgiarrusso/Documents/Research/Sorgenti/stack/src/Network/HTTP/Download/Verified.hs:193:22:
     error: token is not a valid binary operator in a preprocessor subexpression
#if MIN_VERSION_retry(0,7,0)
    ~~~~~~~~~~~~~~~~~^
1 error generated.
intero: phase `C pre-processor' failed (exitcode = 1)
```

After running `stack ghci`, this seems to work, so I suspect the issue might be with generating `cabal_macros.h`, or with me having interrupted `intero` multiple times with `intero-destroy` during startup (it looked as if it was reinstalling `intero` again unexpectedly, while it was only installing the project dependencies — it's not like you can tell from the output).

**Comment by chrisdone** [comment]
Did you try `stack ghci --with-ghc intero` in the terminal?

**Comment by Blaisorblade** [comment]
That works. But `intero` uses `stack ghci --with-ghc intero --no-build --no-load`, and that fails (after stack clean) unless we start a build and get at least to `Preprocessing library stack-1.1.3...`.

Here's a transcript including interrupted processes that tries to show this:

```
$ stack clean
$ stack ghci --with-ghc intero --no-build --no-load
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Configuring GHCi with the following packages: stack
Intero 0.1.15 (GHC 7.10.3)
Type :intro and press enter for an introduction of the standard commands.

Prelude> :load src/Stack/Fetch.hs

/Users/pgiarrusso/Documents/Research/Sorgenti/stack/src/Network/HTTP/Download/Verified.hs:193:22:
     error: token is not a valid binary operator in a preprocessor subexpression
#if MIN_VERSION_retry(0,7,0)
    ~~~~~~~~~~~~~~~~~^
1 error generated.
intero: phase `C pre-processor' failed (exitcode = 1)
$ stack ghci --with-ghc intero
stack-1.1.3: unregistering (local file changes: src/Control/Concurrent/Execute.hs src/Data/Aeson/Extended.hs src/Data/Attoparsec/Args.hs src/Data...)
stack-1.1.3: configure
^Cuser interrupt
$ stack ghci --with-ghc intero --no-load
stack-1.1.3: configure
Configuring stack-1.1.3...
stack-1.1.3: build
Preprocessing library stack-1.1.3...
[ 1 of 86] Compiling Stack.FileWatch  ( src/Stack/FileWatch.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.5.0/build/Stack/FileWatch.o )
^Cuser interrupt
$ stack ghci --with-ghc intero --no-build --no-load
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Configuring GHCi with the following packages: stack
Intero 0.1.15 (GHC 7.10.3)
Type :intro and press enter for an introduction of the standard commands.

Prelude> :load src/Stack/Fetch.hs
```

**Comment by chrisdone** [comment]
Then we either need to remove the --no-build flag or generalize the startup
process which enables building if there's an error. Thanks for reporting.
I'll get to it when I'm back at my desk.

**Comment by Blaisorblade** [comment]
Hm, removing `--no-build` would increase startup times significantly—I was thinking of stopping at preprocessing, but 
I didn't find a proper way — `stack build --only-configure` stops too early, and not even `cabal` or `Setup.hs` offer only preprocessing :-(.

**Comment by chrisdone** [comment]
Wait, the codebase for Emacs is supposed to try restarting with `--no-build` removed when starting up fails. What happens in your Emacs?

**Comment by Blaisorblade** [comment]
Ignoring `--only-preprocess` (I can't tell if you disagree or just know it's hard), I think startup didn't fail "enough" for it. I got a Intero/GHCi prompt with next to no libraries loaded (see transcript section below).

Also, it seems there are technically two phases: "startup" (up to the first prompt) and what seems to be `:load currentFile.hs`. Only `:load` fails. I'm not sure, I just see a small delay between the two and this resembles what I have to do by hand with `stack ghci --with-ghc intero --no-build --no-load`.

BTW, the label `type: needs-repro` for this bug might be outdated, since now we know `stack clean` and C-c C-l is enough to produce this bug.

## Intero services also fail
Other symptoms: not only the REPL process fails, but also intero's backend, so that C-c C-t on top-level modules gives "Couldn't guess that module name. Does it exist?".

From *Messages* on `src/main/Main.hs`, after failing <kbd>C-c C-t</kbd>, <kbd>M-x</kbd> `intero-destroy`, <kbd>M-x</kbd> `revert-buffer` and new failing <kbd>C-c C-t</kbd>. BTW `intero-restart` after `intero-destroy` doesn't work and I don't see an `intero-start`.
Note in particular that it pretends to be booted up successfully which makes diagnosis harder — I'm sorry but I honestly conjectured something in intero broke altogether, instead of "this project doesn't load".
```
Intero process deleted.
Revert buffer from file /Users/pgiarrusso/Documents/Research/Sorgenti/stack/src/main/Main.hs? (y or n) y
Booting up intero ...
Booted up intero!
Couldn't guess that module name. Does it exist?
```

## Transcript
I've represented prompts by `>` below, though I mean the interrobang thingy—copy-paste omits it.

```
Starting:
  stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-build --no-load --ghci-options -odir=/var/folders/_7/hlxv4yv95x95vgnn416b4q4m0000gp/T/intero92806ewF --ghci-options -hidir=/var/folders/_7/hlxv4yv95x95vgnn416b4q4m0000gp/T/intero92806ewF stack
Intero 0.1.15 (GHC 7.10.3)
Type :intro and press enter for an introduction of the standard commands.

> 
/Users/pgiarrusso/Documents/Research/Sorgenti/stack/src/Network/HTTP/Download/Verified.hs:193:22:
     error: token is not a valid binary operator in a preprocessor subexpression
#if MIN_VERSION_retry(0,7,0)
    ~~~~~~~~~~~~~~~~~^
1 error generated.
intero: phase `C pre-processor' failed (exitcode = 1)
 1

<interactive>:3:1: Warning:
    Defaulting the following constraint(s) to type ‘integer-gmp-1.0.0.0:GHC.Integer.Type.Integer’
      (GHC.Num.Num a0) arising from a use of ‘it’ at <interactive>:3:1
      (GHC.Show.Show a0)
        arising from a use of ‘System.IO.print’ at <interactive>:3:1
    In the first argument of ‘System.IO.print’, namely ‘it’
    In a stmt of an interactive GHCi command: System.IO.print it
1
> show 1

<interactive>:4:1: Not in scope: ‘show’
> 1 + 2

<interactive>:5:3: Not in scope: ‘+’
>
```

**Comment by chrisdone** [comment]
This should be fixed in latest stack.

**Comment by saurabhnanda** [comment]
I seem to have hit the same error. `stack build` works on the command line, but `C-c C-l` throws the following error in Intero:

```
<built-in>:17:10: error:
     fatal error: 'dist/build/autogen/cabal_macros.h' file not found
#include "dist/build/autogen/cabal_macros.h"
         ^
1 error generated.
`gcc' failed in phase `C pre-processor'. (Exit code: 1)
```

What's the fix?
