### ISSUE TITLE
Feature request: "imported from"

### ISSUE THREAD

**Issue by parsonsmatt** [commercialhaskell/intero#150]
Given a command like:

`:imported-from Foo 5 7 5 13 liftIO`

and a file like:

``` haskell
module Foo where

import Control.Monad.Reader

foo = liftIO (putStrLn "hello world")
```

It'd be cool to see a response like:

`liftIO:Control.Monad.Reader`

**Comment by chrisdone** [comment]
What do you think about `C-c C-i` (`M-x intero-info`)?

**Comment by chrisdone** [comment]
Ah, that gives definition information. This issue is about the particular import line.

**Comment by chrisdone** [comment]
PR welcome at this point. I'm not likely to work on it.
