### ISSUE TITLE
"Wrong number of arguments" on intero-repl-load

### ISSUE THREAD

**Issue by elvis-sik** [commercialhaskell/intero#153]
Hi. I am trying to use intero. I run `stack new foobar` to create a new project, and then I open some random `.hs` file on it.

I get a `Intero is not installed in the Stack environment.` message, then it proceeds to install intero, and I am prompted with `Booted up intero!`. Then I try evaluating `intero-repl-load` and get the following:

```
apply: Wrong number of arguments: (lambda (f) (let ((buffer (current-buffer))) (funcall f) (pop-to-buffer buffer))), 2
```

But if I run `M-x intero-repl` I get a working repl.

I am not very knowledgeable about how this all works. I tried messing around to see if I could get any hint on this, but I wasn't succesful. Any pointers would be appreciated.

Thanks

**Comment by chrisdone** [comment]
Ah, I don't reproduce this error. Can you run `M-x toggle-debug-on-error` and re-run the `intero-repl-load` command and copy/paste the backtrace here?

**Comment by korayal** [comment]
I'm having the same issue. Below is the debug output:

```
Debugger entered--Lisp error: (wrong-number-of-arguments (lambda (f) (let ((buffer (current-buffer))) (funcall f) (pop-to-buffer buffer))) 2)
  haskell-intero//preserve-focus(#[(&optional prompt-options) "\303 \210\304 \305!r	q\210\306\307p!\310\n\311Q\"\210)\312	!*\207" [prompt-options repl-buffer file save-buffer intero-buffer-file-name intero-repl-buffer comint-send-string get-buffer-process ":l " "\n" pop-to-buffer] 5 ("/home/korayal/.emacs.d/elpa/intero-20160710.2349/intero.elc" . 19393) "P"] nil)
  apply(haskell-intero//preserve-focus #[(&optional prompt-options) "\303 \210\304 \305!r	q\210\306\307p!\310\n\311Q\"\210)\312	!*\207" [prompt-options repl-buffer file save-buffer intero-buffer-file-name intero-repl-buffer comint-send-string get-buffer-process ":l " "\n" pop-to-buffer] 5 ("/home/korayal/.emacs.d/elpa/intero-20160710.2349/intero.elc" . 19393) "P"] nil)
  intero-repl-load(nil)
  call-interactively(intero-repl-load nil nil)
  command-execute(intero-repl-load)
```

**Comment by chrisdone** [comment]
What is `haskell-intero//preserve-focus`? Are you using spacemacs or some kind of wrapper library?

**Comment by elvis-sik** [comment]
I am using spacemacs.

**Comment by chrisdone** [comment]
Can you report this upstream to the author of the spacemacs binding? We recently updated the `haskell-repl-load` function. Perhaps this would be a good time to work out a way to keep in sync with the spacemacs people.

**Comment by TheBB** [comment]
Thanks, pending fix in https://github.com/syl20bnr/spacemacs/pull/6550.
