### ISSUE TITLE
Browse local Haddock HTML documentation inside Emacs

### ISSUE THREAD

**Issue by korayal** [commercialhaskell/intero#156]
It seems viewing haddock documents in haskell-mode is already supported, but it doesn't work with sandboxes (https://github.com/haskell/haskell-mode/issues/1134) hence, no support for Stack.

It would be great to have an option to not leave the Emacs window for documentation and haskell-mode does that with [w3m-haddock](https://github.com/haskell/haskell-mode/blob/master/w3m-haddock.el), but that too also doesn't work in intero because of the same issue.

**Comment by chrisdone** [comment]
`stack haddock` already exists! 💃  We already have the ability to find the haddock files:

```
bash-3.2$ stack exec -- ghc-pkg list 
/Users/chris/.stack/programs/x86_64-osx/ghc-7.10.3/lib/ghc-7.10.3/package.conf.d:
    Cabal-1.22.5.0
    ...

/Users/chris/.stack/snapshots/x86_64-osx/lts-6.4/7.10.3/pkgdb:
    Cabal-1.22.8.0
    QuickCheck-2.8.2
    ...

/Users/chris/Work/foo bar/foo/.stack-work/install/x86_64-osx/lts-6.4/7.10.3/pkgdb:
    foo-0.1.0.0

bash-3.2$ stack exec -- ghc-pkg --simple-output describe foo-0.1.0.0 | grep '^haddock-html:'
haddock-html: "/Users/chris/Work/foo bar/foo/.stack-work/install/x86_64-osx/lts-6.4/7.10.3/doc/foo-0.1.0.0"
```

I think the missing feature here is to browse Haddocks locally.

We could use the `eww` Emacs web browser (`eww-open-file`), and then apply some visual style to the output.

**Comment by chrisdone** [comment]
[`shr.el`](https://github.com/emacs-mirror/emacs/blob/master/lisp/net/shr.el) may be a simpler option, if we want to just render the page and have control over it. We could make `intero-haddock-mode`, for example.

**Comment by korayal** [comment]
Yep! the `inf-haskell.el` in haskell-mode is using `ghc-pkg` [directly](https://github.com/haskell/haskell-mode/blob/master/inf-haskell.el#L605). But since it's using the `haskell-package-manager-name` as the binary parameter of `call-process`, so it needs a minor update for `inferior-haskell-query-ghc-pkg` [function](https://github.com/haskell/haskell-mode/blob/master/inf-haskell.el#L638):

```
(defun inferior-haskell-query-ghc-pkg (&rest args)
  "Send ARGS to `haskell-package-manager-name'.
Insert the output into the current buffer."
  (setq haskell-stack-pm-params '("exec" "--" "ghc-pkg"))
  (apply 'call-process haskell-package-manager-name nil t nil (append haskell-stack-pm-params args)))
```
And it can successfully get the alist of all modules inside the project using [inferior-haskell-module-alist](https://github.com/haskell/haskell-mode/blob/master/inf-haskell.el#L700) which is stored in `/tmp`:

```
(
  ...
  ("Data.Aeson.Types" "aeson" "/home/korayal/.stack/snapshots/x86_64-linux/lts-6.6/7.10.3/doc/aeson-0.11.2.0")
  ...
)
```

But I think it fails to detect hidden modules, (which causes it to trigger opening an alternate search in the browser), It also fail to detect qualified imports but that's probably me using incomplete `stack ghci` command for inferior-haskell-mode.
