### ISSUE TITLE
intero-0.1.16 and master still requires 0.1.15 from hackage

### ISSUE THREAD

**Issue by Blaisorblade** [commercialhaskell/intero#159]
I thought this was still #142, but apparently not.
Here's the offending source code on 0.1.16 tag:
https://github.com/commercialhaskell/intero/blob/0.1.16/elisp/intero.el#L60
BTW, here's yet another copy:
https://github.com/commercialhaskell/intero/blob/0.1.16/elisp/intero.el#L12

Since c1ddcb20e07b513d7ce8792be6ed7fe88b1d6e5d, this is customizable:
https://github.com/commercialhaskell/intero/blob/master/elisp/intero.el#L66
That's excellent if you want to pin the intero version, but I'd rather not.

Is there a good reason or did you just forget?
Beyond the immediate issue, I'd suggest either automating the update at some point, or at least documenting the release workflow if one must update the version in N places by hand.

**Comment by chrisdone** [comment]
0.1.16 is not necessary for the functioning of the Emacs mode, so it's not worth forcing people to upgrade all their intero versions until Intero is updated with something that the Emacs mode needs. :+1: 

Is this causing you problems?

**Comment by Blaisorblade** [comment]
I naively expect that upgrading intero in emacs gets me (by default) the latest and greatest version of `intero`, with all the latest bugfixes, especially to issues I did encounter and report and that you fix! 😄 

Of course these aren't "problems", just annoyances, once I figure it out.

**Comment by acowley** [comment]
I was confused by this, too. I eventually did something like `stack build intero-0.1.16`. @chrisdone's point about the upgrade not being required makes sense. Perhaps there could be an `intero-upgrade` command in the emacs mode, but that might open the door to people having too new an `intero` for their `intero-mode` which would then probably need to trigger an update within emacs.

**Comment by k-bx** [comment]
Sorry, I am still confused. Why do I keep getting 0.1.15 installed even thus I use the latest MELPA elisp? Sorry if the question doesn't make sense.

**Comment by k-bx** [comment]
Ok, got it, because of https://github.com/commercialhaskell/intero/blob/master/elisp/intero.el#L66 and no reason to upgrade it yet. Roger.
