### ISSUE TITLE
Check error in `intero-project-root` function

### ISSUE THREAD

**Issue by marsam** [commercialhaskell/intero#165]
When the [stack command used `intero-project-root`](https://github.com/commercialhaskell/intero/blob/a20351f/elisp/intero.el#L1436-L1442) fails, it set the variable `intero-project-root` to the error output.
And given that some intero functions use the `intero-project-root` as `default-directory`, Emacs throws `cd: No such directory found via CDPATH environment variable`

**Comment by chrisdone** [comment]
Good catch! I'll fix.

**Comment by chrisdone** [comment]
Thanks!
