### ISSUE TITLE
Add option to disable company-mode

### ISSUE THREAD

**Issue by massysett** [commercialhaskell/intero#166]
I find company-mode irritating and I wish there were a way to disable it by default so that I don't have to disable it in every Haskell buffer manually.

Currently I have done this simply by editing out the (company-mode) in the appropriate `.el` file, though I am currently trying to figure out if there is a good way to modify packages installed with `package.el` without just copying out all the Emacs Lisp files and running them from my own `init.el`.

**Comment by chrisdone** [comment]
I can make a customization variable so that it doesn't auto-start company. 😅

**Comment by massysett** [comment]
Thanks very much.  For now I have discovered

    (add-hook 'intero-mode-hook (lambda() (company-mode 0)))

which works well enough.
