### ISSUE TITLE
intero repl doesn't know my functions

### ISSUE THREAD

**Issue by bixuanzju** [commercialhaskell/intero#171]
To reproduce, create a file with the following

``` haskell
module Lib
    ( someFunc
    ) where

someFunc :: IO ()
someFunc = putStrLn "someFunc"

fibs :: [Int]
fibs = 0 : 1 : zipWith (+) fibs (tail fibs)
```

Load this file using `intero-repl-load`, in the repl buffer, type `:t fibs`, an error occurs saying `<interactive>:1:1: Not in scope: ‘fibs’`.

If I add `fibs` to the module export list, or remove the module export list, then everything works. Is this a bug or a intended feature? How should I test some functions that are not meant to be exported in the library?

**Comment by chrisdone** [comment]
I think we can turn off -fobject-code when doing a load in the REPL.

**Comment by chrisdone** [comment]
That is, if you run `:set -fbyte-code` in the REPL and then load the module again, it should see the missing symbols. We need to send that automatically. `object-code` allows faster reloading, but at the expense of all information being available.

**Comment by bixuanzju** [comment]
@chrisdone Thanks for the explanation. What do you mean by "all the information being available"? I assume you mean those definitions imported from other modules? Could it be possible that just all the definitions contained in the present module available?

**Comment by chrisdone** [comment]
`fibs` is not exported, you can only get at it when you load the module _interpreted_. Which is what byte-code means in this context.

**Comment by Blaisorblade** [comment]
> object-code allows faster reloading, but at the expense of all information being available.

Just noticed `-fbyte-code` leading to all/most modules being reloaded from source — but why does `intero` not use `:reload` to speed that up?

**Comment by chrisdone** [comment]
@Blaisorblade Good idea. I've pushed a commit which switches to `-fbyte-code` in the REPL and runs `:reload` when any of the already loaded modules is the current buffer (via `:show modules`), otherwise it runs `:load` (which should happen once per buffer you're working on).

**Comment by chrisdone** [comment]
@Blaisorblade @bixuanzju @karljs Would you like to try it out?

**Comment by korayal** [comment]
I think this breaks `intero-repl-load`, after the upgrade whenever I run that command, emacs freezes. (no issues on other `pop-to-repl` `display-repl` commands.

**Comment by chrisdone** [comment]
Good catch, I'll look at it.

**Comment by chrisdone** [comment]
@korayal I don't reproduce that freezing behaviour. Do you have an example project?

**Comment by korayal** [comment]
@chrisdone unfortunately the one I'm getting these errors are closed-source. But i tried to run the same command below that gets stuck (the one that  I found in `ps`) in terminal, and I get errors like these:
```
<PROJECT_DIR>/.stack-work/install/x86_64-linux/lts-6.7/7.10.3/bin/intero --interactive -i -odir=<PROJECT_DIR>/.stack-work/odir -hidir=<PROJECT_DIR>/.stack-work/odir -hide-all-packages -i<PROJECT_DIR>/src -i<PROJECT_DIR>/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/autogen -i<PROJECT_DIR>/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build -stubdir=<PROJECT_DIR>/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build -package-id=base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d -package-id=tasty-0.11.0.3-edf0bd8df18cca6ef5e3c83ad13da9b4 -package-id=tasty-hunit-0.9.2-55c44e1cba391bbc422af69506b78bdd -package-id=tasty-quickcheck-0.8.4-4d7e6b0b58711c9ef8aa287b3a2eba42 -Wall -rtsopts -with-rtsopts=-N -odir=/tmp/intero25648VMC -hidir=/tmp/intero25648VMC -ghci-script=/tmp/intero-script25648iWI -optP-include -optP/tmp/ghci28538/cabal_macros.h
```

```
WARNING: it is HIGHLY RECOMMENDED to use intero with stack:

  To install:
    stack build intero

  To run with no project:
    stack exec intero
  To run with your project:
    stack ghci --with-ghc intero

Intero 0.1.15 (GHC 7.10.3)
Type :intro and press enter for an introduction of the standard commands.

<command line>: cannot satisfy -package-id tasty-0.11.0.3-edf0bd8df18cca6ef5e3c83ad13da9b4
    (use -v for more information)
```
but if I run `stack ghci --with-ghc intero` I can get to the REPL Prelude.
btw, the source of the buffer is just this:

```
module Exercises.Chapter9
    ( tests
    ) where


-------------------------------------------------------------------------------
import           Test.Tasty
-------------------------------------------------------------------------------

tests :: TestTree
tests = testGroup "Chapter9"
  [
  ]
```

**Comment by hawkish** [comment]
I can confirm the freezing behaviour.

**Comment by chrisdone** [comment]
In that case I'll revert this patch.

**Comment by hawkish** [comment]
Excellent! intero-repl-load works again after the commit. 

Back to work. Please let me know if I can help you in any way in finding the root cause of the issue.

**Comment by chrisdone** [comment]
I've switched intero to always start up with `-fbyte-code` enabled, no dynamic switching or anything fancy.

**Comment by saurabhnanda** [comment]
This change in behaviour has a huge downside when doing iterative coding (especially in webapps) where one need to evaluate the current file in the REPL a lot of times. It starts loading **all** dependant files from scratch, each time.

Can there be an easy switch in the spacemacs file to pick our own default REPL behaviour?

**Comment by chrisdone** [comment]
That's possible. It would require some UI additions to make the user aware that there is a choice. You can open an issue for that. I'm imagining something that displays at the top of the REPL perhaps and never moves to switch between "incremental mode" and "query mode", perhaps.
