### ISSUE TITLE
Haddock integration

### ISSUE THREAD

**Issue by angerman** [commercialhaskell/intero#178]
Could intero possibly support something like
`:doc <symbol>`
and spit out the symbol associated haddock
comment?[1]

If that could work, maybe intero could provide
`documentation-at-point` and show documentation
as

```
symbol :: a -> b -> c

---
<haddock comment>
----
defined at <file or module>:<line>
```

either in a overlay (as flycheck errors) or
popup like the quick-fix ui?

If this _is_ already possible, I'm sorry and would
much appreciate the respective pointers.
If this is however _not_ yet possible, could someone
outline the hurdles to overcome to make this possible?

---

[1]: as I understand right now, I can periodically run
haddock on my whole project and then try to lookup
in the generated documentation, but haddock is not
tightly integrated into the repl, similar to how python
has `help`.

**Comment by chrisdone** [comment]
There is stack hoogle which is on the master branch of stack. I was
intending on using that for doc lookup and general searching. See the open
issue somewhere on this issue tracker about hoogle.

**Comment by angerman** [comment]
I assume you are referring to #53 and #129. Maybe I'm misunderstanding hoogle then,
but would that pull haddocks on-the-fly from the current project I'm writing on?

Otherwise, I'd be getting only documentation for dependencies, or am I mistaken?

**Comment by chrisdone** [comment]
@angerman It generates a database by running `stack haddock` first. So that includes your local project libraries too. 

* Stack issue: https://github.com/commercialhaskell/stack/pull/2301

Example:

``` haskell
bash-3.2$ cd Emacs/packages/hindent/
bash-3.2$ stack hoogle reformat
reformat :: Style -> Maybe [Extension] -> Text -> Either String Builder
```

But it does require regular rebuilding of the haddocks! ☝️ 😏

**Comment by angerman** [comment]
Alright. That though does mean it won't include any docs from the module I'm working on. Otherwise we'd have to run haddock on each save? I guess for that intero would need to know about haddock comments and do the parsing on it's own. I guess at the core is the issue that the docs are not really part of haskell, but a convention that haddock picks up.

**Comment by chrisdone** [comment]
@angerman One possibility is having Intero scan for documentation after collecting type information.

**Comment by mgsloan** [comment]
I think it would be quite reasonable to yield haddocks from the last time they were generated for the project.

**Comment by acowley** [comment]
Not using `haddock` has the advantage of not using `haddock`, though 😀

If the display of documentation isn't going to have links or anything beyond inert text, skimming it off the source ourselves could be much more efficient that regular haddocking.

**Comment by angerman** [comment]
Maybe I should have put in a bit more history to highlight where this comes from. During the day I usually work in mobile app development with Xcode, and Xcode automatically parses the documentation header for functions as you type, and provides you with the documentation right away.

And yes as @acowley *just* the comment for the function would probably be enough without any special haddock specific processing.

**Comment by chrisdone** [comment]
Agreed with all comments so far. Both seeding from last generated haddocks
is reliable e.g imagine conditional compilation which haddock handles, and
scanning the source is an optimisation that could be added later but which
requires work by us to achieve.

**Comment by mgsloan** [comment]
Yeah, it may well make more sense to display the haddock text rather than attempting to render it or using an emacs web browser.  Hopefully it should be straightforward to extract out the code for detecting and associating `-- |` and `-- ^` comments.

**Comment by chrisdone** [comment]
Reducing Intero's scope, closing.
