### ISSUE TITLE
`intero-apply-suggestions` fixed incorrectly on evil-mode (Spacemacs)

### ISSUE THREAD

**Issue by korayal** [commercialhaskell/intero#180]
I'm not exactly sure if this is completely related to the evil-mode. But

When I make a deliberate error on the code like this:

```
x :: Intefer
x = 5
```
and after using keys `C-c C-r` and then `C-c C-c`, I get:

```
x :: Integerfer
x = 5
```

**Comment by chrisdone** [comment]
Thanks for reporting. Pinging @acowley

**Comment by chrisdone** [comment]
Indeed, it says:

```
There are 1 suggestions to apply:

Hit [C-c C-c] to apply these choices.

[x] Replace ‘type’ with ‘Integer’
```

That display is obviously wrong. I'll take a look at the code.

**Comment by chrisdone** [comment]
Oh, looks like @acowley already made a PR for this. I'll merge that.

**Comment by chrisdone** [comment]
Yep, that fixes it! :metal: 😆
