### ISSUE TITLE
Definition location gives errors to stdout instead of stderr

### ISSUE THREAD

**Issue by rikvdkleij** [commercialhaskell/intero#182]
For example when dependent module is not loaded yet so location fails to determine location, it gives this error message to stdout:
`Couldn't guess that module name. Does it exist?`

**Comment by chrisdone** [comment]
Do you want to submit a PR to fix this? There are a few locations where that message is printed. 

https://github.com/commercialhaskell/intero/blob/master/src/InteractiveUI.hs#L1680
https://github.com/commercialhaskell/intero/blob/master/src/InteractiveUI.hs#L1701

etc.

**Comment by rikvdkleij** [comment]
Yes, I will submit PR to fix this.

**Comment by chrisdone** [comment]
Tip top!
