### ISSUE TITLE
Not in scope errors highlight incorrectly on qualified imports

### ISSUE THREAD

**Issue by enolan** [commercialhaskell/intero#183]
If I write:

``` haskell
foo :: Int
foo = Data.Maybe.getFoo
```

I get the red underline under `Data`. It should be under the whole thing: `Data.Maybe.getFoo`. This is minor, but it makes it look at a glance like maybe the module isn't imported or doesn't exist when it's really `getFoo` that's wrong.

**Comment by acowley** [comment]
I think the bounds for that are coming from within `flycheck`, so this could be addressed either upstream or in the pending(?) fork of `flycheck` @chrisdone has expressed an intention of using.

See [here](http://stackoverflow.com/questions/25210958/specify-error-patterns-with-start-and-end-columns-in-emacs-flycheck) for an example of addressing just this problem.
