### ISSUE TITLE
Adding type signatures

### ISSUE THREAD

**Issue by tonyday567** [commercialhaskell/intero#187]
There's a few boiler-plate tasks after adding a type signature that could be integrated into applying the suggestion.  One is that the suggested sig from ghc often includes explicit existential qualifiers that can be removed.  Another is that pragmas are then needed like RankNTypes and KindConstraints.

A natural solution might be to offer a choice of type signature, with and without the forall, in the C-c C-c phase.  Adding pragmas needs a second pass of compilation once the signature gets added.  Would these be easy things to achieve?

**Comment by chrisdone** [comment]
It's possible to query intero for a better type without the explicit foralls using `:type-at` a la `C-c C-t`. It's a pity GHC prints its suggestions with that extra redundancy.
