### ISSUE TITLE
Intero-based refactorings

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/intero#188]
I fear that the parsing in #184 presents a _general_ challenge for a reliable solution. Consider:

``` haskell
{-# LANGUAGE FlexibleContexts #-}
{-# OPTIONS -Wall #-}
module X where

n :: (Show (a,a),
   Num a,Show a) => a
n = 1
```

This is valid code but the regex doesn't parse it. 

For features like this it might be more reliable and generally easier to shift the refactor part to Intero which is capable of parsing it, although not entirely capable of printing reliably, we can write our own printer for class constraints. 

Strawman proposal:

``` haskell
:rewrite-at redundant-constraints 5 1 5 1
n :: (Num a) => a
```

@acowley What do you think?

**Comment by acowley** [comment]
I like this a lot, not so much for this instance which is probably fixable, but as a general approach. It would be fantastic if Intero could provide the long sought after structured error messages from GHC.

**Comment by acowley** [comment]
Btw, I have elisp for doing better parsing of this kind of thing that I use elsewhere, but given the pushback here and in #190, should I just hold off on fixing this until you figure out how you'd rather do this sort of thing?

**Comment by chrisdone** [comment]
I'm not opposed to merging in better parsing meanwhile. Next week I'll probably be bugfixing on the repo rather than doing new features.

**Comment by acowley** [comment]
I think I fixed this on my fork yesterday. When I get a chance, I'm going to take a look at that effort Steve linked to do these auto-correct things as part of `flycheck` instead so that there's a home for it as Intero goes the haskell-ide-engine route. If the `flycheck` feature pans out, it will keep the emacs parts of Intero lighter. If the `flycheck` thing is stalled, a separate minor mode for text-based auto-correct support might make sense. 

The next GHC warnings I plan to support -- import list maintenance -- will again require syntax surgery, and I'd also like to consider making some `hlint` advice actionable as I do like a few of its hints.

**Comment by chrisdone** [comment]
> I think I fixed this on my fork yesterday. When I get a chance, I'm going to take a look at that effort Steve linked to do these auto-correct things as part of `flycheck` instead so that there's a home for it as Intero goes the haskell-ide-engine route. If the `flycheck` feature pans out, it will keep the emacs parts of Intero lighter. If the `flycheck` thing is stalled, a separate minor mode for text-based auto-correct support might make sense. 

I would prefer generally to lean on other externally maintained large quantities of elisp too. 

> The next GHC warnings I plan to support -- import list maintenance -- will again require syntax surgery, and I'd also like to consider making some `hlint` advice actionable as I do like a few of its hints.

Right, removing things from import lists should require a bit of parsing but not crazy level.

One thing I have planned in the feature which may overlap but not conflict is that with the hoogle server running (you probably noticed the code in there, but it's incomplete), we will be able to search for "not in scope" symbols and automatically hoogle search each of them and then suggest imports. So that workflow might be:

* Type `decodeUtf8`.
* Hit `C-c C-r`.
* See list like this:
  - [ ] `import Data.Text.Encoding`
  - [ ] `import Data.Text.Encoding (decodeUtf8)`
* See `Data.Text.Encoding` is in there.
* Apply (`C-c C-c`).
* An `import Data.Text.Encoding (decodeUtf8)` is added.

**Comment by tonyday567** [comment]
PR'ed #204 before I caught up with the above plan for imports.

I started down this path, but there is usually too much choice in what hoogle finds when it comes to which module to use.
