### ISSUE TITLE
Intero REPL buffer in Emacs has mangled prompt

### ISSUE THREAD

**Issue by AlainODea** [commercialhaskell/intero#193]
The REPL prompt inside a an Intero REPL prompt (raised with C-C C-L) looks like a **!** with a **?** superimposed on it.

Running **stack ghci --with-ghc intero --test** in a **shell** or **eshell** buffer shows a correct prompt as GHCi would show (like **Prelude>**).

Is this a known issue?

**Comment by bixuanzju** [comment]
It is a feature, ref #40

**Comment by mgsloan** [comment]
Yup, that's the interobang!

**Comment by chrisdone** [comment]
This seems answered! 😄

**Comment by AlainODea** [comment]
Right you are @chrisdone. Thank @mgsloan and @bixuanzju.
