### ISSUE TITLE
Quickfix does not always work correctly.

### ISSUE THREAD

**Issue by angerman** [commercialhaskell/intero#202]
The QuickFix window (`C-c C-r`) messes up if multiple changes are selected.

I assume this is due to the quick fix suggestions being based on the original file, but
changing the buffer changes the positions. Not sure if markers could help here properly?
Maybe if you go backwards from the End of the file?

On a related note: The quick fix window could possibly group options together.
E.g. if selecting change X to Y offer to apply this change globally?

**Comment by chrisdone** [comment]
Perhaps markers would solve it indeed.
