### ISSUE TITLE
error: attribute ‘lts-6_0’ missing, at (string):1:320

### ISSUE THREAD

**Issue by yamafaktory** [commercialhaskell/intero#203]
Hi,

Intero boots up perfectly up to **lts-5.9** but fails with any of the **6.x** versions with the following error message:

```sh
error: attribute ‘lts-6_0’ missing, at (string):1:320
```

I've also no idea why the `resolver: lts-6.0` of the *stack.yaml* is then interpreted as **lts-6_0**.

N.B.: I am a NixOS user.

Thanks!

**Comment by acowley** [comment]
I think this is fallout from the recent decision for nixpkgs to no longer directly support Stackage. It's a stack bug in that the nix support will likely need tweaking. Eventually there should be a way for you to locally generate a nix expression for the resolver you want to use, but I do not think this exists yet.

**Comment by yamafaktory** [comment]
@acowley Many thanks for the feedback!

**Comment by chrisdone** [comment]
So I'm closing this as a Nix issue unless there's something Intero specifically broke in here.

**Comment by acowley** [comment]
I think it's actually already fixed in `stack`, so perhaps just upgrading that will get things going again @yamafaktory.

**Comment by yamafaktory** [comment]
@acowley Thank you, I'll give it a try!
