### ISSUE TITLE
Multi-package development workflow

### ISSUE THREAD

**Issue by k-bx** [commercialhaskell/intero#205]
I've asked about this before, but really couldn't understand the answer, so sorry for bothering you again, but this really hits our workflow hard, so I'd like to get some clarity here.

Our project has multiple packages working together in our repo, one shared `proj-data`, one for web-server `proj-webapp` and one for producers/consumers `proj-consumer`. It's more complex than this, but let's imagine like that for now. So, the structure is:

```
repo/proj-data/
repo/proj-consumer/
repo/proj-webapp/
repo/stack.yaml
```

Our `stack.yaml` describes all three in `packages` section, and when you finish your changes in any of them, you just run `stack build` and get a rebuild of all the necessary stuff.

Not so with intero. Whenever you make a change in a `proj-data` project, you need to do these steps in order to make intero work well with latest signatures again:

- run `stack build`
- run `intero-restart`

You mentioned previously that doing something with `intero-targets` would help. If this is true – can you remind what exactly should I do? I am happy to try this out on a toy project if this should work in theory, but since it didn't work on our work-project I first want to make sure that I understood this correctly and it should work in theory.

Thank you very much for your work, our productivity increased with intero already, I hope it can grow even more!

**Comment by chrisdone** [comment]
You should just be able to run `M-x intero-targets` and select all the library targets that you're using. Then all the packages are loaded by source into the backend. Does this not work?

**Comment by k-bx** [comment]
@chrisdone ok, just checked – it works on a toy-project, but doesn't on our work-proj, thanks!

I turned on `intero-debug` and saw that probable cause of it not working is that there's a nother problem spotted before related to intero:

```
file.hs:34:20: error:
    • Exception when trying to run compile-time code:
        foo/bar/baz.json: openBinaryFile: does not exist (No such file or directory)

[Intero] <-       Code: embedFile "foo/bar/baz.json"
    • In the untyped splice:
        $(embedFile "foo/bar/baz.json")
```

The thing is, project compiles fine with `stack build`, but with intero it fails to load a ghci via `C-c C-l`, and fails to detect stuff like import errors, that's why I was confused that feature from subj doesn't work (it doesn't show errors on errors).

Should I open a separate discussion for this? Thank you.

**Comment by k-bx** [comment]
@chrisdone also, it might be something different, can't be 100% sure for now, this is just a last "error" from intero debug log I found.

**Comment by mgsloan** [comment]
@k-bx Looks like your TH code cares about the current working dir.  I wrote some utils to help with this: https://www.stackage.org/haddock/nightly-2016-07-31/th-utilities-0.1.1.1/TH-RelativePaths.html

**Comment by k-bx** [comment]
@mgsloan @chrisdone thank you very much! Using "intero-target" and rewriting all TH to go through RelativePaths solved all my problems, it seems. You guys are awesome! :)
