### ISSUE TITLE
Auto-complete problems

### ISSUE THREAD

**Issue by qrilka** [commercialhaskell/intero#206]
When trying to use auto-complete from intero in our project I see errors like:
```
[Intero] -> :complete-at "/home/qrilka/ws/our-project/SomeModule.hs" 45 48 45 54 "unSite"
[Intero] -> :complete repl "unSite"
[Intero] <- *** Exception: Couldn't guess that module name. Does it exist?
CallStack (from HasCallStack):
  error, called at src/InteractiveUI.hs:1801:24 in main:InteractiveUI
```
so auto-complete becomes unusable I'd be glad to debug it further but I'm not sure where to look.
Currently I use `intero-0.1.16` and `0.1.15` was showing the same behavour

**Comment by chrisdone** [comment]
In this case the module isn't loaded successfully, so the completion fails. But Emacs should ignore the failure, I think.
