### ISSUE TITLE
:type-at does not always takes location info into account

### ISSUE THREAD

**Issue by rikvdkleij** [commercialhaskell/intero#207]
For example in:

```
module Example where

a :: Integer -> Integer
a = (+1)

data A a = B a | C
```

Requesting for type gives:
:type-at /home/rik/haskell/projects/quicksort/src/Example.hs 6 8 6 9 a
 a :: Integer -> Integer

I understand it's a weird example but despite location info is given, it returns type of function.

**Comment by chrisdone** [comment]
Right, `:type-at` only works on expressions. 

On a type declaration it doesn't get anything, it falls back to looking in the module-global scope instead. That explains the type you get.

We could change it instead to never look at types in a non-func/var decl?

**Comment by mgsloan** [comment]
It'd be cool if `type-at` on types yielded kinds!

**Comment by rikvdkleij** [comment]
Thanks for you reply. I would suggest not to fallback to module-global scope if no type declaration is present. I assume location info is leading.

@mgsloan I would not mix-up namespaces, I would suggest new command, `kind-at`? :smiley:

**Comment by mgsloan** [comment]
I think overloading `type-at` is fine, because otherwise you have two commands where one is useless in some spots and the other is useless in others.  Kinds really are quite analogous to types.  I actually think we may be able to close this in favor of https://github.com/commercialhaskell/intero/issues/91

**Comment by rikvdkleij** [comment]
About returning kind instead of type.

In the above example I would have to give location info for `A` or intero has to be "smart enough" to find type or kind in local neigherhood of location (together with expression given in command).

**Comment by chrisdone** [comment]
I'll have to check to confirm that Intero can get kind information from a type decl. 

But the concept doesn't seem strange to me. The only way you ought to be able to query a source module for a _kind_ would be by asking it of a type. Therefore, adding a new command that's only going to work in one location, with another command doesn't work but works elsewhere,
``` haskell
x = Just 5      -- type works here
     :: Maybe a -- kind works here
```
seems a bit redundant. We might as well have "get the type of" return type or kind depending on context as #91 suggests.

Closing in favor of #91.
