### ISSUE TITLE
Automatically compile with stack traces in the repl?

### ISSUE THREAD

**Issue by angerman** [commercialhaskell/intero#210]
As recent GHC Versions support stack traces, wouldn't it be a good idea to have the intero repl pass `-prof -fprof-auto -fprof-cafs` and `+RTS -xc` when compiling and running the loaded modules?

Possible benefits: stack traces in the repl, if something fails.
Possible downside: compile time?

**Comment by chrisdone** [comment]
Possibly! There is a trade-off of having to compile everything with profiling, though.

**Comment by mgsloan** [comment]
I can't seem to get -xc to work with ghci.

Does intero support remote GHCi, with `-fexternal-interpreter -prof`?  See Simon Marlow's post on the topic - https://simonmar.github.io/posts/2016-02-12-Stack-traces-in-GHCi.html .

**Comment by angerman** [comment]
I've tried adding `-prof -fexternal-interpreter -fprof-auto -fprof-auto-calls` to the ghci settings file, intero generates.  Together with 8.0.1 this *somewhat* gives stack traces, but I could not get them to be useful. (e.g. for the assert in Module X, i got a stack trace to the line where the assert in X.hs was defined. But not from where it was actually called).

**Comment by gtmacdonald** [comment]
+1

A way to toggle this on and off would be nice.
