### ISSUE TITLE
Allow shell commands to provide ghci history

### ISSUE THREAD

**Issue by louispan** [commercialhaskell/intero#212]
I would like to be able to use external bash tools like fzf (https://github.com/junegunn/fzf) fuzzy finder to the command history in ghci.

To do so, will require at least two features to be added to ghci/intero:

1. A ':save-history' command to save the current history to ~/.ghc/ghci_history on demand instead of at end of ghci-session. Ie, expose https://hackage.haskell.org/package/haskeline-0.7.2.3/docs/System-Console-Haskeline-History.html#writeHistory

2. A ':!= <expr>' which will run a shell command and put the output onto the ghci commandline.
I could use ':cmd <expr>' but it runs the result of <expr> instead of printing it to the commandline. This means:
  2.1. I can't select a command from history, and edit it before running it.
  2.2. The ghci history will show ':cmd (readProcess "fzf-ghci-history.bash" [] "")' and the ghci stdout won't show which command was selected.

3. Optional: a way to bind a key to run ghci ':def' defined commands, so I will be able to bind Ctrl-R to run fzf on ~/.ghc/ghc_history.

Do you think this is a worthwhile addition?

**Comment by chrisdone** [comment]
This only applies to the intero executable? I'm not opposed to these additions. They don't seem to present a big architectural change.

**Comment by chrisdone** [comment]
Feel free to open a PR implementing exactly as you describe above. :+1:

**Comment by louispan** [comment]
Great! I will work on this :)
