### ISSUE TITLE
Intero versions and Stack resolvers

### ISSUE THREAD

**Issue by fosskers** [commercialhaskell/intero#214]
https://github.com/commercialhaskell/intero/blob/master/elisp/intero.el#L67 shows that the intero package itself assumes that the intero version available in the parent stack environment will be 0.1.15. As of (at least) `nightly-2016-08-01`, intero is sitting at 0.1.16. Attempting to install intero automatically (as usual) in such a project current fails unless one manually customizes `intero-package-version`.

How should this be handled? We can't exact just bump `intero-package-version` up to 0.1.16 here in the source, as that would alienate older snapshot users.

**Comment by mgsloan** [comment]
> How should this be handled? We can't exact just bump intero-package-version up to 0.1.16 here in the source, as that would alienate older snapshot users.

We actually can do that - it will install an intero version regardless of your snapshot: https://github.com/commercialhaskell/intero/blob/master/elisp/intero.el#L1252

Not sure how it should be handled.  Some sort of build processes which substitutes the version number into the elisp??

**Comment by fosskers** [comment]
It seems like detecting what intero is available to the snapshot shouldn't be difficult. You could keep internally a version that intero hopes for, and compare it to what's available. Then you could hard-fail on versions that differed by a major version, for API compatibility. Is intero PVP or semver?

**Comment by chrisdone** [comment]
Building intero-0.1.15 works fine on the nightly you specified:

```
bash-3.2$ stack new test 
bash-3.2$ cd test/
bash-3.2$ echo 'resolver: nightly-2016-08-01' > stack.yaml
bash-3.2$ stack build intero-0.1.15
syb-0.6: configure
syb-0.6: build
ghc-paths-0.1.0.9: configure
syb-0.6: haddock
ghc-paths-0.1.0.9: build
ghc-paths-0.1.0.9: haddock
syb-0.6: copy/register
ghc-paths-0.1.0.9: copy/register
intero-0.1.15: configure
intero-0.1.15: build
intero-0.1.15: copy/register
Completed 3 action(s).
Updating Haddock index for snapshot packages in
/Users/chris/.stack/snapshots/x86_64-osx/nightly-2016-08-01/8.0.1/doc/index.html
bash-3.2$ 
```

Seems fine. 👍

**Comment by fosskers** [comment]
It's not building it that's the problem, it's that with a fresh stack environment with `nightly-2016-08-01` and no intero, the current `intero.el` will complain that `0.1.15` doesn't match the intero version available in the snapshot, 0.1.16.

**Comment by chrisdone** [comment]
@fosskers Can you give the output so that I can reproduce it?

**Comment by fosskers** [comment]
I cleared my `.stack_work`, and reverted my customization of `intero-package-version` back to 0.1.15, as matches the current state of the source. When I first open a Haskell file in my test project, I see:

```
The wrong version of Intero is installed for this Emacs package.

Installing intero-0.1.15 automatically ...

Error parsing targets: Specified target version 0.1.15 for package intero does not match snapshot version 0.1.16
Could not install Intero!                                                                                                                                                                                           
                                                                                                                                                                                                                    
We don't know why it failed. Please read the above output and try                                                                                                                                                   
installing manually. If that doesn't work, report this as a                                                                                                                                                         
problem.                                                                                                                                                                                                            
                                                                                                                                                                                                                    
WHAT TO DO NEXT                                                                                                                                                                                                     
                                                                                                                                                                                                                    
If you don't want to Intero to try installing itself again for                                                                                                                                                      
this project, just keep this buffer around in your Emacs.                                                                                                                                                           
                                                                                                                                                                                                                    
If you'd like to try again next time you try use an Intero                                                                                                                                                          
feature, kill this buffer. 
```

**Comment by mgsloan** [comment]
Fixed in stack version 1.1.0: https://github.com/commercialhaskell/stack/issues/2028

**Comment by fosskers** [comment]
```
haskell-core/haskell-stack 1.0.4.3_4-1
    The Haskell Tool Stack
haskell-core/haskell-stack-tool 1.0.4.3_4-1 [installed]
    The Haskell Tool Stack - the binary
community/haskell-stack 1.1.2-14
    The Haskell Tool Stack (docs and libraries)
```
It seems the ArchHaskell repo is actually behind the official one, for once.

**Comment by fosskers** [comment]
`haskell-core` seems to be going defunct. After installing the version of stack from `community`, intero installs into new projects as expected. Thanks guys!

**Comment by mgsloan** [comment]
Welcome!  I've split off #217 to track checking stack version
