### ISSUE TITLE
Have elisp check for recent enough stack version

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/intero#217]
In https://github.com/commercialhaskell/intero/issues/214 , there was some difficulty due to differences in behavior of older stack versions.  We should have the elisp demand an up-to-date enough stack version.  For this particular issue, that's `>= 1.1`

**Comment by chrisdone** [comment]
We could print a warning with `(warn "Your version of stack is out of date, please upgrade to 1.1.")`.

**Comment by mgsloan** [comment]
Yup, that sounds good to me!

**Comment by mgsloan** [comment]
Duplicate of https://github.com/commercialhaskell/intero/issues/127
