### ISSUE TITLE
`intero-project-root' could return nil

### ISSUE THREAD

**Issue by DrsExplorer** [commercialhaskell/intero#218]
When `stack` could not parse stack.yaml file,  `intero-project-root'  would return nil, but you have not checked.

```bash
> touch stack.yaml
> stack path
Could not parse 'stack.yaml':
UnexpectedEvent {_received = Just EventStreamEnd, _expected = Just EventDocumentStart}
See http://docs.haskellstack.org/en/stable/yaml_configuration/.
```

PS. I know this is not the normal procedure, but it could cause serious persistent flycheck error, which makes hard to type any chars in editor!!

**Comment by chrisdone** [comment]
Thanks, I've added a warning to the user which should help them find the issue!
