### ISSUE TITLE
Cannot install intero

### ISSUE THREAD

**Issue by joe9** [commercialhaskell/intero#219]
Hello,

`stack install intero
Run from outside a project, using implicit global project config
Using resolver: lts-6.10 from implicit global project's config file: /home/j/var/stack/global-project/stack.yaml
xmonad-0.12: unregistering (Switching to snapshot installed package)
intero-0.1.16: configure
intero-0.1.16: build

--  While building package intero-0.1.16 using:
      /home/j/var/stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.5.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/j/var/stack/global-project/.stack-work/logs/intero-0.1.16.log

    Configuring intero-0.1.16...
    Warning: This package indirectly depends on multiple versions of the same
    package. This is highly likely to cause a compile failure.
    package intero-0.1.16 requires transformers-0.4.2.0
    package haskeline-0.7.2.3 requires transformers-0.4.2.0
    package ghc-7.10.3 requires transformers-0.4.3.0
    Building intero-0.1.16...
    Preprocessing executable 'intero' for intero-0.1.16...
    [1 of 8] Compiling GhciTypes        ( src/GhciTypes.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/intero/intero-tmp/GhciTypes.o )
    [2 of 8] Compiling GhciMonad        ( src/GhciMonad.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/intero/intero-tmp/GhciMonad.o )

    /tmp/stack17770/intero-0.1.16/src/GhciMonad.hs:189:31:
        No instance for (MonadIO Ghc) arising from a use of ‘liftIO’
        In the expression: liftIO
        In a stmt of a 'do' block: ref <- liftIO $ newIORef state
        In the expression:
          do { ref <- liftIO $ newIORef state;
               unGHCi g ref }

    /tmp/stack17770/intero-0.1.16/src/GhciMonad.hs:213:22:
        No instance for (MonadIO Ghc) arising from a use of ‘liftIO’
        In the second argument of ‘(.)’, namely ‘liftIO’
        In the expression: liftGhc . liftIO
        In an equation for ‘liftIO’: liftIO = liftGhc . liftIO

    /tmp/stack17770/intero-0.1.16/src/GhciMonad.hs:229:10:
        No instance for (transformers-0.4.3.0:Control.Monad.IO.Class.MonadIO
                           GHCi)
          arising from the superclasses of an instance declaration
        In the instance declaration for ‘ExceptionMonad GHCi’

    /tmp/stack17770/intero-0.1.16/src/GhciMonad.hs:248:10:
        No instance for (transformers-0.4.3.0:Control.Monad.IO.Class.MonadIO
                           (InputT GHCi))
          arising from the superclasses of an instance declaration
        In the instance declaration for ‘ExceptionMonad (InputT GHCi)’

    /tmp/stack17770/intero-0.1.16/src/GhciMonad.hs:270:3:
        Could not deduce (MonadIO m) arising from a use of ‘liftIO’
        from the context (GhcMonad m)
          bound by the type signature for
                     printForUserNeverQualify :: GhcMonad m => SDoc -> m ()
          at src/GhciMonad.hs:267:29-54
        Possible fix:
          add (MonadIO m) to the context of
            the type signature for
              printForUserNeverQualify :: GhcMonad m => SDoc -> m ()
        In the expression: liftIO
        In a stmt of a 'do' block:
          liftIO $ Outputable.printForUser dflags stdout neverQualify doc
        In the expression:
          do { dflags <- getDynFlags;
               liftIO $ Outputable.printForUser dflags stdout neverQualify doc }

    /tmp/stack17770/intero-0.1.16/src/GhciMonad.hs:277:3:
        Could not deduce (MonadIO m) arising from a use of ‘liftIO’
        from the context (GhcMonad m)
          bound by the type signature for
                     printForUserModInfo :: GhcMonad m => GHC.ModuleInfo -> SDoc -> m ()
          at src/GhciMonad.hs:272:24-67
        Possible fix:
          add (MonadIO m) to the context of
            the type signature for
              printForUserModInfo :: GhcMonad m => GHC.ModuleInfo -> SDoc -> m ()
        In the expression: liftIO
        In a stmt of a 'do' block:
          liftIO $ Outputable.printForUser dflags stdout unqual doc
        In the expression:
          do { dflags <- getDynFlags;
               mUnqual <- GHC.mkPrintUnqualifiedForModule info;
               unqual <- maybe GHC.getPrintUnqual return mUnqual;
               liftIO $ Outputable.printForUser dflags stdout unqual doc }

    /tmp/stack17770/intero-0.1.16/src/GhciMonad.hs:283:3:
        Could not deduce (MonadIO m) arising from a use of ‘liftIO’
        from the context (GhcMonad m)
          bound by the type signature for
                     printForUser :: GhcMonad m => SDoc -> m ()
          at src/GhciMonad.hs:279:17-42
        Possible fix:
          add (MonadIO m) to the context of
            the type signature for printForUser :: GhcMonad m => SDoc -> m ()
        In the expression: liftIO
        In a stmt of a 'do' block:
          liftIO $ Outputable.printForUser dflags stdout unqual doc
        In the expression:
          do { unqual <- GHC.getPrintUnqual;
               dflags <- getDynFlags;
               liftIO $ Outputable.printForUser dflags stdout unqual doc }

    /tmp/stack17770/intero-0.1.16/src/GhciMonad.hs:395:5:
        No instance for (MonadIO Ghc) arising from a use of ‘liftIO’
        In the expression: liftIO
        In a stmt of a 'do' block:
          liftIO
          $ do { initDynLinker dflags;
                 mb_stdin_ptr <- lookupSymbol
                                   "base_GHCziIOziHandleziFD_stdin_closure";
                 mb_stdout_ptr <- lookupSymbol
                                    "base_GHCziIOziHandleziFD_stdout_closure";
                 mb_stderr_ptr <- lookupSymbol
                                    "base_GHCziIOziHandleziFD_stderr_closure";
                 .... }
        In the expression:
          do { dflags <- getSessionDynFlags;
               liftIO
               $ do { initDynLinker dflags;
                      mb_stdin_ptr <- lookupSymbol
                                        "base_GHCziIOziHandleziFD_stdin_closure";
 `

Thanks

**Comment by chrisdone** [comment]
```
   Configuring intero-0.1.13...
    Warning: This package indirectly depends on multiple versions of the same
    package. This is highly likely to cause a compile failure.
    package intero-0.1.13 requires transformers-0.4.2.0
    package haskeline-0.7.2.2 requires transformers-0.4.2.0
    package ghc-7.10.3 requires transformers-0.4.3.0
```

For some reason your version of GHC is using `transformers-0.4.3.0`.

Right. GHC 7.10.3 ships with transformers-0.4.2.0: http://downloads.haskell.org/~ghc/7.10.3/docs/html/libraries/index.html

Are you on Nix or Gentoo or something with a modified GHC compiler?

**Comment by chrisdone** [comment]
Probable duplicate of #69 and #168.

**Comment by joe9** [comment]
@chrisdone yes, I am on gentoo.

**Comment by joe9** [comment]
For the next gentoo person coming across this error. The below fixed the issue. The ghc ebuild installs transformers 4.3 whereas ghc comes bundled with 4.2.
`
cat /etc/portage/bashrc
# /etc/portage/bashrc
#

for sh in /etc/portage/bashrc.d/*.sh ; do
        [[ -r ${sh} ]] && source "${sh}"
done

- ( 0  /etc  master ) -
cat /etc/portage/patches/dev-lang/ghc/remove_bump_libraries.sh
# /etc/portage/bashrc
#

# This file is sourced by /etc/portage/bashrc.d/source-sh-files-in-patches-directory.sh

# intero build fails when the transformers package installed with ghc is changed

echo "Applying user patches from ${BASH_SOURCE} ..."
BUMP_LIBRARIES=()
echo "Applied ${BASH_SOURCE}"
u`

**Comment by mgsloan** [comment]
You also ought to be able to make stack ignore the system ghc via `--no-system-ghc`
