### ISSUE TITLE
persist history

### ISSUE THREAD

**Issue by angerman** [commercialhaskell/intero#224]
When using projects with depend on other projects, I have to kill the intero section when ever I recompiled the other projects; and inadvertently loose all my history.

You can of course add short hands to the module that's being loaded, and therefore push the history information into the module, but that feels more like a hack.

I'm wondering if comint wouldn't allow to persist history somehow? You'd certainly only want it persisted _per project_ though.

**Comment by chrisdone** [comment]
You mean the prompt history?

**Comment by angerman** [comment]
Yes, exactly!
