### ISSUE TITLE
update intero.el intero-package-version from 0.1.15 to 0.1.16?

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/intero#225]
It seems `intero-package-version` defined in `intero.el` hasn't been updated to 0.1.16?  
Is that intentional or should it be updated?  (Maybe a PR would have been quicker:)

**Comment by chrisdone** [comment]
Related discussion https://github.com/commercialhaskell/intero/issues/159

Are you encountering this due to a problem or because you were reviewing the code?

**Comment by juhp** [comment]
I see thanks, I did try to search the issues.

I encountered this when I tried to check the installed version of intero from within Emacs. I think it is a bit confusing: might be good to add a comment to intero.el.

**Comment by chrisdone** [comment]
Yeah, I'll pop a comment in the docstring for it.

**Comment by chrisdone** [comment]
Added a comment.

**Comment by juhp** [comment]
Thanks
