### ISSUE TITLE
Support adding suggested package to cabal file.

### ISSUE THREAD

**Issue by asmyers** [commercialhaskell/intero#229]
When I import a module which is in a package not in my cabal file haskell-mode will ask if I want to add the package to the dependencies in the cabal file.  This doesn't seem to work when using Intero.

**Comment by chrisdone** [comment]
Support isn't there yet, but `intero-multiswitch` should let us pick which targets to apply the change to.

We can probably add it to the suggestions support via `C-c C-r`.
