### ISSUE TITLE
Intero gets confused by wrong system GHC version

### ISSUE THREAD

**Issue by 23Skidoo** [commercialhaskell/intero#232]
I have a GHC 8.0.2 snapshot from @hvr's repo installed as a default system GHC and `intero-mode` set up as a `haskell-mode-hook`. When I try to open any Cabal source file in Emacs, I get the following:

```
    Intero is not installed in the Stack environment.

Installing intero-0.1.15 automatically ...

Cabal file warning in /home/refold/code/haskell/cabal/cabal-install/cabal-install.cabal: Ignoring unknown section type: custom-setup
Cabal file warning in /home/refold/code/haskell/cabal/cabal-install/cabal-install.cabal: Ignoring unknown section type: custom-setup
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      ghc: needed (>=7.8 && <=8.0.1), 8.0.1.20160725 found
    needed for package intero-0.1.15
Could not install Intero!

We don't know why it failed. Please read the above output and try
installing manually. If that doesn't work, report this as a
problem.

WHAT TO DO NEXT

If you don't want to Intero to try installing itself again for
this project, just keep this buffer around in your Emacs.

If you'd like to try again next time you try use an Intero
feature, kill this buffer.
```

Looks a bit strange to me, since I thought that Stack manages its own GHC installation and does not get affected by whatever GHC version is installed globally. Intero boots up and works fine for me when I open a standalone `.hs` file somewhere.

**Comment by chrisdone** [comment]
> ghc: needed (>=7.8 && <=8.0.1), 8.0.1.20160725 found

It looks like the snapshot just adds an extra component to the regular GHC format. To support this we could change the dependency to `< 8.0.2`. We should technically be able to set it to `<8.1`, but IME GHC changes the API between minor versions too.

> Looks a bit strange to me, since I thought that Stack manages its own GHC installation

It uses the system GHC if it's the expected version; in this case  8.0.1.20160725 is acceptable.

So the choices are:

1. Disable use of the system-wide GHC in your stack config. I can't remember the yaml setting for this off-hand.
2. I change the upper bound to `<8.0.2`.

**Comment by chrisdone** [comment]
I bumped the GHC constraint to `<8.0.2` on intero `0.1.16`, `0.1.15` and `0.1.14`.

**Comment by 23Skidoo** [comment]
Thanks for the fast response!

**Comment by hvr** [comment]
if anyone cares, the versioning scheme is explained in https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/intro.html#ghc-version-numbering-policy

Consequently, GHC 8.0.1.<date> follows the scheme for stable snapshots, and is designed as such to have the proper lexicographic ordering relative to the final 8.0.2 release.
