### ISSUE TITLE
Funny auto completion

### ISSUE THREAD

**Issue by KenetJervet** [commercialhaskell/intero#236]
I think this is related to #206 though the behavior slightly differs.

![2016-08-24 01-29-57](https://cloud.githubusercontent.com/assets/1560189/17902585/8097e34e-692d-11e6-916d-bf8906e09096.png)

**Comment by chrisdone** [comment]
Thanks for reporting. I think this output looks different by coincidence rather than real change of behaviour. Let's fix the other one. Please follow that issue and if it doesn't fix your problem then we can re-open this one.
