### ISSUE TITLE
Experiances after installing

### ISSUE THREAD

**Issue by gurgl** [commercialhaskell/intero#238]
Environment:
GHC 7.10.3
OS ubuntu 14.04
GNU Emacs 24.3.1

Install procedure:
added config from https://commercialhaskell.github.io/intero/ to .emacs

Steps (dont assume any emacs knowledge and implicit steps, this is the only thing ive done)
1. Started emacs (...or when i start emacs now. Dont have the first log avaialble) in the root of a perfectly compiing stack project. _Messages_ shows: 

Warning (initialization): An error occurred while loading `/home/me/.emacs':

File already exists: File exists, /home/me/.emacs.d/elpa/intero-20160817.729/intero-pkg.el
1. Opened .hs file in directory beneth a dir containing stack.yaml file
2. Problems

A. C-c C-t  on a type 

"inferior-haskell-type: No type info: 
<interactive>:1:1: Not in scope: ‘f’" 

...on every expression i use it on

B. M-x . 

Prompt> Visit tags table (default TAGS): ~/Documents/src/labs/haskelltest1/src/JC/Game/
...pressing enter give 
"File /home/me/Documents/src/labs/haskelltest1/src/JC/Game/TAGS is not a valid tags table"

I wonder is this how it should work?

**Comment by gurgl** [comment]
After doing C-c C-l i managed to get some type info.  Does work on local identfiers, only on module level.

C. Also making a selection (with mouse) doesnt seem to pass the selection to the "expression to be evaluated" (C-c C-t) as explained by the intero help

**Comment by gurgl** [comment]
simplified ex:
```
module Bla where 

f1 :: Int -> Int
f1 a1 = f2 a1
  where
  f2 x2 = 2 * f3 x2
    where 
    f3 x3 | x3 > 5 = 3
             | otherwise = 1
```

here i cannot the type info on f2 and f3

**Comment by chrisdone** [comment]
Intero mode isn't running, you're using `inferior-haskell`. 

I suggest scrapping your .emacs and trying with a new one. 😄 

Try e.g.

``` lisp
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(use-package intero :ensure t)
(add-hook 'haskell-mode-hook 'intero-mode)
(require 'haskell-mode)
```

**Comment by gurgl** [comment]
Then i get mode "Haskell Intero company FlyC"

Now, 
C-c C-t and results in "Cannot open load file:ghc". 
"C-c C-i" is bound to save file
"M-." works! But with error message  "Cannot open load file:ghc".

**Comment by gurgl** [comment]
"C-h v load-path"  gives : 

"/home/me/.emacs.d/elpa/intero-20160817.729"
"/home/me/.emacs.d/elpa/haskell-mode-20160819.1008"
"/home/me/.emacs.d/elpa/company-20160823.905"
"/home/me/.emacs.d/elpa/flycheck-20160817.321"
"/home/me/.emacs.d/elpa/dash-20160820.501"
"/home/me/.emacs.d/elpa/let-alist-1.0.4"
"/home/me/.emacs.d/elpa/pkg-info-20150517.443"
"/home/me/.emacs.d/elpa/epl-20150517.433"
"/home/me/.emacs.d/elpa/seq-2.16"
"/home/me/.emacs.d/elpa/use-package-20160815.1137"
"/home/me/.emacs.d/elpa/diminish-20151215.915"
"/home/me/.emacs.d/elpa/bind-key-20160227.48"
"/usr/share/emacs24/site-lisp/ghc-mod"
"/etc/emacs24"
"/etc/emacs"
"/usr/local/share/emacs/24.3/site-lisp"
"/usr/local/share/emacs/site-lisp"
"/usr/share/emacs24/site-lisp/haskell-mode"
"/usr/share/emacs24/site-lisp/dictionaries-common"
"/usr/share/emacs24/site-lisp/cmake-data"
"/usr/share/emacs/24.3/site-lisp"
"/usr/share/emacs/24.3/site-lisp/cmake-data"
"/usr/share/emacs/24.3/site-lisp/haskell-mode"
"/usr/share/emacs/site-lisp"
"/usr/share/emacs/24.3/lisp"
"/usr/share/emacs/24.3/lisp/vc"
"/usr/share/emacs/24.3/lisp/url"
"/usr/share/emacs/24.3/lisp/textmodes"
"/usr/share/emacs/24.3/lisp/progmodes"
"/usr/share/emacs/24.3/lisp/play"
"/usr/share/emacs/24.3/lisp/org"
"/usr/share/emacs/24.3/lisp/nxml"
"/usr/share/emacs/24.3/lisp/net"
"/usr/share/emacs/24.3/lisp/mh-e"
"/usr/share/emacs/24.3/lisp/mail"
"/usr/share/emacs/24.3/lisp/language"
"/usr/share/emacs/24.3/lisp/international"
"/usr/share/emacs/24.3/lisp/gnus"
"/usr/share/emacs/24.3/lisp/eshell"
"/usr/share/emacs/24.3/lisp/erc"
"/usr/share/emacs/24.3/lisp/emulation"
"/usr/share/emacs/24.3/lisp/emacs-lisp"
"/usr/share/emacs/24.3/lisp/cedet"
"/usr/share/emacs/24.3/lisp/calendar"
"/usr/share/emacs/24.3/lisp/calc"
"/usr/share/emacs/24.3/lisp/obsolete"
"/usr/share/emacs/24.3/leim"

...and i noticed

/usr/share/emacs24/site-lisp/ghc-mod 

isnt on disk?

So should both ghc and ghc-mod be available?

**Comment by gurgl** [comment]
M-x toggle-debug-on-error 

gave (when pressing C-c C-t) : 

```
Debugger entered--Lisp error: (file-error "Cannot open load file" "ghc")
  (ghc-init)
  (lambda nil (ghc-init) (flymake-mode))()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook haskell-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook haskell-mode-hook))
  run-mode-hooks(haskell-mode-hook)
  haskell-mode()
  intero-fontify-expression("fmap (adr_loc) $ concatMap id $ maybeToList $ lookup fact attrDecR\n  :: [LocationId]")
  intero-type-at(nil)
  call-interactively(intero-type-at nil nil)

```

 M-: (setq haskell-mode-hook nil) 

Fixed the problem!! So now i just wonder if this is a proper workaround, or is disabling haskell-mode completely bad?

**Comment by acowley** [comment]
@gurgl You don't need or want `ghc-mod` installed. `ghc-init` is the `ghc-mod` initialization function that you are calling from your `haskell-mode-hook`. Best bet is to undo that so `haskell-mode` can work.
