### ISSUE TITLE
Unnecessary buffers in the buffer list

### ISSUE THREAD

**Issue by korayal** [commercialhaskell/intero#240]
When I run a REPL in intero (spacemacs), I'm getting buffers with path `/tmp/intero-script234....` in the list of buffers. And If I kill that  REPL buffer, that buffers also remain. And if I keep opening REPL buffers, after a while I'm having bunch of unnecessary buffers of this kind.

I'm new to Emacs and I see similar behaviors on Magit or PDF-Tools (where I press `q` to exit the buffer, but the buffer remains in the list :) ) So I wanted to know if this was an expected behavior? Shouldn't that buffer kill itself after doing it's task, or at least after the relevant REPL buffer closes?

**Comment by chrisdone** [comment]
Good point, it should kill the buffer after writing.

**Comment by Blaisorblade** [comment]
New in this direction: now jumping to definition jumps to those buffers (as of latest melpa unstable release, 20160907.748).
