### ISSUE TITLE
Support shebang options

### ISSUE THREAD

**Issue by drewr** [commercialhaskell/intero#241]
Intero expects a full stack project, but it would be great to be able to pop open a single file like [`FileServer.hs`](https://github.com/snoyberg/file-server-demo/blob/789de17d976c027e58b61c9f90db2586fc8c6e8b/FileServer.hs), hit `C-c C-l` and hack away.  I can do it with haskell-mode but it would be nice to use the same setup for every type of project.  Maybe this is out of scope for Intero?  Is only meant for a "real" project?

**Comment by meditans** [comment]
I think that is a single file is used, `intero` uses automatically the stack's `global-project`. I can definitely open a file, hit `C-c C-l` and hack away. What problems are you encountering specifically?

**Comment by drewr** [comment]
Intero can't find the dependencies:

```
    Could not find module ‘Network.HTTP.Types’
    It is not a module in the current program, or in any known package.
    Could not find module ‘Network.Wai’
    It is not a module in the current program, or in any known package.
    [...]
```

My `~/.stack/global/stack.yaml` is pretty lean:

```
flags: {}
packages: []
extra-deps:
  - purescript-0.9.3
resolver: lts-6.10
```

**Comment by drewr** [comment]
@meditans Did you open the `FileServer.hs` example?  I'm not sure we're doing the same thing.  You are probably opening a file for which the global `stack.yaml` has your deps?  I'm proposing that Intero honor the shebang `--package`s first.

**Comment by chrisdone** [comment]
Interesting idea -- I think if a file has such shebangs, then Intero could consider it its own little project within the global environment and apply those flags when launching stack.

**Comment by mgsloan** [comment]
Makes sense to me!  I don't think this needs to be tracked as an intero ticket, though, perhaps it is just an aspect of https://github.com/commercialhaskell/stack/issues/1361 ?

**Comment by meditans** [comment]
@chrisdone any news on this feature? What should be done to have it?

**Comment by meditans** [comment]
Ping again @chrisdone, as the feature @mgsloan talked about as a prerequisite has been implemented.

**Comment by chrisdone** [comment]
I think then it should detect a shebang and a --stack line. If there is one
then start an intero session just for that file.

**Comment by chrisdone** [comment]
I pushed an experimental patch that uses the args in the `-- stack` line when there's a shebang in the file.

This doesn't include REPL support yet.

**Comment by meditans** [comment]
That's great @chrisdone, thanks! I'm using this feature, and it seems to work!

**Comment by roman** [comment]
Given the latest release of stack and the `script` sub-command, is there any plan to revisit this implementation?

**Comment by ntc2** [comment]
Just learned about the `stack script` command that automatically detects package dependencies based on imports. Can be used with "shebang", e.g. with

```shell
#!/usr/bin/env stack
-- stack --resolver lts-8.12 script
```

at the top of the `.hs` file.

It would be nice if `intero` handled editing files using such a `stack script` shebang correctly.

**Comment by dmp1ce** [comment]
Why was this issue closed? I have a script which looks like:

```haskell
#!/usr/bin/env stack
-- stack script --package turtle

{-# LANGUAGE OverloadedStrings #-}

import Turtle
```

I'm using Intero on Spacemacs and it is complaining that the `Turtle` import could not be found. Is there another issue I should follow for my use case?

**Comment by chrisdone** [comment]
I’m not going to implement this.
