### ISSUE TITLE
0.1.18: silent failure during intero boot, in case when the project doesn't build

### ISSUE THREAD

**Issue by deepfire** [commercialhaskell/intero#246]
Intero 0.1.18 (Emacs 24.5.2) silently refuses to do anything (`M-.`, `C-c C-t`) when the project doesn't build, nor it helps to resolve the compile errors in any way.

Calling `intero-toggle-debug` gets some info into `*Messages*`:

```
Intero arguments: --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-build --no-load --ghci-options -odir=/tmp/intero1645ZsS --ghci-options -hidir=/tmp/intero1645ZsS youtrack-tools
Booting up intero ...
[Intero] <- The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Configuring GHCi with the following packages: youtrack-tools

[Intero] <- Intero 0.1.18 (GHC 8.0.1)
Type :intro and press enter for an introduction of the standard commands.
 [2 times]
[Intero] <- 

[Intero] <- <interactive>:2:1: error:
    • Variable not in scope: set
    • Perhaps you meant ‘seq’ (imported from Prelude)

<interactive>:2:6: error: Variable not in scope: c
Prelude> Prelude> 
Booted up intero!
[Intero] -> :l /home/deepfire/src/corr/corr.hs
[Intero] <- [ 1 of 12] Compiling Table            ( /home/deepfire/src/corr/Table.hs, /tmp/intero1645ZsS/Table.o )

[Intero] <- 
/home/deepfire/src/corr/Table.hs:95:37: error:
[Intero] <- 
    Not in scope: type constructor or class ‘Name’
    Perhaps you meant ‘Named’ (imported from Brick.Widgets.Core)
Failed, modules loaded: none.
```

**Comment by deepfire** [comment]
Perhaps it should be clarified -- I have expected intero to point me at the error locations.

**Comment by deepfire** [comment]
@chrisdone, is there anything I can do to shed more light?  More debug options?  Insert a print statement in some elisp function?

**Comment by chrisdone** [comment]
You're saying it doesn't show anything in flycheck's error reporting?

**Comment by deepfire** [comment]
Do I have to do anything to enable it?  There aren't any overlays in the source buffers, at least -- no discernible notice that anything is wrong at all, indeed.

**Comment by chrisdone** [comment]
intero-mode should automatically enable it. But you should see `FlyC` in your minibuffer if it's on.

**Comment by deepfire** [comment]
@chrisdone, FlyC is present in the mode line, but no flycheck error overlays are present.

**Comment by deepfire** [comment]
@chrisdone, any hypotheses I can test?

**Comment by chrisdone** [comment]
Can you publish a small reproducing project that I can test?

**Comment by deepfire** [comment]
No longer reproducible with same version of intero -- the set of emacs packages changed, though..
