### ISSUE TITLE
Intero fails to start with 'Invalid package ID' error

### ISSUE THREAD

**Issue by abailly** [commercialhaskell/intero#252]
When starting intero, I recently got error messages telling me there were inconsistencies between versions. I upgraded intero to 0.1.18 using stack and now I got the following errors:

```
Invalid package ID: "array-0.5.1.1 base-4.9.0.0 binary-0.8.3.0 bytestring-0.10.8.1"

---

This is the buffer where Emacs talks to intero. It's normally hidden,
but a problem occcured.

TROUBLESHOOTING

It may be obvious if there is some text above this message
indicating a problem.

The process ended. Here is the reason that Emacs gives us:

  exited abnormally with code 1

For troubleshooting purposes, here are the arguments used to launch intero:

  stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-build --no-load --ghci-options -odir=/var/folders/y3/y8bcknvj15b_1ndyq57rxws00000gn/T/intero273031Gv --ghci-options -hidir=/var/folders/y3/y8bcknvj15b_1ndyq57rxws00000gn/T/intero273031Gv gs-client

WHAT TO DO NEXT

If you fixed the problem, just kill this buffer, Intero will make
a fresh one and attempt to start the process automatically as
soon as you start editing code again.

If you are unable to fix the problem, just leave this buffer
around in Emacs and Intero will not attempt to start the process
anymore.

You can always run M-x intero-restart to make it try again.
```

Project builds fine with stack. I am clueless...

**Comment by abailly** [comment]
When I try to run the given command in a terminal, I get the following output:

```
$  stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-build --no-load --ghci-options -odir=/var/folders/y3/y8bcknvj15b_1ndyq57rxws00000gn/T/intero3910vI --ghci-options -hidir=/var/folders/y3/y8bcknvj15b_1ndyq57rxws00000gn/T/intero3910vI gmail-api
Configuring GHCi with the following packages: gmail-api
Intero 0.1.18 (GHC 8.0.1)
Type :intro and press enter for an introduction of the standard commands.

Prelude> :intro
Here is a list of some of the common commands used when developing Haskell.

:load <filename>
  This loads a module or file and puts you in the context of that file.
  For example, :load X.hs will type-check X.hs and load the interpreted
  code in to be ran from the prompt.

:browse <module name>
  List the declarations and types in the module. 
  Example: :browse Data.List

:help
  Displays a complete list of all the commands available.

Prelude> 
```

**Comment by luispedro** [comment]
I had a similar error in another context which went away after I upgraded stack (from 0.10 to 1.2).

**Comment by abailly** [comment]
This error seems to be caused by a mismatch in `PATH`s: Emacs was using an older version of ghc. It would be helpful to have some way of reporting the exact environment `intero` is operating in. `ghc-mod` used to have a `ghc-debug` command in emacs that dumped all paths.

**Comment by eyeinsky** [comment]
@kryoxide: check which `stack` you're using. `stack upgrade` installs the new version under `~/.local/bin`, but the old one from your package manager might still come first in path.

**Comment by noprompt** [comment]
@eyeinsky, that was precisely my problem. Thanks!

**Comment by gcharnock** [comment]
I'm afraid this one is back. Fresh .emacs.d and fresh project created with `stack new progectname simple` produces

```
Intero is not installed in the Stack environment.

Installing intero-0.1.21 automatically ...

Invalid package ID: "array-0.5.1.1 base-4.9.1.0 binary-0.8.3.0 bytestring-0.10.8.1"
Could not install Intero!

We don't know why it failed. Please read the above output and try
installing manually. If that doesn't work, report this as a
problem.

WHAT TO DO NEXT

If you don't want to Intero to try installing itself again for
this project, just keep this buffer around in your Emacs.

If you'd like to try again next time you try use an Intero
feature, kill this buffer.
```
The resolver is `lts-9.1` which is the latest. Finally `stack --version` from the emacs shell is 

```
stack --version
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e (4861 commits) x86_64 hpack-0.17.1
```
Which is the latest.

**Comment by chrisdone** [comment]
We'll have to check that stack doesn't have a bug.

**Comment by tdox** [comment]
Is there a know work-around for this issue? I'm unable to use intero with lts-9.6.

**Comment by kryoxide** [comment]
The suggestion of @eyeinsky in this thread worked for me.

**Comment by tdox** [comment]
Re @kryoxide's suggestion to follow @eyeinsky's suggestion: This error is occurring for me using stack version 1.5.1.

**Comment by DrumLaude** [comment]
Re @tdox : Are you sure you have 1.5.1? A lower version might still be sticking around. Was the case for me, at least. Try: `curl -sSL https://get.haskellstack.org/ | sh` or, if it asks for a forced command: `curl -sSL https://get.haskellstack.org/ | sh -f` it worked for me. Source: [](https://docs.haskellstack.org/en/stable/README/)

**Comment by tdox** [comment]
@kryoxide & @DrumsnChocolate   Thanks for your help!

When I do: "stack --version", I see Version 1.5.1, Git revision 2fbc3e93121b97d41f125b3aba9e9f2d8c62888f x86_64 hpack-0.18.1

It turns out that emacs was using a different stack. I had the latest stack in ~/.local/bin and another older one in /usr/bin. My shell was using the one in ~/.local/bin but emacs was using the one /usr/bin.  With the emacs command "M-x getenv" I could see that emacs was using the wrong stack.   I unstalled the older stack from /usr/bin.  But then intero could not find the stack in ~/.local/bin. So I installed the emacs package (exec-path-from-shell)[https://github.com/purcell/exec-path-from-shell] to ensure that emacs was using the same PATH env var as my shell. (I'm using Ubuntu 16.04 LTS) Now all is good.

**Comment by kryoxide** [comment]
If more people have a problem with this, maybe a hint for this fix (i.e. upgrading stack) should be integrated into the intero emacs buffer?

**Comment by purcell** [comment]
> If more people have a problem with this, maybe a hint for this fix (i.e. upgrading stack) should be integrated into the intero emacs buffer?

Good suggestion @kryoxide - I added a hint in 9bbb337.

**Comment by andreaskern** [comment]
Although I don't use **intero** I just encountered the same/similar problem on Ubuntu 16.04.4 LTS after _just_ using `stack new` to create a new project. Maybe others find this useful. 

```
> stack new testproject servant
Downloading template ...
...
> stack install
Invalid package ID: "array-0.5.1.1 base-4.9.1.0 bytestring-0.10.8.1 containers-0.5.7.1"
```

```
> stack --version
Version 0.1.10.0 x86_64
> ~/.local/bin/stack --version
Version 1.4.0 x86_64 hpack-0.17.0
```

**Comment by andreas-roehler** [comment]
With Emacs buffer in intero-mode, M-x intero-repl RET:

Starting:
  stack ghci --with-ghc ghci "--docker-run-args=--interactive=true --tty=false" --no-build --no-loadcd
Invalid package ID: "array-0.5.1.1 base-4.9.1.0 binary-0.8.3.0 bytestring-0.10.8.1"

Process intero exited abnormally with code 1

;;;

Checked for array-0.5.1.1, it resides in 

/home/my-name/.stack/programs/x86_64-linux/ghc-8.0.2/lib/ghc-8.0.2
