### ISSUE TITLE
Support using a GHC built from Git

### ISSUE THREAD

**Issue by enolan** [commercialhaskell/intero#253]
It'd be great if I could use Intero on a project that needs a development version of GHC. I don't expect you to actively track GHC's development, but it seems to actively prevent me from doing this. First, it failed because `intero.cabal` specifies `ghc >= 7.8 && <= 8.0.1` and I have `8.0.1.20160901`. Sure, makes sense. So I pulled intero into my project, modified the bound, and added it to `packages` in my `stack.yaml`. It builds fine, but the emacs mode says:

```
Installing intero-0.1.15 automatically ...

Error parsing targets: intero target has a specific version number, but it is a local package.
To avoid confusion, we will not install the specified version or build the local one.
To build the local package, specify the target without an explicit version.
```

I'd like for it to use the intero executable that is already in the project.

**Comment by chrisdone** [comment]
What version of the intero binary do you have installed locally?

**Comment by enolan** [comment]
`Intero 0.1.18 (GHC 8.0.1.20160901)`. From Git b9015faf3efd301b0502738f7fa21048efafee2e. The custom GHC needs to be in the PATH that Emacs sees for this to work. I'm using the emacs mode from MELPA, didn't think that mattered.

**Comment by chrisdone** [comment]
In that case you can probably set your `intero-package-version` to 0.1.18. Or update your Elisp.

**Comment by enolan** [comment]
Oh cool, thanks! Works now.
