### ISSUE TITLE
Jump to definition jumping to intero file in /tmp

### ISSUE THREAD

**Issue by pallix** [commercialhaskell/intero#254]
When using jump to definition on one of my declared function, the cursor jump to the definition in `/tmp/intero6165KMA.hs` instead of jumping to the definition of the function.

Example:
```
module Lib
    ( someFunc
    ) where

someFunc :: IO ()
someFunc = putStrLn "someFunc"

doFun :: IO ()
doFun = someFunc
```

**Comment by chrisdone** [comment]
I was afraid this would happen as a result of https://github.com/commercialhaskell/intero/pull/248.

I think we can probably fix this by only collecting type info for the requested `:load` module.

**Comment by chrisdone** [comment]
Oh wait, it's an easier fix than that.

**Comment by chrisdone** [comment]
Done!

**Comment by pallix** [comment]
That was quick :-). Thank you very much.
