### ISSUE TITLE
Add haskell-docs support

### ISSUE THREAD

**Issue by CSRaghunandan** [commercialhaskell/intero#255]
I was wondering, why not add support for [`haskell-docs`] (https://github.com/ivan-m/haskell-docs) for those who has installed it ? 

We can do two things :- 
1. Add `haskell-docs` support to company,  so that, we can get the info of the function in `company-quickhelp` 
2. If the previous suggestion is not applicable, create a command similar to `intero-info` which will pop up the `haskell-docs` for the thing under cursor.

**Comment by chrisdone** [comment]
We're going to add hoogle support which replaces the need for haskell-docs: https://github.com/commercialhaskell/intero/issues/129
