### ISSUE TITLE
Show suggestions without having to type first

### ISSUE THREAD

**Issue by Johnson-A** [commercialhaskell/intero#256]
Often I'm in the situation where I don't remember the first few characters of the thing I'd like to import. It seems like there is no way to have intero in emacs show `all` suggestions for completion without the need to first type ~3 characters.

for example, when importing 

`import Data.Time (getCurrentTime)`

I'd like to place my cursor inside the empty parenthesis and ask for suggestions

`import Data.Time ()`

but when I do so with company-complete, I don't get the same suggestions as I would after typing "get". Instead, I get a bunch of top level names and nothing that can be imported.

For example, if I type only "ge" and the call company-complete, the suggestions I get are [getChar, getContents, getLine] whereas after `typing` "get" I also get things I can import such as [getCurrentTime, getCurrentTimeZone, ...] as expected.

**Comment by chrisdone** [comment]
The completions with no prefix string come from the REPL. Completions with a prefix come from the module scope. 

I think we could add a special case to complete for import lists.
