### ISSUE TITLE
stack new intero-demo fails

### ISSUE THREAD

**Issue by jmchapman** [commercialhaskell/intero#259]
I get the error message:

Downloading template "new-template" to create project "intero-demo" in intero-demo\ ...
FailedConnectionException2 "raw.githubusercontent.com" 443 True getAddrInfo: does not exist (error 11003)

I am running windows 10 with stack 1.1.2

**Comment by chrisdone** [comment]
I think that's a problem with your internet connection?

**Comment by jmchapman** [comment]
It fails consistency, my internet connection is working fine.
