### ISSUE TITLE
Customize intero to use nix

### ISSUE THREAD

**Issue by jml** [commercialhaskell/intero#262]
My project [difftodo](https://github.com/jml/difftodo) has a [stack.yaml](https://github.com/jml/difftodo/blob/master/stack.yaml) file with a nix stanza that looks like this:

```yaml
# jml uses 'nix' to build on Darwin. These are the non-Haskell packages
# required.
nix:
  enable: false
  packages:
    - pcre
    - pkgconfig
```

I would like to default to nix being disabled, because anecdotal evidence shows that most people don't use it and find the stack error messages confusing. **But**, I would like nix to be enabled in intero, so I can have nix provide `pcre` and `pkgconfig`.

With intero currently, when I load a file in difftodo it starts building dependencies and then alerts "Problem with Intero!". 

Going to the intero backend buffer shows a command line to run. Here's what happens when I run it:

```
$ stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-load --ghci-options -odir=/Users/jml/.emacs.d/temp/intero43767soV --ghci-options -hidir=/Users/jml/.emacs.d/temp/intero43767soV difftodo
highlighter2-0.2.5: configure
highlighter2-0.2.5: build

--  While building package highlighter2-0.2.5 using:
      /Users/jml/.stack/setup-exe-cache/x86_64-osx/setup-Simple-Cabal-1.24.0.0-ghc-8.0.1 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.0.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/jml/src/difftodo/.stack-work/logs/highlighter2-0.2.5.log

    Configuring highlighter2-0.2.5...
    Building highlighter2-0.2.5...
    Preprocessing library highlighter2-0.2.5...
    [  1 of 118] Compiling Text.Highlighter.Types ( src/Text/Highlighter/Types.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Text/Highlighter/Types.o )
… elided …
    [118 of 118] Compiling Text.Highlighter ( src/Text/Highlighter.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Text/Highlighter.o )
    ld: warning: directory not found for option '-L/usr/local/Cellar/pcre/8.39/lib'
    ld: library not found for -lpcre
    clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
    `cc' failed in phase `Linker'. (Exit code: 1)
Warning: build failed, but optimistically launching GHCi anyway
Configuring GHCi with the following packages: difftodo
Progress: 1/2Intero 0.1.18 (GHC 8.0.1)
Type :intro and press enter for an introduction of the standard commands.

<command line>: cannot satisfy -package highlighter2-0.2.5
    (use -v for more information)
```

*Edit*: What I'd like is a file-local variable that I can specify to use nix for certain stack builds. Alternatively, a way to specify my preferences in Stack would also work.

**Comment by mboes** [comment]
I think the solution to this is to use a recent version of Stack. In recent versions, the default as to whether to use Nix is not predicated upon whether the section exists or not: it's predicated on whether you wrote `enable: true` *somewhere* explictly. "Somewhere" can be your ~/.stack/config.yaml or stack.yaml.

I'm on NixOS and I *have* to use `--nix` for all projects on this distro (compiles break if I don't pass it on this platform). So I simply set `nix: enable: true` in my config.yaml and intero happily abides (make sure that no `enable` line is present in the `stack.yaml`).

**Comment by chris-martin** [comment]
:+1:, `~/.stack/config.yaml` is a wonderful thing.

**Comment by jml** [comment]
Thanks. This more or less works for me.
