### ISSUE TITLE
Intero can't see types in Data.Functor.Foldable

### ISSUE THREAD

**Issue by greenrd** [commercialhaskell/intero#264]
I tried to load Data.Functor.Foldable from https://github.com/ekmett/recursion-schemes/ so I could understand the types. I had to add a stack.yaml file because the repo doesn't contain one. But whenever I press C-c C-t, I just get "Couldn't guess that module name. Does it exist?"

**Comment by greenrd** [comment]
If I try `C-c C-l` I get:

```
Starting:
  stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-build --no-load --ghci-options -odir=/tmp/intero95102qs --ghci-options -hidir=/tmp/intero95102qs recursion-schemes
Intero 0.1.18 (GHC 7.10.3)
Type :intro and press enter for an introduction of the standard commands.

WARNING: /tmp is owned by someone else, IGNORING!
Prelude> 
/tmp/intero9510cWg.hs:113:0:
     error: missing binary operator before token "("
     #if HAS_POLY_TYPEABLE
     

/tmp/intero9510cWg.hs:229:0:
     error: missing binary operator before token "("
     #if EXPLICIT_DICT_FUNCTOR_CLASSES
     

/tmp/intero9510cWg.hs:410:0:
     error: missing binary operator before token "("
     #if HAS_POLY_TYPEABLE
     

/tmp/intero9510cWg.hs:420:0:
     error: missing binary operator before token "("
     #if MIN_VERSION_base(4,4,0)
     
intero: phase `C pre-processor' failed (exitcode = 1)
> 
```

**Comment by meditans** [comment]
@greenrd just an idea that might help or not (I wasn't able to reproduce your error): did you try to `stack build` your package from the command line before opening the files with `intero`?

**Comment by chrisdone** [comment]
Can you fix this? 

> WARNING: /tmp is owned by someone else, IGNORING!

Stack passes things to GHCi that are important via a temporary file.
