### ISSUE TITLE
Two completion methods invoked for one completion.

### ISSUE THREAD

**Issue by tshinohara** [commercialhaskell/intero#267]
Recently completion stopped working so I was investing the debug log, and realized something weird.
Both `:complete-at` and `:complete repl` was called for one completion.

    [Intero] -> :complete-at "/tmp/intero13143WdZ.hs" 6 12 6 16 "putS"
    [Intero] -> :complete repl "putS"

Looked into the code, I found a problem in `intero-company-callback` function.

    (defun intero-company-callback (source-buffer prefix-info cont)
      "Generate completions for SOURCE-BUFFER based on PREFIX-INFO and call CONT on the results."
      (cl-destructuring-bind
          (beg end prefix type) prefix-info
        (or (and (bound-and-true-p intero-mode)
                 (cl-case type
                   (haskell-completions-module-name-prefix
                    (intero-get-repl-completions source-buffer (concat "import " prefix) cont))
                   (haskell-completions-identifier-prefix
                    (intero-get-completions source-buffer beg end cont)) ;; line A
                   (haskell-completions-language-extension-prefix
                    (intero-get-repl-completions
                     source-buffer
                     (concat ":set -X" prefix)
                     (-partial (lambda (cont results)
                                 (funcall cont
                                          (mapcar (lambda (x)
                                                    (replace-regexp-in-string "^-X" "" x))
                                                  results)))
                               cont)))
                   (haskell-completions-pragma-name-prefix
                    (funcall cont
                             (cl-remove-if-not
                              (lambda (candidate)
                                (string-match (concat "^" prefix) candidate))
                              intero-pragmas)))))
            (intero-get-repl-completions source-buffer prefix cont))))  ;; Line B

Because `intero-get-completions` returns nil, after Line A, Line B is also executed. `cont` for company mode is called twice, which I don't think is intentional.

**Comment by chrisdone** [comment]
Good detective work!
