### ISSUE TITLE
"No more Flycheck errors" when highlighted errors are visible

### ISSUE THREAD

**Issue by Blaisorblade** [commercialhaskell/intero#268]
Sometimes intero buffers enter a bad state, where errors/warnings are shown with red squiggly lines but M-g n gives "No more Flycheck errors", also shown in `*Messages*` as:

```
user-error: No more Flycheck errors
```

And when a buffer enters that state I don't know how to fix it. I've been having this for a while without insights as to its cause.

**Comment by chrisdone** [comment]
I think that's because flycheck doesn't circle round and start from the beginning again. Your errors are probably above your cursor?

**Comment by Blaisorblade** [comment]
That's annoying but it's not that, sorry for the ambiguous report. Errors
are after the cursor.

**Comment by Blaisorblade** [comment]
Just happened again, but while `M-g n` doesn't work, `C-c ! n` works fine.
The first is bound to `(next-error &optional ARG RESET)`, the second to `(flycheck-next-error &optional N RESET)`. Should I file a ticket with flycheck?

FWIW: I also *seem to have noticed* this state is triggered when trying to do a jump right after a change that introduces warnings.

Some other times, doing a change means that new warnings are shown briefly and then all warnings disappear, but that is fixed by reloading the file (with `M-x revert-buffer`).

**Comment by Blaisorblade** [comment]
Working around this with https://gist.github.com/Blaisorblade/c7349438b06e7b1e034db775408ac4cb for now. I'm an Elisp noob.

**Comment by Blaisorblade** [comment]
> Just happened again, but while M-g n doesn't work, C-c ! n works fine.

Paging @lunaryorn on this—this happened with flycheck integration normally enabled (that is, with `flycheck-standard-error-navigation` set to `t`). That is, `M-g n` gives "No more Flycheck errors" when `C-c ! n` from the same point jumps to the next error. How can this happen?
