### ISSUE TITLE
Test imports not being found

### ISSUE THREAD

**Issue by tekul** [commercialhaskell/intero#270]
I'm using intero in spacemacs with a project I have here [on github](https://github.com/tekul/jose-jwt). I'm using LTS 7.0 (I deleted my entire .stack directory and started afresh). `stack build` and `stack test` both work fine without errors.

When I load [this file](https://github.com/tekul/jose-jwt/blob/master/tests/Tests/JwkSpec.hs), I get the following flycheck errors:

```
     5   1 error           error:
                                    Failed to load interface for ‘Test.Hspec’
                                   It is a member of the hidden package ‘hspec-2.2.3’.
                                   Use -v to see a list of the files searched for. (intero)
     6   1 error           error:
                                   Failed to load interface for ‘Test.HUnit’
                                  It is a member of the hidden package ‘HUnit-1.3.1.2’.
                                  Use -v to see a list of the files searched for. (intero)
     9   1 error           error:
                                  Failed to load interface for ‘Data.Aeson.QQ’
                                  It is a member of the hidden package ‘aeson-qq-0.8.1’.
                                  Use -v to see a list of the files searched for. (intero)
```
Intero seems to be ignoring the test dependencies when loading my test files - for example, if I add `aeson-qq` to the library section in the cabal file, then the 3rd error disappears.

**Comment by Blaisorblade** [comment]
Unfortunately, by default intero only enables the library. Currently you need to select the appropriate targets with `intero-targets`. Once you figure out your targets, you can use this workaround to set `intero-targets` automatically:

https://github.com/commercialhaskell/intero/issues/195#issuecomment-239634535

And BTW this should be a duplicate of #195—if that works could you please close this issue? (But I'm just a fellow user).

**Comment by tekul** [comment]
Ah, OK. Thanks a lot for the pointer. I thought it was working before (a couple of months back) but I must have been mistaken.
