### ISSUE TITLE
No completion for functions/types defined in GHCi

### ISSUE THREAD

**Issue by CSRaghunandan** [commercialhaskell/intero#271]
Looks like there are no `completion-at-point` for functions  or types defined in GHCi. But, I do get completions for functions loaded from a source file, as expected.

**Comment by chrisdone** [comment]
Good catch -- I think it needs to update the completion list after evaluating things.

**Comment by KarlFish** [comment]
Pull request https://github.com/commercialhaskell/intero/pull/454 makes `completion-at-point` emulate tab completion in ghci.
