### ISSUE TITLE
Option to not use docker on mac

### ISSUE THREAD

**Issue by zkessin** [commercialhaskell/intero#273]
when I started up intero it ran this command line
````
 stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-build --no-load --ghci-options -odir=/var/folders/17/7_w5m3d918g8vsqhh0g_xj4m0000gn/T/intero45481CYF --ghci-options -hidir=/var/folders/17/7_w5m3d918g8vsqhh0g_xj4m0000gn/T/intero45481CYF
```` 

Problem is that running docker on a mac is a really bad idea as it tends to fill up the hard drive 

https://forums.docker.com/t/consistently-out-of-disk-space-in-docker-beta/9438

**Comment by chrisdone** [comment]
Those flags should be benign if your stack.yaml doesn't specify a docker. Is it somehow trying to start docker on your system?

**Comment by zkessin** [comment]
ah ok
