### ISSUE TITLE
Add JSON messages for communication

### ISSUE THREAD

**Issue by vavans** [commercialhaskell/intero#274]
It should be great to have a better way to interact with intero than parsing human readable outputs.
A protocol based on **JSON messages** using stdout only (no stderr to avoid sync issues between stdout and stderr) could do the job, like http://www.jsonrpc.org/.

There are good haskell libs like https://hackage.haskell.org/package/json-rpc to deal with the protocol.

**Comment by chrisdone** [comment]
I think a JSON RPC is a good idea. It should be over sockets because stdout/stderr are polluted by the programs being ran inside GHCi.

**Comment by rvion** [comment]
How about using the language-server-protocol ?

> The Language Server protocol is used between a tool (the client) and a language smartness provider (the server) to integrate features like auto complete, goto definition, find all references and alike into the tool. The following diagram illustrates the communication between a tool and the language server.

https://code.visualstudio.com/blogs/2016/06/27/common-language-protocol

#### open spec: 

https://github.com/Microsoft/language-server-protocol

> This is just the start – communities for programming languages like OmniSharp (C#), JSON, C++, xText, JavaFX, and R have made commitments to release language servers for their languages in the future. A full list of protocol implementations, including language servers, editors, and SDKs is available on the GitHub repo.

(ps: I told the same thing here: https://github.com/haskell/haskell-ide-engine/issues/213)

**Comment by vavans** [comment]
Implementing the language-server-protocol would be perfect.

What about dividing the task in 2 parts:

1. Designing an intero API for haskell programs who want to call intero features as simple functions calls. I can import that API in my haskell code and start using functions like locAt, as regular function calls
2. Implement the language-server-protocol and using that API as a "backend"

**Comment by alanz** [comment]
FYI https://github.com/alanz/haskell-lsp and https://github.com/alanz/vscode-hie-server

**Comment by chrisdone** [comment]
There are things to consider for something like this:

1. The protocol should be simple and not impose additional invariants over what we're already doing. JSON RPC satisfies that. Let's not make it more complicated by adding Microsoft's protocol.
2. The messages may support being done concurrently (querying the buffer and doing a compile), which will need to make use of the message id's in JSON RPC. This will also need mutexes (such as only one compile at once) placed appropriately around the codebase. This is an additional invariant.
3. How messages and stdout/stderr/stdin are negotiated needs to be determined. E.g. to run `> print 1`, the result is written to stdout, and then a command result is returned; should the client then be smart enough to always track stdout? Actually, thanks to threads, stdout/stderr can happen at any time, so probably it should.
4. The existing `:foo` messaging structure should be preserved, so you would have to rewrite those in terms of this new architecture. And _don't break it._
5. How the socket is made open and on what port needs to be negotiated by the client and also some kind of token used to authenticate the connection provided by the IDE, to avoid connections by those with no business in doing so.
6. It's not trivial to tell GHC's API to always send messages to the right place, it'll dump things to stdout/stderr anyway in many places. You probably would want to hook into the API to get messages as results for compilation, something else to take into consideration.

It's not a trivial addition. scion, ghc-server, ide-backend, and haskell-ide-engine have all tread this area before.

If you're expecting me to work on this, it'll be on a lower priority than e.g. fixing existing bugs in intero. If you'd like to work on it, then the above things need to be addressed.

**Comment by alanz** [comment]
From GHC 8.0.2 onwards there will also be an option to use the external interpreter and explicitly manage the stdio to it, via https://github.com/ghc/ghc/commit/daa4de57c9faa3ee471fca92386360e1a06c382b
