### ISSUE TITLE
Error message in completion list

### ISSUE THREAD

**Issue by Kwarrtz** [commercialhaskell/intero#275]
Lately, whenever I type three characters while in Intero mode, a completion list appears with exactly two possible completions, regardless of what I type. Those completions are:

```
error, called at src/InteractiveUI.hs:1801:24 in main:InteractiveUI
```

and

```
CallStack (from HasCallStack):
```

It seems to me to be an error message of some sort which is being interpreted as a completion candidates list, but my `*messages*` buffer doesn't show any sign of Intero or company having errored at any point. I've tried all the obvious things (restarting company, restarting Intero, rebooting Emacs, switching to another project, etc.) all to no avail. Any help is appreciated.

I'm running Emacs 24.5 and GHC 7.8 on Mac OS X El Capitan.

**Comment by chrisdone** [comment]
Thought we had an issue open for this. It's what happens when the module wasn't loaded successfully.

**Comment by Kwarrtz** [comment]
Which module? Intero or my program?

**Comment by acowley** [comment]
Maybe @chrisdone is remembering #223 which does seem related.

**Comment by anderspapitto** [comment]
I'm seeing similar things (errors in the completion menu). Right now I have a completion menu with one entry, `<no location info>: error: not an expression: ''`

**Comment by chrisdone** [comment]
@anderspapitto yours should be fixed. But I'm having trouble reproducing `error, called at src/InteractiveUI.hs:1801:24 in main:InteractiveUI`.

@Kwarrtz Do you have some reproduction steps? An example module or project?

**Comment by Ptival** [comment]
I'm having the same problem as @anderspapitto 

![image](https://user-images.githubusercontent.com/478606/40250278-a769db4e-5a8a-11e8-92ab-a9d4420071bf.png)

Version:
`./.local/packages/elpa/intero-20180418.503/intero.el`
