### ISSUE TITLE
Not working for docker stack projects

### ISSUE THREAD

**Issue by houli** [commercialhaskell/intero#279]
I have a project using the "basic" stack template. When I build it with

``` yaml
docker:
  enable: true
```

in my `stack.yaml` file intero stops working. Turning off docker support, deleting `.stack-work` and rebuilding and intero starts working again.
This is using the latest Docker for Mac with intero 0.1.18 for reference.

**Comment by houli** [comment]
Here's some logs from the docker containers when intero is booted up.
```
Configuring GHCi with the following packages: distributed-systems
Intero 0.1.18 (GHC 7.10.3)
Type :intro and press enter for an introduction of the standard commands.
2016-10-02T11:29:56.646518707Z 
2016-10-02T11:29:57.800842691Z 
<no location info>:
    can't find file: /var/folders/y1/_sd9mpx526j25qk9546fdz_c0000gn/T/intero14547Icw.hs
> > Failed, modules loaded: none.
2016-10-02T11:30:00.031501949Z 
<no location info>:
    can't find file: /var/folders/y1/_sd9mpx526j25qk9546fdz_c0000gn/T/intero14547Icw.hs
Failed, modules loaded: none.
Couldn't guess that module name. Does it exist?
```

Also, every time I restart intero a new docker container is being created not sure if this is intended behaviour.

**Comment by houli** [comment]
Just another update, I can confirm that these `/var/folders` paths are present on my host Mac filesystem but the Docker containers running intero are failing to find them as they don't exist within the container

**Comment by chrisdone** [comment]
Does `stack ghci` work?

**Comment by houli** [comment]
Yes just the basic `stack ghci` works as expected. Sorry I should clarify this is using the `simple` template not `basic` as I said before but applies to any project. I've also noticed this while using the `stack-build` container for LTS 7.3 as well as LTS 6.19 so it doesn't appear to be LTS specific.

**Comment by shanemikel** [comment]
I'm having this problem too, for this file: /var/folders/xz/99z8msbn5_s_c8prs1x5h5hr0000gn/T/intero18946_Ms.hs

If it's a docker project, why should intero require anything from the host?  I would think, as stack installs itself in the container, that intero would as well.

**Comment by shanemikel** [comment]
So, I believe that Stack (with that Docker flag) forwards all Stack commands (reinvokes with Docker exec) to another Stack executable in the container.

It looks like Intero (Emacs client) is writing changes to working buffer in a temporary file since #248, and clearly the container won't have this path.

I think a solution would be to put the temporary file in the Project directory (perhaps $PROJECT/.intero ?) or in the .stack directory

**Comment by chrisdone** [comment]
@shanemikel Good point, and I think your solution makes sense.

**Comment by purcell** [comment]
@chrisdone @shanemikel @houli I believe the changes I've submitted in #293 should address this successfully - please take a look and comment there if you have feedback.

**Comment by houli** [comment]
@purcell Unfortunately there still seems to be problems after the merge of your PR.
```
Using main module: 1. Package `test' component exe:test with main-is file: /Users/eoinhoulihan/Desktop/test/src/Main.hs
Configuring GHCi with the following packages: test
Intero 0.1.18 (GHC 7.10.3)
Type :intro and press enter for an introduction of the standard commands.
2016-10-20T11:45:32.107848570Z 
Prelude> Prelude> [1 of 1] Compiling Main             ( /Users/eoinhoulihan/Desktop/test/.stack-work/intero/intero16061AUn.hs, /var/folders/y1/_sd9mpx526j25qk9546fdz_c0000gn/T/intero16061Net/Main.o )
*** Exception: /var/folders: createDirectory: permission denied (Permission denied)
[1 of 1] Compiling Main             ( /Users/eoinhoulihan/Desktop/test/.stack-work/intero/intero16061AUn.hs, /var/folders/y1/_sd9mpx526j25qk9546fdz_c0000gn/T/intero16061Net/Main.o )
*** Exception: /var/folders: createDirectory: permission denied (Permission denied)
Couldn't guess that module name. Does it exist?
Couldn't guess that module name. Does it exist?
```

**Comment by purcell** [comment]
Hmm. I think that just means that the further changes mentioned in #293 will be necessary after all. I can probably get to that over the weekend and report back. :-)

**Comment by purcell** [comment]
@houli #296 should address that too.

**Comment by houli** [comment]
Working now with the merge of #296

**Comment by purcell** [comment]
@houli Awesome, thanks for confirming!
