### ISSUE TITLE
Type display problem: Two type variables with the same name

### ISSUE THREAD

**Issue by meditans** [commercialhaskell/intero#280]
I'm having some problems with the types intero infers for this program:

``` haskell
data Proxy a' a b' b m r
  = Request a' (a  -> Proxy a' a b' b m r)
  | Respond b  (b' -> Proxy a' a b' b m r)
  | M (m (Proxy a' a b' b m r))
  | Pure r

instance Monad m => Functor (Proxy a' a b' b m) where
  fmap f (Request a' g) = undefined
  fmap f (Respond b  g) = undefined
  fmap f (M m)          = undefined
  fmap f (Pure r)       = undefined
```

If I query for the type of `g` in the first line of the instance declaration, I get `g :: a -> Proxy a' a b' b m a
`, while it's clear that the `a` variable is captured in this way (it should have been `g :: a -> Proxy a' a b' b m x` with a fresh variable). So to correct that I add `InstanceSigs` and write:

``` haskell
{-# LANGUAGE InstanceSigs #-}

data Proxy a' a b' b m r
  = Request a' (a  -> Proxy a' a b' b m r)
  | Respond b  (b' -> Proxy a' a b' b m r)
  | M (m (Proxy a' a b' b m r))
  | Pure r

instance Monad m => Functor (Proxy a' a b' b m) where
  fmap :: (r -> s) -> Proxy a' a b' b m r -> Proxy a' a b' b m s
  fmap f (Request a' g) = Request a' (\aa -> fmap f (g aa))
  fmap f (Respond b  g) = undefined
  fmap f (M m)          = undefined
  fmap f (Pure r)       = undefined
```

Now when querying for the types of `fmap`, `f`, `g` and `aa` in the right hand side of the first clause of the definition of `fmap` I get very strange types, like `fmap :: a -> Proxy a' a b' b m s` or `g :: Proxy a' a b' b m r`. Do you get the same errors? What's going on here?

**Comment by meditans** [comment]
Ok, I got what was going on: I was trying `'(haskell-font-lock-symbols t)` in my config, along with the `hasklig` font. That evidently disturbed the column numbering, and that explains the incorrect types.

My question still stands on the variable capture in `g :: a -> Proxy a' a b' b m a`, however.

**Comment by chrisdone** [comment]
For me, `g` is reported as `g :: a -> Proxy a' a b' b m r`.

**Comment by chrisdone** [comment]
That is, with your additional signature, it's reported as 
``` haskell
g :: a -> Proxy a' a b' b m r
```

Without it, I get:
``` haskell
g :: a -> Proxy a' a b' b m a
```

Yeah, I think you're right, the two `a`'s are different, but their scope isn't delimited so we don't know that. Maybe we should do alpha-renaming when reporting types, using the Uniqueness of a name rather than what it pretty-prints like as the comparison function.

**Comment by meditans** [comment]
Sure, I meant the error is there without the additional signature (I added it to correct that mismatch).
I really think this should be fixed, because the reply silently changed the meaning of the objects involved; alpha renaming seems a good thing to do, but at that point one also needs a system to keep the chosen type variable consistent (in the example I made before, if you rename automatically the first proxy to `Proxy a' a b' b m r` then you should also have the inferred type for `f` be like `f :: r -> b`). That seems a non obvious problem to me; is this analysis correct in your opinion or am I missing something?

**Comment by chrisdone** [comment]
I think your analysis is correct. Here is a simplified version of the problem:

``` haskell
data X a b = X a b
data X' a b = X' a b

instance Functor (X x) where
  fmap f (X a b) = X a (f b)
         --   ^ type: a
         -- ^ type: x
         -- The a comes from: forall a b. (a -> b) -> f a -> f b

instance Functor (X' a) where -- x is changed to a
  fmap f (X' a b) = X' a (f b)
         --   ^ type: a
         -- ^ type: a
         -- But the two a's are different!
```

I agree with your evaluation also that alpha-renaming presents a challenge.

I'll welcome any ideas for presenting this better.

**Comment by chrisdone** [comment]
Here's a strawman idea. Whenever we display a type with a type-variable in it, we include the provenance of that type variable (from where it was quantified). For example:

``` haskell
fmap f (X' a b) = X' a (f b)
```

* Instead of `a :: a`, we could get:

  ``` haskell
  a :: a
  where
     instance forall a. Functor (X' a)
  ```
* Instead of `b :: a`, we could get:

  ``` haskell
  b :: a
  where
     fmap :: forall a b. (a -> b) -> f a -> f b
  ```
* Instead of `X' a b :: X' a a`, we could get:

  ``` haskell
  X' a b :: X' a[1] a[2]
  where
     instance forall a[1]. Functor (X' a[1])
     fmap :: forall a[2] b. (a[2] -> b) -> f a[2] -> f b
  ```

Upon thinking about it I think that alpha-renaming them (i.e. changing to a different letter) is likely to be confusing. Whereas this approach of suffixing which 'a' we're referring to is neither misleading nor incorrect. At this point, the programmer might be motivated to rename the variable themselves to e.g. `x`.

**Comment by chrisdone** [comment]
Alternatively, we do alpha-renaming with some numeric arguments like GHC does:
```
X' a b :: a0 a1
```

But that still leaves the question of where these come from, so it seems like a poor solution.

**Comment by alanz** [comment]
FYI, if you want to use colour as suggested by @goldfirere, you should be able to do it based on the class of the occname. See [isTvOcc](https://downloads.haskell.org/~ghc/7.10.3/docs/html/libraries/ghc-7.10.3/OccName.html#v:isTvOcc) and friends.
