### ISSUE TITLE
M-. opens temprorary file

### ISSUE THREAD

**Issue by qrilka** [commercialhaskell/intero#282]
I have the latest `intero` from Melpa stable and recently I have noticed quite weird behavior from it: I try "jump to definition" for some symbols and get files from `~/tmp` directory opened even when those symbols are defined in the same package as there file where I press `C-.`
Is it some expected thing and if it's not is there any good way to debug what's going on here?

**Comment by acowley** [comment]
I've seen this, too. As I understand it, the temporary files shouldn't be added to whatever set of files is consulted when jumping to source, but some part of that isn't working correctly.

**Comment by chrisdone** [comment]
Could you try the latest elisp? I seem to recall seeing that and fixing it, but I don't know how melpa stable chooses which version it includes.

**Comment by qrilka** [comment]
I've run `cask update` and now I see more datails:
```
Warning (intero): Couldn't get the Stack project root.

This can be caused by a syntax error in your stack.yaml file. Check that out.

Otherwise, please report this as a bug!
Warning (intero): Couldn't get the Stack project root.

This can be caused by a syntax error in your stack.yaml file. Check that out.

Otherwise, please report this as a bug!
Warning (intero): Couldn't get the Stack project root.

This can be caused by a syntax error in your stack.yaml file. Check that out.

Otherwise, please report this as a bug!
```
That's contents of `*Warnings*` buffere which opened after some jumping around in our repo and it's reproducible in open repo too - I've clicked `M-.` for `Comment` on https://github.com/qrilka/xlsx/blob/master/src/Codec/Xlsx/Types.hs#L122 and see temporary file + warnings.
So the problem seems to be about record and module sharing 1 name
