### ISSUE TITLE
add file imports in REPL?

### ISSUE THREAD

**Issue by unhammer** [commercialhaskell/intero#284]
If I have a file 

```
module Foo where
import qualified Bar as B
```

then I have to to `import qualified Bar as B` in the REPL too. Can the REPL do this automatically for me? I always spend a lot of time copy-pasting import lines whenever I reload.

**Comment by unhammer** [comment]
I see that haskell-mode's REPL seems to include more (but not all) of the imports, e.g. if I have unqualified `import Bar`, where `Bar.hs` defines `bar`, I can do `bar` from haskell-mode's REPL, but have to do `Bar.bar` from intero's REPL.

**Comment by chrisdone** [comment]
A workaround is to set `:set -fbyte-code` in the REPL and reload.

**Comment by chrisdone** [comment]
The REPL now defaults to -fbyte-code.
