### ISSUE TITLE
Should intero disable on non-stack projects?

### ISSUE THREAD

**Issue by MichaelXavier** [commercialhaskell/intero#285]
Thankfully, most of my projects are stack-based now, but I work on a few projects that aren't there yet. I have intero-mode set up as a haskell-mode-hook, so whenever I open a file in that project intero I end up getting a buffer pop up with an error message. I think I could probably use projectile to find the root and wrap the `intero-mode` function in one that's conditional based on if there's a `stack.yaml` in the root. However, if intero will _always_ fail on non-stack projects, it seems pretty common that haskell devs will work on both kinds of projects and this will become an annoyance. Is it worth considering intero detecting non-stack projects and not starting. Alternatively, maybe intero could expose a function that could determine if the current project is a stack project and then the readme could have an example with that instead of one that unconditionally launches intero.

**Comment by chrisdone** [comment]
How would we determine that you're not using stack on a given project?

**Comment by MichaelXavier** [comment]
Would it be reasonable to check for a stack.yaml? `stack path` has a line `config-location` that gives you the absolute path of the stack.yaml. I tried running it in a non stack project and it warns that its run from outside a project so it gives you information about the global stack project, so it seems like stack itself knows whether its in a project.

**Comment by chrisdone** [comment]
@MichaelXavier What about the use-case of editing a file outside of any project?  I regularly open random files and intero assumes the global project.

Should this be a config flag perhaps?

**Comment by MichaelXavier** [comment]
That's a good point. It makes adding this feature fairly hard to justify. I think maybe the best thing is instead of doing `(add-hook 'haskell-mode-hook 'intero-mode)`, I could use some convention on projects I want to exempt from intero (maybe projectile has a convention for this) and then put the `intero-mode` behind a conditional. If I remember, I could update this ticket with my solution, but at this point I think its probably best for intero to stay neutral.

**Comment by MichaelXavier** [comment]
Here's what I've thrown together and it seems to work. I'm no elisp master so I make no claims about this being the "right" way:

```elisp
(defvar intero-exempt-projects '("oldproject") "List of projectile project names that cannot run intero.")

(defun intero-mode-unless-exempt ()
  "Run intero-mode unless the current project is in intero-exempt-projects"
  (interactive)
  (unless (member (projectile-project-name) intero-exempt-projects)
    (intero-mode)))

;; hook in intero
(add-hook 'haskell-mode-hook 'intero-mode-unless-exempt)
```

If this sounds good, feel free to close.

**Comment by chrisdone** [comment]
@MichaelXavier That sounds good. I'll include that in intero proper and put it in the docs.

**Comment by chrisdone** [comment]
You can now use a blacklist documented here: https://github.com/commercialhaskell/intero#whitelistingblacklisting-projects

It works on directories, which while not as convenient as package names, lets you blacklist a whole directory.
