### ISSUE TITLE
Make intero-mode togglable

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/intero#286]
Related to #285, it should be easy to disable intero-mode entirely for any given source file. I have `intero-mode` in my `haskell-mode-hook`. So when I load a source file Intero is always on. If I want to turn it off, `M-x intero-mode` isn't sufficient: `flycheck-mode` and `company-mode` are still there, so I have to additionally toggle each of those to undo the effect of the hook.

Command: `M-x intero-mode`
Expected: all modes enabled by `intero-mode` are disabled, i.e. `intero-mode` twice == id.
Actual: only intero-mode is disabled, but not flycheck nor company.

**Comment by chrisdone** [comment]
Sounds fair.

**Comment by deepfire** [comment]
@mboes, @chrisdone, in my experience it isn't as simple as just `flycheck-mode` and `company-mode` -- sometimes I'm literally stuck, unable to figure out _what_ I need to disable to stop `intero` from trying (and failing to, due to external reasons) start up.  It can be pretty frustrating..
