### ISSUE TITLE
Intero refuses to start with a compiler error in source

### ISSUE THREAD

**Issue by zkessin** [commercialhaskell/intero#287]
If you open up a source file that can not compile for some reason then intero does not work and in some cases it will lock up emacs. The problem is that often a program is a state where part of it is broken (hence the need to edit) but having some of the functions of intero would be really useful

**Comment by mgsloan** [comment]
I believe this will be fixed in the next stack release - see https://github.com/commercialhaskell/stack/issues/1364

**Comment by chrisdone** [comment]
@zkessin I think updating to the latest stack release should fix this.
