### ISSUE TITLE
Questions about TOOLING.md

### ISSUE THREAD

**Issue by Tehnix** [commercialhaskell/intero#289]
Hey!

I was looking into what was required to make an intero plugin for the Atom editor, and was wondering if someone could expand a bit on the [tooling.md](https://github.com/commercialhaskell/intero/blob/master/TOOLING.md)?

From what I can see:
1. You build stack for the current project with `stack build intero`
2. You start a process running `stack ghci --with-ghc intero` to load the project (what is the difference between that and just running `stack exec intero`?)
3. You send input to the process on its stdin, such as `:type-at Settings.hs lineStart colStart lineEnd colEnd functionName` (e.g. `:type-at Settings.hs 171 1 171 15 combineScripts`)
4. You catch the output from running that and display it to the user in a neat way

Some immediate questions (I'm sure there'll be more later on):
- Are the any documentation on the arguments the various functions expect?
- How do you currently handle things like docker processes? An example being if the docker container has a name, then intero can't run if the container is already running

**Comment by chrisdone** [comment]
> What is the difference between that and just running stack exec intero?

`stack ghci` sets up the load paths and targets and such.

If you run `:type-at` it replies with the required args:

> Are the any documentation on the arguments the various functions expect?

    <no location info>: Expected a span: "<module-name/filepath>" <start line> <start column> <end line> <end column> "<sample string>"

> How do you currently handle things like docker processes? An example being if the docker container has a name, then intero can't run if the container is already running

`stack` itself handles the docker stuff. I don't know much about it.
