### ISSUE TITLE
error in process filter: Symbol’s function definition is void: haskell-utils-repl-response-error-status

### ISSUE THREAD

**Issue by jwaldmann** [commercialhaskell/intero#290]
When I open a source file in emacs with intero, the status line (minibuffer) shows
```
error in process filter: Symbol’s function definition is void: haskell-utils-repl-response-error-status [12 times]
```
and this brings emacs nearly to a halt (makes the editor unusable, because any key press is only handled after several seconds of delay)

perhaps this is #287 ?

**Comment by chrisdone** [comment]
Seems like haskell-mode removed yet another function. I've cloned the function that we were using into intero. Please pull. =)
