### ISSUE TITLE
A second attempt to run `main` results in "Segmentation fault/access violation".

### ISSUE THREAD

**Issue by effectfully** [commercialhaskell/intero#291]
I've installed intero today and there is a problem. After creating a new stack project and opening `Main.hs` in intero, I type `C-c C-l`, the module type checks successfully and I run `main` in the interpreter, which prints "someFunc". However if I do the same again (`C-c C-l` and run `main`) it results in

```
Segmentation fault/access violation in generated code

Process intero exited abnormally with code 1
```

I tried to reinstall intero, but it didn't help. The OS is Windows 7.

**Comment by chrisdone** [comment]
Does `stack ghci` work for your project?

**Comment by effectfully** [comment]
I removed `intero`, reinstalled `haskell-mode` and it works with stack. I don't know, whether it calls `stack ghci` or not.

**Comment by chrisdone** [comment]
Fair enough.
