### ISSUE TITLE
Suggestion/feature request: automatically wild-card unitialized record fields

### ISSUE THREAD

**Issue by ocharles** [commercialhaskell/intero#292]
I often work with records that have enough fields that I can't quite remember all of them. Consider a record `R`, I will often write code such as

``` haskell
foo = do
 ...
 return R {}
```

This causes a warning that there are uninitialized fields, so it would be nice if `intero` could automatically expand `R {}` into all of its fields:

``` haskell
foo = do
 ...
 return R {a = _, b = _, c = _}
```

**Comment by chrisdone** [comment]
I want the same thing! I think it's relatively straight-forward to implement.

**Comment by chrisdone** [comment]
This is implemented, by the way. If you write `Foo{}`, GHC suggests missing fields. You can hit `C-c C-r` and `C-c C-c` and it'll fill in the fields.
