### ISSUE TITLE
Automatic installation customization

### ISSUE THREAD

**Issue by acowley** [commercialhaskell/intero#295]
I find myself annoyed by the automatic installation system rather often because it always wants to install an older version of `intero` than I want (I enjoy the qualified import completion thing which was merged a bit over a month ago). What I'm imagining is something like a change to `intero-auto-install` that checks a variable to tell stack to build intero from a particular file path rather than a released version.

Any thoughts?

**Comment by chrisdone** [comment]
Possibly, I'm not sure how one might install from a specific path.

I could be more prompt at releasing a new version after merging in
features. Between September and October I got married and moved country, so
I've not had much time. But I'm back now.

**Comment by acowley** [comment]
Priorities: CONGRATULATIONS! 🎉✨🎆😃

**Comment by chrisdone** [comment]
Pushed to hackage.

**Comment by chrisdone** [comment]
@acowley I've added you as a collaborator to the project. If I'm unresponsive in future you can resolve the issue without having to wait around. 😄
