### ISSUE TITLE
YCMD-like completion for Haskell

### ISSUE THREAD

**Issue by korayal** [commercialhaskell/intero#299]
Is there any future plan for fuzzy auto-completion?

The [ycmd](https://github.com/Valloric/YouCompleteMe) package has this feature for several languages where you can start typing characters that the word you are looking for has and it finds that word. What you type doesn't need to be a substring or the first few characters of what you are looking for:

![YCMD demo](https://camo.githubusercontent.com/1f3f922431d5363224b20e99467ff28b04e810e2/687474703a2f2f692e696d6775722e636f6d2f304f50346f6f642e676966)

**Comment by unhammer** [comment]
I was about to say you could just use [company-flx](https://github.com/PythonNut/company-flx), but then I noticed I'm already using that in emacs-lisp, but it doesn't work in haskell/intero. That page says: 

> Caveats
> This only works with the company-capf backend. Most sources use this backend, with the exception of the more advanced sources.

**Comment by PythonNut** [comment]
Yeah, support for fuzzy matching would ideally be added to the backend itself. `company-flx` takes care of sorting primarily.
