### ISSUE TITLE
Intero can fail where `stack build` succeeds, if ~/.ghci sets pragmas that break compilation

### ISSUE THREAD

**Issue by afcady** [commercialhaskell/intero#300]
I had a source file that was compiling fine with `stack build`, but Intero reported a whole bunch of type errors.

I was able to silence Intero by explicitly specifying `{-# language NoOverloadedStrings #-}` in the source file.

It turns out this was because my `~/.ghci` contained `:set -XOverloadedStrings`.

It seems to me that Intero syntax checking should use the same pragmas as `stack build`, rather than be influenced by `~/.ghci`.

**Comment by afcady** [comment]
I found out this was caused by `:set -XOverloadedStrings` in my `~/.ghci` file.  Not closing because it still seems like a bug to me.

**Comment by chrisdone** [comment]
Perhaps intero should pay attention to a `.intero` file?

**Comment by afcady** [comment]
Looks like this is fixed.
