### ISSUE TITLE
Setting env-file in docker-args in stack.yaml breaks installation and project root finding

### ISSUE THREAD

**Issue by enolan** [commercialhaskell/intero#302]
I'm not sure if this is related to commercialhaskell/stack#2757 or the same problem or not. With a `--env-file` argument in the docker.run-args key in `stack.yaml`, the emacs mode gives an error message and a bunch of warnings installing the Haskell Intero package.

Concretely, following the steps to reproduce in the linked issue and opening `src/Lib.hs` in Emacs instead of running `stack ghci` gets you nine copies of this:
```
Warning (intero): Couldn't get the Stack project root.

This can be caused by a syntax error in your stack.yaml file. Check that out.

Otherwise, please report this as a bug!
```
in `*Warnings*` and this message:
```
SQLite3 returned ErrorBusy while attempting to perform step.

---

This is the buffer where Emacs talks to intero. It's normally hidden,
but a problem occcured.

TROUBLESHOOTING

It may be obvious if there is some text above this message
indicating a problem.

The process ended. Here is the reason that Emacs gives us:

  exited abnormally with code 1

For troubleshooting purposes, here are the arguments used to launch intero:

  stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-build --no-load --ghci-options -odir=/home/enolan/junk/docker-env/src/.stack-work/intero/intero21181kJ2 --ghci-options -hidir=/home/enolan/junk/docker-env/src/.stack-work/intero/intero21181kJ2 docker-env

WHAT TO DO NEXT

If you fixed the problem, just kill this buffer, Intero will make
a fresh one and attempt to start the process automatically as
soon as you start editing code again.

If you are unable to fix the problem, just leave this buffer
around in Emacs and Intero will not attempt to start the process
anymore.

You can always run M-x intero-restart to make it try again.


```
in `intero:backend:docker-env`. Afterward, the `intero` executable is installed in the root's `.stack-work`. Intero seems to work after restarting but stills outputs the "Couldn't get stack project root" message every time the file is rechecked. There's also a `.stack-work` under `src`, with only an `intero` subdirectory, but I'm not sure if that part's actually a bug.

**Comment by enolan** [comment]
commercialhaskell/stack#2774 fixes this (provided you get `exec-path` set right).

**Comment by mgsloan** [comment]
I've merged the PR, so I think this can be closed.
