### ISSUE TITLE
Work under tramp

### ISSUE THREAD

**Issue by k-bx** [commercialhaskell/intero#303]
This is definitely an "I wish one day" item, but it'd be nice if intero would be able to launch itself on a remote machine when you open a remote file. That would let you easily program from a weak machine over ssh to a "beefy" server. Text-mode emacs could do that, of course, but tramp would be also nice, would use your local config so you wouldn't have to put it on server plus things like scrolling would still work.

**Comment by WraithM** [comment]
That would be amazing. I also sometimes use tramp for accessing code on a locally hosted virtual machine, eg. Linux virtual machine on a macOS host. It would be nice if intero worked there.

**Comment by chrisdone** [comment]
I think the diff to get from here to there wouldn't be too large. I'd also like this once in a while.

**Comment by rlupton20** [comment]
I've been using this for the last couple of months successfully. Are there any further tweaks that need doing here? I'd be happy to take a look if there are, otherwise, this can be closed?

**Comment by k-bx** [comment]
Great news! I'll check it out, but I think it makes sense closing this anyways.
