### ISSUE TITLE
Respond to changes in cabal file (dependencies)

### ISSUE THREAD

**Issue by shanemikel** [commercialhaskell/intero#305]
I'm using intero with stack's docker support, and it looks to be working now thanks to @houli.

Though, when I make a change to my .cabal file (like adding a build-depends item), the changes don't seem to take until I kill the repl buffer.

This isn't that big a deal now that I figured out how to work around it, but and perhaps this should be opened in another issue, killing the buffer seems to leave a running docker process around.

**Comment by chrisdone** [comment]
I'd agree some kind of note or behaviour should react to changes.

**Comment by ntc2** [comment]
And to be clear, a workaround is `M-x intero-restart`.
