### ISSUE TITLE
constant error messages in fontification

### ISSUE THREAD

**Issue by anderspapitto** [commercialhaskell/intero#306]
whenever I stop moving the cursor, up pops the message `error in process filter: Wrong argument type: characterp, nil`

here's the backtrace that gets hit if I use toggle-debug-on-error. intero is in there at the end of the call stack.

It might have to do with the fact that my file doesn't currently compile.

```

[bt.txt](https://github.com/commercialhaskell/intero/files/574112/bt.txt)

```

**Comment by joehillen** [comment]
@anderspapitto Are you using spacemacs? I've been having this issue in spacemacs as well, but I wasn't sure if intero was the culprit.

**Comment by anderspapitto** [comment]
no spacemacs. And actually, the error went away after restarting emacs once or twice, and I believe also clearing out everything named .stack or .stack-work on my filesystem (that might not have been entirely necessary though)

I'm fine with this being closed, since it doesn't affect me any more

**Comment by joehillen** [comment]
Don't close this. I've been having this problem for weeks. I think the buffer somehow gets into a bad state and it isn't fixed without closing the buffer and reopening the file.

**Comment by chrisdone** [comment]
If it's fixed then I'll close. 👏

**Comment by mrBliss** [comment]
See haskell/haskell-mode#1485.
