### ISSUE TITLE
Can't build Intero with Stack 1.12 & lts 7-8

### ISSUE THREAD

**Issue by Rydgel** [commercialhaskell/intero#307]
Trying to build intero and got this:

```
$ stack build intero       

While constructing the build plan, the following exceptions were encountered:

In the dependencies for intero-0.1.19:
    ghc-8.0.1.20161022 must match >=7.8 && <=8.0.1

Plan construction failed.
```

Not sure what to do.

**Comment by chrisdone** [comment]
What does `stack ghc -- --version` say?

**Comment by chrisdone** [comment]
Oh, it's `ghc-8.0.1.20161022`.

**Comment by Rydgel** [comment]
```
The Glorious Glasgow Haskell Compilation System, version 8.0.1.20161022
```

**Comment by Rydgel** [comment]
I'm sorry, I'm kind of dumb. I'm not sure why, but stack took the GHC that was installed by Homebrew (which does that weird thing with dates).

Uninstalling it resolved my issue. Sorry for the inconvenience.

**Comment by ddacunha** [comment]
I noticed that `brew install ghc` uses a bottle that installs `8.0.1.20161022` instead of `8.0.1`. Will see if I have time to submit a MR to homebrew.
