### ISSUE TITLE
intero-read-buffers problem

### ISSUE THREAD

**Issue by ibequa** [commercialhaskell/intero#308]
Getting these errors on macOS Sierra running emacs 25.1:
```
error in process filter: intero-read-buffer: Selecting deleted buffer
error in process filter: Selecting deleted buffer
```

upd: this happens only when adding `(add-hook 'haskell-mode-hook 'intero-mode)` to the init file. Invoking `intero-mode` manually inside .hs files seems fine.

**Comment by pmiddend** [comment]
I'm seeing the same on Linux (same emacs version).

**Comment by chrisdone** [comment]
Can you enable debugging with `M-x toggle-debug-on-error`, reproduce the error, and then paste the trace output that pops up here?

**Comment by yyadavalli** [comment]
I am getting similar error when I try to use REPL with `haskell-interactive-switch`

Here is the debugger output with `M-x toggle-debug-on-error`
```
Debugger entered--Lisp error: (error "Selecting deleted buffer")
   #[(state string) "\305\306^H\"^Yr\307\n\310\"q\210\311\312^H\"\313\307\n\314\"p^H#^[^\\315^K!\210\307\n\316\"\317\320\321^K\"\"\210 \2059^@\322\323\324\325\f\326\327#P\330\331$,\207" [string compile-ok state msgs modules string-match "OK, modules loaded:$
   intero-read-buffer()
   #[(process string) "^H\203  ^@\306\307  \"\210\310\311\n!!\205Q^@r\311\n!q\210db\210  c\210^K\203N^@\f\203N^@\312\313 \314 \"^]\315\316^M\"\203I^@\306\317\320\321\322\323^M#\323\324#@\206C^@\325\227\"\210\202M^@\306\326!\210)\327 )\207" [intero-debug str$
```
Again this is happening only when adding `(add-hook 'haskell-mode-hook 'intero-mode)`

Thanks

**Comment by truls** [comment]
Was any progress made on this? I've had this problem coming and going, seemingly at random, over the past couple of years. The problem only occurs with some projects and only if Intero is started using `(intero-global-mode 1)`. If I manually `M-x intero-mode` after opening a buffer everything works fine.

I'm happy to provide additional information, but I'm a bit unsure where to begin approaching this problem.

The backtrace from `M-x toggle-debug-on-error`: 

```
Debugger entered--Lisp error: (error "Selecting deleted buffer")
  #f(compiled-function (state string) #<bytecode 0x16b973d>)((:cont #f(compiled-function (&rest args) #<bytecode 0x1a48025>) :file-buffer #<killed buffer> :checker intero) "[1 of 1] Compiling Main             ( /.../.stack-work/intero/intero8wVZkY-TEMP.hs, /.../.stack-work/odir/Main.o )\nOk, modules loaded: Main.\nCollecting type info for 1 module(s) ... \n")
  intero-read-buffer()
  #f(compiled-function (process string) #<bytecode 0x14761f9>)(#<process stack> "Ok, modules loaded: Main.\nCollecting type info for 1 module(s) ... \n\004")
```

**Comment by zhangjunphy** [comment]
I suspect calling `(haskell-mode)` somehow adds `intero` back into `flycheck-checkers`. 
Removing the call to `(haskell-mode)` temporarily solved the problem, with the cost of eldoc highlighting through.
https://github.com/commercialhaskell/intero/blob/c452c67ec6efb2b064e7d1b90738690be28301d8/elisp/intero.el#L407-L418
