### ISSUE TITLE
intero-apply-suggestions is shadowed by haskell-process-reload in haskell-mode

### ISSUE THREAD

**Issue by novakboskov** [commercialhaskell/intero#309]
When I move the cursor to the place where GHC suggests improvements I get suggested improvements  alongside with a `(Hit ``C-c C-r' in the Haskell buffer to apply suggestions)`, but `C-c C-r` is by default bound to `haskell-process-reload` in `haskell-mode`. Even when I bound `intero-apply-suggestions` to another keys the message in mini buffer remains the same which cause inconsistency.
I am not sure is it issue for `intero` or maybe `flycheck`.

I also see that all key bindings from `intero-mode-map` infer with those from `haskell-mode`. Is that aimed to be loaded before `haskell-mode-map` to shadow keys from it?

**Comment by chrisdone** [comment]
You should be able to disable `haskell-interactive-mode`, the minor mode. Does that work?

**Comment by chrisdone** [comment]
I suggest removing your current haskell-mode configurations and starting a-fresh.
