### ISSUE TITLE
Feature request: Expand & display template haskell expression

### ISSUE THREAD

**Issue by saurabhnanda** [commercialhaskell/intero#310]
Would it be possible to take my cursor on the following expression, hit a keybinding, and view the expanded splice:

```
$(defineTable "roles")
```

**Comment by meditans** [comment]
@saurabhnanda if you do `:set -ddump-splices` in your ghci panel, you will see the generated splices on reload. It's still not comfortable as viewing only the splice, but it's a start!

**Comment by saurabhnanda** [comment]
Do I have to `C-c C-l` (load the current buffer in GHCi) for that to take effect?

**Comment by meditans** [comment]
yes @saurabhnanda, and the splices will be below the eventual compilation errors and above the new prompt.
