### ISSUE TITLE
Literate Haskell not recognised (intero 0.1.18, ghc 8.0.1)

### ISSUE THREAD

**Issue by patrikja** [commercialhaskell/intero#311]
On loading a file "Bug.lhs" with only "main = print 1738" in it intero gives me
error:
    parse error on input ‘>’
as if this had been a non-literate Haskell file.

It looks like the file that intero (ghci) actually loads is a copy of my "Bug.lhs" with .hs ending:
patrikj@jansson:~/bug$ more .stack-work/intero/intero20874i_l.hs 
> main = print 1738

Is there an easy workaround?

/Patrik

To reproduce:

echo "> main = print 1738" > Bug.lhs
emacs Bug.lhs

Context: After installing fresh stack and adding this to .emacs.d/init.el
(require 'package)
(add-to-list
  'package-archives
  '("melpa" . "http://melpa.org/packages/") t)
(package-initialize)
(package-refresh-contents)

;; Install Intero
(package-install 'intero)
(add-hook 'haskell-mode-hook 'intero-mode)

and using 
resolver: lts-7.9

patrikj@jansson:~/bug$ stack --version
Version 1.2.0, Git revision 241cd07d576d9c0c0e712e83d947e3dd64541c42 (4054 commits) x86_64 hpack-0.14.0
patrikj@jansson:~/bug$ stack exec -- ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1
patrikj@jansson:~/bug$ more stack.yaml 
resolver: lts-7.9

**Comment by chrisdone** [comment]
Correctly spotted. The extension should be taken from the original file, not assumed .hs.

**Comment by chrisdone** [comment]
Pinging @purcell 

https://github.com/commercialhaskell/intero/blob/master/elisp/intero.el#L1094

Any chance you can tackle this? I've got quite a backlog of intero issues to go through.

**Comment by purcell** [comment]
Sure. #321 should do the trick.

**Comment by chrisdone** [comment]
@patrikja This was fixed in #321 by @purcell. Can you confirm?

**Comment by patrikja** [comment]
Thanks fort the quick action.

I'd be happy to confirm, but how do I go about testing it? (How can I tell
emacs to use an intero version from github?)

/P

**Comment by chrisdone** [comment]
If you're using MELPA you can just wait for it to update and reinstall the package, I think.

**Comment by patrikja** [comment]
I confirm the the bug has been fixed (melpa: intero 20161123.715).
Thanks!
/P

**Comment by purcell** [comment]
Yay!
