### ISSUE TITLE
Name of where binding conflicts with imported library name

### ISSUE THREAD

**Issue by rikvdkleij** [commercialhaskell/intero#312]
For example, when I use hasql library and create inside function a where binding which name is `statement`, `loc-at` refers to imported statement from hasql instead of name of where binding. Even though hasql is imported qualified.

**Comment by chrisdone** [comment]
Can you give me a short code sample that I can reproduce?

**Comment by rikvdkleij** [comment]
Created short code sample which also shows problem:
https://gist.github.com/rikvdkleij/17694ec5a3d02dd842e539fd8c26739a

**Comment by rikvdkleij** [comment]
It looks like intero does not take qualified imports correctly into account. 

For example when 2 modules export the same name `'foo`. When a module imports both modules as qualified, `loc-at` for `foo` gives no info or it seems to guess which module name belongs to.

**Comment by rikvdkleij** [comment]
Also, it does not matter if the location info to `loc-at` is with or without qualifier.

**Comment by rikvdkleij** [comment]
```haskell
module Intero where

import qualified Hasql.Decoders               as HD (text)
import qualified Text.PrettyPrint.Leijen.Text as PP (text)

foo = HD.text
```
```
15:28	[project-stack-repl] command: :loc-at /home/rik/haskell/projects/foo-api/src/Intero.hs 6 7 6 13 HD.text

15:28	[project-stack-repl] stdOut: Couldn't resolve to any modules.
						^IntellijHaskell^

15:28	[project-stack-repl] errOut: 

15:28	[project-stack-repl] command: :loc-at /home/rik/haskell/projects/foo-api/src/Intero.hs 6 7 6 14 HD.text

15:28	[project-stack-repl] stdOut: Couldn't resolve to any modules.
						^IntellijHaskell^

15:28	[project-stack-repl] errOut: 

15:28	[project-stack-repl] command: :loc-at /home/rik/haskell/projects/foo-api/src/Intero.hs 3 54 3 57 text

15:28	[project-stack-repl] stdOut: hasql-0.19.16-2160cbR0b0TGswGuI9hapv:Hasql.Decoders
						^IntellijHaskell^

15:28	[project-stack-repl] errOut: 

15:28	[project-stack-repl] command: :loc-at /home/rik/haskell/projects/foo-api/src/Intero.hs 4 54 4 57 text

15:28	[project-stack-repl] stdOut: hasql-0.19.16-2160cbR0b0TGswGuI9hapv:Hasql.Decoders
						^IntellijHaskell^

15:28	[project-stack-repl] errOut: 
```

**Comment by rikvdkleij** [comment]
@chrisdone Why is prio low of this issue?

**Comment by rikvdkleij** [comment]
@chrisdone I did some debugging and found that the issue is caused by the fact that the `ModInfo` which is passed to `findName` in `GhciFind` does not contains the qualified names. `ModInfo` comes from `GHCiState` and I have no idea how to solve this.....

**Comment by rikvdkleij** [comment]
@chrisdone I wonder if you are willing to solve this issue? For me it is too difficult to solve.
