### ISSUE TITLE
gcc failed in phase linker

### ISSUE THREAD

**Issue by corymickelson** [commercialhaskell/intero#313]
running stack install intero I get this:     Linking .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/intero/intero ...
    /usr/bin/ld: cannot find -ltinfo
    collect2: error: ld returned 1 exit status
    `gcc' failed in phase `Linker'. (Exit code: 1)
 
Any ideas on how to resolve would be greatly appreciated.

**Comment by dhruvin2910** [comment]
Hello, Same problem here. Do you mind sharing what solved the problem ?

**Comment by dhruvin2910** [comment]
Installing **libtinfo-dev** solved my problem.
