### ISSUE TITLE
Autocompletion in spacemacs

### ISSUE THREAD

**Issue by Cmdv** [commercialhaskell/intero#315]
Description :octocat:

in Spacemacs intero autocompletion not working fully as expected

**Reproduction guide** 🐝 

- [x] Start Spacemacs
- [x] Install haskell layer
- [x] add `haskell-completion-backend 'intero` to haskell variables in `.spacemacs`
- [x] `> stack new test` in spacemacs go to `app/Main.hs` -> intero will automatically install
- [x] type new type def in file: 
```
myFunc :: Int -> Int
```

**Observed behaviour:** 👀 💔
Now start adding the body of the function:
```
myFunc :: Int -> Int
my...
``` 
I do not get prompted with `myFunc` so it has to be fully written out 😿 

**Expected behaviour:** ❤️ 😄
We programmers / me can be a little lazy please could we have a prompt to autocomplete `myFunc`.
_*Should be added that once you have created the function then you are able to use it with autocompletion just fine_ 😸 

**System Info** 💻
OS: OSX sierra
Spacemacs: 0.200.5@25.1.1 
Graphic display: t
Distribution: spacemacs
Editing style: vim
Completion: helm

**Layers:** 📚 
```
(
 better-defaults emacs-lisp osx git version-control  syntax-checking markdown auto-completion
 (haskell :variables haskell-completion-backend 'intero)
)
```

**Comment by chrisdone** [comment]
Can someone with spacemacs reproduce?

**Comment by Cmdv** [comment]
@chrisdone I was unsure if the problem lied in intero or spacemacs. What bought me to posting the bug here was that when using ghc-mod instead of intero everything works as expected. I should add that this was 3 days of investigation with adding an array of variables and custom scripts to the `.spacemacs` file. Different combinations of Haskell / ghci / spacemacs. 😄

**Comment by chrisdone** [comment]
Mmm, actually I see that this expects completion before the module has been type checked yet. That's not supported behaviour presently.

**Comment by Cmdv** [comment]
@chrisdone that's a shame, it will also stop autocomplete if you haven't fulfilled imports or there are any errors on the page. Makes it fairly unworkable if you are new to Haskell like my self. 
do you think it will be an added feature or is it that the expected functionality? thanks for the response otherwise 👍

**Comment by chrisdone** [comment]
It might be added later, based on just scanning the buffer for words like Emacs does.
