### ISSUE TITLE
Repl not loading?

### ISSUE THREAD

**Issue by aulambda** [commercialhaskell/intero#320]
I'm running Emacs 25.1 on Arch. I think I have the latest versions of stack and intero, but when I try to run the repl in intero I get this:
`Started Intero process for REPL.`
And then nothing . . . Emacs hangs and has to be killed. Not a hugemongous deal, since there are other ways to get a REPL in emacs, but I thought I'd submit it incase it is either unkown or has a simple solution.

I've never submitted an issue before, so let me know if there is more info that would be usefull.

**Comment by chrisdone** [comment]
Does `stack ghci` work in your project directory?

**Comment by eriksvedang** [comment]
I get the same problem in Emacs 25.1 on MacOS 10.12.3. 
It only happens when I try to evaluate a file outside a stack project.
Still, would be nice to be able to do just that.
