### ISSUE TITLE
bump ghc dependency to 8.0.1.20161114 for mac users

### ISSUE THREAD

**Issue by esjmb** [commercialhaskell/intero#322]
Hi,

I'm getting the following error when launching intero 

```
While constructing the build plan, the following exceptions were encountered:

In the dependencies for intero-0.1.18:
    ghc-8.0.1.20161114 must match >=7.8 && <=8.0.1

Plan construction failed.
```

I am using a mac, with Sierra, with latest ghc installed via Homebrew

```
ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1.20161114
```

Could the dependency in the cabal file be bumped?

thanks,
Stephen.

**Comment by chrisdone** [comment]
You can run `stack setup` or put `use-system-ghc: false` in your global `~/.stack/config.yaml`. That'll install the right GHC version and manage it within your stack environment. :+1:

**Comment by esjmb** [comment]
thanks.

setting 'system-ghc' rather than 'use-system-ghc' worked for me, but unfortunately on a Mac with Sierra right now ghc-8.0.1 is not building. 

running 'stack setup 8.0.1' in the project directory had no effect incidentally. 

tried setting `allow-newer: true` in `~/.stack/config.yaml` (ugghhhh! :) ) but hit a build error in GHCI.TH.

I'll stick to working with docker enabled for the moment, in which context intero works fine.

thanks,
Stephen.
