### ISSUE TITLE
Can anyone help me fix this error?

### ISSUE THREAD

**Issue by arbitary** [commercialhaskell/intero#323]
<img width="561" alt="screen shot 2016-11-26 at 10 24 42 am" src="https://cloud.githubusercontent.com/assets/22099021/20641323/796ce93a-b3c3-11e6-8956-8bb6239fe359.png">

**Comment by bjarkevad** [comment]
This happens when GHC is installed with homebrew on macOS. A fix is to remove any version of GHC and Stack installed through homebrew, and reinstall it using the official instructions here: https://docs.haskellstack.org/en/stable/install_and_upgrade

**Comment by chrisdone** [comment]
I can probably just relax this bound for future versions. I could do that
retroactively on hackage when I'm back at a computer tomorrow.

**Comment by arbitary** [comment]
> I can probably just relax this bound for future versions. I could do that
> retroactively on hackage when I'm back at a computer tomorrow.

That would be great. Can't wait.

**Comment by chrisdone** [comment]
I've relaxed the dependencies on hackage. This should take about half an hour to update, run `stack update` to get the updated version.
