### ISSUE TITLE
Install intero once per ghc version

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/intero#324]
I've opened a PR for stack adding a proposed `--copy-compiler-tool` flag.  This flag causes stack to copy executables to a dir for compiler-specific tools, e.g. `/home/mgsloan/.stack/compiler-tools/x86_64-linux/ghc-8.0.1/bin`.  The intention of this is to allow installation of tools that need to match the ghc version.

In order to use this with intero, it seems like the following will need to happen:

1) Add checking of stack version - https://github.com/commercialhaskell/intero/issues/127
2) Pass in this new flag when automatically building intero

Ideally, we'd also check that we are using an intero that matches our GHC - https://github.com/commercialhaskell/intero/issues/161 .  One option here might be to demand that intero be located at `stack path --compiler-tools-bin`

The way intero is installed could be sensitive to particular choices in the stack.yaml (dependencies, etc).  I think it also makes sense to have configurations like `stack-7.8.yaml`, `stack-7.10.yaml`, etc for each compiler version.  Then, these configurations can be used when installing intero.

Thoughts?  Perhaps this isn't worth the effort, maybe the new `--copy-compiler-tool` flag shouldn't be merged?

**Comment by chrisdone** [comment]
Interesting stuff I'll look into it when I get home.

**Comment by ntc2** [comment]
Just worked around a failing project-local intero install by installing globally with `--copy-compiler-tool` as suggested here:

https://github.com/commercialhaskell/intero/issues/504

If intero installed itself globally in this way, instead of in my project, that would resolve the problem for me automatically.

**Comment by chrisdone** [comment]
I need to know the version of stack that introduced that flag, and then
intero can do a version detection to use that flag or not. Otherwise it'll
obviously fail if the stack version is older.

**Comment by ntc2** [comment]
Looks like `--copy-compiler-tool` was added in Stack 1.6.1:
https://github.com/commercialhaskell/stack/blob/master/ChangeLog.md#v161 .

**Comment by mgsloan** [comment]
Note that if `stack build --copy-compiler-tool` is used within a project, then that particular project's settings and dependencies will affect the resulting `intero` binary.  This is why in the original issue I'm describing having different stack.yaml files for building intero, based on ghc major version.

**Comment by chrisdone** [comment]
@mgsloan OK, so it would have to detect the GHC version with

```
-bash-3.2$ stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2
```

then based on that, the Elisp would run in a temporary directory

```
stack build --copy-compiler-tool --resolver ghc-8.0.2 intero-0.1.31 <other deps for this ghc>
```

And after that, `intero` would be in the `PATH` when I do `stack exec intero` specific to the GHC currently in use?

**Comment by ntc2** [comment]
To clarify, the way I installed Intero globally after it failed to install in a project was closer to what @mgsloan is suggesting. I did

```
cd /tmp
stack install intero-0.1.30 --copy-compiler-tool --resolver lts-11.8
```

where the point is that I don't have any `stack.yaml` files in `/tmp`. If I try to install with a generic `ghc-<version>` resolver, e.g. with

```
stack install intero-0.1.30 --copy-compiler-tool --resolver ghc-8.2.2
```

then the install fails because the dependency versions are not specified, but I guess that's what @chrisdone 's "`<other deps for this ghc>`" is for.

**Comment by chrisdone** [comment]
Right, in order to not specify the dependencies we can rely on the lts or nightly resolver. But then if someone is not using one of those resolvers it'll fail. 

We could have a mapping in the elisp like:

```lisp
(defvar intero-deps (list "8.0.2" "lts-x.y"))
```

So we can lookup the GHC for the current project and then build intero with the right resolver.

What do you think?

**Comment by ntc2** [comment]
Why would it fail if someone is not using one of those resolvers?

But yes, using a mapping from GHC versions to resolvers seems like a nice, simple solution.

**Comment by chrisdone** [comment]
> Why would it fail if someone is not using one of those resolvers?

For example:

```
-bash-3.2$ stack install intero --resolver ghc-8.0.2

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for intero-0.1.31:
    ghc-paths must match -any, but the stack configuration has no specified version (latest
              matching version is 0.1.0.9)
    mtl must match -any, but the stack configuration has no specified version (latest
        matching version is 2.2.2)
    network must match -any, but the stack configuration has no specified version (latest
            matching version is 2.7.0.0)
    random must match -any, but the stack configuration has no specified version (latest
           matching version is 1.1)
    syb must match -any, but the stack configuration has no specified version (latest
        matching version is 0.7)
needed since intero is a build target.

Some potential ways to resolve this:

  * Recommended action: try adding the following to your extra-deps
    in /Users/chris/.stack/global/stack.yaml:

- ghc-paths-0.1.0.9
- mtl-2.2.2
- network-2.7.0.0
- random-1.1
- syb-0.7

```

**Comment by chrisdone** [comment]
Confirming proper behavior of the invocation that Emacs Lisp would run, on my system:

```
bash-3.2$ stack build --resolver ghc-8.0.2 --copy-compiler-tool intero-0.1.31 ghc-paths-0.1.0.9 mtl-2.2.2 network-2.7.0.0 random-1.1 syb-0.7
...
Completed 6 action(s).
Copying from /Users/chris/.stack/global/.stack-work/install/x86_64-osx/ghc-8.0.2/8.0.2/bin/intero to /Users/chris/.stack/compiler-tools/x86_64-osx/ghc-8.0.2/bin/intero

Copied executables to /Users/chris/.stack/compiler-tools/x86_64-osx/ghc-8.0.2/bin:
- intero
bash-3.2$ rm /Users/chris/.stack/global/.stack-work/install/x86_64-osx/lts-9.18/8.0.2/bin/intero
bash-3.2$ rm /Users/chris/.stack/global/.stack-work/install/x86_64-osx/ghc-8.0.2/8.0.2/bin/intero
bash-3.2$ stack exec which intero
/Users/chris/.stack/compiler-tools/x86_64-osx/ghc-8.0.2/bin/intero
```

**Comment by ntc2** [comment]
Note that the way the Intero Emacs mode currently invokes `intero` doesn't necessarily use the `compiler-tools` version.  E.g. I have a project that uses `lts-11.1` and a version of Intero Emacs mode that uses `intero` 0.1.30. If I do

```
$ stack --resolver lts-11.1 --copy-compiler-tool build intero-0.1.31
$ stack --resolver lts-11.2 --copy-compiler-tool build intero-0.1.30
```

to install the wrong version of  `intero` for `lts-11.1` and the right version for `lts-11.2`, and then load project, Emacs complains

```
The wrong version of Intero is installed for this Emacs package.
Installing intero-0.1.30 automatically ...
```

Note that both of these LTSs use GHC 8.2.2:

```
$ stack --resolver lts-11.2 exec -- intero --version                
Intero 0.1.30
$ stack --resolver lts-11.1 exec -- intero --version 
Intero 0.1.31
$ stack --resolver lts-11.1 exec -- ghc --version   
The Glorious Glasgow Haskell Compilation System, version 8.2.2
$ stack --resolver lts-11.2 exec -- ghc --version 
The Glorious Glasgow Haskell Compilation System, version 8.2.2
```

However, there is only one "compiler tools" version of `intero` at this point, and it's the correct version 0.1.30, since I installed that one last:

```
$ `stack --resolver lts-11.1 path --compiler-tools-bin`/intero --version 
Intero 0.1.30              
$ `stack --resolver lts-11.2 path --compiler-tools-bin`/intero --version 
Intero 0.1.30
$ `stack --resolver ghc-8.2.2 path --compiler-tools-bin`/intero --version 
Intero 0.1.30
```

Note that when using the generic `ghc-8.2.2` resolver we always get the most recently installed `intero`:

```
$ stack --resolver ghc-8.2.2 exec -- intero --version
Intero 0.1.30
```

**Comment by chrisdone** [comment]
Yes, the short version is that the PATH prefers LTS-local binaries over compiler tool ones:

```
bash-3.2$ stack exec -- env | grep ^PATH
PATH=/Users/chris/.stack/global/.stack-work/install/x86_64-osx/lts-9.18/8.0.2/bin
:/Users/chris/.stack/snapshots/x86_64-osx/lts-9.18/8.0.2/bin
:/Users/chris/.stack/compiler-tools/x86_64-osx/ghc-8.0.2/bin
:/Users/chris/.stack/programs/x86_64-osx/ghc-8.0.2/bin
:/Users/chris/.cargo/bin/
etc...
```

**Comment by chrisdone** [comment]
I think intero's checking and running should check for the path from `stack path --compiler-tools-bin`:

```
bash-3.2$ stack path --compiler-tools-bin
/Users/chris/.stack/compiler-tools/x86_64-osx/ghc-8.0.2/bin
```

So that it always prefers the compiler-tools-bin version of intero.

**Comment by chrisdone** [comment]
Implemented and pushed! Please all give it a try.

It should install intero once per GHC version. If it installs on a project that you already built intero for, that will be because it demands that it's in `compiler-tools-bin`.

**Comment by mgsloan** [comment]
Woohoo!

**Comment by ntc2** [comment]
Works for me, thanks! Tested on three projects, two using GHC 8.2.2 and one using GHC 8.0.2.

**Comment by chrisdone** [comment]
@ntc2 Thanks for testing!
