### ISSUE TITLE
White list does not work

### ISSUE THREAD

**Issue by s9gf4ult** [commercialhaskell/intero#326]
I have just set variable `intero-whitelist` via `M-x customize-variable` to list of my projects (one directory) and set 

```lisp
(add-hook
 'haskell-mode-hook 'intero-mode-whitelist)
```

as documentation says. Intero still loads on every project it can touch and eats all my memory for nothing.

**Comment by chrisdone** [comment]
Try `M-x describe-variable haskell-mode-hook`. Make sure that you no longer have `intero-mode` in that list. You can do this by running `(remove-hook 'haskell-mode-hook 'intero-mode)`.
