### ISSUE TITLE
[BUG] Intero does not check type error on Windows emacs + stack

### ISSUE THREAD

**Issue by chunsj** [commercialhaskell/intero#329]
I've installed stack and intero, emacs (25.1.1) on windows 10.
The intero can detect plain syntax errors like invalid quote in string and indentations, however, it cannot
detect invalid type as in following example;

someFunc :: IO ()
someFunce = putStrLn (Just 1)

Of course, on macOS or Linux, the problem is detected well.

**Comment by deepfire** [comment]
There's definitely something wonky with flycheck error reporting going on -- I have seen multiple different oddities -- failure to refresh, failure to propagate errors from other modules, failure to handle TH-related errors, etc.
