### ISSUE TITLE
Intero reload on every file change, makes things slow

### ISSUE THREAD

**Issue by RasmusWL** [commercialhaskell/intero#332]
Hi. First off, thanks for the great work here!

I'm experiencing some problems though, as intero reloads all files whenever I make *any* change in my file (even if I don't save). I verified this with `M-x intero-toggle-debug`. For the specific file I'm editing, this means reloading 55 files, which takes ~1 minute.

While this process is gonig on, any `goto-definition` og `type-at` operations are deferred until all files have been reloaded (which might be the same issue reported as #294).

Is there any way to only trigger reloading the files when I actually save a file? -- and possibly disable that as well, as I tend to save my files way more often than I would like the reloading

**Comment by chrisdone** [comment]
Sure! You can just add this to your config:

```lisp
(setq flycheck-check-syntax-automatically '(save idle-change new-line mode-enabled))
```

Remove the automatic ones that you don't like. It seems that `idle-change` and `new-line` are the ones bothering you.
