### ISSUE TITLE
"stack ghci --with-ghc intero ..." segfault

### ISSUE THREAD

**Issue by jchia** [commercialhaskell/intero#335]
I opened a .hs file in emacs and the Intero tried to run this:

    stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-build --no-load --ghci-options -odir=/home/jchia/git/tms/hs/.stack-work/intero/intero31725Fz1 --ghci-options -hidir=/home/jchia/git/tms/hs/.stack-work/intero/intero31725Fz1 rgr-automation

The result is this:

    The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
    Using main module: 1. Package `rgr-automation' component exe:daily-worker with main-is file: /home/jchia/git/tms/hs/rgr-automation/app/dailyWorker.hs
    Configuring GHCi with the following packages: rgr-automation
    Intero 0.1.20 (GHC 8.0.1)
    Type :intro and press enter for an introduction of the standard commands.

    ghc-iserv-dyn: {handle: <file descriptor: 12>}: GHCi.Message.remoteCall: end of file
    Segmentation fault (core dumped)

The stack command is what Intero tried to use from emacs.

This happens with intero installed from lts-7.13 and nightly-2016-12-15. The project I'm trying to work on uses nightly-12-05. I'm using stack 1.2.0 on Arch Linux. `stack ghci` works fine.

**Comment by jchia** [comment]
I was able to repro with just a very basic stack project by adding this to the `library` section:

    ghc-options:         -Wall -fwarn-tabs -dynamic -fexternal-interpreter

**Comment by tobiasgwaaler** [comment]
There were big changes to GHC/GHCi introduced in GHC 8.0.1 to support -fexternal-interpreter. As far as I can tell Intero is a "fork" of GHCi, meaning that the changes introduced in GHC 8.0.1 are not automatically ported to Intero. 
Just as an example of the kind of changes introduced, see https://phabricator.haskell.org/rGHC4905b83a2d448c65ccced385343d4e8124548a3b#ababf87b
(that's the diff for the -fexternal-interpreter feature)
It seems to me that supporting -fexternal-interpreter in Intero is non-trivial

**Comment by chrisdone** [comment]
Probably won't be supporting it. GHCi can be used for running interpreted code. Intero's main use is checking code and reporting information, so I ported it to GHC 8.0.1's API, not GHCi's feature set.
