### ISSUE TITLE
Parse error with OverloadedLabels

### ISSUE THREAD

**Issue by kiripon** [commercialhaskell/intero#337]
When using `OverloadedLabel` extension, the intero causes parse error on the label.
```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE OverloadedLabels #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedLabels #-}

import GHC.OverloadedLabels
foo :: (IsLabel "bar" (a -> Int)) => a -> Int
foo x = #bar x -- Parse error 

main = do
  return ()
```
I am using Intero 0.1.20(GHC 8.0.1).

**Comment by kiripon** [comment]
This problem is caused by hlint (not intero). Sorry.

**Comment by unhammer** [comment]
For future searchers who find this issue before the solution: ensure you're running version 2 or later of HLint, and put `- fixity: infixr 0 :=` in an `.hlint.yaml` file in your project (cf. https://www.lumensoutdoors.org/posts/2017-05-05-month-of-haskell-4.html )
