### ISSUE TITLE
Bring multiple modules into REPL scope

### ISSUE THREAD

**Issue by ysangkok** [commercialhaskell/intero#338]
Currently, if I use `C-c C-l` to get a REPL with a module in scope, and I go to another module and press that key combination, my previous scope is destroyed. It would be nice if there was a way to add to the scope like `:m +`. But I tried using `:m +` and it can only see what was compiled when I ran `C-c C-l`.

**Comment by chrisdone** [comment]
I'm afraid that's just how GHCi works. :(
