### ISSUE TITLE
Work with TH files

### ISSUE THREAD

**Issue by k-bx** [commercialhaskell/intero#347]
Unfortunately, some time ago our project's template haskell code stopped working properly with intero. Previously we've had problems with paths which were resolved by usage of `th-utilities` package, now problems are arising again.

I've created a small project which gives you clear reproduction instructions https://github.com/k-bx/th-utils-intero-test

Just clone it anywhere, see `stack build` working, `stack repl` as well, but not `C-c C-l` in emacs or intero itself.

Seems like the problem is related to working with data-files used by TH. "Working directory" is somehow being set to be inside `$HOME/tmp` dir, as I understand, and templates are searched there, but not found.

I'd love to provide more details or maybe even try to address the issue, but unfortunately don't have a lot of understanding about it yet, so valuable input is appreciated. Thank you.

**Comment by k-bx** [comment]
th-utilities solution was first pointed from https://github.com/commercialhaskell/intero/issues/205

**Comment by k-bx** [comment]
UPDATE: not using `th-utilities` now works in this toy-project, and it works in intero flycheck with our work-project, but doesn't work in intero's ghci in work-project. Will check further and reopen when reproduction is ready.

**Comment by k-bx** [comment]
Ok, reproduced. Needed to have stack.yaml upper than the package itself. Now intero-the-flycheck-tool works well, but intero-ghci fails with:

```
Starting:
  stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-build --no-load --ghci-options -odir=/Users/kb/tmp/intero42051STc --ghci-options -hidir=/Users/kb/tmp/intero42051STc th-utils-intero-test
Intero 0.1.20 (GHC 8.0.1)
Type :intro and press enter for an introduction of the standard commands.

 [1 of 1] Compiling Main             ( /Users/kb/tmp/intero42051gYD.hs, /Users/kb/tmp/intero42051STc/Main.o )

/Users/kb/tmp/intero42051gYD.hs:14:14: error:
    • Exception when trying to run compile-time code:
        data/foo.hamlet: openFile: does not exist (No such file or directory)
      Code: shamletFile "data/foo.hamlet"
    • In the untyped splice: $(shamletFile "data/foo.hamlet")
Failed, modules loaded: none.
```

**Comment by chrisdone** [comment]
Try setting the path to an absolute path based on the current file path.
