### ISSUE TITLE
":unset +c" doesn't seem to work

### ISSUE THREAD

**Issue by thomasjm** [commercialhaskell/intero#350]
In normal GHCI, you can type `:unset +c` to disable "collecting type and location information after loading modules." But in Intero, I get the error `unknown option: 'c'`.

I want to do this because collecting type information is pretty slow on nontrivial Haskell projects -- see https://ghc.haskell.org/trac/ghc/ticket/12706. Sometimes I'd rather forego some type-related IDE features to make reloading fast.

**Comment by chrisdone** [comment]
Intero is meant to be used for IDE stuff. Intero doesn't have the +c option. Using `:set -fobject-code` means you don't have to collect type info for every module every time.

For just loading stuff and using the REPL, you can use ghci.

**Comment by thomasjm** [comment]
@chrisdone thanks for the quick responses!

Followup question: is there a convenient way to use GHCi in tandem with Intero in Emacs? It seems like Intero is designed to completely supplant `haskell-interactive-mode`, since `C-c C-l` runs `intero-repl-load`, `C-c C-z` runs `intero-repl`, etc.

**Comment by chrisdone** [comment]
`C-c C-l` runs ghci, not intero itself. It used to, but for the past few months it launches ghci.

**Comment by thomasjm** [comment]
I must be missing something -- I have Intero `20161230.352` installed, and `C-c C-l` launches a REPL that is almost but not quite just like GHCi. (For example, `:unset +c` doesn't work in it.)

Or are you saying that reloading via `C-c C-l` is different from typing `:r` in the REPL? The latter does seem slightly faster because it doesn't seem to be recompiling every module. Although when I do `:set -fobject-code`, both commands seem to perform exactly the same (much faster, only collects type info for the 1 module.)
