### ISSUE TITLE
Intero doesn't pick up changes in other projects

### ISSUE THREAD

**Issue by thomasjm** [commercialhaskell/intero#351]
I often develop on Haskell projects that "import" other local projects in `stack.yaml`: for example, 

```
packages:
- '.'
- '../some-other-project'
```

When trying out Intero, I found that it doesn't pick up changes to these projects. For example, if I add a new data constructor to a type defined in `some-other-project`, then use it in my main project and reload, I get an error. 

Since my workflow often involves tweaking the sub-projects, this is a showstopper for using Intero. Normal Emacs `haskell-mode` behavior with `haskell-interactive-mode` doesn't have this problem.

**Comment by chrisdone** [comment]
Run `M-x intero-targets`, and then choose both packages together. That will make it load both from source in the same intero process. 👍  By default it doesn't do this, because it gets pathological in bigger projects.
