### ISSUE TITLE
Use cabal in the absence of stack.yaml

### ISSUE THREAD

**Issue by ElvishJerricco** [commercialhaskell/intero#361]
When there is a `.cabal` file, but not a `stack.yaml` file, it'd be nice if Intero supported falling back on Cabal with `cabal repl --with-ghc=intero`. I like to use Nix to manage my dependencies, and the nice thing about this is that it lets me use Cabal for incremental compilation during development. I'd love to have it use Stack so that I could use Intero easily, but Stack's Nix integration [is insufficient for anyone really using Nix](https://github.com/commercialhaskell/stack/issues/2378#issuecomment-272365245), and makes difficult to reliably use Intero.

Though maybe the solution is a smarter integration with Nix by Intero rather than a falback to cabal. Certainly that would have the advantage of making sure the `intero` it used came from the project's `nixpkgs`.

**Comment by deepfire** [comment]
Just so people know -- the Haskell/Nix community really does care about this problem.  Using `intero` inside `nix-shell` is pain, currently, because it appears as if stack layers complex and brittle logic atop Cabal -- and it breaks _systematically_, with new surprises coming up monthly..

In contrast, `Cabal`-Nix integration has been rock-solid for more than a year.

So, maybe removing a layer in case of Nix is actually the long-term way to go.

**Comment by chrisdone** [comment]
Nix is unsupported, I don't make changes to support it.

**Comment by sebeaumont** [comment]
Can cabal be supported in place of stack?

**Comment by ElvishJerricco** [comment]
@seabeaumont you should probably use [dante](https://github.com/jyp/dante) if you want support for something other than Stack.

**Comment by sebeaumont** [comment]
@ElvishJerricco  thanks indeed! -- that may well be what I'm looking for I really want something that's not bound to stack -- well not really: I'm happy with stack but also living on the hackage bleeding edge as a user of ghc-8.2 however most tooling (that needs to invoke the ghc modules for type introspection i.e. IHaskell, intero in my case) now seems bound to stack -- and that means mega pain in extra-deps. I was just embarking on the idea of a custom resolver that uses hackage.   I have a bunch of packages in my project that are all built with the same ghc and I find cabal new-build fits this bill... Actually a hackage resolver makes a lot of sense here --  I can use stack with 8.2 and get the latest packages from hackage (i.e. mega extra-deps). Shouldn't be this hard eh? but catering for all tastes is always tricky.   I'll take a look at dante and see how to proceed. Thanks again.

**Comment by mgsloan** [comment]
@sebeaumont `stack solver` should help a lot with the extra-deps pain.  Basically, this means you run the cabal solver only when you need to, and then can still take advantage of stack's snapshot sharing and deterministic builds
