### ISSUE TITLE
intero-blacklist and intero-whitelist not working

### ISSUE THREAD

**Issue by themoritz** [commercialhaskell/intero#364]
When I use `intero-mode-blacklist` (or whitelist), they don't have any effect, meaning intero is _always_ started.

I'm using the intero master with the following haskell related stuff in my `init.el`:

```elisp
(require 'prelude-haskell)

(add-hook 'haskell-mode-hook 'haskell-auto-insert-module-template)

(use-package intero
  :load-path "~/code/intero/elisp"
  :ensure t)
(setq intero-blacklist '("~/code/haskell-project/"))
(add-hook 'haskell-mode-hook 'intero-mode-blacklist)
```

When I run the debugger on `intero-mode-blacklist`, everything seems to be fine. It even returns `nil` in the blacklisted project, then some other hooks (some magit stuff, for example) get called, and then unfortunately my debugger hangs.

One idea might me that `intero-mode` is called after `intero-mode-blacklist` finishes with `nil`, but I have no proof of that.

There's nothing else in my `init.el` that might start `intero-mode`, but it can certainly have to do with my emacs setup (using prelude)...

Any ideas?

**Comment by themoritz** [comment]
Interestingly,
* intero even starts when I omit the `(add-hook 'haskell-mode-hook 'intero-mode-blacklist)`
* if I use `(package-install 'intero)`, intero never starts

**Comment by chrisdone** [comment]
If that's the only stuff in your init.el, then presumably the list itself doesn't match the project in the expected way.

* `intero-mode-blacklist` means "allow everything, except this list: ..."
* `intero-mode-whitelist` means "reject everything, except this list: ..."

So you can try:

* Checking you have the white/black the right way round with the project you want to ignore/accept.
* Try expanding the filename to a canonical form like `/foo/bar/mu/`.

**Comment by themoritz** [comment]
Indeed the problem arises when combining with prelude. I bisected my init.el and the problem occurs when adding prelude support for certain languages (`prelude-emacs-lisp`, `prelude-js`, `prelude-haskell`) but not for others (`prelude-latex`, `prelude-scss`, `prelude-shell`, `prelude-yaml`).

Has anyone an idea why this might happen or can at least reproduce it?

**Comment by qrilka** [comment]
I don't have any prelude-XXX in my .emacs and I see the same problem.
In `~/.emacs` I have
```
(require 'intero)
(setq intero-whitelist '("/home/qrilka/ws/h/" "/home/qrilka/ws/tl/"))
(add-hook 'haskell-mode-hook 'intero-mode-whitelist)
```
and when opening `/home/qrilka/.xmonad/xmonad.hs` I see ordinary intero warnings about stack project root.
Any hints how to debug it?

**Comment by qrilka** [comment]
Actually those warnings were about `stack setup` not being run for my global project but that doesn't resolve the problem of not working `intero-whitelist`

**Comment by PierreR** [comment]
FWIW, I have never managed to get this to work [in spacemacs](https://github.com/syl20bnr/spacemacs/issues/8383). I don't have any `prelude-*` package installed.

This makes the `intero/spacemacs` experience far less pleasant ... Even after disabling `flycheck` completely on a `hs` file (that should be blacklisted for instance a .xmonad.hs without cabal file) emacs starts to be so slow that my only workaround is to kill it and start editing that file with `vim`.

**Comment by purcell** [comment]
This is an interesting one. I took a look over the `intero-whitelist` code and didn't see any faults with it, but I discovered that when `intero` is loaded, it defines a new flycheck checker which is unconditionally enabled in `haskell-mode`: this then triggers the loading of `intero`'s backend support, even if `intero-mode` itself is enabled.

Commit 71474dd, then, fixes this by setting the checker to be active when `intero-mode` is enabled.

Separately, I'd like to make it so that we could all simply enable `intero-global-mode`, and have it respect both `intero-whitelist` and `intero-blacklist`. The logic I'd suggest there would be that if a `haskell-mode` file is whitelisted and is not blacklisted, then `intero-mode` would be enabled. Would that work for everyone? The current method of adding either `intero-mode-whitelist` or `intero-mode-blacklist` is a bit clunky IMO.

**Comment by purcell** [comment]
See https://github.com/commercialhaskell/intero/pull/418 for how I propose to make whitelisting/blacklisting work with less faff.

**Comment by themoritz** [comment]
@purcell this sounds goot and would certainly work for me!

**Comment by purcell** [comment]
> See #418 for how I propose to make whitelisting/blacklisting work with less faff.

Okay, I've merged that PR now, so please ping me if any of you whitelist/blacklist users experience any issues.

**Comment by hhefesto** [comment]
I can't seem to be able blacklist.

When I am on my blacklisted file, before and after having to close intero's error buffer, intero-blacklist variable (`C-h v intero-blacklist`) is set to:

> intero-blacklist is a variable defined in ‘intero.el’.
> Its value is
> ("/home/hhefesto/dev/YesodEmailAuthBookExample/src/Main.hs")
> Original value was nil
> ...

The pertinent part of my init.el is:
```
(add-hook 'haskell-mode-hook 'intero-global-mode)
(add-hook 'haskell-mode-hook 'haskell-decl-scan-mode)
(setq intero-blacklist '("/home/hhefesto/dev/YesodEmailAuthBookExample/src/Main.hs"))
(add-hook 'haskell-mode-hook 'intero-mode-blacklist)
```
the whole init.el is:
https://github.com/hhefesto/dotfiles/blob/cfad08bba724e6a00297f0d029a6ac9dc17480f0/init.el

**Comment by purcell** [comment]
@hhefesto You're meant to blacklist project directories, not individual files. Also, from looking at the snippet you've supplied above, you haven't followed the standard set-up instructions. Try something like the following:

```el
(intero-global-mode 1)
(add-hook 'haskell-mode-hook 'haskell-decl-scan-mode)
(setq intero-blacklist '("/home/hhefesto/dev/YesodEmailAuthBookExample/"))
```

**Comment by hhefesto** [comment]
Thank you!
Works like a charm.
