### ISSUE TITLE
Has default behaviour of the REPL changed?

### ISSUE THREAD

**Issue by saurabhnanda** [commercialhaskell/intero#365]
Recently I updated Intero and/or spacemacs (I don't remember which). It seems that the behaviour of `C-c C-l` has changed. Earlier it used to load only the current buffer in the REPL (and reloading any other file it depends on - **only if the other file has changed** However, after the updated, `C-c C-l` loads **all** the dependent files, irrespective of whether they have changed or not.

How do I get back to the old behaviour?

**Comment by chrisdone** [comment]
It was changed here: https://github.com/commercialhaskell/intero/issues/171 It was turned off `-fobject-code` while enabling incremental compilation throws away information and bindings that are useful in the REPL.

To get the old behavior you can run `:set -fobject-code` in your REPL prompt.
