### ISSUE TITLE
Configuration to change REPL behaviour

### ISSUE THREAD

**Issue by saurabhnanda** [commercialhaskell/intero#366]
The change introduced by #171 has a significant downside when doing iterative coding (especially in webapps) where one need to evaluate the current file in the REPL a lot of times. It starts loading **all dependant files** from scratch, each time.

Is it possible to have a variable in the spacemacs configuration file to control the `-fobject-code` and `-fbyte-code` behaviour? Building on it, is it possible to have a persistent UI in the REPL buffer which shows the current mode and allows the user to easily change it with a click?

**Comment by pseudonom** [comment]
FYI, it is possible to temporarily get `-fobject-code` behavior by `:set -fobject-code` at the prompt. It only lasts until the process restarts though.
