### ISSUE TITLE
Disable automatic show type at point

### ISSUE THREAD

**Issue by tepf** [commercialhaskell/intero#367]
This is a neat feature but only until you need to keep a type signature as reference. Moving the cursor somewhere else and accidently touching a function will remove the signature you want to remember.

**Comment by chrisdone** [comment]
You can disable this by turning off eldoc mode in haskell-mode.

**Comment by tepf** [comment]
Thanks turning the `(global-eldoc-mode -1)` turned it off. But the type signature disappears immediately after pressing another key. Is there a way to prevent that?

**Comment by chrisdone** [comment]
What type signature? You just disabled eldoc mode.

**Comment by tepf** [comment]
The purpose of this was to show the type on demand and not automatically. I trigger type-at manually.

I want to keep it as a reference. Similar to a feature in Intellij. Let's say you write `object.fun(` then Intellij would create a little popup right beneath your cursor with the expected arguments e.g. `fun(arg1: String, arg2: Int)` so you don't have to look into the documentation.

This is not possible if Emacs always deletes the type signature after it appeared in the mode-line.
