### ISSUE TITLE
:loc-at/:type-at does not work for type signature in where clause

### ISSUE THREAD

**Issue by rikvdkleij** [commercialhaskell/intero#369]
At top-level `:loc-at` refers for type signature to it's accompanying definition. In a where clause, `loc-at` does not work for typesignature.

Short example:
```
foo = x + 1
  where
    x ::Integer
    x = 1
```
So first `x` refers to last `x`. Second `x` does not give result for `loc-at`.

**Comment by ice1000** [comment]
Just curious: is this issue "closed as fixed"

**Comment by chrisdone** [comment]
Closed as I'm not going to implement it, and seemingly neither is anyone else. :+1:

**Comment by ice1000** [comment]
I suppose it'll be better to, i.e. add a "wontfix" tag.
