### ISSUE TITLE
nix support: intero and its dependencies are installed via stack even when available via nix

### ISSUE THREAD

**Issue by 3noch** [commercialhaskell/intero#371]
For some reason the Emacs intero plugin always installs intero and its dependencies with stack, even when the stack.yaml file is configured to use nix and the nix shell already includes intero. This makes it impossible to use intero with any packages that share its dependencies because stack tries to use a dependency that is now installed twice.

**Comment by chrisdone** [comment]
Nix is not supported by Intero.

**Comment by 3noch** [comment]
Actually it is. It's just the emacs plugin that has issues and only for certain dependencies.

**Comment by 3noch** [comment]
I use intero perfectly well on top of stack on NixOS. Haskero for VS Code does not automatically install intero for you, so my nix-shell supplies it. Everything works extremely well!

**Comment by 3noch** [comment]
This request could be simplified to:

In the Intero emacs plugin, don't install the Intero executable if there is already an `intero` executable available on the path.

**Comment by purcell** [comment]
> This request could be simplified to:
> 
> In the Intero emacs plugin, don't install the Intero executable if there is already an intero executable available on the path.

That sounds pretty reasonable, and it would be quite easy to test the version of any `intero` found on the path before trying to `stack exec intero`. Are you set against this, @chrisdone?

**Comment by chrisdone** [comment]
It already doesn't install anything if there is an intero on the PATH: 

```lisp
(defun intero-installed-p ()
  "Return non-nil if intero (of the right version) is installed in the stack environment."
  (redisplay)
  (intero-with-temp-buffer
    (if (= 0 (intero-call-stack nil t nil intero-stack-yaml
                                "exec"
                                "--verbosity" "silent"
                                "--" "intero" "--version"))
        (progn
          (goto-char (point-min))
          ;; This skipping comes due to https://github.com/commercialhaskell/intero/pull/216/files
          (when (looking-at "Intero ")
            (goto-char (match-end 0)))
          ;;
          (if (string= (buffer-substring (point) (line-end-position))
                       intero-package-version)
              'installed
            'wrong-version))
      'not-installed)))
```

@3noch Perhaps your version of Intero doesn't match what the Emacs package expects (this is why the Emacs package installs the correct version of Intero automatically).

**Comment by 3noch** [comment]
@chrisdone That's quite possible. Would someone who actively uses Emacs with Nix be able to look into it?

Another possibility would to have a setting for the emacs plugin that tells it to just assume `intero` is on the path and fail otherwise. This would make it work like VSCode's Haskero plugin which works just fine with Stack+Nix+Intero.

**Comment by clojurians-org** [comment]
intero-0.1.30 is okay, but intero-20180622.2152 is wrong
it seems link didn't take affect .stack/compiler-tools/x86_64-linux-nix(stack/compiler-tools/x86_64-linux) for nix mode
