### ISSUE TITLE
Intero and terminfo

### ISSUE THREAD

**Issue by magthe** [commercialhaskell/intero#372]
I'm using _spacemacs_ for my emacs setup and trying out _intero_. When opening a haskell source file the building of _intero_ fails with the following message:

    Installing intero-0.1.20 automatically ...

    haskeline-0.7.3.0: configure
    haskeline-0.7.3.0: build

    --  While building package haskeline-0.7.3.0 using:
          /tmp/stack19961/haskeline-0.7.3.0/.stack-work/dist/x86_64-linux/Cabal-1.24.0.0/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.0.0 build --ghc-options " -ddump-hi -ddump-to-file"
        Process exited with code: ExitFailure 1
        Logs have been written to: /home/lmagnus/Work/lcam/src/utils/.stack-work/logs/haskeline-0.7.3.0.log

        [1 of 2] Compiling Main             ( /tmp/stack19961/haskeline-0.7.3.0/Setup.hs, /tmp/stack19961/haskeline-0.7.3.0/.stack-work/dist/x86_64-linux/Cabal-1.24.0.0/setup/Main.o )
        [2 of 2] Compiling StackSetupShim   ( /home/lmagnus/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /tmp/stack19961/haskeline-0.7.3.0/.stack-work/dist/x86_64-linux/Cabal-1.24.0.0/setup/StackSetupShim.o )
        Linking /tmp/stack19961/haskeline-0.7.3.0/.stack-work/dist/x86_64-linux/Cabal-1.24.0.0/setup/setup ...
        *** Warning: running on POSIX but not building the terminfo backend. ***
        You may need to install the terminfo package manually, e.g. with
        "cabal install terminfo"; or, use "-fterminfo" when configuring or
        installing this package.

        Configuring haskeline-0.7.3.0...
        Building haskeline-0.7.3.0...
        Preprocessing library haskeline-0.7.3.0...
        /usr/bin/ld: cannot find -ltinfo
        collect2: error: ld returned 1 exit status
        linking .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/System/Console/Haskeline/Directory_hsc_make.o failed (exit code 1)
        command was: /usr/bin/gcc .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/System/Console/Haskeline/Directory_hsc_make.o .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/System/Console/Haskeline/Directory_hsc_utils.o -o .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/System/Console/Haskeline/Directory_hsc_make -fno-stack-protector -L/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/transformers-0.5.2.0 -Wl,-R,/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/transformers-0.5.2.0 -L/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/terminfo-0.4.0.2 -Wl,-R,/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/terminfo-0.4.0.2 -ltinfo -L/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/directory-1.2.6.2 -Wl,-R,/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/directory-1.2.6.2 -L/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/unix-2.7.2.0 -Wl,-R,/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/unix-2.7.2.0 -lrt -lutil -ldl -L/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/time-1.6.0.1 -Wl,-R,/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/time-1.6.0.1 -L/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/filepath-1.4.1.0 -Wl,-R,/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/filepath-1.4.1.0 -L/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/containers-0.5.7.1 -Wl,-R,/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/containers-0.5.7.1 -L/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/bytestring-0.10.8.1 -Wl,-R,/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/bytestring-0.10.8.1 -L/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/deepseq-1.4.2.0 -Wl,-R,/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/deepseq-1.4.2.0 -L/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/array-0.5.1.1 -Wl,-R,/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/array-0.5.1.1 -L/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/base-4.9.0.0 -Wl,-R,/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/base-4.9.0.0 -L/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/integer-gmp-1.0.0.1 -Wl,-R,/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/integer-gmp-1.0.0.1 -lgmp -L/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/ghc-prim-0.5.0.0 -Wl,-R,/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/ghc-prim-0.5.0.0 -L/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/rts -Wl,-R,/home/lmagnus/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/rts -lm -lrt -ldl

Hopefully I'm correct in thinking that this is an issue with _intero_, if not I hope for some pointers of where the blame should be put :)

**Comment by chrisdone** [comment]
It looks like the haskeline package doesn't install because you need the terminfo package.

Have you tried installing it?

**Comment by magthe** [comment]
Hmm, strange. Today it works fine. I'll close this and keep my fingers crossed.

**Comment by magthe** [comment]
Sorry for re-opening this, but now I'm running into this again.

I see the same error as above, `-ltinfo` fails. However, I _do_ have terminfo installed:

    $ stack exec ghc-pkg -- list |grep terminfo
        terminfo-0.4.0.2

That lib is in turn linked to `/usr/lib/libtinfo.so.5`, which is a symbolic link:

    lrwxrwxrwx 1 root root 24 Jan 10 11:28 /usr/lib/libtinfo.so.5 -> /usr/lib/libncurses.so.5

**Comment by jfennick** [comment]
I'm having the exact same issue, and I also have terminfo installed.  I just had to add the following symlink, and then intero installed perfectly.

sudo ln -s /lib/x86_64-linux-gnu/libtinfo.so.5 /lib/x86_64-linux-gnu/libtinfo.so

**Comment by Jiehong** [comment]
I'm experiencing the exact same issue, but it seems a haskeline issue, more than an intero one.

I've opened a ticket on haskeline for that as well: https://github.com/judah/haskeline/issues/57

**Comment by Jiehong** [comment]
Copy from my comment on haskeline:

> Alright, I think this is a distribution issue actually, as libtinfo is the only lib which doesn't have a symlink such as libtinfo.so --> libtinfo.so.5.
My guess is that the linker only look for *.so, and not *.so.*. I'll open a ticket on the archlinux bug tracker for that then.
> 
> Therefore I'm closing this issue as not an haskeline issue.

This could be closed as not an intero issue as well I think.

**Comment by Jiehong** [comment]
For reference: https://bugs.archlinux.org/task/53157

**Comment by geekosaur** [comment]
Wait, are you really dlopen()ing a shared object without specifying the API version? Do you then have certainty that the API will never change incompatibly?

**Comment by aijony** [comment]
I uninstalled ncurses5-compat-libs from the aur and let stack install its own ghc-ncurses6-8.0.2. That fixed the issue for me. 

`pacaur -R ncurses5-compat-libs
stack setup
stack install haskeline
stack install intero`
