### ISSUE TITLE
go-to definition only works intra-package for a repo with a root stack.yaml - not other packages

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/intero#374]
We share database models across multiple packages including the core web application.

It's structured like: https://github.com/yesodweb/yesod

Presently I cannot go-to definition outside of the package I am currently looking at.

Two cases I tried:

Persistent QQ generated type: did nothing
Normal function exported by sister package: froze with the mouse pointer doing the loading spin for 15 seconds, then nothing.

**Comment by chrisdone** [comment]
In the case of multiple packages in the same stack.yaml, you should be able to run `M-x intero-targets` and select all the targets you want to be loaded into the same intero instance. That should load everything from source, and so enable go to definition.

If you have any ideas on how to nicely expose this functionality to the user, let me know.

Currently it's not possible to jump to library definitions.

**Comment by bitemyapp** [comment]
@chrisdone making the intero targets interface list the possible targets and let you check them off would be nice. I'm giving it the names of my app and the library for `intero-targets`, letting intero reboot, and re-attempting `M-.` but to no avail. It does pause to load for awhile when I attempt go-to definition.

Actually, at the moment, I can't go-to definition successfully on something bound within the same function.

```
user <- ...
...
[(user, ...)]
```

Fails. I think I just broke intero somehow but it said it booted up successfully with no error on the provided targets (just package names space separated, attempt to add `:library` or similar caused an error)

**Comment by bitemyapp** [comment]
Looks like `library-name` was a no-op, which is pretty likely to confuse people. `library-name:library-name` kicked off this process: 
![screenshot from 2017-02-09 14-27-49](https://cloud.githubusercontent.com/assets/320177/22801805/f4d08564-eed3-11e6-8b8c-80be5a1bbadb.png)

**Comment by acowley** [comment]
@bitemyapp I may be misunderstanding precisely what you're trying, but `M-x intero-targets` lists available targets which you then check off. The library targets end up being called `package-name:lib`.

**Comment by bitemyapp** [comment]
@acowley doesn't list available targets for me. it's just a blank input.

Currently dying on this hill (10 core desktop computer almost unusable, this is taking awhile)

![screenshot from 2017-02-09 14-37-06](https://cloud.githubusercontent.com/assets/320177/22802158/69954546-eed5-11e6-9188-760024383a45.png)
![screenshot from 2017-02-09 14-37-26](https://cloud.githubusercontent.com/assets/320177/22802163/6d581190-eed5-11e6-965e-a259d06c6fd5.png)

This is much slower than when I do it from the command-line and I am not sure why.

**Comment by acowley** [comment]
I try to do a `stack build` in a terminal before using Intero if I haven't built a project in a while and may have lost `stack` state. I'm not sure why it would be slower, but I find it easier to navigate dependency problems that way as opposed to things happening in the background of emacs.

But this raises another question: presumably you already did a `stack build` for the project you want to work on, in which case is it possible that `intero` is finding the wrong `stack.yaml` (or not finding one at all)?

**Comment by bitemyapp** [comment]
>But this raises another question: presumably you already did a stack build for the project you want to work on, in which case is it possible that intero is finding the wrong stack.yaml (or not finding one at all)?

Yes, I build this project 30 times a day. There's a root `stack.yaml`, it's possible it's using global project instead but I was assured root `stack.yaml` worked.

**Comment by bitemyapp** [comment]
Okay, finally booted with `library-name:lib` for three targets (app plus shared packages), still not able to go-to definition. Is it possible it somehow built in spite of being global project somehow?

**Comment by bitemyapp** [comment]
`user <- ... user` case still doesn't work either. I'm using fresh elisp from the git repo.

**Comment by acowley** [comment]
I think the `intero-project-root` variable should confirm whether or not it's using the right `stack.yaml`.

**Comment by bitemyapp** [comment]
@acowley yep, it has the right project root which makes sense when you consider that it didn't error in the build. Whence everything else then?

**Comment by acowley** [comment]
Drats, I guess that would have been too easy. I can't really think why it would want to rebuild all the dependencies if the project was already built in the terminal. Something is clearly hinky, but I'm afraid I don't know what. In my experience, problems like this have always been due to confusion about which `stack.yaml` is driving things. There is `intero-debug`, but I don't actually know what it does.

**Comment by bitemyapp** [comment]
![screenshot from 2017-02-09 15-36-31](https://cloud.githubusercontent.com/assets/320177/22804193/8a04da28-eedd-11e6-9c76-7133000661a5.png)

This is what I get on `M-.`

**Comment by bitemyapp** [comment]
I found out why the type errors don't work.

![screenshot from 2017-02-09 15-37-21](https://cloud.githubusercontent.com/assets/320177/22804230/ad62b29c-eedd-11e6-9a7f-6b3e5c52e296.png)

`data/` lives in the library package, not the app package I'm currently in.

**Comment by chrisdone** [comment]
I think you identified two problems at once. Intero doesn't pick up "Exception when trying" as an error type (e.g. "Warning: " and "Error: "). I copied haskell-mode's error parsing for that, seems like I should extend it. 

The second thing, TH code is known for stack ghci as being a problem. I'll discuss that further in the #375 issue you created.
