### ISSUE TITLE
TH doesn't run in correct pwd for additional intero targets from other packages

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/intero#375]
I'm working in `hestia`, a web app. I turn on intero's debug mode to find out why type errors aren't working.

Turns out, the problem is that the `pwd` isn't correct for running compile-time code in the library project `thoth`.

https://github.com/commercialhaskell/intero/issues/374#issuecomment-278781889

```
[Intero] <- 
/home/callen/work/betterteamapp/solo/thoth/src/Betterteam/StaticData/Types.hs:34:25:
    Exception when trying to run compile-time code:
      ./data/EmailClassification.csv: openBinaryFile: does not exist (No such file or directory)
    Code: embedFile "./data/EmailClassification.csv"
    In the splice: $(embedFile "./data/EmailClassification.csv")
Failed, modules loaded: Helpers.Error.
```

`data` is under `solo/thoth` not `solo/hestia`. Project root is `solo`.

**Comment by bitemyapp** [comment]
`intero-restart` nets me the same error.

**Comment by chrisdone** [comment]
This is a tricky issue: https://github.com/commercialhaskell/stack/issues/1057#issuecomment-144699469

TH using the current directory for getting its files makes cross-project compiling tricky.

I think we could possibly add some Elisp to launch Intero in a specific directory. Although a satisfactory solution for this in general would be much better.

**Comment by chrisdone** [comment]
Niklas Hambuchen has a nice approach for this that makes paths relative to the stack.yaml

**Comment by chrisdone** [comment]
E.g. Take the absolute path of the current file, strip off the file name and add your foo.csv. So the result is an absolute path, and doesn't care from where the Haskell file is loaded.

**Comment by felixSchl** [comment]
I am running into the same problem. @chrisdone Is there an example somewhere as to how to go about this? Does it involve the `CPP` language extension?

**Comment by mgsloan** [comment]
@felixSchl https://hackage.haskell.org/package/th-utilities-0.2.0.1/docs/TH-RelativePaths.html

**Comment by chrisdone** [comment]
@mgsloan Thanks, I was trying to remember where that was.
