### ISSUE TITLE
Fails to load with spaces in project parent directory

### ISSUE THREAD

**Issue by enolan** [commercialhaskell/intero#381]
Maybe related to #109? I get a different error message, and this is on Linux.

Steps to reproduce:
- `mkdir "test with space"`
- `cd "test with space"`
- `stack new testpkg`
- `cd testpkg`
- `stack build intero`
- `stack ghci --with-ghc intero`

Expected behavior: loads a GHCi prompt with the added Intero features.
Actual behavior: error message:
```
$ stack ghci --with-ghc intero
Warning: File listed in testpkg.cabal file does not exist: README.md
Warning: File listed in testpkg.cabal file does not exist: README.md
testpkg-0.1.0.0: configure (lib + exe)
Configuring testpkg-0.1.0.0...
testpkg-0.1.0.0: initial-build-steps (lib + exe)
Warning: File listed in testpkg.cabal file does not exist: README.md
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Configuring GHCi with the following packages: testpkg
Using main module: 1. Package `testpkg' component exe:testpkg-exe with main-is file: /home/enolan/junk/test with space/testpkg/app/Main.hs
Intero 0.1.20 (GHC 8.0.2)
Type :intro and press enter for an introduction of the standard commands.

*** Exception: "/home/enolan/junk/test with space/testpkg/": changeWorkingDirectory: does not exist (No such file or directory)
*** Exception: "/home/enolan/junk/test with space/testpkg/": changeWorkingDirectory: does not exist (No such file or directory)

<no location info>: error:
    Could not find module ‘Lib’
    It is not a module in the current program, or in any known package.
Prelude> 
```

The normal `stack ghci` works fine:
```
$ stack ghci
Warning: File listed in testpkg.cabal file does not exist: README.md
Warning: File listed in testpkg.cabal file does not exist: README.md
testpkg-0.1.0.0: initial-build-steps (lib + exe)
Warning: File listed in testpkg.cabal file does not exist: README.md
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Configuring GHCi with the following packages: testpkg
Using main module: 1. Package `testpkg' component exe:testpkg-exe with main-is file: /home/enolan/junk/test with space/testpkg/app/Main.hs
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
[1 of 1] Compiling Lib              ( /home/enolan/junk/test with space/testpkg/src/Lib.hs, interpreted )
Ok, modules loaded: Lib.
[2 of 2] Compiling Main             ( /home/enolan/junk/test with space/testpkg/app/Main.hs, interpreted )
Ok, modules loaded: Lib, Main.
Loaded GHCi configuration from /tmp/ghci16245/ghci-script
```

In the Emacs mode it just fails silently. Flycheck errors don't show up and `intero-type-at` gives the "Couldn't guess that module name" message.

**Comment by ulyssesp** [comment]
Getting this message on Windows too.

**Comment by VitorCBSB** [comment]
Having this issue as well. Although slightly different, (since this is on Windows), here's what I get:

```
C:\Users\Vitor Coimbra\ProjectName>stack ghci --with-ghc intero
ProjectName-0.1.0.0: initial-build-steps (lib + exe)
The following GHC options are incompatible with GHCi and have not been passed to it: -O2 -threaded
Configuring GHCi with the following packages: ProjectName
Using main module: 1. Package `ProjectName' component exe:ProjectName-exe with main-is file: C:\Users\Vitor Coimbra\ProjectName\app\Main.hs
Intero 0.1.20 (GHC 8.0.2)
Type :intro and press enter for an introduction of the standard commands.

*** Exception: SetCurrentDirectory "\"C:\\\\Users\\\\Vitor Coimbra\\\\ProjectName\\\\\"": invalid argument (A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.)
*** Exception: SetCurrentDirectory "\"C:\\\\Users\\\\Vitor Coimbra\\\\Project Name\\\\\"": invalid argument (A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.)

<no location info>: error:
    Could not find module `Lib'
    It is not a module in the current program, or in any known package.
Prelude>
```

(As a sidenote, "A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta." translates roughly to "The file, directory or drive name's syntax is incorrect.")

Intero also straight up doesn't work (no commands, no type-checking, no compilation, nothing). Launching the REPL (C-c C-z) gives the following messages:

```
Starting:
  stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-build --no-load --ghci-options "-odir=c:/Users/Vitor Coimbra/ProjectName/.stack-work/intero/intero1156CcY" --ghci-options "-hidir=c:/Users/Vitor Coimbra/ProjectName/.stack-work/intero/intero1156CcY" ProjectName
Intero 0.1.20 (GHC 8.0.2)
Type :intro and press enter for an introduction of the standard commands.

Warning: ignoring unrecognised input `Coimbra\ProjectName\.stack-work\intero\intero1156CcY'
Warning: ignoring unrecognised input `Coimbra\ProjectName\.stack-work\intero\intero1156CcY'
Warning: ignoring unrecognised input `Coimbra\ProjectName\.stack-work\intero\intero-script1156Pme'
Prelude> 
```

As it can be seen, the warnings clearly show the space character is eating the full path it's supposed to be using.

**Comment by fly** [comment]
I changed this [line](https://github.com/commercialhaskell/intero/blob/13b402890cdaa2990add3539c91888bc777f01be/src/InteractiveUI.hs#L1666) to the following: `setCurrentDirectory (read (ghc_work_directory state)))` and it works for me. Of course this is just a dirty hack. But I only started to learn haskell and I'm not confident enough to dig through `getGHCiState` and make PR with correct fix.
But, this may save someone like me, while we are waiting for release with fixed version.

**Comment by purcell** [comment]
Check out https://github.com/commercialhaskell/intero/commit/cf30e8068ee5e2a8f496dccb144af3d941caa71e, which I'm hopeful will fix this issue. Please all let me know how you get on.

**Comment by fly** [comment]
@purcell does not work for me. The same error.

**Comment by purcell** [comment]
Sorry, my bad: I missed that the original issue arose even without elisp in the mix.

**Comment by purcell** [comment]
I had a dig into this and I really can't see where the spurious wrapping quotes are coming from. :-/

**Comment by chrisdone** [comment]
I reproduce this here:

```
Intero 0.1.21 (GHC 8.0.2)
Type :intro and press enter for an introduction of the standard commands.

*** Exception: "/Users/chris/Emacs/packages/intero/test with space/testpkg/": changeWorkingDirectory: does not exist (No such file or directory)
*** Exception: "/Users/chris/Emacs/packages/intero/test with space/testpkg/": changeWorkingDirectory: does not exist (No such file or directory)

<no location info>: error:
    Could not find module ‘Lib’
    It is not a module in the current program, or in any known package.
```

I think we can create a test in the test suite for this and then fix it out in the intero side.

**Comment by chrisdone** [comment]
I suspect that stack is passing in a quoted name, as if the argument is being used in a shell command string, when actually the argument is probably passed directly into "ghci" (intero). I'll check.

**Comment by chrisdone** [comment]
Oh, I see it doesn't reproduce with ghci itself. So this is purely in Intero. I'll take a look.

**Comment by chrisdone** [comment]
Arguments passed in are:

``` 
/Users/chris/.stack/snapshots/x86_64-osx/lts-9.3/8.0.2/bin/intero
--interactive
-i
"-odir=/Users/chris/Emacs/packages/intero/test with space/testpkg/.stack-work/odir"
"-hidir=/Users/chris/Emacs/packages/intero/test with /testpkg/.stack-work/odir"
-hide-all-packages
"-i/Users/chris/Emacs/packages/intero/test with space/testpkg/src"
"-i/Users/chris/Emacs/packages/intero/test with space/testpkg/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/autogen"
"-i/Users/chris/Emacs/packages/intero/test with space/testpkg/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build"
"-stubdir=/Users/chris/Emacs/packages/intero/test with space/testpkg/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build"
-I/usr/local/Cellar/r/3.4.1_1/include
-I/usr/local/opt/icu4c/include
-I/usr/local/opt/libxml2/include/libxml2/
-L/usr/local/Cellar/gmp/6.1.0/lib
-L/usr/local/Cellar/gsl/1.16/lib
-L/usr/local/Cellar/r/3.4.1_1/lib
-L/usr/local/opt/icu4c/lib
-L/usr/local/opt/libxml2/lib
-package-id=base-4.9.1.0
"-i/Users/chris/Emacs/packages/intero/test with space/testpkg/app"
"-i/Users/chris/Emacs/packages/intero/test with space/testpkg/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/testpkg-exe/testpkg-exe-tmp"
-rtsopts
-with-rtsopts=-N
-optP-include
-optP/private/var/folders/2s/6j1qqrgd57bg9ctkltrkn3z80000gn/T/ghci70154/cabal_macros.h
-ghci-script=/private/var/folders/2s/6j1qqrgd57bg9ctkltrkn3z80000gn/T/ghci70154/ghci-script
```

**Comment by chrisdone** [comment]
I believe @fly is onto something. [This](https://github.com/commercialhaskell/intero/blob/55919310997d1c6393c5c257c38aa0f881703f72/src/InteractiveUI.hs#L579..L605) is where `ghc_work_directory` is initially set. However, [these two commands](https://github.com/commercialhaskell/intero/blob/55919310997d1c6393c5c257c38aa0f881703f72/src/InteractiveUI.hs#L1415..L1460) :cd and :cd-ghc update the value.

I have a hunch that Stack in its passed-in GHCi script file provides `:cd "foo .."`, and Intero interprets that literally without handling the speech marks.

**Comment by chrisdone** [comment]
**Found it** 🔎 😄 ☝️ 

```
Intero 0.1.21 (GHC 8.0.2)
Type :intro and press enter for an introduction of the standard commands.

*** Exception: "/Users/chris/Emacs/packages/intero/test with space/testpkg3/": changeWorkingDirectory: does not exist (No such file or directory)
*** Exception: "/Users/chris/Emacs/packages/intero/test with space/testpkg3/": changeWorkingDirectory: does not exist (No such file or directory)

<no location info>: error:
    Could not find module ‘Lib’
    It is not a module in the current program, or in any known package.
Prelude> :!cat /private/var/folders/2s/6j1qqrgd57bg9ctkltrkn3z80000gn/T/ghci92132/ghci-script
:cd-ghc "/Users/chris/Emacs/packages/intero/test with space/testpkg3/"
:add Lib
:cd-ghc "/Users/chris/Emacs/packages/intero/test with space/testpkg3/"
:add "/Users/chris/Emacs/packages/intero/test with space/testpkg3/app/Main.hs"
:module + Lib
```

So the difference between `:load` and `:add`  versus `:cd`/`:cd-ghc` is that the latter does not (never has) properly used the `toArgs` function to interpret command arguments for filepaths. See [here](https://github.com/commercialhaskell/intero/blob/55919310997d1c6393c5c257c38aa0f881703f72/src/InteractiveUI.hs#L233..L233) for example, commands taking pathnames should use `keepGoingPaths`.

So that's the fix! Commit incoming.

**Comment by chrisdone** [comment]
Give it half an hour from now until [the cabal hashes repo](https://github.com/commercialhaskell/all-cabal-hashes/blob/hackage/intero/0.1.23/intero.cabal) updates, and then you can pull this down and it'll install intero-0.1.23 with the fix.

**Comment by VitorCBSB** [comment]
Hey guys, sorry I never got around to checking if this was fixed or not. The original bug seems to have been fixed, but the second part of my first comment is still not working (i.e.: intero in Emacs does not work), which is exactly what #109 is about. What's the correct course of action here? Re-open this one? Or #109?

**Comment by VitorCBSB** [comment]
I do believe that this issue is fixed with the changes in https://github.com/commercialhaskell/intero/commit/cf30e8068ee5e2a8f496dccb144af3d941caa71e , but they were reversed for some reason?
