### ISSUE TITLE
Intero is using an insane amount of CPU and memory on mac

### ISSUE THREAD

**Issue by jaseemabid** [commercialhaskell/intero#388]
I've no idea how I can help debug this issue, but is more than happy to help. Please see the 2 attached screenshots. 

<img width="735" alt="screen shot 2017-03-17 at 5 11 47 pm" src="https://cloud.githubusercontent.com/assets/601714/24069980/f40ca8ec-0bd9-11e7-8bfe-724a6337733b.png">

<img width="746" alt="screen shot 2017-03-17 at 5 12 43 pm" src="https://cloud.githubusercontent.com/assets/601714/24069982/f51abbe8-0bd9-11e7-9e5f-10d20528d7ee.png">

**Comment by agocorona** [comment]
Also in windows around 45% CPU, 900Mb o RAM. ghc-8,0.1  w

$ intero --version
Intero 0.1.20

when running haskero, the command that haskero report is:

stack ghci --with-ghc intero --no-build --no-load --ghci-options=-ignore-dot-ghci -Wall

however executing in in the command line produce error becausse -Wall

removing Wall

stack ghci --with-ghc intero --no-build --no-load --ghci-options=-ignore-dot-ghci  

executes with reasonable memory and CPU consumption:

$ stack ghci --with-ghc intero --no-build --no-load --ghci-options=-ignore-dot-ghci
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Configuring GHCi with the following packages: axiom, transient-universe, transient
Intero 0.1.20 (GHC 8.0.1)
Type :intro and press enter for an introduction of the standard commands.
Prelude >

**Comment by agocorona** [comment]
Hi:
Just to let you know: 

I installed intero VScode and haskero in a new computer with the last versions of everithing. All works well with the same multi-project environment. Intero works in 0.5 MB RAM and does not go abobe 1 M RAM. Everithing works nice. Thanks

**Comment by chrisdone** [comment]
Closing as duplicate
