### ISSUE TITLE
Intero over TRAMP

### ISSUE THREAD

**Issue by osbugs** [commercialhaskell/intero#391]
I am currently trying to edit a Haskell file via TRAMP on a remote host. On both hosts I have Intero and stack installed (same version), the global project points to the same LTS version, and everything is set up.
Nevertheless I got an error message:

```
Installing intero-0.1.20 automatically ...

Run from outside a project, using implicit global project config
Using resolver: lts-8.5 from implicit global project's config file: /home/thomas/.stack/global-project/stack.yaml
Compiler version mismatched, found ghc-8.0.1 (x86_64), but expected minor version match with ghc-8.0.2 (x86_64) (based on resolver setting in /home/thomas/.stack/global-project/stack.yaml).
Try running "stack setup" to install the correct GHC into /home/thomas/.stack/programs/x86_64-linux/
Could not install Intero!
```

I could not explain where Intero could have found ghc-8.0.1, since on the local host the versions are:
```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3
$ stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2
```

Then, I ran these commands on the remote (TRAMP) host:
```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1
$ stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2
```

Is there a `stack` invocation missing somewhere?

**Comment by rlupton20** [comment]
Hmmm, I've had the install process for intero work fine over TRAMP a number of times (my global is currently `lts-7.14`). I've seen some issues with recent package sets in some of my CI pipelines to do with compiler mismatch, but I didn't dig into them. I'm suspicious. I'll try to reproduce this.

**Comment by rlupton20** [comment]
I tried this on an Arch VM with a fresh `stack` install - this doesn't reproduce for me. My local machine doesn't have stack setup with global configuration (I use the docker integration typically), so it's definitely installing remotely.

It looks like it's failing in `stack`. I don't have a way to debug this at present, so I'll make some suggestions that might help. Some are trivial - don't be offended, I often forget to do silly things :-)

- Which version of `intero` are you running? I recall needing to install from unstable melpa to get TRAMP integrations. Try deleting `~/.emacs.d/elpa/intero*` and doing a fresh install (or upgrade from the package manager, whichever you prefer - for some reason I often use the "kill with fire" approach).
- Evaluate `intero-project-root` in the haskell buffer which is trying to bootstrap `intero`. I'm not sure if this will work, but might give an indication of where `stack` is being run from.
- Run `stack setup` on the remote (I'm mostly interested here in whether `stack` spots a compiler mismatch in a different context).

**Comment by osbugs** [comment]
I have just done some debugging regarding this issue. It seems that Intero is not at fault here: When TRAMP calls stack on the remote host it uses the globally installed `/usr/bin/stack` instead of the version in the user directory due to `$PATH` being set to a conservative value by TRAMP.

The following Elisp command makes the bug go away (after having cleaned the connection cache in ~/.emacs.d/tramp as outlined in the TRAMP user manual):
```
(add-to-list 'tramp-remote-path "~/.local/bin")
```

Running `/usr/bin/stack path --project-root` results in the part of the above error message related to the mismatched compiler version.

Perhaps the error message can be changed to help the user to debug such a problem more easily? (My suggestion would be to refer the user to `M-! which stack`.) Another possibility would be to make the `stack` executable somehow configurable/auto-detected.

**Comment by rlupton20** [comment]
Perhaps something like an `intero-validate-setup` command might be useful? (Ala flycheck and friends). Executed on a per-project basis it might highlight the path for stack, the location of the stack.yaml, which version of intero is in use etc. Perhaps this might offer a more generic way of introspecting the system?

Failed installs could point the user a this, or provide the inforomation live on failure.

Thoughts?

**Comment by osbugs** [comment]
Your suggestion sound reasonable. Having more information in the error case instead of just throwing a generic message at the user is definitely the appropriate direction towards a more user friendly Haskell environment.

**Comment by mgsloan** [comment]
While I haven't encountered this myself, I've heard from others that emacs maintains its own PATH.  This particularly seems to be the case with tramp.
