### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by Alok** [commercialhaskell/intero#395]
This is rather basic but I've failed to fix it for a while.

I try to run `intero`, and get this:

```
dyld: Library not loaded: /usr/local/opt/ghc/lib/ghc-8.0.1/haskeline-0.7.2.3/libHShaskeline-0.7.2.3-ghc8.0.1.dylib
  Referenced from: /Users/alokbeniwal/.local/bin/intero
  Reason: image not found
```

How would I go about reinstalling the relevant packages?

**Comment by holguinj** [comment]
I ran into this exact same thing and solved it by deleting `~/.local/bin/intero`and then reinstalling intero.
