### ISSUE TITLE
Parse error on injective type families syntax

### ISSUE THREAD

**Issue by queertypes** [commercialhaskell/intero#399]
GHC Version: 8.0.2 (stackage: lts-8.5)
Intero version: 0.1.20

I'm using injective type families for a recent project. Intero fails to parse the syntax but `stack build` and `stack ghci` have no problems at all. Here's the types in question:

```haskell
type family TypeOf (a :: FType) = r | r -> a where
  TypeOf 'FInt = Int
  TypeOf 'FBool = Bool
  TypeOf 'FUuid = UUID
  TypeOf 'FString = Text
  TypeOf 'FDouble = Double

data FType
  = FInt
  | FString
  | FUuid
  | FBool
  | FDouble
  deriving (Show, Eq)
```

The parse error highlights specifically on the `=` above, and it reports as:

```haskell
Parse error: =
Found:
    deriving instance Show (Expression a)

 > type family TypeOf (a :: FType) = r | r -> a where
      TypeOf 'FInt = Int
      TypeOf 'FBool = Bool
```

Here's the enabled extensions, to be sure:

```haskell
{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE EmptyCase #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE StandaloneDeriving #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeFamilyDependencies #-}
{-# OPTIONS_GHC -Wall #-}
```

Some of these are used in other portions of the implementation, so this is more extensions than is strictly needed to parse the above code set.

Let me know if y'all need any more information. Thanks so much for looking at this!

**Comment by chrisdone** [comment]
That's hlint not Intero, disable hlint.
