### ISSUE TITLE
TRAMP issues with Intero/Spacemacs

### ISSUE THREAD

**Issue by MikeCain** [commercialhaskell/intero#400]
When I tried opening a Haskell file today, I was getting errors such as these:

```
File local-variables error: (void-variable tramp-file-name-regexp)
Error while checking syntax automatically: (void-variable tramp-file-name-regexp)
eldoc error: (void-variable tramp-file-name-regexp)
```

I reported a bug with the TRAMP mailing list, since the variable name led me to believe it was something related to TRAMP, but when I enabled "toggle-debug-on-error", I got this stack trace:

```
Debugger entered--Lisp error: (void-variable tramp-file-name-regexp)
  intero-tramp-path-p(<haskell file name here>)
  intero-buffer-host()
  intero-extend-path-by-buffer-host(<stack project root here>)
  intero-get-buffer-create(backend)
  intero-buffer(backend)
  intero-eldoc()
  eldoc-print-current-symbol-info()
  #[0 "\204	\205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2]()
  apply(#[0 "\204	\205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2] nil)
  timer-event-handler([t 0 0 500000 nil #[0 "\204	\205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2] nil idle 0])
```

So, it seems like that variable isn't defined when that function is called, causing it to error.

**Comment by purcell** [comment]
Which Emacs version do you have, and did you install `intero` using `package.el`?

In addition to being autoloaded, that variable is defined in `tramp.el`, which is explicitly loaded by `intero`, so it's hard to see why you'd have a problem.

**Comment by MikeCain** [comment]
Sorry for the delay, my Emacs version is 26.0.50 (I use the daily build Ubuntu PPA, found here: [https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa](https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa)).
I spoke with someone from the TRAMP mailing list, and they told me they had recently changed `tramp-file-name-regexp` to become a function rather than a variable.  As I understand it, they are now including the variable as well for backward compatibility.

**Comment by purcell** [comment]
Aha, okay. That makes sense: with current and older Emacs versions, there was no way this could have happened. Regressions in Emacs HEAD do happen, and I guess it's good if you're volunteering as a canary on behalf of the rest of us. :-)

In any case, we now call `tramp-tramp-file-p` instead of looking at `tramp-file-name-regexp`, which I believe will eliminate the issue in released Emacs versions and your bleeding edge snapshot.
