### ISSUE TITLE
Allow varying DynFlags among modules

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/intero#41]
See https://ghc.haskell.org/trac/ghc/ticket/10827 .  It'd be interesting to see how much mileage we can get out of having intero vary flags when loading modules.  This will hopefully allow https://github.com/chrisdone/intero/issues/39 to work much better.

**Comment by chrisdone** [comment]
Too hard for me. Closing for [reasons in here](https://github.com/commercialhaskell/intero/issues/49#issuecomment-451153567).

**Comment by Ericson2314** [comment]
ghc-proposals/ghc-proposals#263 There's a proposal this (and WIP PR for the first step of this).
