### ISSUE TITLE
Feature request: suggestion to create missing function

### ISSUE THREAD

**Issue by AlainODea** [commercialhaskell/intero#410]
I imagine it working like this:

```haskell
import Conduit

main :: IO ()
main = runConduitRes
     $ sourceFile "input.txt"
    .| myTakeCE 5
    .| stdoutC
```

**myTakeCE** doesn't exist. Invoking **C-C-C-R** (**intero-apply-suggestions**) on it would bring up a multiswitch with the following:

```plain
There is 1 suggestions to apply:

Hit [C-c C-c] to apply these choices.

[x] Add myTakeCE :: Monad m => Integer -> ConduitM ByteString ByteString m ()
        myTakeCE = undefined
```

**Comment by AlainODea** [comment]
@acowley glad you like it. The compilation error sometimes has a silly type, but it would be enough to get a scaffold in place and keep the programmer coding in flow. In flow I see C-C-C-R, C-C-C-C, M-. happening a LOT if this gets in :)

**Comment by chrisdone** [comment]
Submit a PR and I'll merge immediately. It's a great idea.

**Comment by bradrn** [comment]
I know this suggestion may be slightly too late, as this has already been closed, but: wouldn't it be nicer if the function was defined as a typed hole rather than `undefined` so that we get a type error reminding the programmer to define the function?
