### ISSUE TITLE
flycheck and Parse error: @

### ISSUE THREAD

**Issue by tonyday567** [commercialhaskell/intero#411]
The intero process in flycheck-mode reports `Parse Error: @` for the code below.

This does not occur for the same code with `stack ghci --with-ghc=intero`, for `stack ghci` or with `intero-repl-load`.  So my hypothesis is that there is an issue with the flychecker process.

A similar error does occur on selecting `haskell-stack-ghc` as the flycheck checker, so the problem may be upstream.  Unfortunately, I got lost trying to follow the stream to the source of the bug.  I don't have a global install of ghc so I couldn't try a flychecker sans stack.

#399 may be a similar problem.

haskell/haskell-mode#1481 may also be related.

to reproduce:
---

GHC Version: 8.0.2 (stackage: lts-8.12)
Intero version: 0.1.20

```
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE TypeApplications #-}

import GHC.TypeLits (Nat, type (+))
import Data.Singletons.Prelude (Sing)
import Data.Singletons.TypeLits -- SNat

data Bug :: Nat -> * where
    Bug :: Sing x -> Bug (x + y)

sBug = Bug (SNat @0)
```

**Comment by chrisdone** [comment]
I think this is hlint.

**Comment by tonyday567** [comment]
thanks @chrisdone, I'd forgotten about hlint in there, sorry for the noise.
