### ISSUE TITLE
menu items blank

### ISSUE THREAD

**Issue by Plantgrower** [commercialhaskell/intero#412]
When editing a haskell file if I select the menu item Haskell from the main menu, the items are all blank and unselectable. In the repl if I select Complete, In/Out and Signals the same happens. I am using  Emacs 25.1.1 on Ubuntu 17.04.

**Comment by purcell** [comment]
This isn't an `intero` issue, sorry. For what it's worth, I also notice some strange menu behaviour (in Emacs 25.2 on OS X) -- sometimes I have to click between Emacs windows for the menus to get updated properly.
