### ISSUE TITLE
company completion doesn't play nice with haskell-unicode-input

### ISSUE THREAD

**Issue by kfiz** [commercialhaskell/intero#419]
Hi,
at my end company completion only works, when I'm not using haskell-unicode-input at the same time. I'm seeing this on OS X as well as on linux. 
Steps to reproduce: 
1. add (turn-on-haskell-unicode-input-method) to your haskell-mode-hook
2. add intero-mode to your haskell-mode-hook.
3. open any .hs file and check whether code-completion is working.

Best

**Comment by chrisdone** [comment]
Intero doesn't support haskell-mode. If it interferes I suggest disabling that feature.
