### ISSUE TITLE
Watch expressions

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/intero#420]
Here's a small script to have "watch expressions" that hook into flycheck and after each check will re-run the given expression.

https://gist.github.com/chrisdone/e54a2ff511d54cb79f02b6b59e45adc7

![screenflow](https://cloud.githubusercontent.com/assets/11019/25997053/412ce016-3712-11e7-9cb5-b8e1c5cf73ee.gif)

Incrementally working on a function and seeing the result as you type is pretty cool.

Does Emacs already have a "thing" for this?

**Comment by purcell** [comment]
> Does Emacs already have a "thing" for this?

Not exactly, but for related work, check out:

- https://github.com/seanirby/evalator
- https://github.com/Fuco1/litable
- https://github.com/emacsorphanage/lively/blob/master/lively.el

I like the idea of having a separate buffer (not the minibuffer) to display one or more watch expressions.

**Comment by unhammer** [comment]
This is cool! What if I need e.g. Data.Text in the watch expression, is there a simple way to get the imports, or do I just have to put `, module T` in my module exports?
