### ISSUE TITLE
find-uses issues

### ISSUE THREAD

**Issue by FongHou** [commercialhaskell/intero#425]
These issues only happen to find-uses merged into master a day ago. 

1. intero-uses-at does not highlight all occurence anymore, not even defining location. Only current location where cursor is. I notice "Invalid face reference: isearch-lazy-highlight [14 times]" in *Messages* buffer.

2. intero-hightlight-uses-mode-replace puts buffer in read-only and stay in that mode, until I toggled read-only-mode manullay I can't undos, or do any editing.

The code in original find-uses branch did work pretty well, even with spacemacs haskell layer.

**Comment by purcell** [comment]
Turned out that `isearch-lazy-highlight` is not a face. `isearch-lazy-highlight-face` is, though, but it's obsolete as of Emacs 22, so I've fixed the code to refer to the new name for it: `lazy-highlight-face`.

**Comment by FongHou** [comment]
lazy-highlight (without -face) works for me. 

I'm on GNU Emacs 25.2.1 (x86_64-apple-darwin15.6.0, Carbon Version 157 AppKit 1404.47) of 2017-04-22.

**Comment by purcell** [comment]
Doh, thanks @FongHou, I've removed the `-face` suffix now!
