### ISSUE TITLE
Does not work in macOS 10.12.5

### ISSUE THREAD

**Issue by noraesae** [commercialhaskell/intero#428]
After macOS 10.12.5 update, I get the following error on every intero command including `intero-restart`.

```
Wrong type argument: number-or-marker-p, "Abort trap: 6"
```

Is there anybody having the same problem as mine?

**Comment by dzhus** [comment]
Same here on 10.12.2. No idea what's causing this just yet.

**Comment by purcell** [comment]
Please can you set `debug-on-error` and post the resulting backtrace?

**Comment by purcell** [comment]
It's also a good idea to supply the following info with bug reports like this:
- GHC version
- Intero version
- Emacs version

**Comment by dzhus** [comment]
Stack trace:
```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p "Abort trap: 6")
  signal(wrong-type-argument (number-or-marker-p "Abort trap: 6"))
  flycheck-buffer()
  flycheck-buffer-automatically()
  flycheck-perform-deferred-syntax-check()
```

With flycheck disabled, this happens in a buffer with intero enabled:
```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p "Abort trap: 6")
  intero-installed-p()
  intero-get-worker-create(backend nil #<buffer ingester.hs>)
  intero-buffer(backend)
  intero-eldoc()
  eldoc-print-current-symbol-info()
  #[0 "\204	\205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2]()
  apply(#[0 "\204	\205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2] nil)
  timer-event-handler([t 0 0 500000 nil #[0 "\204	\205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2] nil idle 0])
```

GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2016-09-21

Intero 20170611.437

**Comment by dzhus** [comment]
This was easy to fix, I'm not sure what exactly caused this though. Looking at `intero-installed-p` I found out that `(intero-call-stack nil t nil intero-stack-yaml
                                "exec"
                                "--verbosity" "silent"
                                "--" "intero" "--version")` returns 
```
dyld: Library not loaded: @rpath/libHShaskeline-0.7.3.1-19q6LHqZ5xHeU9qD4pnHO-ghc8.0.2.dylib
  Referenced from: /Users/dmitrydzhus/.local/bin/intero
  Reason: image not found
```

I reinstalled intero (`stack install intero`) in the context of my global project and it works as expected now. I have LTS-8.21 selected in my global project.
I suggest that you do `stack exec -- intero --version` in your global project (= from you home directory) as a first step to troubleshoot this.

**Comment by k-bx** [comment]
Wow, thanks for the find! I didn't use intero for quite some time because of the crypticness of the error :)

**Comment by wilfreddenton** [comment]
I am receiving this error on macOS 10.13.2 with spacemacs `0.200.10@27.0.50 (spacemacs)`. I tried running `stack install intero` in my home directory but that did not solve the issue.
