### ISSUE TITLE
How to enable Cabal flags in Intero?

### ISSUE THREAD

**Issue by ntc2** [commercialhaskell/intero#429]
I poked around a bit and found the `intero-repl-options` function, but when I do `M-x intero-repl-options RET` nothing happens. How do I enable Cabal flags in Intero, i.e. corresponding to `stack --flag <package>:<flag>`?

I'm using `intero-20170518.307` from ELPA on Ubuntu 16.04.

**Comment by chrisdone** [comment]
It's not possible via Emacs, but you can specify it in your stack.yaml.

**Comment by mgsloan** [comment]
Haven't done it in a while, but IIRC you can also pass in flags when setting targets
