### ISSUE TITLE
Shortcut to reload entire library

### ISSUE THREAD

**Issue by karljs** [commercialhaskell/intero#430]
Suppose I have two modules in my project `A` and `A.B`.

```
module A where
import A.B
...
```

```
module A.B where
...
```

Now after making changes to A.B, I want to be able to reload the entire project including the outer module A.  Currently it seems like I have to either: 1) open A.hs and reload it, or 2) switch to the REPL and type `:r`.  Ideally I'd like to avoid having to switch buffers at all.

I believe haskell-mode used to support this via `haskell-process-reload`. What is the preferred way to do this in Intero?

**Comment by purcell** [comment]
Maybe `M-x intero-restart`?

**Comment by karljs** [comment]
Thanks for the suggestion.  That's easier than implementing my own workaround in elisp.  I still support something like this being considered for the todo list.  I can't promise too much time in the immediate future, but if I were to work on a patch would it be considered for inclusion?

**Comment by purcell** [comment]
Yes, I would think so, unless it would be a huge amount of code, or there are some technical issues I'm unaware of.
