### ISSUE TITLE
Can't load .emacs

### ISSUE THREAD

**Issue by Gurkenglas** [commercialhaskell/intero#432]
The `.emacs` from https://commercialhaskell.github.io/intero/ leads to "error: Package `emacs-24.4' is unavailable". This openSUSE machine has 24.3 and upgrading would be a can of worms according to the admin. Does that dependency need to be hard?

**Comment by purcell** [comment]
Yes, sorry. Emacs 24.4 was released on [2014-10-20](https://www.emacswiki.org/emacs/EmacsReleaseDates), and you should reasonably expect to develop on a machine which has newer software, even if your deployment target machine is older.
