### ISSUE TITLE
Flycheck warnings doesn't work after update

### ISSUE THREAD

**Issue by korayal** [commercialhaskell/intero#433]
I'm using Intero on Spacemacs, and a few days ago I did an upgrade on some of my emacs packages (I do 
 this daily). I guess after some change I stopped receiving flycheck warnings from Intero.

At first I thought this was about me having a custom prelude file named `Prelude.hs` at the same path with the file I'm working with (I was getting this error before, but it was working alright). I noticed that this error is coming from [flycheck-haskell](https://github.com/flycheck/flycheck-haskell/issues/70) so also created an issue there.

After that I renamed my prelude file to a different name and stopped getting the errors mentioned in the issue above.

But still I'm not getting any flycheck highlights in the buffer. ie. renaming `MonadIO` to `MonadIOt` doesn't highlight that part in the code, the only way for me to see this error is via manually building the project and looking at the errors, another indicator is the type-signatures that are displayed at the bottom (when we place the cursor on an expression) stops showing (if we save the buffer)

**Comment by concavegit** [comment]
For now, revert
[this commit](https://github.com/commercialhaskell/intero/commit/70c9c524b3de8dce739df7fe0fdb5128fc8adf11
) and recompile the file.

**Comment by korayal** [comment]
@concavegit yup! that did the trick. thanks!

**Comment by WraithM** [comment]
Same error here.

**Comment by CarstenKoenig** [comment]
had quite a few problems with this (no errors shown, no warnings/hlint shown, ...) - for me deinstalling intero and then installing the 1.20.xxx version from melpa-staple fixed it again

**Comment by chrisdone** [comment]
Reverted!
