### ISSUE TITLE
the problem of intero-mode jumping to definition

### ISSUE THREAD

**Issue by jimmyhuco** [commercialhaskell/intero#435]
intero-mode seems can not go to definition out of current project.

For example

```
module Main where

import           Data.ByteString as B
import           Lib

main :: IO ()
main = someFunc

cc = B.unpack
```

I can not use `M-.` to jump to the definition of `unpack` .

But, jump to `someFunc` in `Lib` is ok.

> GHCi, version 8.0.2
> Intero, version 0.1.20
> Emacs, version 25.2.1
> Mac OS, version 10.10.5

**Comment by michalrus** [comment]
Duplicates #231.

**Comment by jimmyhuco** [comment]
@michalrus  Thank you.
I think that it's time to close this issue.
