### ISSUE TITLE
Cloned GH project now appears in Interos execution path (Emacs)

### ISSUE THREAD

**Issue by gentauro** [commercialhaskell/intero#439]
Hi, all.

I don't know if it's a bug related to intero, but I get this strange execution path when I hit `C-c C-l`:

```bash
stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-build --no-load --ghci-options -ignore-dot-ghci --ghci-options -odir=/home/mon/.stack/global-project/.stack-work/intero/intero5760MAt --ghci-options -hidir=/home/mon/.stack/global-project/.stack-work/intero/intero5760MAt albums 
```

I have given the following project a try:

- https://github.com/rundis/albums/tree/master/backend

and as you can see it has a `stack.yaml` file. What I don't seem to understand, is why that project now appears in my intero execution path :-1: 

I hope you can help as I simple can't find the reason of this issue ...

**Comment by gentauro** [comment]
I mean, there is something really _*spooky*_ going on here.

I can use `intero-targets` and set the value to `ghc` and then I can use the `REPL` from inside Emacs, but as soon as I close it down. I will ask again about _*albums*_.

I have asked around in Slack -> Haskell but people don't some to know what happens neither ...

`grep -r "albums"` in `~/` give no results what so ever :hankey:

**Comment by purcell** [comment]
Do you have a `.dir-locals.el` file containing that string? I'm surprised that there's no mention of "albums" in any file under `~` - are you absolutely sure about that?

**Comment by gentauro** [comment]
Sorry late response.

Yes, I'm absolutely sure. That's why this seems so strange ... Right now I'm living with just changing the `targets` as described above, so this can actually be closed.

> Note: No `.dir-locals.el`, when I tried to save, it appeared in the `global` path ...

**Comment by chrisdone** [comment]
What is the actual problem?

**Comment by gentauro** [comment]
OK, I will have to re-open this issue.

I have a new laptop and I have installed `emacs`, `stack` and `intero`. I have ofc copied my profile from my old laptop and I get the same behavior as before.

In order to get over this annoying issue, I have deleted both `.stack` and moved `.emacs.d` but I still get the same error:

Emacs file info containing `backend` and `albums` from the following project https://github.com/rundis/albums:
```
-UUU:**--F1   intero:backend:albums /home/user/.stack/global-project   Bot (73,0) 
```

and error:
```
Warning: Some targets (albums) are not
         local packages, and so cannot
         be directly loaded. In future
         versions of stack, this might
         be supported - see
         https://github.com/commercialhaskell/stack/issues/1441
         . It can still be useful to
         specify these, as they will be
         passed to ghci via -package
         flags.

Warning: No local targets specified, so
         ghci will not use any options
         from your package.yaml /
         *.cabal files.
         
         Potential ways to resolve this:
         * If you want to use the
           package.yaml / *.cabal
           package in the current
           directory, use stack init to
           create a new stack.yaml.
         * Add to the 'packages' field
           of /home/user/.stack/global-project/stack.yaml
         
Configuring GHCi with the following packages: 
Intero 0.1.30 (GHC 8.2.2)
Type :intro and press enter for an introduction of the standard commands.

<command line>: cannot satisfy -package albums
    (use -v for more information)

---

This is the buffer where Emacs talks to intero. It's normally hidden,
but a problem occcured.

TROUBLESHOOTING

It may be obvious if there is some text above this message
indicating a problem.

If you do not wish to use Intero for some projects, see
https://github.com/commercialhaskell/intero#whitelistingblacklisting-projects

The process ended. Here is the reason that Emacs gives us:

  exited abnormally with code 1

For troubleshooting purposes, here are the arguments used to launch intero:

  stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-load --ghci-options -ignore-dot-ghci --ghci-options -odir=/home/user/.stack/global-project/.stack-work/intero/intero60740ot --ghci-options -hidir=/home/user/.stack/global-project/.stack-work/intero/intero60740ot albums

It's worth checking that the correct stack executable is being
found on your path, or has been set via
`intero-stack-executable'.  The executable being used now is:

  /usr/local/bin/stack

WHAT TO DO NEXT

If you fixed the problem, just kill this buffer, Intero will make
a fresh one and attempt to start the process automatically as
soon as you start editing code again.

If you are unable to fix the problem, just leave this buffer
around in Emacs and Intero will not attempt to start the process
anymore.

You can always run M-x intero-restart to make it try again.
```

but I simple can't find where to remove `albums` ... could anybody point me in the right direction?

Thx in advance

> Note: The way I solve this right now is by doing this (every time, which is annoying) in `Emacs`:
```
M-x > intero-targets > ghc
Save selected target(s) in directory local variables for future sessions? (y or n) 
```
