### ISSUE TITLE
Fix unrelated Travis build failures

### ISSUE THREAD

**Issue by KarlFish** [commercialhaskell/intero#443]
Travis builds are failing for a reason unrelated to pull request contents.

Most of the specific job failures end with the same error ([example](https://travis-ci.org/commercialhaskell/intero/jobs/249616830#L605)), pasted below.

    In `intero.el'
      at 357:5: error: You should depend on (emacs "25") if you need `font-lock-ensure'.

These errors are because 4 out of the 5 travis jobs specify using `emacs-24.4-travis`, while [this commit](https://github.com/commercialhaskell/intero/commit/39685c21f5fdc5aa3a94f532627a7014ecf266e1) removed the check to only run `font-lock-ensure` if it's available.

This commit should be reverted, or the `.travis.yml` should be updated.

**Comment by purcell** [comment]
I ended up fixing this in `package-lint`, since the code was sensibly using `fboundp` to check that `font-lock-ensure` was available before actually calling it: now `package-lint` holds its tongue in that case.
