### ISSUE TITLE
Jump to definition does not work with import qualified as

### ISSUE THREAD

**Issue by renzhi** [commercialhaskell/intero#447]
Jump to definition does not work with import qualified as, pressing M-. does not nothing.

For example, I have a function `doSomething` in the `Lib` module, and in the `Main` module, if I do

`import Lib`
and do
`doSomething`

Pressing M-. on `doSomething` will jump to the definition in the `Lib` module.

If I do
`import qualified Lib`
and do
`Lib.doSomething`

It also works. But if I do
`import qualified Lib as L`
and do
`L.doSomething`

Then jump to definition does not work anymore. But if I first do
`import qualified Lib`
and then change to
`import qualified Lib as L`
Then it still works.

**Comment by rikvdkleij** [comment]
Similar issue as mentioned in #312
