### ISSUE TITLE
Wrong suggestion for missing data constructor

### ISSUE THREAD

**Issue by kephas** [commercialhaskell/intero#450]
If I have the following code:

```haskell
import Data.LargeWord (Word128, LargeKey)    
foo = LargeKey bar baz -- bar and baz are Word64
```

the last `LargeKey` will be underlined as an error and if I go to suggestions, I get

> Add ‘LargeKey’ to import of ‘Data.LargeWord’

If I do it, I get:

```haskell
import Data.LargeWord (LargeKey, Word128, LargeKey)
```

but the correct modification should be:

```haskell
import Data.LargeWord (Word128, LargeKey(LargeKey))
```

**Comment by chrisdone** [comment]
There's no way to fix this as implemented. The "add to import" is very literal.
