### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/intero#451]
The current HEAD works with GHC 8.2. The latest release does not. A new release would help people trying out Intero with GHC 8.2.

**Comment by PierreR** [comment]
Would love a release too. There are a couple of fixes in master I would be happy to try out.

It is a bit peculiar,  22 releases in 2016 and none so far in 2017.

**Comment by acowley** [comment]
Version 0.1.21 should be on melpa and hackage now. Let me know if anything else needs doing for the release!

**Comment by pepeiborra** [comment]
Thanks Anthony ! Do you know what needs to be done to get intero back in Stackage Nightly ?

**Comment by acowley** [comment]
@pepeiborra I think a PR to stackage is needed. I probably won't be able to do so today, so if you're desperate you can make the PR re-adding `intero` and link back to this thread. Otherwise I will get to it as soon as I have some keyboard time.

**Comment by pepeiborra** [comment]
I've sent a PR.

**Comment by chrisdone** [comment]
Thanks @acowley
