### ISSUE TITLE
Expose haskell API

### ISSUE THREAD

**Issue by noughtmare** [commercialhaskell/intero#453]
Please make a haskell package that exposes the intero functionality directly to haskell. I'm writing [intero integration for Yi](https://github.com/yi-editor/yi/tree/master/yi-intero) and would really appreciate being able to directly call the functions and getting nice output.

**Comment by KarlFish** [comment]
@noughtmare Intero (and ghci) exposes the api through commands. Completion, for example, use `interoEval` to send `:complete repl "<prefix to complete>"` to the intero process. This is how the the emacs `intero.el` works.

    ghci> :complete repl "si"
    4 4 ""
    "significand"
    "signum"
    "sin"
    "sinh"

    ghci> :complete repl "import Data.Li"
    2 2 "import "
    "Data.List"
    "Data.List.NonEmpty"

**Comment by kRITZCREEK** [comment]
@KarlFish Yes, but that's only because emacs can't be programmed in Haskell. For an editor like Yi which is written in Haskell it's going to be a lot easier and less error prone to directly use Intero's datatypes rather than parsing it's textual output.

**Comment by chrisdone** [comment]
This won't happen any time soon.

**Comment by mgsloan** [comment]
Also, one downside of this approach is that in some cases you may want to kill interpreter.  It's easy to end up in circumstances where your ghci session has multiple threads running / resources acquired / etc, and the only way to clean it up is to kill it.  If the interpreter is baked in with the editor, you have to kill your editor, and your editor's stability is affected by the interpreter.
