### ISSUE TITLE
Invalid use of ‘\’ in replacement text

### ISSUE THREAD

**Issue by tonyday567** [commercialhaskell/intero#455]
Intero 0.1.20

I get the following error multiple times on intero-repl-load:

~~~
error in process filter: intero-linkify-file-line-char: Invalid use of ‘\’ in replacement text
error in process filter: Invalid use of ‘\’ in replacement text
~~~

Intero continues but slows significantly.

I'm on windows 10 and that might well matter given backslash hell.  Happy to help locate the bug if one exists, but process debugging in emacs is so very tricky.

**Comment by jbransen** [comment]
I have the same issue, and noticed that `stack build` gives the following warning, which may be what the `intero-linkify-file-line-char` is choking on:

`Cabal file warning in C:\some\path\project.cabal: This package requires at least Cabal version 1.24`

**Comment by chrisdone** [comment]
I had problems with this code too which was contributed in a PR, I've stripped it out for now.
