### ISSUE TITLE
Trying to install intero but I get hung up trying to install terminfo

### ISSUE THREAD

**Issue by gremdrus** [commercialhaskell/intero#456]
This is what I get when I try to open a file created by "stack new hackerrank simple" in emacs with intero enabled:

> Intero is not installed in the Stack environment.
> 
> Installing intero-0.1.20 automatically ...
> 
> terminfo-0.4.1.0: configure
> 
> --  While building package terminfo-0.4.1.0 using:
>       /tmp/stack16564/terminfo-0.4.1.0/.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0 configure --with-ghc=/home/g/.stack/programs/x86_64-linux/ghc-nopie-8.0.2/bin/ghc --with-ghc-pkg=/home/g/.stack/programs/x86_64-linux/ghc-nopie-8.0.2/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/home/g/.stack/snapshots/x86_64-linux-nopie/lts-9.0/8.0.2/pkgdb --libdir=/home/g/.stack/snapshots/x86_64-linux-nopie/lts-9.0/8.0.2/lib --bindir=/home/g/.stack/snapshots/x86_64-linux-nopie/lts-9.0/8.0.2/bin --datadir=/home/g/.stack/snapshots/x86_64-linux-nopie/lts-9.0/8.0.2/share --libexecdir=/home/g/.stack/snapshots/x86_64-linux-nopie/lts-9.0/8.0.2/libexec --sysconfdir=/home/g/.stack/snapshots/x86_64-linux-nopie/lts-9.0/8.0.2/etc --docdir=/home/g/.stack/snapshots/x86_64-linux-nopie/lts-9.0/8.0.2/doc/terminfo-0.4.1.0 --htmldir=/home/g/.stack/snapshots/x86_64-linux-nopie/lts-9.0/8.0.2/doc/terminfo-0.4.1.0 --haddockdir=/home/g/.stack/snapshots/x86_64-linux-nopie/lts-9.0/8.0.2/doc/terminfo-0.4.1.0 --dependency=base=base-4.9.1.0
>     Process exited with code: ExitFailure 1
>     Logs have been written to: /home/g/src/haskell/hr/.stack-work/logs/terminfo-0.4.1.0.log
> 
>     [1 of 2] Compiling Main             ( /tmp/stack16564/terminfo-0.4.1.0/Setup.lhs, /tmp/stack16564/terminfo-0.4.1.0/.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/setup/Main.o )
>     [2 of 2] Compiling StackSetupShim   ( /home/g/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /tmp/stack16564/terminfo-0.4.1.0/.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/setup/StackSetupShim.o )
>     Linking /tmp/stack16564/terminfo-0.4.1.0/.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/setup/setup ...
>     Configuring terminfo-0.4.1.0...
>     configure: WARNING: unrecognized options: --with-compiler
>     checking for gcc... /usr/bin/gcc
>     checking whether the C compiler works... yes
>     checking for C compiler default output file name... a.out
>     checking for suffix of executables... 
>     checking whether we are cross compiling... no
>     checking for suffix of object files... o
>     checking whether we are using the GNU C compiler... yes
>     checking whether /usr/bin/gcc accepts -g... yes
>     checking for /usr/bin/gcc option to accept ISO C89... none needed
>     checking for setupterm in -ltinfo... no
>     checking for setupterm in -lncursesw... no
>     checking for setupterm in -lncurses... no
>     checking for setupterm in -lcurses... no
>     configure: error: in `/tmp/stack16564/terminfo-0.4.1.0':
>     configure: error: curses library not found, so this package cannot be built
>     See `config.log' for more details
> Could not install Intero!
> 
> We don't know why it failed. Please read the above output and try
> installing manually. If that doesn't work, report this as a
> problem.
> 
> WHAT TO DO NEXT
> 
> If you don't want to Intero to try installing itself again for
> this project, just keep this buffer around in your Emacs.
> 
> If you'd like to try again next time you try use an Intero
> feature, kill this buffer.
>

**Comment by CarstenKoenig** [comment]
Hi,

you need to have the (n)curses headers installed in your system - on an Ubuntu/Deb based you can get those with

    sudo apt-get install libncurses-dev

I think on most other systems you should look vor `ncurses` / `curses` and `dev` - usually you find it with something like synaptic.

**Comment by gremdrus** [comment]
That was indeed the issue! Thank you so much CarstenKoenig.

**Comment by rhalldearn** [comment]
I think it would also help if this was mentioned on the readme as an installation dependency.

**Comment by PampasGrass** [comment]
It work when I run:
        stack install --resolver lts-6.6 intero-0.1.15
and get an exception.
