### ISSUE TITLE
Emacs freezes while intero waits for nix dependencies to build

### ISSUE THREAD

**Issue by ruhatch** [commercialhaskell/intero#461]
Entering a project with stack nix support enabled just hangs while the dependencies are built. It would be good to get the nix output piped into a buffer and avoid the whole UI freezing.

**Comment by chrisdone** [comment]
Intero doesn't support nix.

**Comment by ruhatch** [comment]
Thanks for responding to this. Can I ask whether you actively do not want intero to support nix or whether you just don't have time? I would be happy to contribute to adding support for nix if it is the latter.

**Comment by acowley** [comment]
@ruhatch I think the ideal here is to not have to include logic that is nix-specific in intero. As a nix user myself, I know exactly the issue you describe, so I can sympathize, but find that entering the project's `nix-shell` before editing after a nixpkgs upgrade is not too onerous to make things unusable.
