### ISSUE TITLE
Inhibit automatic install

### ISSUE THREAD

**Issue by rightfold** [commercialhaskell/intero#464]
I am working on an old project that uses a configuration under which Intero fails to build. As a result, every time I open a Haskell file or await a completion, Intero starts installing (which then fails). Can I disable the automatic install altogether?

**Comment by kRITZCREEK** [comment]
https://github.com/commercialhaskell/intero#whitelistingblacklisting-projects

Does this do what you need?

**Comment by rightfold** [comment]
Sick feature! Thanks!
