### ISSUE TITLE
Intero recompiles all modules on every startup.

### ISSUE THREAD

**Issue by jonathanknowles** [commercialhaskell/intero#465]
I'm attempting to use Intero with a fairly large project of around 250 modules.

One issue that I'm repeatedly running into is the long startup time for an Intero session (several minutes).

It may be that I'm invoking Intero in the wrong way, but no matter how I invoke it, Intero seems to want to **recompile all modules on every startup**. Is there any way to get Intero to reload previously-compiled modules instead of recompiling them every time?

## Reproduction Steps

For simplicity, I'll reproduce this with a smaller project:
```
$ git clone https://github.com/jonathanknowles/distributed-process-experiment
$ cd distributed-process-experiment
```
To start off with, let's build the project:
```
$ stack setup
$ stack build
```
Next, let's build Intero:
```
$ stack build intero
```
Now, let's start Intero, taking care to specify that it should use compiled code, rather than interpreted code:
```
$ stack ghci distributed-process-experiment:lib --with-ghc intero --ghc-options "-fobject-code"
Configuring GHCi with the following packages: distributed-process-experiment
Intero 0.1.20 (GHC 8.0.2)
Type :intro and press enter for an introduction of the standard commands.

[ 1 of 10] Compiling Time             ( /private/jsk/projects/distributed-process-experiment/source/library/Time.hs, /private/jsk/projects/distributed-process-experiment/.stack-work/odir/Time.o )
[ 2 of 10] Compiling Process          ( /private/jsk/projects/distributed-process-experiment/source/library/Process.hs, /private/jsk/projects/distributed-process-experiment/.stack-work/odir/Process.o )
...
[10 of 10] Compiling Startup          ( /private/jsk/projects/distributed-process-experiment/source/library/Startup.hs, /private/jsk/projects/distributed-process-experiment/.stack-work/odir/Startup.o )
Ok, modules loaded: CLI, Config, Context, Master, Message, Pretty, Process, Slave, Startup, Time.
Collecting type info for 10 module(s) ... 
Prelude CLI Config Context Master Message Pretty Process Slave Startup Time> :quit
Leaving GHCi.
```
Intero has recompiled the modules on first run. How about the second run? Let's try again:
```
$ stack ghci distributed-process-experiment:lib --with-ghc intero --ghc-options "-fobject-code"
Configuring GHCi with the following packages: distributed-process-experiment
Intero 0.1.20 (GHC 8.0.2)
Type :intro and press enter for an introduction of the standard commands.

[ 1 of 10] Compiling Time             ( /private/jsk/projects/distributed-process-experiment/source/library/Time.hs, /private/jsk/projects/distributed-process-experiment/.stack-work/odir/Time.o ) [flags changed]
[ 2 of 10] Compiling Process          ( /private/jsk/projects/distributed-process-experiment/source/library/Process.hs, /private/jsk/projects/distributed-process-experiment/.stack-work/odir/Process.o ) [flags changed]
...
[10 of 10] Compiling Startup          ( /private/jsk/projects/distributed-process-experiment/source/library/Startup.hs, /private/jsk/projects/distributed-process-experiment/.stack-work/odir/Startup.o ) [flags changed]
Ok, modules loaded: CLI, Config, Context, Master, Message, Pretty, Process, Slave, Startup, Time.
Collecting type info for 10 module(s) ... 
Prelude CLI Config Context Master Message Pretty Process Slave Startup Time> :quit
Leaving GHCi.
```
On the second run, Intero still recompiles all the modules, claiming `flags changed` for every single module.

## Questions

 1. Is this behaviour by design?
 2. Is there a way to persuade Intero to reload previously-compiled modules, rather than recompiling everything from scratch each time? Ideally, it would be able to detect objects built during the `stack build` phase.

Apologies if I am invoking intero in completely the wrong way, or if I've overlooked something obvious. :)

Thanks in advance!

**Comment by chrisdone** [comment]
This normal and expected. Intero is normally run for long periods of time (e.g. Days) in an Emacs pipe, so restarting is rare but expensive. On a 200-300 module project, that hurts, indeed. But it just takes a minute or two.
