### ISSUE TITLE
Could not start Intero : Invalid package ID: "array-0.5.1.1 base-4.9.1.0 binary-0.8.3.0 bytestring-0.10.8.1"

### ISSUE THREAD

**Issue by tdox** [commercialhaskell/intero#467]
using lts-9.2.
stack version:
Version 1.5.1, Git revision 2fbc3e93121b97d41f125b3aba9e9f2d8c62888f x86_64 hpack-0.18.1

$ stack new intero-bug simple
creates Main.hs
Opening Main.hs in emacs results in 

-----------------------------------------------------------------------------
Intero is not installed in the Stack environment.

Installing intero-0.1.21 automatically ...

Invalid package ID: "array-0.5.1.1 base-4.9.1.0 binary-0.8.3.0 bytestring-0.10.8.1"
Could not install Intero!

We don't know why it failed. Please read the above output and try
installing manually. If that doesn't work, report this as a
problem.
----------------------------------------------------------------

I see that gcharnock added a similar comment to closed issue #252

**Comment by chrisdone** [comment]
Thanks, closing in favor of the original issue which has more context.
