### ISSUE TITLE
Keybinding for :r in Intero

### ISSUE THREAD

**Issue by saurabhnanda** [commercialhaskell/intero#474]
When using `stack ghci` on the terminal, I notice the following behaviour:

*  `:l` to loads a module, and compiles all the dependencies of that module first. 
* If I hit `:l` again, it loads/compiles **everything** all over again.
* However, if I hit `:r` it only compiles the final module.

What is the equivalent of `:r` in Intero? I have a workaround which involves doing `:set -fobject-code` in the intero REPL, but it exhibits some weird behaviour about what modules are in-scope in the REPL.

**Comment by chrisdone** [comment]
I think for a given REPL we could have a local variable of "last loaded module". If the last loaded module is the same as the one currently requested, we could run `:r` instead of `:l`. 

I don't *think* there are any problems with that.

**Comment by chrisdone** [comment]
There *might* be problems if the module wasn't successfully loaded -- I suspect GHCi won't do a ":reload" without a successful ":load". We'd need to confirm that first.

**Comment by khanage** [comment]
Just testing this out - if I load a module with a parse error, `:r` ghci will try to reload that same module, so no issue there.

Looking at [the elisp here](https://github.com/commercialhaskell/intero/blob/2d3c04ce523674e79f9339189a79e6841e1fa587/elisp/intero.el#L1115) looks like it would be simplest to do on a per-frontend basis (as the string ":load File.hs" gets passed directly to the backend?

**Comment by kryoxide** [comment]
I think the merged pull request #498 resolves this issue?
