### ISSUE TITLE
Passing flags to stack

### ISSUE THREAD

**Issue by capitanbatata** [commercialhaskell/intero#478]
The project I'm working on takes 1.5 hours to compile, which is unacceptable during development. For this reason I use `stack` with the `--fast` flag. Is there a way to set this up in Intero?

**Comment by joehillen** [comment]
How long does it take for `stack ghci` to finish building? intero is mostly an interface in front of ghci

All `--fast` does is pass `-O0` to ghc which is not a valid option for ghci.

**Comment by mgsloan** [comment]
Yeah, `--fast` isn't going to make a difference, I believe that intero still passes `--no-build`, so it will not build anything, even if dependencies are missing.

**Comment by capitanbatata** [comment]
Oh, I didn't know about that. The [project](https://github.com/TorXakis/TorXakis/) contains some Happy code, which uses untyped attribute grammars, which makes the compilation time extremely slow. Building with `stack ghci` takes about 2 minutes.

Indeed it seems that the "--no-build" flag is being passed by default:

```elisp
(defcustom intero-repl-no-build
  t
  "Pass --no-build when starting the repl.
This causes it to skip building the target."
  :group 'intero
  :type 'boolean)
```

So I guess for now the best thing I can do is go for a coffee every-time I touch code that the parser depends on :)
