### ISSUE TITLE
Installation doesn't honour the contents of stack.yaml.

### ISSUE THREAD

**Issue by seanparsons** [commercialhaskell/intero#479]
With a checkout of the repo, doing a `stack build` will correctly pull in the nix packages specified. However a `stack build intero` will get a bundle that doesn't include `stack.yaml` (I checked with `cabal get intero`) and then fails because ncurses isn't available to it.

**Comment by chrisdone** [comment]
That's just how stack works.

**Comment by mgsloan** [comment]
True, though, we may indeed want to install intero based on a configuration that is included with the package - see https://github.com/commercialhaskell/intero/issues/324

**Comment by seanparsons** [comment]
The problem is that because intero works by triggering an install itself if you're on nix the compile will just fail.

**Comment by chrisdone** [comment]
Intero doesn't support nix.

**Comment by acowley** [comment]
@seanparsons The way I deal with this is to always use a `shell.nix` file. You can put `ncurses` and `zlib` in the `buildInputs` there, and `intero` will build.
