### ISSUE TITLE
Removing redundant constructor imports breaks syntax

### ISSUE THREAD

**Issue by koterpillar** [commercialhaskell/intero#480]
On this file:

```haskell
{-# OPTIONS_GHC -Wall #-}

import Data.Maybe (Maybe (..), fromMaybe)

main :: IO ()
main = return $ fromMaybe undefined undefined
```

intero displays a suggestion that the `Maybe` import is redundant. However, applying the suggestion leaves the import line as:

```
import Data. ( (..), fromMaybe)
```

This is invalid - the module name has been removed, but the `(..)` has not.

**Comment by chrisdone** [comment]
Good catch.
