### ISSUE TITLE
Report when a dependency doesn't compile

### ISSUE THREAD

**Issue by reactormonk** [commercialhaskell/intero#481]
I've refactored some code in my `Types.hs`, which broke module `B`, which my module `A` was dependent on. I was puzzled on why intero wouldn't report a status on `B` - when I fixed `A`, it compiled again. So it would be nice to have intero report an error on the import which imports a failing module.

**Comment by purcell** [comment]
This is really a limitation of Flycheck, for which Chris submitted a large PR that never got merged. It got picked up later and refreshed, but still failed to get merged.

**Comment by purcell** [comment]
Now fixed upstream in Flycheck via https://github.com/flycheck/flycheck/pull/1427, w00t!
