### ISSUE TITLE
how to turn verbosity on ? 

### ISSUE THREAD

**Issue by nrolland** [commercialhaskell/intero#484]
I have an error saying 

> Failed to load interface for ‘Intro1’
> Use -v to see a list of the files searched for.

Pasting the command used for intero in a shell, there is no error load interfaces.

Is there a way to instruct emacs intero to launch stack ghci with the verbose option to see what is going on ?

**Comment by chrisdone** [comment]
You can run `M-x intero-toggle-debug` to see everything sent/received from the process.
