### ISSUE TITLE
Go to definition should work even when there are type errors / scope errors

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/intero#485]
Currently, if I type an expression that is a type error, go-to-definition does not seem to work on the expression.  It does work on other symbols in the code, though, I think using older info.

It should be possible to do something similar to `-fdefer-type-errors` and `-fdefer-out-of-scope-variables` to still get this info, perhaps leveraging these mechanisms.

Ideally this would apply to other queries too, like type information.

**Comment by chrisdone** [comment]
I've recently merged `-fdefer-type-errors` (which seems to imply also the latter). https://github.com/commercialhaskell/intero/pull/495

This lets type and goto definition information still work much more of the time. There's a speed hit, but I feel that the increase in functionality is worth it.
