### ISSUE TITLE
Do not install intero automatically

### ISSUE THREAD

**Issue by corpix** [commercialhaskell/intero#486]
When I am opening any `.hs` file in Emacs `intero-mode` is applied and it tries to install `intero` executable, but this is not what I am mean usually, I mean "just open this file", not "open this file and install intero for me".

Automatic installation is failing for me most of time because I don't have ncurses or some other dependencies. In my opinion installation should be manual(with system package manager/stack/nix/...), `intero-mode` should show me an error if `intero` executable is not installed on my system, not more.

**Comment by acowley** [comment]
I use and recommend `intero-whitelist` for this purpose. Set it to the list of primary projects where you want to use `intero`.

**Comment by corpix** [comment]
Whitelisting is good, but I don't thing it will help to solve the issue.

I do want to use intero for all my projects, but I don't want it to be installed automatically every time I open the `.hs` files because:
- when I open a file with a source code I don't expect anything to be installed automatically
- in some environments I don't need intero(I am comfortable with ability to just read the code without intero, but I do want use my emacs configuration)

**Comment by mgsloan** [comment]
Agreed. I think the ideal solution here would be:

1. Continue to automatically install intero, but make it necessary far less frequently - https://github.com/commercialhaskell/intero/issues/324

2. Ideally, do it async and not block using the buffer.  I do not know enough emacs / elisp to evaluate the difficulty of doing this.

**Comment by tonyday567** [comment]
How about:

3. Do not automatically install intero, without confirmation.

For my use case whitelisting is not ideal - I have like 150 active projects, spin new ones up every day etc, and keeping track would slow me down.  I'd like to use intero almost all of the time, except when it isn't installed yet, which usually means I have the wrong ghc, or opened a random .hs etc

**Comment by mgsloan** [comment]
Yeah, I can buy that being a good thing.  Might also have an option there be to automatically add it to the blacklist

**Comment by chrisdone** [comment]
I'm not going to change this behavior. If you want manual install, there are half a dozen other packages that provide that experience.

**Comment by corpix** [comment]
Could you please tell me the names of this packages? I have searched on Melpa by keyword `intero` and found nothing but `intero` package.
