### ISSUE TITLE
Intero checking ~/.ghci ownership?

### ISSUE THREAD

**Issue by michalrus** [commercialhaskell/intero#488]
When running Intero, I’m getting the following warning:

```
WARNING: /nix/store/ih7lz6ndx5qhwnxx4a9jywsjhjd45a1h-dotfiles/michalrus/base/.ghci is owned by someone else, IGNORING!
```

That same file works with regular GHCi.

Why is that check useful?

**Comment by michalrus** [comment]
Oh:

```
-- NOTE: We only read .ghci files if they are owned by the current user,
-- and aren't world writable.  Otherwise, we could be accidentally
-- running code planted by a malicious third party.

-- Furthermore, We only read ./.ghci if . is owned by the current user
-- and isn't writable by anyone else.  I think this is sufficient: we
-- don't need to check .. and ../.. etc. because "."  always refers to
-- the same directory while a process is running.
```

https://github.com/commercialhaskell/intero/blob/3865aad923559bee140eaede20c3510890979930/src/InteractiveUI.hs#L742-L749

Could `root` be excluded from that check?

**Comment by joehillen** [comment]
It's weird that intero has this kind of check when almost any dotfile could have the same kind of security implications. 

Why does intero need to take on this responsibility?

**Comment by mgsloan** [comment]
This check comes from the ghci source code (intero is essentially a fork).  Are you using docker in your stack config?  Could cause the difference in user.

**Comment by michalrus** [comment]
Well, pure GHCi (at least 8.0.2) doesn’t have this behavior:

```
% ghci
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /nix/store/9q6wr10zcbg210hmzb7gxr5ll31a616g-dotfiles/michalrus/base/.ghci
λ> ^D
Leaving GHCi.

% ls -l /nix/store/9q6wr10zcbg210hmzb7gxr5ll31a616g-dotfiles/michalrus/base/.ghci
-r--r--r-- 5 root root 177 Jan  1  1970 /nix/store/9q6wr10zcbg210hmzb7gxr5ll31a616g-dotfiles/michalrus/base/.ghci

%
```

I’m keeping dotfiles in `/nix/store` on NixOS, which should be quite a popular practice (on NixOS), and:
> * `/nix/store` is mounted read-only, all files in there are `-r--r--r--`, and owned by root,

@mgsloan I see @chrisdone in git-blame of that fragment, in an initial commit (2be50d0bb5754c095fcf6d008a7251ddc1a8a275), so it’s not particularly helpful info, as the code seems copied and recommitted here instead of forked/merged w/ history.

But if you look at how this works in current GHCi:

https://github.com/ghc/ghc/blob/feac0a3bc69fd376231aa3c83d031c131156ddb9/ghc/GHCi/UI.hs#L672-L690

… they’re just checking if that file is writable by someone else, the owner check is gone (or was it there in the first place? Needs some digging).

So:

* If Intero is a fork, and that ownership check got indeed removed in upstream, why wasn’t this upstream change merged back to Intero?

* And if it’s pure Intero’s addition, why is it useful (considering upstream doesn’t have it)?

**Comment by mgsloan** [comment]
Ah, interesting!

> If Intero is a fork, and that ownership check got indeed removed in upstream, why wasn’t this upstream change merged back to Intero? (This is a broader question, I guess: are upstream changes being merged back to Intero?)

Guessing this is what happened.  Intero has lots of modifications - it takes a different approach than ghci-ng, which carefully tried to keep the diff minimal.  So it's hard to directly merge upstream changes.  There should be a process of looking at all changes to GHCI's implementation and merging anything that matters back to intero.

**Comment by chrisdone** [comment]
I'm not merging upstream GHCi changes into Intero. Feel free to open a PR to remove this behavior, I don't think it's particularly useful behavior.
