### ISSUE TITLE
Dependency management

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/intero#49]
There're a few factors for this:
- Munging the .cabal file to add the dependency to the right stanza.
- Automatically setting `-package foo` in the running `intero` to avoid restarts.
- Possibly support finding unused dependencies via stack.

Related to #48.

**Comment by mgsloan** [comment]
> Munging the .cabal file to add the dependency to the right stanza.

Yup, textual .cabal file munging makes sense to me.

In the case that the user is using `hpack`, I think we could potentially have a more generic approach to package refactoring, built atop a yaml refactorer (which would also be useful for stack.yaml).  See https://github.com/commercialhaskell/stack/issues/1933#issuecomment-199534766

> Automatically setting -package foo in the running intero to avoid restarts.

Related to https://github.com/commercialhaskell/intero/issues/39 - being able to switch which components are loaded also implies automatic setting of `-package foo`.

> Possibly support finding unused dependencies via stack.

Yeah, I think maybe ghci still outputs `ddump-hi` files if the appropriate flags are passed to it.  We could add a stack command that just checks for unused deps.  Alternatively, stack could get linked in (which is something we might want to do for a number of reasons).

**Comment by chrisdone** [comment]
I think I'm going to close this with the intention of eventually merging with haskell-ide-engine, restricting the scope of intero to merely doing what it does presently but with bugs fixed.

**Comment by mwotton** [comment]
@chrisdone apologies if you've written this up elsewhere, i couldn't find it - would the eventual split be merging useful backend stuff into haskell-ide-engine and maintaining intero as an opinionated LSP wrapper?

**Comment by chrisdone** [comment]
My present goal is to mercilessly prune away feature issues that I’m evidently never going to work on, and then smooth over any remaining bugs, bringing Intero to a “move slowly and break nothing” steady maintenance mode.

Ideally, I’d also get time to implement a test suite for the Emacs side of things.

I intend to sit down and try out HIE and evaluate everything. I’m not optimistic that it’s a drop in replacement merely because I’ve looked at Emacs’s support for LSP and it’s a bit fresh, in addition to there being a non zero diff between feature sets of that and Intero. Obviously, assuming stack and nothing else has also made a lot of things easier too which HIE probably has to make up for with configuration or guess work.

In any case I’ll do a write-up on my findings.

In the ideal case if HIE shapes up, I’d plan a smooth migration path from Intero to HIE. If it doesn’t shape up then I’ll have to open a discussion with the HIE maintainers.
