### ISSUE TITLE
How to upgrade intero?

### ISSUE THREAD

**Issue by saurabhnanda** [commercialhaskell/intero#490]
Sorry about the dumb question, but how does one upgrade intero to the latest stable version? `intero --help` doesn't give me anything, neither does `stack install intero` upgrade to the latest version.

**Comment by tonyday567** [comment]
- delete/rename your old intero executable, which will be in `stack path --local-bin`
- check that your ~/.stack/global-project/stack.yaml has a modern resolver (lts-9.12 as at time of writing)
- `stack install intero`
- upgrade the intero emacs package via your fave package management method

**Comment by mgsloan** [comment]
Ah, yeah, that isn't a very good upgrade mechanism, huh?  Maybe it does already, but the emacs side of things should check that intero is as new as it should be, and if not, reinstall the new one.

**Comment by tristangreeno** [comment]
I think it's a good upgrade process to avoid surprises: I'm not entirely certain, but I don't think new intero versions are backwards compatible with older GHC versions. I could be wrong, though. Please correct me if I am.

**Comment by mgsloan** [comment]
I believe that intero works with 7.8.4 and up.  Check out the CI: https://travis-ci.org/commercialhaskell/intero

Along with various other niceties, this is one of the big differences between intero and the ghci in the GHC tree - it supports multiple GHC versions.

**Comment by chrisdone** [comment]
@saurabhnanda The Intero version is always updated via Emacs, because the Emacs and the Intero executable have to be kept in sync. You should never have to run a commandline tool to update it.
