### ISSUE TITLE
Documentation request: Intero vs GHCi 

### ISSUE THREAD

**Issue by parsonsmatt** [commercialhaskell/intero#492]
GHCi 8.0.2 has `:type-at` and `:loc-at` support, which are two of the big things that motivated me to use Intero. Given that, why should one use Intero over GHCi?

Motivation: I maintain a plugin for intero and neovim, and we've been discussing getting stock GHCi support. Maintaining two backends makes sense if intero has advantages over GHCi, but if GHCi can handle everything Intero can do now, I'd prefer to simplify the project.

Thanks! :smile:

**Comment by chrisdone** [comment]
GHCi merged in some old things from ghci-ng that I wrote. I've since added to or fixed bugs in Intero, and they are backported to 7.8.4. I haven't been following them much, though.
