### ISSUE TITLE
intero-mode.el and ghc-8.2.2

### ISSUE THREAD

**Issue by sebeaumont** [commercialhaskell/intero#502]
Seems to be an issue with colorized output from ghc -- not sure if defaults have changed since 8.2.1 but I found I needed to add ```(process-send-string process ":set -fdiagnostics-color=never\n")``` to ```intero-start-process-in-buffer``` to avoid a load of spurious messages. Not sure if this is a proper fix but it's made life bearable again.

BTW is there anyway to see the log of interactions between emacs/intero/ghc for future debugs?

Not sure what would happen on older versions of ghc that dont support that flag. Don't really care personally now that 8.2.2 is  LTS-10 compiler.

**Comment by chrisdone** [comment]
To see the log you can run `M-x intero-toggle-debug`.

I'm not sure why yours would output color. But I can add the flag as it should have benign effects.
