### ISSUE TITLE
Modules with the same name from different components confuse intero

### ISSUE THREAD

**Issue by koterpillar** [commercialhaskell/intero#503]
When two modules with identical names exist in two components (e.g. executables), intero always chooses one when checking either component's files, resulting in spurious errors.

### How to reproduce

* Have a project with two executables, each with a `Main` and `Foo` modules.

`a/Main.hs`:
```haskell
import Foo
main = one
```
`a/Foo.hs`:
```haskell
one = pure ()
```
`b/Main.hs`:
```haskell
import Foo
main = two
```
`b/Foo.hs`:
```haskell
two = pure ()
```

* Check both `Main` modules via Intero (tested through Spacemacs).

### Expected results

Both modules show no errors.

### Actual results

One of the `Main` modules complains about `one` or `two` not known.

### Workaround

Deselect one of the components when choosing Intero targets.

**Comment by mgsloan** [comment]
Unfortunately, resolving this would require some pretty heavy changes to GHC.  I think those changes are worth doing, though.
