### ISSUE TITLE
Strange Type-At-Selection behaviour

### ISSUE THREAD

**Issue by BillyBadBoy** [commercialhaskell/intero#506]
I'm a Haskell newbie so maybe I've got this all wrong - but anyway here goes:

I define this function in emacs:

```
f :: Monoid t => [t] -> t 
f = foldr (<>) mempty
```
When I put the cursor over mempty and do `C-c C-t` it says `mempty :: [t] -> t` which is wrong isn't it ?

Then I added some redundant brackets:
```
f :: Monoid t => [t] -> t 
f = foldr (<>) (mempty)
```
Now when I put the cursor over mempty and do `C-c C-t` it says `mempty :: t`.

Is this a bug?

**Comment by BillyBadBoy** [comment]
On further investigation it seems that the  problem relates to the hasklig font that I was using (along with the script from https://github.com/i-tu/Hasklig/issues/84). If I go back to Inconsolata-g then everything works as it should do.

It's a  pity - I thought the font ligatures were really cool.

**Comment by acowley** [comment]
I had irregular slowdowns in emacs for a while, and eventually tracked it down to the Hæk font’s ligatures. I guess they explore some not so great corners of emacs.

In this case, I guess intero is getting the wrong column. Is the type reported still that of the whole expression if you put point one character into the `mempty` token?

**Comment by BillyBadBoy** [comment]
>> Is the type reported still that of the whole expression if you put point one character into the mempty token? 

It gets it wrong wherever I put the cursor. 

Anyway, it's not the end of the world - I can live without ligatures.
