### ISSUE TITLE
Support intero-mode toggle per project via .dir-locals.el

### ISSUE THREAD

**Issue by ozataman** [commercialhaskell/intero#508]
Short summary: A code block such as the following in the `.dir-locals.el` file fails to properly wire intero. I have also failed to get it properly working after having tried a number of variations on the concept. For some reason (probably a race condition of boot sequencing issue), several of the keybinds get overriden by the haskell interactive mode, even through intero properly loads (e.g. flycheck works).

```elisp
((nil
  (eval ignore-errors
        (add-hook 'haskell-mode-hook 'intero-global-mode)))
  ))
```

Could we work this out so that it's possible to enable intero on a per-project basis via `.dir-locals.el` or a similar file-based mechanism (without explicitly working with the whitelist)? I do think there would be people out there who would find this pattern a useful alternative.

Motivation: As far as I'm aware, the current smoothest way to operate intero is through the `intero-global-mode` and optional use of the blacklist to disable projects known apriori to cause problems. This, however, also gets intero to eagerly try to boot upon visiting any other not explicitly blacklisted project. In an environment with 10s or 100s projects, where it's common to visit an old project just to take a look at a few things, this becomes a real and frequent pain point. Having a project-local, "right there" toggle would be really nice.

While initiating a `stack build` on every old project momentarily visited is already wasteful (HDD space, battery drain, etc.), the issue is worse because emacs pretty much freezes up while intero/stack try to get the project up and running. Further, if intero boot fails, it appears to keep retrying, freezing cursor frequently as it touches various names in the file.

**Comment by ozataman** [comment]
Update: The following appears to work, so perhaps this is already possible. Still, I'd suggest advertising this alternative approach on standard documentation as well. I'll confirm after working with it some more.

```elisp
((haskell-mode
  (eval ignore-errors
        (intero-mode t))))
```

**Comment by purcell** [comment]
I haven't tried this, but you could add `/` to `intero-blacklist`, then in your `.dir-locals`, use `(eval (add-to-list 'intero-whitelist default-directory))`.

Of course, after a while your new projects will become old-projects, which will then have intero enabled via their `.dir-locals.el` -- what you really want is a command to enable `intero` for the current project only. You might consider try something like this:
```el
 (defun intero-enable-here ()
  (interactive)
  (let ((root (locate-dominating-file default-directory "stack.yaml")))
    (add-to-list 'intero-whitelist root)
    (dolist (buf (buffer-list))
      (with-current-buffer buf
        (when (and (derived-mode-p 'haskell-mode)
                   (string-prefix-p root default-directory))
          (intero-mode))))))
```
You'd still blacklist `"/"` and leave `intero-global-mode` enabled, so that new buffers you open in the current explicitly-enabled project will have `intero` enabled.

**Comment by ozataman** [comment]
I've found white/blacklist based management a little onerous. Here's how I'm handling this as of late:

1) Disable `intero-global-mode`
2) Make a `.dir-locals` file containing the following bit in every active project where I'd like intero automatically triggered on every file:

```
((haskell-mode
  (eval ignore-errors
        (intero-mode t))))
```

**Comment by chrisdone** [comment]
I guess if you have something working I'll close.
