### ISSUE TITLE
monospaced font not lining up correctly

### ISSUE THREAD

**Issue by BillyBadBoy** [commercialhaskell/intero#509]
Monospaced font is not lining up correctly in emacs.

For example, when I enter this function the 2 zeroes do not line up exactly:

```
xxxx |False=0
     |True =0
```
The 'xxxx' and the first '|' are rendered in a slightly bigger font than the rest of the text (and in a different color).

For comparison if I re-enter this function like this (without a space between 'xxxx' and '|'):

```
xxxx|False=0
    |True =0
```
then everything lines up. Note that, in this case, the 'xxxx' and the first '|' are rendered the using the same size font as the rest.

It seems that top-level function names are rendered in a bigger font than everything else (including nested functions) and this causes the misalignment.

How can I change my font setup to fix this ?

**Comment by BillyBadBoy** [comment]
I was being stupid.

It turns out that the theme I'm using, manoj-dark, uses a slightly bigger font for function names. (Why any programmer would want this is beyond me.) But anyway, editing the theme to use the same font size fixes my problem.

**Comment by purcell** [comment]
> It turns out that the theme I'm using, manoj-dark, uses a slightly bigger font for function names. (Why any programmer would want this is beyond me.) But anyway, editing the theme to use the same font size fixes my problem.

Yeah, it's not good practice to override people's font families or sizes, but some theme authors do it anyway.
