### ISSUE TITLE
Emacs mode underlines typed holes as errors even with -fdefer-typed-holes on

### ISSUE THREAD

**Issue by enolan** [commercialhaskell/intero#510]
The Emacs mode is underlining holes in red as though they were errors, regardless of whether `-fdefer-typed-holes` is set in the project or file options. E.g. this file:
```haskell
foo = _
```
Shows the red squiggle underline under the `_`, correctly. If you try to load it in GHCi, or compile it, you get:
```
/home/enolan/test.hs:1:7: error:
    • Found hole: _ :: t
      Where: ‘t’ is a rigid type variable bound by
               the inferred type of foo :: t at /home/enolan/test.hs:1:1
[snip]
```

But if I add the flag:
```haskell
{-# OPTIONS_GHC -fdefer-typed-holes #-}
foo = _
```

The `_` is still marked as an error in Emacs, but GHCi will load it and print a warning instead:
```
/home/enolan/test.hs:2:7: warning: [-Wtyped-holes]
    • Found hole: _ :: t
      Where: ‘t’ is a rigid type variable bound by
               the inferred type of foo :: t at /home/enolan/test.hs:2:1
```

[According to the GHC manual](https://downloads.haskell.org/~ghc/8.0.2/docs/html/users_guide/using-warnings.html#ghc-flag--fdefer-type-errors), `-fdefer-type-errors` implies `-fdefer-typed-holes`, so it's effectively always on in Intero, and there's elisp code to turn the warning messages back into errors [here](https://github.com/commercialhaskell/intero/blob/master/elisp/intero.el#L748-L754), which is what you want if Intero set the option, but confusing if the user set it.

**Comment by chrisdone** [comment]
Intero always sets this option on start-up. What behavior are you looking for?

**Comment by mpardalos** [comment]
I'm having the same issue. I'm trying to make intero show the holes as just warnings. I've set -fdefer-typed-holes in .cabal, with a pragma, and in `intero-extra-ghc-options` but it keeps showing up as an error.
