### ISSUE TITLE
applying haskell-hlint suggestion

### ISSUE THREAD

**Issue by mut0u** [commercialhaskell/intero#511]
This is my demo code like this
```
helloFunction x = (("hello" ++ " ") ++ x)

```
and the hlint show the  suggestion is

```
Redundant bracket
Found:
  (("hello" ++ " ") ++ x)
Why not:
  ("hello" ++ " ") ++ x

```

I hope that `intero-apply-suggestions` can apply this suggestion from hlint

**Comment by purcell** [comment]
`intero` doesn't run `hlint` itself, so it's unlikely we'd add code here for applying `hlint`: you probably have `flycheck-hlint` chained after Intero's checker, e.g. if you're using my Emacs config, but the two checkers are quite separate.

**Comment by chrisdone** [comment]
Won't be adding this.
