### ISSUE TITLE
How do I set the intero blacklist / whitelist?

### ISSUE THREAD

**Issue by chrissound** [commercialhaskell/intero#513]
What code do I need to set within my emacs config? It's not particularly clear to a non elisper like myself.

**Comment by acowley** [comment]
If you’re using `use-package`, this would go in a `:config` section,

`(setq intero-whitelist '("~/Projects/MyHaskellProject" "~/Projects/OtherProject"))`

**Comment by chrissound** [comment]
I'm using spacemacs and I'm setting a blacklist with:
`(setq intero-blacklist '("/home/chris/Projects/Haskell/LearningHaskellPlaygorund"))`
this is within `(defun dotspacemacs/user-config ()..`

However when opening a file within that directory I'm still getting intero trying to startup and it ends up failing with the below *. Quite strangely `LambdaCms` is another directory / project (not present in the blacklist).

Is there is a way to debug this further? If I do a `describe-variable`, `intero-blacklist` I see:
```
intero-blacklist is a variable defined in ‘intero.el’.
Its value is ("/home/chris/Projects/Haskell/LearningHaskellPlaygorund")

Original value was nil

```

&#42;
```

Warning: Some targets (LambdaCms) are
         not local packages, and so
         cannot be directly loaded. In
         future versions of stack, this
         might be supported - see
         https://github.com/commercialhaskell/stack/issues/1441
         . It can still be useful to
         specify these, as they will be
         passed to ghci via -package
         flags.

Warning: No local targets specified, so
         ghci will not use any options
         from your package.yaml /
         *.cabal files.
         
         Potential ways to resolve this:
         * If you want to use the
           package.yaml / *.cabal
           package in the current
           directory, use stack init to
           create a new stack.yaml.
         * Add to the 'packages' field
           of /home/chris/stack.yaml
         
Configuring GHCi with the following packages: 
Intero 0.1.24 (GHC 8.0.2)
Type :intro and press enter for an introduction of the standard commands.

<command line>: cannot satisfy -package LambdaCms
    (use -v for more information)

---

This is the buffer where Emacs talks to intero. It's normally hidden,
but a problem occcured.

TROUBLESHOOTING

It may be obvious if there is some text above this message
indicating a problem.

If you do not wish to use Intero for some projects, see
https://github.com/commercialhaskell/intero#whitelistingblacklisting-projects

The process ended. Here is the reason that Emacs gives us:

  exited abnormally with code 1

For troubleshooting purposes, here are the arguments used to launch intero:

  stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-load --ghci-options -ignore-dot-ghci --ghci-options -odir=/home/chris/.stack-work/intero/intero72681Nc --ghci-options -hidir=/home/chris/.stack-work/intero/intero72681Nc LambdaCms

It's worth checking that the correct stack executable is being
found on your path, or has been set via
`intero-stack-executable'.  The executable being used now is:

  /usr/bin/stack

WHAT TO DO NEXT

If you fixed the problem, just kill this buffer, Intero will make
a fresh one and attempt to start the process automatically as
soon as you start editing code again.

If you are unable to fix the problem, just leave this buffer
around in Emacs and Intero will not attempt to start the process
anymore.

You can always run M-x intero-restart to make it try again.
```

**Comment by acowley** [comment]
Perhaps `intero` is finding the wrong `stack.yaml`? Does one that mentions `LambdaCms` exist up the directory tree from `/home/chris/Projects/Haskell/LearningHaskellPlaygorund`?

**Comment by chrissound** [comment]
Hmm no it exists in `/home/chris/Haskell/LambaCms/stack.yaml`. Just to test I tried renaming that file to stack2.yaml and get the same behaviour.

**Comment by jonascarpay** [comment]
just to be sure; there's a typo in `LearningHaskellPlaygorund`, is that also the name of the actual directory?

**Comment by chrissound** [comment]
Sorry for the confusion, although there is a typo in the 'word' it is the actual directory name.

It still seems to be picking up the (completely unrelated?) 'intero:backend:LambdaCms' in that directory for some strange reason.

**Comment by chrissound** [comment]
I think I figured this out! I must have mistakenly 'copied' the contents of that directory `~/Haskell/LambdaCms` into ~/Haskell. I had a `LambdaCms.cabal` file within `~/Haskell`, as soon as I deleted this - it seems to be worked correctly.
