### ISSUE TITLE
mapcan requires cl at runtime

### ISSUE THREAD

**Issue by ssmolkin1** [commercialhaskell/intero#520]
When I try to open a file in `intero-mode`, I get this error: `Symbol's function definition is void: mapcan`, and `intero` doesn't work. If I recompile `intero.el`, I get a warning that `mapcan` requires `cl` at runtime.  If I add `(require 'cl)` to my `init.el`, `intero` boots up and works just fine. However, I believe that requiring cl at runtime is not recommended. That said, if there's no way to work around this, then I think `(require 'cl)` should be added to `intero.el` so that it works out the box? Or am I the only one experiencing this issue?

**Comment by sergv** [comment]
@ssmolkin1  This should be fixed with commit 47e0daab98e25807f72fde5b5dbae1f4bf18ad12. Perhaps you're not using the latest version.

**Comment by ssmolkin1** [comment]
Hmm... odd, I installed from MELPA using `M-x package-install`, so not sure how that happened... but now I've reinstalled and have a version using `cl-mapcan` instead of `mapcan`. Thanks @sergv !
