### ISSUE TITLE
RFC: hole filling

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/intero#524]
I've implemented a working hole filler on a branch in the `intero` executable. The motivation is to fill in functions that are obvious from the types, or that you know exists but you can't remember the name exactly, or you don't feel like typing it. 

This means that you can write code like this:

```haskell
import qualified Data.Map.Strict as M
import           Data.Generics as K
main :: IO ()
main = _ (M.insert 'a' 'b' _)
```
And run `:fill Demo 4` (fill in the module Demo the declaration on line 3) and get:

```haskell
Completion: print, mempty
Completion: print, K.empty
Completion: print, M.empty
Completion: print, undefined
Completion: mempty, mempty
Completion: mempty, K.empty
-- etc.
```

All these completions are well-typed and work together. Something simpler:

``` haskell
main :: IO ()
main = putStrLn (_ 123)
```
```
Completion: show
Completion: mempty
Completion: undefined
```
An example from within the source that provides this feature:

```haskell
    unambiguous grelt = null conflicts
      where
        conflicts =
          filter
            greltUnqualified
            (filter
               (/= grelt)
               (lookupGlobalRdrEnv gre (_ (gre_name grelt))))
```
```haskell
Completion: getOccName
Completion: occName
Completion: nameOccName
Completion: Data.Generics.empty
Completion: undefined
Completion: errorBadArgument
Completion: errorMissingArgument
Completion: errorShortFormat
```

I'm wondering how to implement a UI for this in Emacs.

*  One option is to just re-use the suggestions system of Intero, listing all the combinations: x,y,z, x,y,c, x,k,m etc. 
* Another would be to show an overlay on the first hole e.g. `[print]` and then you can somehow UI-toggle other options. Upon committing to one choice from that hole, it moves onto the next one. That permits you to interactively narrow down things if you like. 
* Just show one hole completion at a time in Intero's suggestions system.
* With a keybinding, manually trigger company-mode to present a list on the first hole. And repeat. I kind of like this idea. We could also make simply `_` trigger company-mode in this special way. If I can just figure out how to replace the `_` hole entirely after choosing a choice, this might be ideal!

Completion for one hole with a big set of imports (e.g. lots of GHC imports) with 5K~ symbols takes around 200ms. For more holes, it can explode to 10 seconds. So it may be best to go one hole at a time.

Any input from Intero users welcome.

**Comment by david-christiansen** [comment]
I don't know whether Company can give a good interface for something like this, but if it can, it might be good with a Company keybinding.

I would prefer that, if Company doesn't do the trick, intero would just call something like `completing-read` with the various completion sets. On my system, that'd give a nice Helm popup.

Are there any plans for holes with names and this interface? E.g. if I wrote:

``_thing `mappend` _otherThing``

it would be nice to get suggestions like:
 * `_thing = [], _otherThing = []`
 * `_thing = 0, _otherThing = 0`
 * ...

Is this going to be backported into ghci proper? It seems like it would be useful in many contexts other than Emacs.

**Comment by chrisdone** [comment]
> Are there any plans for holes with names and this interface? E.g. if I wrote:
> 
> _thing `mappend` _otherThing

Possibly. I think that's something Emacs can handle with overlays too. For now I don't assign any meaning to hole strings. 

Though, I had been imagining using it to guide the completion process, e.g. writing `_type` could be a really handy way to guide completion to the much longer `substitutionType` (field accessor); so you avoid writing the prefix. That's one thing I really dislike doing in Haskell, so this would make that much more convenient. E.g. 
```haskell
(sum .
 map (typeSpecificity . _) .
 declarationCompletionSubstitutions)
```

Is able to complete to `substitutionType` in 600ms. Using the string `_type` would help it be immediate. I think people avoid having descriptive record field names because typing them is such a PITA. This could mitigate that.

> Is this going to be backported into ghci proper? It seems like it would be useful in many contexts other than Emacs.

It's in [a self-contained module](https://github.com/commercialhaskell/intero/blob/code-completion/src/Completion.hs), so ghc-mod, ghci and haskell-ide-engine may all use it trivially. It's a drop-in module.

**Comment by parsonsmatt** [comment]
It'd be really *neat* if you could `tab` over to a hole, choose a selection, and have the other holes refined from that. No idea how feasible that would be, though.

**Comment by chrisdone** [comment]
I actually already do have some tabbing to `undefined` and `_` if made by structured-haskell-mode. I could copy that code over. Intero could report on an idle timer where the holes are.

**Comment by AnthonyJacob** [comment]
Amazing! This is just a little step from providing fully type aware auto completion...

**Comment by edkolev** [comment]
I think a completing-read would suffice - the UI will then be handled by ido/helm/ivy/etc. whatever the user uses.

Implementing an overlay feels like re-impelenting company frontends to me.

**Comment by chrisdone** [comment]
Re-using company-mode, this works:

<img width="692" alt="screenshot 2018-02-16 17 21 44" src="https://user-images.githubusercontent.com/11019/36320381-f145d914-133d-11e8-9c41-fb031dcc7b20.png">

**Comment by joehillen** [comment]
`undefined` doesn't seem worth including in the completion options. It's obvious and not very useful.

**Comment by fosskers** [comment]
The `mempty` there must be the instance for `a -> b`. In a similar vein to @joehillen 's comment about `undefined`, is this `mempty` here useful?

**Comment by chrisdone** [comment]
I'm glad others notice the same thing. I was thinking it would be appropriate to just remove `undefined` from results. I did do that in a previous commit, but took out the filter for testing purposes. Anybody opposed to hiding it? It's really the type of value that you can just type manually on the rare times you need it, it'll always be in the list.

Regarding `mempty` I'm not sure what to do with it. It seems that `mempty` fits everywhere. On the other hand, it's not doing any harm to be in the list, is it? It's the order that's the problem, if anything. 

Actually, Intero returns the results by most specific first, so it returns it as `personName`, `mempty`, `undefined`, it's just that company-mode seems to list things in alphabetic order by default. I'm not sure where to tell it not to do that. I'll look into that tomorrow.

**Comment by chrisdone** [comment]
Idea: Intero could have a customizable list of identifiers not to list in the hole completions.

**Comment by kRITZCREEK** [comment]
IIRC you can pass `(sorted t)` to tell company to not resort things: https://github.com/epost/psc-ide-emacs/blob/085e9d5541ccf35e876a6135daaddaa0a58f3bb2/psc-ide.el#L207

**Comment by fosskers** [comment]
If the suggestions were sorted by relevance, then `a -> b` 's `mempty` could stay. Also off the top of my head: is `id` being filtered out as well? That's the other "duh" apart from `undefined` that comes to mind.

**Comment by chrisdone** [comment]
@kRITZCREEK Thanks, very helpful!

**Comment by fosskers** [comment]
Scratch that - `id` would still be useful in many cases.

**Comment by mgsloan** [comment]
Definitely getting into gnitty gritty details, but `id` should probably be omitted from results when the hole is applied to an argument.

**Comment by AnthonyJacob** [comment]
This should be solved systematically and definitely not for each case manually, although it might look attractive first.

Few question about the feature behavior:

1) Does the auto completion need all arguments to be present? For example, will `_ 1` suggest both `take` and `repeat`?
2) Does it work well with infix operators? For example will `Just 1 & _` suggest `maybe` ?
3) Does it constraint the auto completion based on type signature? For example will suggestions for `{x :: Int; x = _}` differ from `{x :: String; x = _}`?

**Comment by chrisdone** [comment]
> Does the auto completion need all arguments to be present? For example, will _ 1 suggest both take and repeat?

The whole declaration needs to type-check aside from the holes. So the arguments do need to be present if you would write them eventually. Due to type defaulting (`Integer`), it suggests:

<img width="226" alt="screenshot 2018-02-18 20 15 49" src="https://user-images.githubusercontent.com/11019/36356334-8a013c6a-14e8-11e8-926c-1d9b62d9fac6.png">

However, I'm considering adding some special handling for inferred literals (`1`, `"1"`).

> Does it work well with infix operators? For example will Just 1 & _ suggest maybe ?

That works OK:

<img width="332" alt="screenshot 2018-02-18 20 18 25" src="https://user-images.githubusercontent.com/11019/36356363-e57d70c2-14e8-11e8-936b-235462c2bc17.png">

> Does it constraint the auto completion based on type signature? For example will suggestions for {x :: Int; x = _} differ from {x :: String; x = _}? (I think it is impossible, because of infix operators, but maybe you figured out something...)

It's purely based on types, yeah. Example:

<img width="184" alt="screenshot 2018-02-18 20 19 45" src="https://user-images.githubusercontent.com/11019/36356374-19cf323e-14e9-11e8-90e3-db887ebbaebc.png">

**Comment by AnthonyJacob** [comment]
Oh I see, 3) works because 1) does does not. 

The thing is, I would favor behavior 1) over 3) (perhaps under different command).

Because ultimately when writing `1 & _` I would like to see suggestions in this order:

```haskell
-- argument type exactly matches
foo1 :: ? -> Integer -> ?
foo2 :: ? -> ? -> Integer -> ?
foo3 :: ...
-- argument type belongs to type class
bar1 :: TypeClass a => ? -> a -> ?
bar1 :: TypeClass a => ? -> ? -> a -> ?
...
-- argument type is generic
baz1 :: ? -> a -> ?
baz1 :: ? -> ? -> a -> ?   
```

**Comment by chrisdone** [comment]
@AnthonyJacob I think that could be a thing to explore for the next iteration. The idea of generating results that type check _but for n missing arguments that could be holes_ seems pretty reasonable and it wouldn't blow up the search space too much.

**Comment by chrisdone** [comment]
**This has been implemented on intero master** using company-mode and is accessible by typing anything starting with `_` (i.e. any hole), or being over a hole and running `company-complete`. It's only available on GHC 8.2, because that API exposes enough access to the type checker, earlier ones don't. 

It has a few remaining issues:

1. [ ] It's slow on large files. This can possibly be mitigated by making [`tryWellTypedFill`](https://github.com/commercialhaskell/intero/blob/d183ad24f66d7e80d38adac1503d579c3e184093/src/Completion.hs#L442..L455) type check a smaller subset of the module.
1. [ ] Type aliases aren't collapsed before doing [the type comparison](https://github.com/commercialhaskell/intero/blob/66337af1b6e1b7d3c4f31993465058ef22522f88/src/Completion.hs#L341). I saw a function in the GHC API somewhere to do that, but I can't find it at the moment.
2. [ ] Defaulting (numbers and overloaded strings) will make completion on `Int` and `Text` functions not trigger yet. I'll have to add some special handling for that.
4. [ ] Doesn't include non-top-level locally defined names, but this information is available in [`declarationTypeCheckedModule`](https://github.com/commercialhaskell/intero/blob/d183ad24f66d7e80d38adac1503d579c3e184093/src/Completion.hs#L72..L72), so it shouldn't be hard to also add that to [the list of names](https://github.com/commercialhaskell/intero/blob/d183ad24f66d7e80d38adac1503d579c3e184093/src/Completion.hs#L198) using some code like [`typeAt`](https://github.com/commercialhaskell/intero/blob/d183ad24f66d7e80d38adac1503d579c3e184093/src/Completion.hs#L174).

**Comment by chrisdone** [comment]
In existing Emacs running sessions, you need to restart intero-mode in buffers, so that it sets the minimum company mode completion to `1`.

**Comment by fosskers** [comment]
I'm not sure if its races between flycheck or what, but I'm seeing a lot of error messages appear in company mode instead of actual suggestions.

**Comment by chrisdone** [comment]
Seems to occur when you have a type error in your module. I'll fix that.

**Comment by acowley** [comment]
A doubly-minor annoying variation of what @fosskers describes is that I get type errors in `RULES` pragmas that I don't think should be type errors (the errors speak of missing constraints as if these were top level declarations), and those errors also overwhelm the hole-filling code.

**Comment by chrisdone** [comment]
@acowley @fosskers That behavior should stop now. I did a quick fix in the Elisp, but when I get time I'll try to fix it in the intero executable too.
