### ISSUE TITLE
Grand scheme: integration of autocomplete, hoogle, location info, type info, import management, and dependency management

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/intero#53]
There's quite a lot to this, but I think it would be a great feature.  I believe that leksah supports the autocompletion + import management, so there is some precedent.

There are a couple main ideas here:
- It's helpful to see the type of an identifier as you are deciding to use it.
- It's also helpful to see the docs of this identifier.
- There are quite a few different logical sources for completions.  Lets combine them into one convenient utility!  It'd also be possible to have completion queries that use some subset of these sources.

The general idea is that there are a number of scopes we might want to pull autocompletions from:
1. Local identifiers within a declaration
   - Developer context specified by cursor position.  Possibly also declaration text (heuristically extracted by editor), which can then be parsed in a lenient way to guess which identifiers are available.
2. Top level identifiers with a module
3. Imported identifiers
4. Identifiers which can be imported from a module that has an explicit import list.
5. Identifiers from packages which are dependencies of this project.
6. Identifiers from packages in stackage

(4) and (5) would integrate with - import list management - https://github.com/commercialhaskell/intero/issues/48 to extend the imports.  This would use a combination of info from hoogle and the package being compiled.

(6) would integrate with both import list management - https://github.com/commercialhaskell/intero/issues/48 and dependency management -  https://github.com/commercialhaskell/intero/issues/49 to extend both imports and deps while completing an identifier.

And for identifiers that come from these scopes, there're a few interesting things:
1. Full name of the identifier.
2. Location info if available.  For the package(s) being compiled, provide the most up-to-date info possible from compilation info.
3. Type info if available.
4. Documentation, perhaps from hoogle.  For the package(s) being compiled, just give the user raw haddocks?  Better would be to use hoogle's approach to presenting haddocks.

Note that there's no reason not to also use this for the CLI completion.  It will just be a bit tricky to manage display of the info associated with the completion possibilities.
# Even grander: type directed autocompletion

As the user is entering their completion query, compile another version of the module with the identifier replaced with a hole or undefined.  Use the type info for this hole to perform a number of hoogle queries:

1) All dependencies + local packages.  Prioritize identifiers by match, prefer those already imported.
2) If more results still needed, run hoogle on all of stackage (either hosted or locally).

With this scheme, we'd also use hoogle's type matching logic for local types.  

Alternatively, since ghc is linked in, we could try to unify the type of the hole with the in-scope identifiers that match the user's query.  Could also parse out the "relevant bindings" from the ghc message for the hole, and present those to the user.

With type directed autocompletion, we'd want to be able to initiate completion without even typing a prefix, to get the results unbiased by a text filter.

**Comment by mwotton** [comment]
am pining for type-aware completion of holes. Likely to be on the horizon soon? I would take a hack at it myself, but it looks like it's all part of some grand structure I don't quite understand.

**Comment by unhammer** [comment]
For inspiration, here's what you get in OCaml with merlin: http://the-lambda-church.github.io/merlin/destruct.ogv

**Comment by ntc2** [comment]
The video from @unhammer is really cool! It would be great if intero supported case splits like that!

**Comment by chrisdone** [comment]
Closing for [reasons in here](https://github.com/commercialhaskell/intero/issues/49#issuecomment-451153567).

**Comment by mgsloan** [comment]
:+1:
