### ISSUE TITLE
Intero-mode causes annoying "electric" underscores

### ISSUE THREAD

**Issue by truls** [commercialhaskell/intero#532]
I have an issue which started occurring within the past couple of weeks following an update: My underscores became "electric" which is quite annoying. The issue only occurs in haskell-mode when intero is enabled and not in other major modes using the same minor modes (company, flycheck, etc..)

To clarify what I mean by electric, my issues are the following:
- If I type an underscore, and press space, the cursor will jump pack to the underscore, leaving trailing whitespace in front of it.
- If I type _), and press space, the cursor will move over the ) after a short delay
- If I type _foo and press space, the cursor will move back to the end of the word (right after foo)
- If I place an underscore in front of an existing word, for example by changing foo to _foo, the cursor will move to the end of the word within a second after the _ was inserted.

The problem starts when after running M-x intero-mode and persists even after running the same command again to disable it. I have to close and re-open the buffer for the problem to go away.

I'm having a really hard time debugging this, so please let me know if I need to provide any additional information.

**Comment by acowley** [comment]
I'm not seeing that problem, but it could be related to the recent typed hole completion. You could try disabling `company-mode` to see if the cursor stops jumping around; if so, intero's company backend might be to blame. That completion doesn't usually work for me, so the fact that I'm not seeing the same problem you are may be due to some other aspect of my setup.

**Comment by truls** [comment]
You are correct. When disabling the intero company backend the problem goes away.

**Comment by truls** [comment]
For now, I've replaced the body of the intero-grab-hole function with nil, which solves my problem so it does indeed seems to be related to the typed hole completion feature.

**Comment by purcell** [comment]
I believe I've fixed this in f4cd072 - can you confirm and close this if so, please?

**Comment by truls** [comment]
As committed it is completely broken, but I think you have an extra parenthesis on line 891? Emacs even warns about it. After removing that it works.

**Comment by truls** [comment]
Just updated from MELPA. Everything is fine now. Thnks a lot! :)

**Comment by fosskers** [comment]
Something about this update may be sending my Spacemacs into an infinite loop. The electric `.` is fixed, but when my cursor approaches a `(` or `[`, it freezes. Any ideas?

**Comment by purcell** [comment]
@fosskers Nothing about this specific change should cause that. You can try enabling `debug-on-quit`, then `C-g` should provoke an emacs backtrace showing what it was busy with.

**Comment by fosskers** [comment]
It seems to have fixed itself with the latest slew of Emacs package updates. False alarm then I guess.

As a note, the behaviour I was seeing was the `emacs` process itself running at 100%, not any of the spawned `intero` processes. It wouldn't even respond to `C-g`.
