### ISSUE TITLE
Intero fails to self-install with cassava error

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/intero#534]
```
Intero is not installed in the Stack environment.

Installing intero-0.1.28 automatically ...

Downloading lts-10.3 build plan ...
Downloaded lts-10.3 build plan.
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
Could not install Intero!

We don't know why it failed. Please read the above output and try
installing manually. If that doesn't work, report this as a
problem.

WHAT TO DO NEXT

If you don't want to Intero to try installing itself again for
this project, just keep this buffer around in your Emacs.

If you'd like to try again next time you try use an Intero
feature, kill this buffer.
```

Happens in purescript/purescript

They're using LTS 10.3 in their `stack.yaml`

My Stack version is 1.6.5:

```
$ stack --version
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
```

Unclear how I'm meant to self-install, seems like it's not encouraged or allowed.

`intero-mode` output:

```
Syntax checker in buffer intero.el in emacs-lisp-mode:

  intero
    - major mode: `emacs-lisp-mode' not supported
    - may enable: yes
    - predicate:  t

Flycheck cannot use this syntax checker for this buffer.

Flycheck Mode is disabled.  Use C-u M-x flycheck-disable-checker to
enable disabled checkers.

--------------------

Flycheck version: 31snapshot (package: 20170626.1707)
Emacs version:    27.0.50
System:           x86_64-pc-linux-gnu
Window system:    x
```

`intero` was installed from MELPA this night.

**Comment by mgsloan** [comment]
:herb: :bug:

Should probably have a stack.yaml per ghc version as described in https://github.com/commercialhaskell/intero/issues/324

**Comment by chrisdone** [comment]
@bitemyapp 

    AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""

This requires a stack upgrade, I'm afraid there isn't a better error message. See here if you want the story of how the grinch stole christmas: https://github.com/haskell-hvr/cassava/pull/155

**Comment by bitemyapp** [comment]
@chrisdone I'm familiar with the error and the solution, that's why I mentioned that I was using Stack 1.6.5.

**Comment by chrisdone** [comment]
Probably an incomplete Emacs PATH.

Try running `M-! stack --version; which stack`. Your Emacs path is probably <1.6 from /usr/bin while your shell is probably 1.6.5 from `~/.local/bin`.

**Comment by bitemyapp** [comment]
@chrisdone I'm testing it now but I'm pretty sure that's the problem. I've had tremendous problems overrides of the Emacs path getting picked up by packages/modes before so I'm just going to copy the one of my from `~/.local/bin` to `/usr/bin`. It's successfully installing `intero` now so I think this is sorted. Sorry for the hassle, thank you!
