### ISSUE TITLE
Intero fails to load with -tty=false error

### ISSUE THREAD

**Issue by OmanF** [commercialhaskell/intero#536]
On MacOSX, Emacs 25.3.3, using Spacemacs 0.200.13.
Resolver: lts-10.8, Stack 8.2.2.
When started editing a Haskell file, got auto-installed Intero 0.1.28.

Getting the following error message on the Intero-Emacs buffer:
```lisp
Invalid option `--tty=false'

Usage: stack ghci [TARGET/FILE] [--ghci-options OPTIONS] [--ghc-options OPTIONS]
                  [--flag PACKAGE:[-]FLAG] [--with-ghc GHC] [--[no-]load]
                  [--package ARG] [--main-is TARGET] [--load-local-deps]
                  [--[no-]package-hiding] [--only-main] [--trace] [--profile]
                  [--no-strip] [--[no-]test] [--[no-]bench] [--help]
  Run ghci in the context of package(s) (experimental)

---

This is the buffer where Emacs talks to intero. It's normally hidden,
but a problem occcured.

TROUBLESHOOTING

It may be obvious if there is some text above this message
indicating a problem.

If you do not wish to use Intero for some projects, see
https://github.com/commercialhaskell/intero#whitelistingblacklisting-projects

The process ended. Here is the reason that Emacs gives us:

  exited abnormally with code 1

For troubleshooting purposes, here are the arguments used to launch intero:

  stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-build --no-load --ghci-options -ignore-dot-ghci --ghci-options -odir=/<User Directory Name>/blah/.stack-work/intero/intero55561tJo --ghci-options -hidir=/<User Directory Name> /blah/.stack-work/intero/intero55561tJo blah

It's worth checking that the correct stack executable is being
found on your path, or has been set via
`intero-stack-executable'.  The executable being used now is:

  /<User Home Directory/.asdf/shims/stack
```

As can be seen I'm using the `asdf` version manager, but that has never caused me issues till today.
Also, the `stack` executable is on the `PATH` just fine, can fire it up the usual `stack ghci` from the shell prompt.
Using `--tty=false` on the prompt, while making no sense, gives the exact same error about it being invalid option.

Like to *draw attention* to the `--tty=false` being invalid at the top of the error message...

(By the way, also failed using Intero 0.1.23 which I have on another project, using `asdf`).

**Comment by OmanF** [comment]
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
(And as previously said, installed using the `asdf` version manager).

**Comment by chrisdone** [comment]
Perhaps that no-tty flag was removed recently. Let me see.

**Comment by Zeeker** [comment]
I've encountered the same error on my mac, also using `asdf`.

- macOS High Sierra 10.13.2
- Spacemacs v.0.200.10
- Resolver: lts-10.8
- Stack 1.6.5
- GHC 8.2.2

**Comment by chrisdone** [comment]
I'm on OS X 10.10.5 Yosemite and Stack 1.6.5. 

Stack the executable seems to have no problem with the arguments as passed in:
```
bash-3.2$ stack-1.6.5 ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --verbosity error
Intero 0.1.30 (GHC 8.0.2)
Type :intro and press enter for an introduction of the standard commands.

Intero-Service-Port: 51748
package flags have changed, resetting and loading new packages...
Prelude Describe> 
Leaving GHCi.
```

So I don't know where this is coming from. Try running this in your Emacs:

```lisp
(start-file-process "stack"
                    (switch-to-buffer (get-buffer-create "*process-output*"))
                    intero-stack-executable
                    "ghci"
                    "--docker-run-args=--interactive=true --tty=false")
```

**Comment by Zeeker** [comment]
Okay, I've boiled it down to the usage of `asdf`. I've reinstalled everything via `homebrew` and not it works.

`asdf` "shims" the binary to allow easily switching between versions and it seems it does something odd with the CLI options.

Nothing to do here, I think.

**Comment by chrisdone** [comment]
Thanks @Zeeker for reporting back.
