### ISSUE TITLE
intero opens new *repl* window even when there's another frame with the repl window already open

### ISSUE THREAD

**Issue by mwotton** [commercialhaskell/intero#540]
i'd like to be able to have one emacs frame with the repl open on a separate screen rather than splitting the emacs window into code and repl, but even if the repl is open in the other frame, intero opens a new window onto the buffer in the original frame.

**Comment by purcell** [comment]
I imagine that one way or another, the code uses `display-buffer`, in which case you can use the standard mechanisms for configuring what that does on a per-command basis. See https://www.gnu.org/software/emacs/manual/html_node/elisp/Display-Action-Functions.html

**Comment by mwotton** [comment]
Thanks Steve, that works great!

**Comment by purcell** [comment]
Great, glad you figured it out!
