### ISSUE TITLE
Many ` intero-network:backend-` buffers getting created

### ISSUE THREAD

**Issue by ChickenProp** [commercialhaskell/intero#544]
As I use intero, it seems that the length of my buffer list keeps increasing. This is a problem for me, as it slows down `ido-switch-buffer`.

It looks as though the problem is caused by a lot of buffers named like ` intero-network:backend-*` (with a leading space). For example, if I do `(insert (substring (format "%S" (mapcar 'buffer-name (buffer-list (selected-frame)))) 0 1000))`, I get

```
("*scratch*" " *Minibuf-1*" "*Backtrace*" "*Messages*" "PermissionSpec.hs" "TestQueryUtil.hs" "Api.hs" "Review/Queries.hs" "src/Queries.hs" "Standardize.hs" "excelsior.cabal" "QuerySpec.hs" "Util.hs" "CDMVarIds.hs" "User/Types.hs" "Reports/Queries.hs" " *Minibuf-0*" "Properties/Queries.hs" "Review/Types.hs" ".dir-locals.el" "*GNU Emacs*" " *code-conversion-work*" " *Echo Area 0*" " *Echo Area 1*" " intero-network:backend" " intero-network:backend-150056" " intero-network:backend-806060" " intero-network:backend-958468" " intero-network:backend-695967" " intero-network:backend-359141" " intero:backend:excelsior /home/phil/code/excelsior" " intero-network:backend-241704" " intero-network:backend-804390" " intero-network:backend-853775" "*Help*" " intero-network:backend-655359" " intero-network:backend-644620" " intero-network:backend-119029" " intero-network:backend-537428" " intero-network:backend-262984" " intero-network:backend-706094" " intero-network:backend-799389" " intero-network
```

Yesterday I restarted emacs to clear these out (`intero-restart` didn't seem to do the trick), but today my buffer list was already over 3000 items. Just now I did

```elisp
(defun intero-buffers (frame)
  (delq nil
	(mapcar
	 (lambda (x)
	   (let ((name (buffer-name x)))
             (if (string-prefix-p " intero-network:backend-" name)
		 name)))
	 (buffer-list frame))))

(defun kill-intero-buffers ()
  (mapcar 'kill-buffer (intero-buffers (selected-frame))))
(kill-intero-buffers)
```

and that seems to have worked. The buffer list is down to 34. Intero still seems to work, though I can't rule out that I've broken it subtly.

If necessary I can call that function once a day, but that's not ideal.

Perhaps worth noting, this didn't appear to start as soon as I started using intero, but I'm not sure when it did start. It might have been after I set `intero-targets`. (Or it might just have become a lot faster then, possibly because I set five targets at once? Which itself might not have been the best idea, I don't know. I'll stop speculating now.)

**Comment by chrisdone** [comment]
Seems like the buffers aren't being killed after use. I'll check that.

**Comment by chrisdone** [comment]
Thanks for reporting and the handy elisp functions to help me repro.

**Comment by purcell** [comment]
This fix isn't correct, I believe. Working in a big project I now constantly get "error: selecting deleted buffer". I merged a similar fix from #523, and later had to revert it for the same reason. I don't think we're taking into account the lifecycle/re-use of these buffers somehow.

**Comment by purcell** [comment]
Okay, I made this a bit safer in 37af015.

**Comment by chrisdone** [comment]
Cool!

**Comment by chrisdone** [comment]
So the `delete-process` is used in both branches and that triggers the "deleted\n" case which kills the buffer. Good stuff.

**Comment by purcell** [comment]
Yeah, it was a bit fiddly to track down, and it might be dependent on Emacs versions. There should arguably be no "deleted" event delivered if the process's buffer has been killed. Alternative would have been to somehow unset the sentinel for the process upon deleting it. Anyhow, seems working now. :-)
