### ISSUE TITLE
eldoc error

### ISSUE THREAD

**Issue by dgh1000** [commercialhaskell/intero#547]
Usually intero works fine for me, but recently I started getting 

"eldoc error: (wrong-type-argument number-or-marker-p Abort trap: 6)"

Can I get some help how to go about debugging this?

**Comment by dgh1000** [comment]
I started a new, empty, project with a more recent version of stack. I copied over just the source files I need for now, and everything is working for now. So I'll leave this be.

**Comment by wraithm** [comment]
Same issue here.
