### ISSUE TITLE
Auto-detect necessary stack target for a given file

### ISSUE THREAD

**Issue by bjchambers** [commercialhaskell/intero#55]
A common setup might be to have a cabal file containing a library (named `somelib`) and some tests for it (named `sometests`). It is also likely that the cabal configuration for `sometests` includes additional dependencies (HUnit, hspec, QuickCheck, etc.).

When opening emacs pointing at one of these files, flycheck reports:
```
error:
  Failed to load interface for 'Test.Tasty'
  It is a member of the hidden package 'tasty-0.11.0.3'.
  Use -v to see a list of the files searched for.
```

This is odd, because (1) `stack test` succeeds and (2) tasty is listed as a dependency of the tests. If I call `intero-targets` and set it to `<package>:tests` then flycheck becomes happy.

My guess is that flycheck is interacting with a GHCI (intero?) session that only has the dependencies from the library loaded. Should it use the dependencies of the current file instead? Is there an easy way to set it up to do this?

Ideally, it would be possible to just load the right set of dependencies, but I think this would require parsing the cabal files (and/or extending stack to report this). I could write a function to automatically set the targets based on the directory of the file, but that will be hard-coded for a specific directory layout, and also (I think) will need to reload intero every time I switch files.

**Comment by chrisdone** [comment]
Generally you can just pass both the library and the tests as arguments: `pkg:lib pkg:tests` sort of thing. 

We've discussed this and also concluded we'd like for Stack to tell us which target a file comes from, and then we can prompt the user to reload with those targets or not to (and either add the target or switch to it; the former choice doesn't mean restarting for every file).

**Comment by bjchambers** [comment]
If I understand correctly, using `pkg:lib pkg:tests` should work, but you won't receive errors about using a dependency in a file that isn't part of the target containing that file. Not a major problem (and certainly better than rejecting correct code).

Even if stack reported the target a file came from, adding the target to the set would potentially have this problem. Depending on how heavy weight intero instances are, another possibility would be to run a separate session for each target.

**Comment by mgsloan** [comment]
Covered by https://github.com/commercialhaskell/intero/issues/39, particularly the first comment.

**Comment by bjchambers** [comment]
I'm going to close this. Auto-detection would be nice, but based on the suggestion of using intero-targets, and finding that I can use `.dir-locals.el` to automatically configure intero-targets for a directory, addresses my original use case (not needing to run intero targets every time I restarted emacs).
