### ISSUE TITLE
Opening editor fails with process XXX not running

### ISSUE THREAD

**Issue by janesser** [commercialhaskell/intero#559]
Trying around, i cleared `~/.emacs.d/elpa`. So (m)elpa packages should be up-to-date. I have only intero installed right now. My project is https://github.com/janesser/rsync-imap/commit/a91808b29f6916c4d1c1d8e5fb4efe11e69165dd.

`(setq debug-on-error t)` is active.

Often emacs just freezes when i try to open any *.hs file after emacs start.
Then i occasionally clear `rm .stack-work/intero -fR`. Not really changing much.

Finally i get that stacktrace:
```
Debugger entered--Lisp error: (error "Process /home/jan/projs/rsync-imap not running")
  process-send-string(#<process /home/jan/projs/rsync-imap> "check /home/jan/projs/rsync-imap/app/Main.hs\n")
  ghc-with-process("check /home/jan/projs/rsync-imap/app/Main.hs\n" ghc-check-callback #[nil "\301\211\207" [mode-line-process " -:-"] 2])
  ghc-check-syntax()
  ghc-init()
  (lambda nil (ghc-init))()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook haskell-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook haskell-mode-hook))
  run-mode-hooks(haskell-mode-hook)
  haskell-mode()
  set-auto-mode-0(haskell-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer Main.hs> "~/projs/rsync-imap/app/Main.hs" nil nil "~/projs/rsync-imap/app/Main.hs" (548264 47))
  find-file-noselect("/home/jan/projs/rsync-imap/app/Main.hs" nil nil nil)
  find-file("/home/jan/projs/rsync-imap/app/Main.hs")
  dired-find-file()
  call-interactively(dired-find-file nil nil)
  command-execute(dired-find-file)
```

I can get past this with `M-x debugger-continue`.

Then saving a changed file again freezes emacs. I let it run for more than 20 minutes, which should be enough even on my legacy netbook (amd k125). Emacs will not come back.

**Comment by janesser** [comment]
actually same setup on another computer works perfectly.

any hints what to look for?

**Comment by janesser** [comment]
https://emacs.stackexchange.com/questions/21643/what-do-i-do-when-emacs-is-frozen

found hint to try C-g which resolves my issue.

I don't understand what "Spam" exactly means in this context. Weird somehow.

**Comment by purcell** [comment]
> I don't understand what "Spam" exactly means in this context. Weird somehow.

If you think of "spamming" as sending something incessantly whether the receiver wants it or not, then it makes sense for keypresses too. :-)
