### ISSUE TITLE
Support completion for stack targets

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/intero#56]
I'd like an interface that pops up something like this:

```
[x] weigh:lib  [ ] weigh:test:weigh-test
[ ] store:lib  [ ] store:test:store-test [ ] store:bench:store-bench
```

And you can use your cursor or mouse to click the targets you want.

For this we need a list of packages from Stack, and a list of available stanzas from within each one, according to what is configured with the current flags, etc. Stack is completely capable of passing this information to us.

**Comment by magthe** [comment]
Maybe this could be done via `helm` or something similar?

**Comment by chrisdone** [comment]
@magthe I'm not up on helm. If you're familiar with it can you answer a couple quick questions:

1) does it have a small foot-print (the kind users wouldn't mind paying; like flycheck and company)?
2) is it trivially programmable, so we could use it for this use-case (and maybe others)?
3) does it take over your whole emacs or is it like ido where it can be used on a per-need basis?

**Comment by magthe** [comment]
I'm not intimately familiar with it either, I only use it via *spacemacs*.

1. I'm not sure about the footprint but `helm-core` and `helm` occupy 608k and 1.6M respectively on my system, so it's a bit larger than `flycheck` and `company`.
2. I believe it's trivially programmable, at least if one looks at the number of extensions to it for various things.
3. It pretty much does take over Emacs.

Given 2 and 3 I guess I should instead request that you don't do it in such a way that it's difficult to integrate with `helm`.

**Comment by akermu** [comment]
As an alternative there's also the stock emacs interface for such things: `completing-read`. Helm and other completion systems, like ivy or ido, hook into it, so users of these could use it as well.

**Comment by chrisdone** [comment]
The `completing-read` function just lets you choose one option at once. We want to choose *n* at once. I.e. we want to enable many stack targets in one session (library and test suite, for example).

**Comment by magthe** [comment]
A possibly completely naive and silly thing to say, but how about `completing-read-multiple` from `crm.el`?

**Comment by chrisdone** [comment]
@magthe That's not bad but I think part of my motivation for this completion is discoverability; if I don't know how to specify stack targets or what mine are called, it doesn't matter; the UI shows the available targets immediately.

**Comment by chrisdone** [comment]
I've pushed an example in 62246d9. It's used like this:

``` lisp
(intero-multiswitch
 "Pick your targets: "
 '((:key foo :title "foo")
   (:key foo-exe-bar :title "foo:exe:bar")
   (:key foo-lib :title "foo:lib")
   (:key foo-test-zak :title "foo:test:zak")))
```

It looks like this:

<img width="516" alt="screenshot 2016-06-29 11 24 03" src="https://cloud.githubusercontent.com/assets/11019/16447291/0d8f0fd8-3dec-11e6-8353-b59ace6163e4.png">

Hitting `C-c C-c` returns `'(foo:exe:bar)` to the caller.

I think this is pretty decent, it uses standard the Emacs widget library. What's missing is the integration from stack.

**Comment by chrisdone** [comment]
Done. You need to pull stack master for this feature, otherwise it falls back to the current behaviour.

**Comment by unhammer** [comment]
Could we have a note that you have to use `RET` to select an option? Took me forever to figure that out :-) 

Or perhaps allow `SPC` as well (and maybe rebind `n/p` to `C-n/p`?).

**Comment by unhammer** [comment]
thanks!
