### ISSUE TITLE
Windows file names: \ vs /

### ISSUE THREAD

**Issue by lukexi** [commercialhaskell/intero#57]
Giving Intero a whirl on Windows - many things seem to work (`C-c C-t`, completion) but I haven't managed to get any flycheck output yet. Best guess so far is that it's a line ending issue, as the strings coming back from intero-async-call are chock full of `^M`s when I dump them. 

I don't use emacs regularly so I'll be a bit slow to debug it; will try though! Also happy to test any ideas.

**Comment by chrisdone** [comment]
Interesting. How about printing out some of the string values like `string` in here? https://github.com/commercialhaskell/intero/blob/master/elisp/intero.el#L268..L274

Perhaps the ` "OK, modules loaded: \\(.*\\)\\.$"` regex is too strict. Try removing the `$`?

**Comment by lukexi** [comment]
I got a little further via stripping with
`(let ((string (replace-regexp-in-string "\r" "" (buffer-substring (point-min) (1- (point))))))`
at 
https://github.com/commercialhaskell/intero/blob/master/elisp/intero.el#L913

Which gets me past "OK, modules loaded" and I'm able to use C-c C-i now (before I'd get "not in scope" errors).

I'm inspecting the results of `intero-parse-errors-warnings` now and they seem to be constructing correctly... but FlyC reports nothing when asking it to show all errors (these are all warnings, but I've tried inducing errors as well).
```
([cl-struct-flycheck-error nil intero "C:\\msys64\\home\\lukex\\Projects\\rumpus\\src\\Rumpus\\Systems\\Hands.hs" 98 1 "
    Top-level binding with no type signature:
      isBeingHeldByHand :: forall (m :: * -> *).
                           (MonadState ECS m, MonadReader EntityID m) =>
                           WhichHand -> m Bool" warning nil] [cl-struct-flycheck-error nil intero "C:\\msys64\\home\\lukex\\Projects\\rumpus\\src\\Rumpus\\Systems\\Hands.hs" 8 1 "
    The qualified import of ‘Data.List’ is redundant
      except perhaps to import instances from ‘Data.List’
    To import instances alone, use: import Data.List()" warning nil] [cl-struct-flycheck-error nil intero "C:\\msys64\\home\\lukex\\Projects\\rumpus\\src\\Rumpus\\Systems\\Creator.hs" 313 1 "
    Top-level binding with no type signature:
      spawnChildInstance :: forall (m :: * -> *).
                            (MonadIO m, MonadState ECS m, MonadReader EntityID m) =>
                            FilePath -> m EntityID" warning nil] [cl-struct-flycheck-error nil intero "C:\\msys64\\home\\lukex\\Projects\\rumpus\\src\\Rumpus\\Systems\\Creator.hs" 13 1 "
    The import of ‘Rumpus.Systems.CodeEditor’ is redundant
      except perhaps to import instances from ‘Rumpus.Systems.CodeEditor’
    To import instances alone, use: import Rumpus.Systems.CodeEditor()" warning nil] [cl-struct-flycheck-error nil intero "C:\\msys64\\home\\lukex\\Projects\\rumpus\\src\\RumpusLib.hs" 39 15 "
    This binding for ‘angle’ shadows the existing binding
      imported from ‘PreludeExtra’ at C:\\msys64\\home\\lukex\\Projects\\rumpus\\src\\RumpusLib.hs:4:1-19
      (and originally defined in ‘linear-1.20.4:Linear.V2’)" warning nil] [cl-struct-flycheck-error nil intero "C:\\msys64\\home\\lukex\\Projects\\rumpus\\src\\Rumpus\\Systems\\HandControls.hs" 72 1 "
```

**Comment by lukexi** [comment]
Flycheck works fine with hlint in vanilla haskell-mode... perhaps something to do with generic syntax checkers...

**Comment by chrisdone** [comment]
@lukexi Oh -- perhaps you're getting type errors in a module that your current module depends on. Can you try opening a fresh `X.hs` file and put in a type error like `x = 1 * 'a'` and see what happens?

**Comment by chrisdone** [comment]
I have an open PR for flycheck so that it shows errors/warnings from other files: https://github.com/flycheck/flycheck/pull/972

**Comment by lukexi** [comment]
Aha, I'm getting something now:
With a buffer of
```
module Lib
    ( someFunc
    ) where

someFunc :: IO ()
someFunc = putStrLn (1 + 'c'
```
(with a fresh `stack new`)

I get a result from flycheck `FlyC:1/0` and highlighting etc (with this log output)
```
Booted up intero!
intero-parse-errors-warnings parsing:
[1 of 1] Compiling Lib              ( C:\msys64\home\lukex\intero-testing\src\Lib.hs, C:\Users\lukex\AppData\Local\Temp\intero13976Kns\Lib.o )

C:\msys64\home\lukex\intero-testing\src\Lib.hs:7:1:
    parse error (possibly incorrect indentation or mismatched brackets)
Failed, modules loaded: none.

([cl-struct-flycheck-error nil intero "C:\\msys64\\home\\lukex\\intero-testing\\src\\Lib.hs" 7 1 "parse error (possibly incorrect indentation or mismatched brackets)" error nil])
```

But as soon as I close the parenthesis, leaving the type error, Flycheck reports everything as clean again (and no log, so it doesn't look like intero-parse-errors-warnings is getting called in that case).

I'll see what I can figure out from that.

**Comment by lukexi** [comment]
Oops, no, the successful flycheck was from hlint! I moved hlint aside and now neither case gives flycheck output.

and I do get a log both errors after all:
```
Booted up intero!
intero-parse-errors-warnings parsing:
[1 of 1] Compiling Lib              ( C:\msys64\home\lukex\intero-testing\src\Lib.hs, C:\Users\lukex\AppData\Local\Temp\intero12088v0s\Lib.o )

C:\msys64\home\lukex\intero-testing\src\Lib.hs:6:26:
    Couldn’t match type ‘Char’ with ‘[Char]’
    Expected type: String
      Actual type: Char
    In the second argument of ‘(+)’, namely ’c’
    In the first argument of ‘putStrLn’, namely ‘(1 + ’c’)’
    In the expression: putStrLn (1 + ’c’)
Failed, modules loaded: none.

([cl-struct-flycheck-error nil intero "C:\\msys64\\home\\lukex\\intero-testing\\src\\Lib.hs" 6 26 "Couldn’t match type ‘Char’ with ‘[Char]’
    Expected type: String
      Actual type: Char
    In the second argument of ‘(+)’, namely ’c’
    In the first argument of ‘putStrLn’, namely ‘(1 + ’c’)’
    In the expression: putStrLn (1 + ’c’)" error nil])
```

**Comment by lukexi** [comment]
Oh! I think it's down to
```
:buffer (when (string= (intero-buffer-file-name buffer)
                        file)
         buffer)
```
`intero-buffer-file-name buffer` is
```
"c:/msys64/home/lukex/intero-testing/src/Lib.hs"
```

whereas file is
```
"C:\\msys64\\home\\lukex\\intero-testing\\src\\Lib.hs"
```


causing the `nil` in the `cl-struct-flycheck-error` struct

**Comment by chrisdone** [comment]
Aha! Good work investigating! Now, let's see whether Emacs has a normalizing function for this.

**Comment by chrisdone** [comment]
@lukexi Does it solve your problem if you use `(replace-in-string "C:\\foo\\bar\\mu" "\\\\" "/") => "C:/foo/bar/mu"`?

**Comment by lukexi** [comment]
`convert-standard-filename` is close! But it's not normalizing the capitalization of the drive, so I've got
```
"C:\\msys64\\home\\lukex\\intero-testing\\src\\Lib.hs"
```
and
```
"c:\\msys64\\home\\lukex\\intero-testing\\src\\Lib.hs"
```
now
:100: 

Let me fix that and see if we're in the clear : )

**Comment by lukexi** [comment]
Yaha, all good now : )

I'll clean things up and make a pull request, thanks for the help!

**Comment by chrisdone** [comment]
That sounds spiffing. Thanks @lukexi!  I've got to leave the house now, but I'll be back later to merge what PR you make.

**Comment by chrisdone** [comment]
Fixed by your PR!
