### ISSUE TITLE
How do I make autocomplete on demand when using Emacs?

### ISSUE THREAD

**Issue by serefarikan** [commercialhaskell/intero#574]
Sorry for such a simple question but I've been lost in various google search results. 
The autocomplete provided by intero is getting in the way when I'm using emacs. I pause for a second when writing = and the autocomplete drop down emerges, which won't go away with a single key press (such as esc). 

How can I make this feature on-demand? As in, I only want to trigger autocomplete manually with a shortcut such as ctrl+space rather than the popup activated on its own.

**Comment by chrisdone** [comment]
You can configure company-mode which is what provides the functionality!

**Comment by serefarikan** [comment]
@chrisdone  That is exactly what I was looking for. Thanks a lot!
