### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by unhammer** [commercialhaskell/intero#582]
The current release doesn't work with the newest stackage lts

```
In the dependencies for intero-0.1.30:
    ghc-8.4.3 from stack configuration does not match >=7.8 && <=8.4.1  (latest matching version
              is 8.4.1)
```

**Comment by CarstenKoenig** [comment]
I don't think this is the current release - it should be 0.1.32 (this is what I got)

**Comment by unhammer** [comment]
there's no 0.1.32 tag from what I can tell

**Comment by CarstenKoenig** [comment]
true - I guess someone forgot to add this - but here is the commit: https://github.com/commercialhaskell/intero/commit/7db6ba44572dc8207a2c6d24c14e06206f7426d2

**Comment by unhammer** [comment]
OK, melpa-stable gives only what's tagged – can we have a tag? :-)

**Comment by CarstenKoenig** [comment]
oh - did not even notice that - as a workaround you should be fine with `stack build intero --copy-compiler-tool`

**Comment by develop7** [comment]
@ntc2 [does it](https://travis-ci.org/commercialhaskell/intero/jobs/471933957)?

**Comment by ntc2** [comment]
@develop7 Yes, it works for me. Note that the failed build you linked to is failing due to `-Werror` (treat warnings as errors) along with some warnings.
