### ISSUE TITLE
Support for GHC 8.6.1

### ISSUE THREAD

**Issue by d12frosted** [commercialhaskell/intero#584]
Hi,

Any plans for supporting GHC 8.6.1?

**Comment by janpath** [comment]
#580 has been sitting in the pull-requests for some time.

You can use this in your stack.yaml to use it now:

```
extra-deps:
...
- git: https://github.com/janpath/intero.git
  commit: c32d87a170495d106744c3f7275a9d24ed0e3e42
```

**Comment by d12frosted** [comment]
@janpath thank you for the link to PR. For some reason I totally missed it.

**Comment by simonmichael** [comment]
Ping.. I see there were a bunch of releases early in the year but none since. Might there be a release soon to make intero usable with GHC 8.6-based projects ?

**Comment by develop7** [comment]
#580 has been landed in 0.1.34, @d12frosted please test

**Comment by simonmichael** [comment]
intero-0.1.34 installed fine with GHC 8.6.1 here. Thanks!

**Comment by d12frosted** [comment]
@develop7 thank you! I will take a look.

**Comment by DanBurton** [comment]
There is a test suite failure that looks trivial:

```
Failures:

  src/test/Main.hs:71:15:
  1) Basics :i Nothing
       expected: "data Maybe a = Nothing | ... \t-- Defined in \8216GHC.Base\8217\n"
        but got: "data Maybe a = Nothing | ... \t-- Defined in \8216GHC.Maybe\8217\n"

  To rerun use: --match "/Basics/:i Nothing/"

Randomized with seed 1434543268

Finished in 24.9978 seconds
44 examples, 1 failure, 1 pending
```

https://github.com/commercialhaskell/intero/blob/4be2a4a5de81bae504654a6b3a5d8a340be00e7e/src/test/Main.hs#L73

I guess the location that `Nothing` is defined in changed with ghc 8.6.
