### ISSUE TITLE
Intero in stackage lts-12.15 and lts-12.16 can't build

### ISSUE THREAD

**Issue by declension** [commercialhaskell/intero#586]
### Steps to replicate
* Create a new Stack project with `lts-12.16`
* `stack install intero`

### Expected
Build to succeed

### Actual

Fails with:
```
In the dependencies for intero-0.1.32:
    ghc-8.4.4 from stack configuration does not match >=7.8 && <=8.4.3  (latest matching version is 8.4.3)
needed since intero is a build target.
```

### Notes
[lts-12.15](https://www.stackage.org/lts-12.15) and [lts-12.16](https://www.stackage.org/lts-12.16) both include `ghc-8.4.4`, and  `intero-0.1.32`,

Looks similar to #582, though I think that was referring to different versions.

**Comment by develop7** [comment]
This actually breaks https://github.com/rikvdkleij/intellij-haskell users' workflow, others maybe affected too.

**Comment by declension** [comment]
@develop7 agreed (that's how I got here actually)

**Comment by declension** [comment]
Thanks!
