### ISSUE TITLE
Disable (or document how to) close inferior process prompt

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/intero#59]
intero-mode interacts with `intero` as a subprocess. This process is pretty well hidden (the interaction buffer doesn't show up in the normal list of buffers), but when exiting Emacs is pretty keen to ask if we really want to exit given that this subprocess is alive. I'd say in this case a user pretty much never cares that there's some interaction process lying around. Is there a way to disable that? If it's not an intero-mode thing, then just document how to switch off this annoying prompt?

**Comment by chrisdone** [comment]
Oh, that's a feature of `comint-mode`; any REPL derived from it (shell, scheme, etc.) will prompt for that. But it's trivial to disable with a buffer-local variable. I'll make a patch.

**Comment by chrisdone** [comment]
Ah looks like we can do it per process: https://www.gnu.org/software/emacs/manual/html_node/elisp/Query-Before-Exit.html

Lovely.
