### ISSUE TITLE
How to enable Emacs intero-mode better?

### ISSUE THREAD

**Issue by re-mx** [commercialhaskell/intero#597]
Hello, and forgive my poor English.

I see two ways to enable it:
1.
```
(with-eval-after-load 'haskell-mode
    (intero-global-mode))
```
2.
```
(with-eval-after-load 'Haskell-mode
     (add-hook 'haskell-mode-hook 'intero-mode))
```

Which of these two methods is better?

And do I need to manually add flyckeck's checker?
like this:
```
(flycheck-add-next-checker 'intero '(warning . haskell-hlint))
```

Thank you!

**Comment by purcell** [comment]
The former is better because it allows use of the whitelist and blacklist options, so that intero can be enabled/disabled on a per-project basis.

As for the `haskell-hlint` checker, yes, that's manual: not everyone will want it.

**Comment by re-mx** [comment]
Thanks.
