### ISSUE TITLE
Improve Emacs's auto installation of the intero package

### ISSUE THREAD

**Issue by iainnicol** [commercialhaskell/intero#63]
I started off with a clean user profile on a fresh operating system install.  I installed stack and then the intero Emacs package.  I ran into two places where the intero installation could be slicker.

When I opened a .hs file in Emacs, I got this error message:

```
Intero is not installed in the Stack environment.

Installing intero-0.1.13 automatically ...

No compiler found, expected minor version match with ghc-7.10.3 (x86_64) (based on resolver setting in /home/iain/Desktop/foo/stack.yaml).
Try running "stack setup" to install the correct GHC into /home/iain/.stack/programs/x86_64-linux/
Could not install Intero!
```

The fix, as it says, is to run "stack setup" manually, which downloads GHC.  But could intero run that itself, to make the installation slicker?

When I restarted Emacs, I saw a different error with the auto installation of intero:

```
    configure: error: in `/tmp/stack9568/terminfo-0.4.0.2':
    configure: error: curses headers could not be found, so this package cannot be built
    See `config.log' for more details
Could not install Intero!
```

This I solved with a `apt-get install libncurses-dev`.  I'm not sure realistically how to make this slicker.  Have intero run sudo apt-get install?  Document the dependency?

**Comment by chrisdone** [comment]
It's always possible to add more stuff to streamline the installation
procedure. Running stack setup is free so we can use that whenever we
install intero. For the rest, I'll have a think and comment more when I get
back to a computer!

**Comment by IvanMalison** [comment]
It's also kind of annoying that intero hangs emacs when it is doing the install.

Why not allow the user to keep doing stuff while this compilation step is happening?

**Comment by chrisdone** [comment]
@IvanMalison because doing it asynchronously causes an intermediate incomplete state. I've gone down that route in Emacs before and it's difficult to make reliable.

**Comment by esjmb** [comment]
so how about doing it sequentially, and adding a configurable option to decide whther the use wants  hang for install or not?

**Comment by narendraj9** [comment]
It is extremely annoying to have Emacs in that state while intero is getting installed. What happens in the intermediate state (if you have the time to describe it)?

**Comment by chrisdone** [comment]
I'm not going to touch the this code any time soon. Making auto install work even this well took a long time.
