### ISSUE TITLE
Command to paste in is missing quotes, so fails.

### ISSUE THREAD

**Issue by dbp** [commercialhaskell/intero#65]
When `intero` has a problem starting up, it (very helpfully) shows the command it was trying to run. But, unfortunately, it is missing quotes around the arguments to pass to docker, which means the command fails because docker arguments are being passed to stack (which doesn't understand them). 

An example command is:

```
stack ghci --with-ghc intero --docker-run-args=--interactive=true --tty=false --no-load --no-build --ghci-options "-odir=/var/folders/4q/x49z7wfx6656_0h1_stqth5h0000gn/T/intero88354yPD" --ghci-options "-hidir=/var/folders/4q/x49z7wfx6656_0h1_stqth5h0000gn/T/intero88354yPD" project
```

And the problem is that there aren't quotes around the `--docker-run-args` (I'm not actually sure how far they need to go, but at least `--tty` is not a stack argument).

**Comment by chrisdone** [comment]
Good catch.  I'll fix when I get home. Thanks!

**Comment by dbp** [comment]
Thanks!

I've had to run the command manually a few times when switching
targets (which succeeds the first time, and then once that happens, intero
works), but overall, this seems like finally the Haskell Emacs IDE that
actually just works. Somehow it always seemed like it should be possible to
have flycheck/type lookup that reliably worked, but I guess stack had to
come first...

Anyway, great job (as always).
