### ISSUE TITLE
Completion does not work for qualified modules

### ISSUE THREAD

**Issue by rainbyte** [commercialhaskell/intero#66]
With this code company shows `forM` `forM_` and `forever` as posible completions

```haskell
module Main where

import Control.Monad

main :: IO ()
main = do
  for|--pointer is here
  putStrLn "hello"
```

But if code is written like this, nothing is shown as completion

```haskell
module Main where

import qualified Control.Monad as CM

main :: IO ()
main = do
  CM.for|--pointer is here
  putStrLn "hello"
```

Expected: `CM.forM` `CM.forM_` and `CM.forever` are shown as posible completions

Thanks in advance!

**Comment by yamafaktory** [comment]
Facing the same issue. Thanks for the great work!

**Comment by chrisdone** [comment]
Indeed, discussed this with @snoyberg. Good to have an issue open for it.
Thanks for reporting!
