### ISSUE TITLE
Show type and module of completion

### ISSUE THREAD

**Issue by kRITZCREEK** [commercialhaskell/intero#71]
It would be nice if intero could show the module and type for a completion while browsing the company popup. I've implemented something similar for purescript's `psc-ide` using company's `meta` case for backends.

![](http://i.imgur.com/H6rSS9L.gif)

I tried to make a PR but couldn't manage to get the type info for a "string" with intero. In `psc-ide` the completions sent to the editor already contain a module and type field for editors to use like this:

``` json
{
  "module": "Data.List",
  "identifier": "sort",
  "type": "forall a. (Ord a) => List a -> List a"
}
```

Maybe we could get something similar to work for intero?

**Comment by chrisdone** [comment]
I think that's completely possible to expose from intero. We'd have to have the command return something more structured at this point. JSON output seems like a good step.

**Comment by mgsloan** [comment]
Agreed, autocompletion could potentially provide a lot of additional info, this is also covered by my grand scheme for it: https://github.com/commercialhaskell/intero/issues/53 .  Makes sense to have more tickets, though, to track incremental progress towards that.

**Comment by chrisdone** [comment]
@Tombert 

If you want to get started on this, you can look here:

https://github.com/commercialhaskell/intero/blob/master/src/GhciFind.hs#L55

You'd need a way to grab a `Type` given a `Name`. There's some code doing that here: https://github.com/commercialhaskell/intero/blob/master/src/GhciFind.hs#L344

I would make findLocalizedCompletions return a `(Name,Maybe Type)` via `spaninfoVar` and `spaninfoType`. And then do a lookup for each of the `filteredToplevels` here https://github.com/commercialhaskell/intero/blob/master/src/GhciFind.hs#L93 with the code I mentioned above. 

Ideally at the end you'll have a complete list of `[(Module, Name, Type)]` and then you can print e.g.

```haskell
Prelude.(++) :: [a] -> [a] -> [a]
Data.List.sortBy :: (a -> Ordering) -> [a] -> [a]
```

which would provide qualified names and types in one go. The Emacs Intero mode could deal with this information however it likes.

Later when we add some kind of JSON/protocol we can do something structured.

**Comment by stellarhoof** [comment]
@chrisdone This is extremely useful not only for completion but also for looking up documentation with `hoogle --info`, which requires a fully qualified name almost always to unequivocally identify correctly the identifier we're looking for.

**Comment by chrisdone** [comment]
I won't be implementing this. But a PR is welcome.
