### ISSUE TITLE
Support structured-haskell-mode nodes with intero-type-at

### ISSUE THREAD

**Issue by dramforever** [commercialhaskell/intero#72]
I use the very useful [SHM](https://github.com/chrisdone/structured-haskell-mode) with intero, and it would be even better if intero-type-at honored the current active node when I checked its type. For example,

```
this :: IO ()
this = fmap id (pure ())
```

When the cursor is on `f` and the current node is `fmap id (pure ())`, I would expect the type be `IO ()`, instead of the type of `fmap`.

This could be added as an option. Thanks.

**Comment by chrisdone** [comment]
I'd like the same for myself. This is pretty easy to add to intero as a feature which activates when SHM is enabled locally.

**Comment by chrisdone** [comment]
I'm not going to get around to this. The workaround is to use `C-M-SPC` to select the current node.
