### ISSUE TITLE
Improve message/behaviour when a dependency is not installed

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/intero#75]
We pass `--no-build` for start-up speed, but we could turn off that flag if a dependency is missing. For example.

**Comment by mgsloan** [comment]
I believe that `--no-dependencies` will have this effect.  It's like `--no-build` except if a dependency is missing. Ideally we'd just fix this pre-build step stuff in stack - https://github.com/commercialhaskell/stack/issues/1364

**Comment by chrisdone** [comment]
Closing in favour of #90.
