### ISSUE TITLE
Need package `company-0.9.0', but only 0.8.12 is available

### ISSUE THREAD

**Issue by mageshb** [commercialhaskell/intero#76]
I'm unable to install interno. It is failing with following error.
  Need package `company-0.9.0', but only 0.8.12 is available
I refreshed package content and I could see only version of 0.8.12 of company package available in MELPA repo.
Is there any thing I'm missing here

**Comment by chrisdone** [comment]
Hm. Perhaps you are on melpa stable? 0.9 is on MELPA presently.

But I can set the lower bound to 0.8.12, I'm not using any fancy features of company.
