### ISSUE TITLE
Intero debug mode

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/intero#79]
Sometimes intero fails to load a project properly. This can manifest itself in various ways such as "module not found errors" when requesting for the type of something. But it's hard to find the root cause, especially when `stack ghci` works just fine. What would be great is if the user could turn on a flag to observe the interaction between intero.el and intero-the-process for debugging purposes. @chrisdone is this something you use already when hacking on intero?

**Comment by chrisdone** [comment]
I don't have anything like that presently.
