### ISSUE TITLE
Feature request: Intero overrides "jump to tag" but not "jump back"

### ISSUE THREAD

**Issue by Blaisorblade** [commercialhaskell/intero#81]
`M-.` is usually serviced using tags. If that's overridden, also `M-,` and `M-*` should be — 

Instead, `M-,` still gives (inside `*Messages*`):
```
user-error: No M-x tags-search or M-x tags-query-replace in progress
```

and `M-*` gives:
```
pop-tag-mark: No previous locations for find-tag invocation
```

**Comment by chrisdone** [comment]
Closing in favour of #78!
