### ISSUE TITLE
Intero setup doesn't install dependencies

### ISSUE THREAD

**Issue by Blaisorblade** [commercialhaskell/intero#82]
I installed intero and opened a file.
It first showed me some error I lost because I didn't have a Stack project — arguably, it should tell me that instead of showing an internal failure. Then, more interestingly, after I did create a stack project:

```
stack init --resolver nightly-2016-06-06
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- Unification-Playground.cabal
Selected resolver: nightly-2016-06-06
Initialising configuration using resolver: nightly-2016-06-06
Total number of user packages considered: 1
Writing configuration to file: stack.yaml
All done.
```

Loading the file still failed. Reproducing the command gave:
```
$ stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-load --no-build --ghci-options -odir=/var/folders/_7/hlxv4yv95x95vgnn416b4q4m0000gp/T/intero75981lDx --ghci-options -hidir=/var/folders/_7/hlxv4yv95x95vgnn416b4q4m0000gp/T/intero75981lDx Unification-Playground
Configuring GHCi with the following packages: Unification-Playground
Intero 0.1.13 (GHC 8.0.1)
Type :intro and press enter for an introduction of the standard commands.

<command line>: cannot satisfy -package mtl-2.2.1
    (use -v for more information)
```
I fixed this with `stack build`, but the messages should say so. EDIT: actually, `stack build` is probably overkill, we just need to build dependencies — it will even fail if the project has type errors, but in that context `intero` should still support editing the project.*

\*Unlike `haskell-mode`, that supports loading a REPL for projects with type errors *once it started* (where it loads a REPL but not the project, and that's OKish), but not at boot time (where it loads no REPL).

**Comment by Blaisorblade** [comment]
Also arguably related: #63.

**Comment by chrisdone** [comment]
Made an issue specifically for handling dependencies: #90 Please follow that one for the upcoming fix!
