### ISSUE TITLE
Doc request: Intero doesn't document keybindings in `C-h m`

### ISSUE THREAD

**Issue by Blaisorblade** [commercialhaskell/intero#83]
Behavior: open mode help with `C-h m`.
What happens: docs are shown, and `haskell-mode` documents its keybindings as a good citizen.
What should IMHO happen: `intero` should also document its keybindings, so I could check how to jump back (in the context of #81).
If I need to motivate that intero should follow Emacs conventions, read on.
Caveat: I'm not an Emacs expert (I grew up with Vim), so I might be misunderstanding Emacs conventions.

## Context
`intero` does seem impressive for a young program, and I'll keep using it. But FYI, the user experience doesn't "just work" for me, so the claims on the homepage feel a bit exaggerate to me.

I'm aware of https://github.com/commercialhaskell/intero#default-key-bindings, but Emacs has its rules and they're embedded into muscle memory.
I found this issue, #81 and #82 within few minutes simply by installing intero, loading a file, jumping to a definition and trying to go back by muscle memory.

EDIT: I managed to type correctly `C-h m` yet write the nonsense `C-c m` throughout the issue. Sorry.

**Comment by Blaisorblade** [comment]
> But FYI, the user experience doesn't "just work" for me, so the claims on the homepage feel a bit exaggerate to me.

I just confirmed this was announced a few hours ago and found
https://www.reddit.com/r/haskell/comments/4mrotr/intero_for_emacs/d3xu7zf

So I would still revise the homepage a bit, but huge kudos nonetheless!

**Comment by chrisdone** [comment]
No problem, adding them is a one-liner. Emacs auto-generates these. Thanks for reporting!
