### ISSUE TITLE
Unable to install intero due to weird package dependency error

### ISSUE THREAD

**Issue by saurabhnanda** [commercialhaskell/intero#85]
What's the right place for debugging and troubleshooting? Pasting the error message below. I have a global GHC & cabal set-up alongside stack. Is that the problem? Do I have to nuke my regular setup?

    The following GHC options are incompatible with GHCi and have not been passed to it: -threaded -O0
    Configuring GHCi with the following packages: Nightwatch
    Intero 0.1.13 (GHC 7.10.3)
    Type :intro and press enter for an introduction of the standard commands.

    <command line>: cannot satisfy -package aeson-0.10.0.0
        (use -v for more information)

    ---

    This is the buffer where Emacs talks to intero. It's normally hidden,
    but a problem occcured.

    It may be obvious if there is some text above this message
    indicating a problem.

    The process ended. Here is the reason that Emacs gives us:

      exited abnormally with code 1

    For troubleshooting purposes, here are the arguments used to launch intero:

      stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-load --no-build --ghci-options -odir=/var/folders/j7/fgt692sj0wzg0lvrk86ctnxc0000gn/T/intero1855H2s --ghci-options -hidir=/var/folders/j7/fgt692sj0wzg0lvrk86ctnxc0000gn/T/intero1855H2s Nightwatch

    After fixing this problem, you could switch back to your code and
    run M-x intero-restart to try again.

    You can kill this buffer when you're done reading it.

**Comment by mgsloan** [comment]
Have you done a `stack build` of the project you are running intero on?

**Comment by saurabhnanda** [comment]
@mgsloan thanks for replying. Trying `stack build` first. Will report back.

**Comment by chrisdone** [comment]
Thanks for reporting @saurabhnanda. I've made an issue #90 explaining this and for making it more automated!

**Comment by saurabhnanda** [comment]
@mgsloan @chrisdone everything seems to be working fine after `stack build`. So excited to see symbol auto-completion. Hopefully coding in Haskell will be an order of magnitude easier now :)
