### ISSUE TITLE
intero-info does not use imports

### ISSUE THREAD

**Issue by kanterov** [commercialhaskell/intero#86]
`intero-info` works for types from Prelude, but it does not take into account imports in a current file. This snippet doesn't work for me. I've found a workaround to add common imports to `.ghci`.

```haskell
{-# LANGUAGE DeriveFunctor #-}

module Lib () where

import Control.Monad.Free

data ConsoleF a
  = WriteLine String a
  | ReadLine (String -> a)
  deriving Functor

type Console a = Free ConsoleF a
--                ^
--                |--- pointer is here
--
-- C-C C-i
-- Not in scope: Free
```

**Comment by chrisdone** [comment]
That's right. I've made an explanation in #89. Thanks for reporting. I'm closing this issue in favor of that one.
