### ISSUE TITLE
Display no completions when the module hasn't been loaded yet

### ISSUE THREAD

**Issue by agrafix** [commercialhaskell/intero#87]
Thanks for this, it looks awesome! I have installed intero via https://gist.github.com/dysinger/63b7cd03f77ac0125356051b23f47a37 for spacemacs, but it always displays "Exception: Couldn't guess that module name. Does it exist?" when trying to autocomplete. Any ideas?

**Comment by magthe** [comment]
I'm seeing the same thing.

Arch Linux, Emacs 24.5.1, Spacemacs on the `develop` branch,  GHC 8.0.1, intero 0.1.13.

**Comment by chrisdone** [comment]
@agrafix @magthe Can you confirm whether your buffer has successfully been checked with flycheck?

**Comment by magthe** [comment]
Hmm, after a restart of emacs it seems to work fine for me. Surprising, but good! :)

**Comment by chrisdone** [comment]
In any case, there's some work I can do here so that when it doesn't have type info yet because it hasn't loaded the module, rather than reporting that message, it just displays no completions.

**Comment by agrafix** [comment]
@chrisdone how can I check that? For me restarting (spac)emacs didn't solve the problem. I used this gist: https://gist.github.com/dysinger/63b7cd03f77ac0125356051b23f47a37 . When installing intero, I got an error: `intero.el:50:1:Error: Cannot open load file: no such file or directory, flycheck`. Sounds like flycheck is not working properly

**Comment by chrisdone** [comment]
Yeah, I think your flycheck isn't being installed right.

**Comment by agrafix** [comment]
Okay, I will try to get rid of it and reinstall everything

**Comment by chrisdone** [comment]
@agrafix Any luck?

**Comment by agrafix** [comment]
It seems to be working now at least for the usual code bases - in our 800+ module code base it causes emacs to hang so I've disabled flycheck there.

**Comment by chrisdone** [comment]
Fixed in #206.
