### ISSUE TITLE
Make :info use the same database as :loc-at

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/intero#89]
Currently, the `:info` command uses the interactive REPL context. Which is fine for the REPL case. In our case, we're loading the code with `-fobject-code`, which loads less information in the interactive context. This excludes getting info for things which are imported or defined locally in a module. Boo!

Happily, `:type-at` and `:complete-at` demonstrate that we already have such information, we just need to make `:info` a bit smarter and use either its existing backend or fallback to the same database that `:type-at` and `:complete-at` use. Then we get our `:info` command back and retain fast compilation.

**Comment by chrisdone** [comment]
Pinging @kanterov.

**Comment by kanterov** [comment]
Thanks, it is exactly what I wanted.

**Comment by clojj** [comment]
So this why Emacs C-c C-i gives me "error: Not in scope.." yet th :info command in the REPL (stack ghci --with-ghc ...) works fine  ?

**Comment by chrisdone** [comment]
Correct!

**Comment by chrisdone** [comment]
Now `C-c C-i` (intero-info) seems to work very well. I've also upgraded its UI so that it dumps the information in `*Help*`, supporting forward/back, sharing the same functionality as Emacs's regular help browser.

<img width="646" alt="screenshot 2016-07-08 17 10 48" src="https://cloud.githubusercontent.com/assets/11019/16692320/908783e8-4530-11e6-8240-f68b36794dbc.png">
<img width="659" alt="screenshot 2016-07-08 17 10 11" src="https://cloud.githubusercontent.com/assets/11019/16692318/908599fc-4530-11e6-897f-d62b7a7457ad.png">
<img width="647" alt="screenshot 2016-07-08 17 10 26" src="https://cloud.githubusercontent.com/assets/11019/16692321/908b5a04-4530-11e6-9cf1-11a92c9f5b00.png">

**Comment by clojj** [comment]
very nice, thx
