### ISSUE TITLE
Make more user-friendly report when package dependencies are not installed

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/intero#90]
When launching `stack ghci --with-ghc intero`, stack needs the packages to be installed before it can start up the process. It gives a message like this:

```
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded -O0
Configuring GHCi with the following packages: Nightwatch
Intero 0.1.13 (GHC 7.10.3)
Type :intro and press enter for an introduction of the standard commands.

<command line>: cannot satisfy -package aeson-0.10.0.0
    (use -v for more information)
```

We can easily detect that, and re-run `stack ghci` without the `--no-build` argument. 

A lot of users are running into this issue. Though it has a simple fix (run `stack build`), it's not immediately obvious. We can easily automate this and remove a step for the user.

**Comment by chrisdone** [comment]
Pinging @saurabhnanda.

**Comment by chrisdone** [comment]
Pinging @Blaisorblade.

**Comment by chrisdone** [comment]
Adding relevant comment by @mgsloan:

> I believe that `--no-dependencies` will have this effect.  It's like `--no-build` except if a dependency is missing. Ideally we'd just fix this pre-build step stuff in stack - https://github.com/commercialhaskell/stack/issues/1364

**Comment by chrisdone** [comment]
Now when you open a project with Intero it detects if there's a missing package. Assuming that you just need to restart without `--no-build` on, restarts without that flag, which triggers a build on startup.

While doing so, it reports the progress in the minibuffer like this (here I ran `M-x intero-targets` and specified `:vegito-bench` and `:vegit-test`, which triggered installing things like hspec and criterion):

<img width="473" alt="screenshot 2016-06-07 16 53 18" src="https://cloud.githubusercontent.com/assets/11019/15862571/63813196-2cd0-11e6-8e39-67ae1440c2a3.png">

After it's done, it starts up as normal and flychecks the buffer.

**Comment by greenrd** [comment]
@chrisdone This didn't quite work for me. I moved a dependency from the library to the executable, and didn't do stack build, and then got this error. Shall I file a new bug?
