### ISSUE TITLE
:type-at should give kind for types

### ISSUE THREAD

**Issue by gergoerdi** [commercialhaskell/intero#91]
If I do an `intero-type-at` on a type, I'd expect its kind to be displayed. Instead, I get the error message
`Not in scope: data constructor 'Foo'`.

**Comment by chrisdone** [comment]
That's an interesting idea. I like it!

**Comment by mgsloan** [comment]
Good idea!  Ideally, this'd also clarify that it's giving kind info.  While experienced haskellers won't have too much of an issue, could be particularly good to clarify that in the presence of DataKinds.

I suppose this'd also provide kinds for different parts of types.  So like if you ask for the kind of `Maybe` in `Maybe Int`, you get `* -> *`.

One day we may also want it to give the "sort" of different parts of kind sigs, hah.

**Comment by chrisdone** [comment]
Probably not going to implement this. That info is available in the repl anyway.
