### ISSUE TITLE
push-mark in intero-goto-definition

### ISSUE THREAD

**Issue by cruegge** [commercialhaskell/intero#92]
Not quite sure, but `intero-goto-definiton`'s use of `pop-mark`  before jumping should probably be a `push-mark` instead.

**Comment by chrisdone** [comment]
`pop-mark` is used to avoid the mark selection being expanded from the start point to the jump point. `push-mark` would set the new mark as far as I know. If you see bad behaviour open an issue about that!

**Comment by cruegge** [comment]
I see, I thought it was for providing a way to jump back to the previous point in the target file. But wouldn't `deactivate-mark` suffice to prevent expanding the selection, while leaving the mark and the mark ring unmodified?
