### ISSUE TITLE
Company autocompletion failing with 'invalid read syntax "?"'

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/intero#95]
Using Tim's spacemacs layer https://gist.github.com/dysinger/63b7cd03f77ac0125356051b23f47a37

If I type in an identifier like `fooo`, I get:

> Company: An error occurred in auto-begin
> Company: backend company-intero error "Invalid read syntax "?"" with args (candidates fooo)

**Comment by chrisdone** [comment]
Can you provide a minimal example file?

**Comment by mgsloan** [comment]
Yeah, no longer affecting my usage, should have closed it earlier!
