### ISSUE TITLE
can't find package not in Hackage/Stackage?

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/intero#96]
Thanks for making intero... I just tried it under emacs-24.5 and stack-1.1.2 (on Fedora).

I tried it on my ugly code https://github.com/fedora-haskell/fedora-haskell-tools/ which is not in Hackage, and doesn't have a stack.yaml file. Then `intero:backend:fedora-haskell-tools` shows:

```
Run from outside a project, using implicit global project config
Using resolver: lts-3.22 from implicit global project's config file: /home/petersen/.stack/global/stack.yaml
The following target packages were not found: fedora-haskell-tools
```

intero seems to be running `stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-load --no-build --ghci-options -odir=/tmp/intero9180mOM --ghci-options -hidir=/tmp/intero9180mOM fedora-haskell-tools`. If I replace `s/fedora-haskell-tools/./` there it can run okay.  So maybe it is a stack issue?

(When I tried loading a file from cabal-rpm which is in stackage/hackage the file this doesn't happen though I couldn't get `M-.` to work yet.)

**Comment by chrisdone** [comment]
You need a `stack.yaml` file, yeah. You can get one via `stack init`. It uses your `.cabal` package name as the default stack target, but you don't have a stack file.

Meanwhile, I pushed a fix which doesn't pass any default target if there is no stack config.
