### ISSUE TITLE
Jumps don't seem to work for not exported types

### ISSUE THREAD

**Issue by qrilka** [commercialhaskell/intero#98]
This seems to be a  minimal example

```haskell
module Main (main) where

type MyType = (Int, Bool)

-- | example function, trying to jump from it's return type 'MyType'
myVal :: MyType
myVal = (42, True)

main :: IO ()
main = putStrLn $ "Hello, " ++ show myVal
```

`M-.` on usage of `MyType` in `myVal` doesn't work for me.
When I remove `(main)` and make all definitions exported jumping starts to work

**Comment by chrisdone** [comment]
Good catch!

**Comment by chrisdone** [comment]
A little bit more debugging shows that this applies only to types:

```haskell
module X where
data T = T
t :: T
t = T
```

I think this is probably due to type-signatures not being picked up in the type collection process. Therefore it falls back to looking at exports of modules.
