### ISSUE TITLE
crashes emacs

### ISSUE THREAD

**Issue by sboosali** [commercialhaskell/intero#99]
stack had some issue:

```
$ stack build
Could not find module ‘Foreign.CStorable’ There are files missing in the ‘c-storable-deriving-0.1.3@cstor_5vWYMhepxNR9yqcjDc1HbQ’ package, try running 'ghc-pkg check'. Use -v to see a list of the files searched for.

```

(fixed with `ghc-pkg unregister`, btw), intero displayed a different error (in the `intero:backend:<package>` buffer):

`<command line>: can't load .so/.DLL for: libHSc-storable-deriving-0.1.3-5vWYMhepxNR9yqcjDc1HbQ.dylib (dlopen(libHSc-storable-deriving-0.1.3-5vWYMhepxNR9yqcjDc1HbQ.dylib, 5): image not found)
`

and then emacs hanged. Sometimes it didn't hang until I killed the `intero:backend:<package>` buffer, and sometimes it did the second or third time it was invoked (like with `:type-at`).

wild guess: Emacs is single threaded (or something like that), so maybe `intero` is blocking on reading from some channel that hasn't been closed, but won't ever produce data. 

(However, so far, if `stack build` works, so does `intero`, even on a package with foreign bindings. Which is pretty great.)

**Comment by chrisdone** [comment]
So what are the steps to reproduce this?

**Comment by sboosali** [comment]
I tried

`
$ rm .stack-work/install/x86_64-osx/lts-6.1/7.10.3/lib/x86_64-osx-ghc-7.10.3/c-storable-deriving-0.1.3-5vWYMhepxNR9yqcjDc1HbQ/Foreign/CStorable.hi 
$ stack clean
`

which trigged the same error on stack build, but intero still worked, even on a module that imported `Foreign.CStorable`. ¯\_(ツ)_/¯

**Comment by chrisdone** [comment]
Marking as stack problem.
